import type { PhraseRow } from "../englishPhraseTables";
import * as style from "./style";

// Sound-alike small words inside frames where only one spelling is French. Every row's typed
// form is never correct as written; frames that need the context of a verb or a subject live in
// homophones.ts.

/** One row per frame: `~` stands for the typed word, replaced by the intended one. */
const one = (frames: string[], typed: string, fixed: string): PhraseRow[] =>
  frames.map((frame) => [frame.replace("~", typed), frame.replace("~", fixed)]);

/** Rows for englishPhraseCorrections (contextual grammar). */
export const PHRASES: readonly PhraseRow[] = [
  // "et" after an elided pronoun is always the verb "est": "c'et", "n'et", "s'et".
  ["c'et", "c'est"],
  ["n'et", "n'est"],
  ["s'et", "s'est"],
  ["qu'et", "qu'est"],
  // "à": prepositional locutions whose "a" can never be the verb.
  ...one(
    [
      "tout ~ fait",
      "tout ~ coup",
      "tout ~ l'heure",
      "grâce ~ toi",
      "grâce ~ vous",
      "grâce ~ lui",
      "grâce ~ eux",
      "face ~ face",
      "quant ~",
      "jusqu'~",
      "suite ~ votre",
      "suite ~ ton",
      "suite ~ notre",
      "par rapport ~",
      "contrairement ~",
      "pas ~ pas",
      "peu ~ peu",
      "petit ~ petit",
      "côte ~ côte",
      "nez ~ nez",
      "goutte ~ goutte",
      "mise ~ jour",
      "au fur et ~ mesure",
      "de temps ~ autre",
      "~ cause de",
      "~ cause du",
      "~ cause des",
      "~ partir de",
      "~ partir du",
      "~ travers",
      "~ côté de",
      "~ côté du",
      "~ peu près",
      "~ propos de",
      "~ condition que",
      "~ l'égard de",
      "~ l'instar de",
      "~ la hâte",
      "~ l'aveuglette",
      "~ la rescousse",
      "~ l'improviste",
      "~ contrecœur",
      "~ vol d'oiseau",
      "~ temps plein",
      "~ temps partiel",
      "~ plein temps",
      "~ coup sûr",
      "garde ~ vue",
      "machine ~ laver",
      "machines ~ laver",
      "fer ~ repasser",
      "salle ~ manger",
      "bonjour ~ tous",
      "merci ~ tous",
      "rien ~ voir",
    ],
    "a",
    "à",
  ),
  ["a tort et a travers", "à tort et à travers"],
  // "où": "d'ou", "par ou", "jusqu'ou" and "n'importe ou" never mean "or".
  ...one(
    [
      "d'~",
      "jusqu'~",
      "n'importe ~",
      "au moment ~",
      "à l'instant ~",
      "dans la mesure ~",
      "au cas ~",
    ],
    "ou",
    "où",
  ),
  ["plus où moins", "plus ou moins"],
  // "sûr": certain.
  ...one(
    [
      "bien ~,",
      "j'en suis ~",
      "en suis-je ~",
      "~ et certain",
      "à coup ~",
      "en lieu ~",
      "est ~ de lui",
      "est ~ d'elle",
      "suis ~ de moi",
      "es ~ de toi",
      "suis ~ que",
      "es ~ que",
      "est ~ que",
      "pas ~ que",
      "~ de soi",
    ],
    "sur",
    "sûr",
  ),
  ...one(["suis ~ que", "es ~ que", "est ~ que", "est ~ d'elle", "~ d'elle-même"], "sure", "sûre"),
  ...one(["sont ~ que", "sommes ~ que", "êtes ~ que", "sont ~ d'eux"], "surs", "sûrs"),
  ...one(["sont ~ que", "sommes ~ que", "êtes ~ que", "sources ~", "mains ~"], "sures", "sûres"),
  // "sont", "ont", "on" after a subject pronoun.
  ...one(
    ["ils ~", "elles ~", "ne ~ pas", "ne ~ plus", "ne ~ jamais", "ne ~ guère", "ne ~ que"],
    "son",
    "sont",
  ),
  ...one(["ils ~", "elles ~"], "on", "ont"),
  ...one(["si ~ peut", "si ~ veut", "si ~ doit", "si ~ va"], "ont", "on"),
  // "se" / "ce", "s'est" / "c'est".
  ...one(
    ["~ qui", "~ que", "~ qu'il", "~ qu'elle", "~ qu'on", "tout ~ qui", "tout ~ que"],
    "se",
    "ce",
  ),
  ...one(["~ matin", "~ soir", "~ week-end", "~ jour-là", "~ moment-là"], "se", "ce"),
  // "Elle c'est ma sœur" dislocates without a comma: only "il" and "on" are never stressed.
  ...one(["il ~", "on ~", "il ne ~", "elle ne ~", "on ne ~"], "c'est", "s'est"),
  ...one(["il ~", "on ~"], "c'était", "s'était"),
  // "ça" before a pronoun or a negation: a possessive never comes there.
  ...one(
    ["~ me", "~ m'", "~ te", "~ t'", "~ se", "~ s'", "~ ne", "~ n'", "~ y est", "~ fait mal"],
    "sa",
    "ça",
  ),
  // "dû": owed to, had to. The subject's gender is unknown here, so "dû" and "due" are offered.
  ...["est ~ à", "est ~ au", "était ~ à", "était ~ au", "sera ~ à"].map((frame): PhraseRow => [
    frame.replace("~", "du"),
    ["dû", "due"].map((f) => frame.replace("~", f)),
  ]),
  // "dès": from, as soon as.
  ...one(
    [
      "~ que",
      "~ qu'il",
      "~ qu'elle",
      "~ qu'on",
      "~ lors",
      "~ aujourd'hui",
      "~ demain",
      "~ maintenant",
      "~ à présent",
      "~ le début",
      "~ la fin",
      "~ l'aube",
      "~ le départ",
      "~ la naissance",
    ],
    "des",
    "dès",
  ),
  ...one(["~ que", "~ qu'il", "~ à présent", "~ lors"], "dés", "dès"),
  // "peu" / "peut" / "peux".
  // "l'un peut", "quelqu'un peut": "un" there is a pronoun.
  ...one(
    [
      "un ~ de",
      "un ~ plus",
      "un ~ moins",
      "un ~ trop",
      "très ~",
      "à ~ près",
      "il y a ~ de",
      "~ à peu",
    ],
    "peut",
    "peu",
  ),
  ...one(["il ~", "elle ~", "on ~", "il ne ~", "on ne ~"], "peu", "peut"),
  ...one(["je ~", "tu ~", "je ne ~", "tu ne ~"], "peu", "peux"),
  // "leur" before a verb is the pronoun: it never takes an s.
  ...one(
    ["je ~", "tu ~", "il ~", "elle ~", "on ~", "ils ~", "elles ~", "ne ~", "je ne ~"],
    "leurs",
    "leur",
  ),
  // "quant à" / "quand".
  ...one(
    ["~ à moi", "~ à toi", "~ à lui", "~ à elle", "~ à nous", "~ à vous", "~ à eux", "~ à elles"],
    "quand",
    "quant",
  ),
  ...one(
    [
      "~ il",
      "~ elle",
      "~ on",
      "~ je",
      "~ j'",
      "~ tu",
      "~ nous",
      "~ ils",
      "~ elles",
      "~ même",
      "~ bien même",
    ],
    "quant",
    "quand",
  ),
  // "as" / "a" after the subject.
  ...one(["tu ~"], "a", "as"),
  ...one(["il ~", "elle ~", "on ~"], "as", "a"),
  // "est" fixed in "qui plus est", "n'en est rien", "m'est égal".
  ...one(["qui plus ~", "m'~ égal", "t'~ égal"], "ait", "est"),
  // "voilà": "voila" is the past of "voiler" ("elle se voila le visage"), so only frames.
  ...one(
    [
      "et ~",
      "que ~",
      "me ~",
      "te ~",
      "nous ~",
      "vous ~",
      "le ~",
      "les ~",
      "en ~",
      "~ pourquoi",
      "~ tout",
      "~ qui",
      "~ ce que",
      "~ ce qui",
    ],
    "voila",
    "voilà",
  ),
  // "jusque" elides before "à" and its contractions.
  ["jusque à", "jusqu'à"],
  ["jusque au", "jusqu'au"],
  ["jusque aux", "jusqu'aux"],
  // Sound-alike nouns inside fixed phrases: "de bonne foi", "tenir compte", "point de vue".
  ...one(
    ["de bonne ~", "de mauvaise ~", "sans ~ ni loi", "digne de ~", "ma ~ !", "profession de ~"],
    "foie",
    "foi",
  ),
  ["foie en Dieu", "foi en Dieu"],
  ["foi gras", "foie gras"],
  ...one(["une ~", "à la ~", "il était une ~", "chaque ~"], "foie", "fois"),
  ["chaque foi", "chaque fois"],
  ...one(
    [
      "~ agréer",
      "~ trouver",
      "~ me",
      "~ m'",
      "~ nous",
      "~ excuser",
      "~ noter",
      "~ patienter",
      "~ accepter",
      "~ recevoir",
      "~ croire",
    ],
    "veillez",
    "veuillez",
  ),
  ...one(["~ à ce que", "~ sur", "~ bien à"], "veuillez", "veillez"),
  ...one(["à la ~", "~ ingrate", "~ ardue", "~ difficile"], "tache", "tâche"),
  ...one(
    ["~ de café", "~ de vin", "~ de sang", "~ de graisse", "~ d'encre", "~ de rousseur"],
    "tâche",
    "tache",
  ),
  ["tâches de rousseur", "taches de rousseur"],
  ...one(
    [
      "à bon ~",
      "en fin de ~",
      "en ligne de ~",
      "~ tenu",
      "tenir ~",
      "tient ~",
      "rendre ~",
      "rend ~",
      "~ en banque",
      "tout ~ fait",
      "au bout du ~",
    ],
    "conte",
    "compte",
  ),
  ...one(["règlement de ~", "règlements de ~", "cour des ~"], "contes", "comptes"),
  ...one(
    [
      "rendu ~",
      "rendue ~",
      "rendus ~",
      "rends ~",
      "rendons ~",
      "rendez ~",
      "rendent ~",
      "rendait ~",
      "rendra ~",
      "tenu ~ de",
      "tenez ~ de",
      "~ à rebours",
      "laissé pour ~",
      "laisser pour ~",
      "loin du ~",
      "~ sur moi",
      "~ sur toi",
      "~ sur vous",
      "~ sur nous",
    ],
    "conte",
    "compte",
  ),
  ...one(["en fin de ~", "laissés pour ~"], "contes", "comptes"),
  // "gré": consent and pleasure; "grès" is sandstone.
  ...one(
    [
      "contre mon ~",
      "contre ton ~",
      "contre son ~",
      "contre leur ~",
      "contre notre ~",
      "contre votre ~",
      "à mon ~",
      "à ton ~",
      "à son ~",
      "à votre ~",
      "à leur ~",
      "au ~ de",
      "au ~ du",
      "au ~ des",
      "bon ~ mal gré",
      "de ~ ou de force",
      "de plein ~",
      "sais ~",
      "sait ~",
      "savons ~",
      "savez ~",
    ],
    "grès",
    "gré",
  ),
  // "plus" missing its s in fixed phrases.
  ...one(["en ~,", "~ ou moins", "non ~", "de ~ en plus", "de plus en ~"], "plu", "plus"),
  // "pose": laying (tiles, a stone) and a model's posture; "pause": a break.
  ...one(
    [
      "la ~ du carrelage",
      "la ~ des ardoises",
      "la ~ de la première pierre",
      "la ~ du papier peint",
      "~ problème",
      "~ question",
    ],
    "pause",
    "pose",
  ),
  ...one(["faire une ~", "une courte ~", "une petite ~ de"], "pose", "pause"),
  // "croire" (to believe) takes "que" and "en" + a person; "croître" (to grow) does not.
  ...one(
    ["~ que", "~ qu'il", "~ qu'elle", "~ en Dieu", "~ en lui", "~ en elle", "~ en toi"],
    "croît",
    "croit",
  ),
  ...one(["je ne ~ pas", "tu ne ~ pas", "je ~ que"], "croîs", "crois"),
  ...one(["~ en toi", "~ en moi", "~ en vous", "~ en nous"], "croix", "crois"),
  ["compte de fées", "conte de fées"],
  ["comptes de fées", "contes de fées"],
  ...one(["confiance en ~", "va de ~", "chez ~"], "soit", "soi"),
  ["ver à soi", "ver à soie"],
  ["soit disant", "soi-disant"],
  ["soit-disant", "soi-disant"],
  ["soit-même", "soi-même"],
  ...one(["~ à tout"], "près", "prêt"),
  ...one(["à peu ~", "tout ~"], "prés", "près"),
  ...one(["à peu ~", "au plus ~", "de plus ~", "de très ~"], "prêt", "près"),
  ["fin près", "fin prêt"],
  ...one(
    ["à ~ de", "de ~", "du ~ de", "d'un ~", "de l'autre ~", "à son ~", "~ gauche", "~ droit"],
    "coté",
    "côté",
  ),
  ["à ses cotés", "à ses côtés"],
  ["cote à cote", "côte à côte"],
  ["cote de bœuf", "côte de bœuf"],
  ...one(
    ["à ~ d'œil", "à perte de ~", "garde à ~", "en ~ de", "point de ~", "à première ~"],
    "vu",
    "vue",
  ),
  ...one(["faire ~ honorable", "mis à l'~", "mise à l'~"], "amande", "amende"),
  ...one(["pâte d'~", "lait d'~"], "amende", "amande"),
  ["au cour de", "au cours de"],
  ["à cour terme", "à court terme"],
  ...one(["à ~ terme", "coupe ~", "couper ~", "tourner ~", "prendre de ~"], "cours", "court"),
  ["cours-circuit", "court-circuit"],
  ...one(["par ~ de conséquence", "en ~ de", "~ ferrée", "~ sans issue"], "voix", "voie"),
  ...one(["~ off", "à haute ~", "à ~ basse"], "voie", "voix"),
  ...one(["~ café", "~-café", "~ déjeuner"], "pose", "pause"),
  ...one(
    [
      "de ma ~",
      "de ta ~",
      "de sa ~",
      "de votre ~",
      "de leur ~",
      "de la ~ de",
      "pour ma ~",
      "nulle ~",
      "quelque ~",
      "d'autre ~",
      "à ~ ça",
    ],
    "par",
    "part",
  ),
  ...one(["faire ~ de", "fait ~ de", "fais ~ de"], "par", "part"),
  ...one(
    ["~ contre", "~ rapport", "~ exemple", "~ ailleurs", "~ hasard", "~ conséquent"],
    "part",
    "par",
  ),
  ...one(
    ["~ être", "~ faire", "~ avoir", "~ savoir", "~ aller", "~ venir", "~ partir", "~ arriver"],
    "sensé",
    "censé",
  ),
  ...one(["~ être", "~ faire", "~ avoir"], "sensée", "censée"),
  ...one(["~ être", "~ faire", "~ avoir"], "sensés", "censés"),
  ...one(["~ être", "~ faire", "~ avoir"], "sensées", "censées"),
  ...one(
    [
      "~ les jours",
      "~ les deux",
      "~ les ans",
      "~ les matins",
      "~ les soirs",
      "~ les mois",
      "~ les gens",
    ],
    "tout",
    "tous",
  ),
  ["de tout côtés", "de tous côtés"],
  ["temps pis", "tant pis"],
  ["temps mieux", "tant mieux"],
  // "de temps en temps que" is fine: only "en temps que tel(le)".
  ["en temps que tel", "en tant que tel"],
  ["en temps que telle", "en tant que telle"],
  ["de tant en tant", "de temps en temps"],
  ...one(["~ que prévu", "le ~ possible", "au ~"], "plutôt", "plus tôt"),
  ["m'en fou", "m'en fous"],
  ["s'en fou", "s'en fout"],
  ["au dépend de", "aux dépens de"],
  ["aux dépend de", "aux dépens de"],
  ["aux dépends de", "aux dépens de"],
  ...one(
    ["faire ~ de", "fait ~ de", "font ~ de", "faisait ~ de", "fais ~ de", "faisant ~ de"],
    "parti",
    "partie",
  ),
  ["au font", "au fond"],
  ["à font", "à fond"],
  // "tout" fixed in its number inside idioms.
  ["à tous prix", "à tout prix"],
  ["à tous hasards", "à tout hasard"],
  ["de tous cœurs", "de tout cœur"],
  ["à toutes vitesses", "à toute vitesse"],
  ["à tous propos", "à tout propos"],
  [
    ["à tous bouts de champs", "à tout bout de champs", "à tous bouts de champ"],
    "à tout bout de champ",
  ],
  ["toute à l'heure", "tout à l'heure"],
  ["toute de suite", "tout de suite"],
  ["toute à fait", "tout à fait"],
  // "quelque" as an adverb (somewhat, about) and in set phrases.
  ["quelques peu", "quelque peu"],
  ["quelques temps", "quelque temps"],
  ["en quelques sortes", "en quelque sorte"],
  // "quelle que soit" written with the pronoun "qu'elle".
  // The noun after it sets the gender, so both forms are offered: "Quel que soit le prix".
  ["qu'elle que soit", ["quelle que soit", "quel que soit"]],
  ["qu'elles que soient", ["quelles que soient", "quels que soient"]],
  ["qu'elle qu'en soit", ["quelle qu'en soit", "quel qu'en soit"]],
  ["qu'elle qu'elle soit", "quelle qu'elle soit"],
  ["qu'elles qu'elles soient", "quelles qu'elles soient"],
  ["quoiqu'il en soit", "quoi qu'il en soit"],
  ["quoiqu'il advienne", "quoi qu'il advienne"],
  // "c'en est fini": the demonstrative, not the reflexive.
  ["s'en est fini", "c'en est fini"],
  ["s'en est trop", "c'en est trop"],
  ["s'en est assez", "c'en est assez"],
  ["d'en la", "dans la"],
  ["dans haut", "d'en haut"],
  ["dans bas", "d'en bas"],
  ["aux leur", "aux leurs"],
  // "ci" (here) and "si" (if, so) swapped in compounds.
  ["si-joint", "ci-joint"],
  ["si-jointe", "ci-jointe"],
  ["si-dessous", "ci-dessous"],
  ["si-dessus", "ci-dessus"],
  ["si dessous", "ci-dessous"],
  ["comme-ci comme-ça", "comme ci comme ça"],
  ["plus mieux", "mieux"],
  ["mille merci", "mille mercis"],
  ["de d'autres", "d'autres"],
  // "an" counts whole years; a year lived or described is "année".
  ["chaque an", "chaque année"],
  ["d'an en an", "d'année en année"],
  ["au cours des ans", "au cours des années"],
  ["tout l'an", "toute l'année"],
  ...["fin", "début", "milieu", "cours"].map((part): PhraseRow => [
    `${part} de l'an`,
    `${part} de l'année`,
  ]),
  ...[
    "vingt",
    "trente",
    "quarante",
    "cinquante",
    "soixante",
    "soixante-dix",
    "quatre-vingt",
    "60",
    "70",
    "80",
    "90",
    "2000",
  ].map((decade): PhraseRow => [`des ans ${decade}`, `des années ${decade}`]),
  // Subject + elided "ne" or object glued to the auxiliary.
  ...one(["il ~", "elle ~", "on ~", "qui ~"], "na", "n'a"),
  ...one(["ils ~", "elles ~", "qui ~"], "mont", "m'ont"),
  // The rib or slope (côte), the rating (cote) and the coat of mail (cotte).
  ...["veau", "bœuf", "porc", "agneau", "mouton"].flatMap((meat): PhraseRow[] => [
    [
      meat === "bœuf" ? [`cotte de ${meat}`] : [`cote de ${meat}`, `cotte de ${meat}`],
      `côte de ${meat}`,
    ],
    [[`cotes de ${meat}`, `cottes de ${meat}`], `côtes de ${meat}`],
  ]),
  ...["cassée", "fêlée", "fracturée", "brisée"].flatMap((state): PhraseRow[] => [
    [[`cote ${state}`, `cotte ${state}`], `côte ${state}`],
    [[`cotes ${state}s`, `cottes ${state}s`], `côtes ${state}s`],
  ]),
  [["fracture des cotes", "fracture des cottes"], "fracture des côtes"],
  [["cote de mailles", "cote de maille", "côte de mailles", "côte de maille"], "cotte de mailles"],
  ...["a", "as", "ont", "avoir", "avait", "avaient"].flatMap((have): PhraseRow[] => [
    [[`${have} la côte auprès`, `${have} la cotte auprès`], `${have} la cote auprès`],
    [[`${have} toujours la côte`, `${have} toujours la cotte`], `${have} toujours la cote`],
    [[`${have} encore la côte`, `${have} encore la cotte`], `${have} encore la cote`],
  ]),
  // Faith (foi), liver (foie) and time (fois).
  ["de mauvaise fois", "de mauvaise foi"],
  ["de bonne fois", "de bonne foi"],
  ["ma foie", "ma foi"],
  ["profession de fois", "profession de foi"],
  [["acte de fois", "acte de foie"], "acte de foi"],
  [["mal au foi", "mal au fois"], "mal au foie"],
  ["fois gras", "foie gras"],
  [["crise de foi", "crise de fois"], "crise de foie"],
  ...["prochaine", "dernière", "première", "seule", "autre"].map((which): PhraseRow => [
    `${which} foie`,
    `${which} fois`,
  ]),
  // A print or mark (empreinte) and a loan (emprunt).
  ["une emprunte", "une empreinte"],
  ["des empruntes", "des empreintes"],
  ["emprunte digitale", "empreinte digitale"],
  ["empruntes digitales", "empreintes digitales"],
  ["emprunte carbone", "empreinte carbone"],
  ["empruntes de pas", "empreintes de pas"],
  ["un empreint", "un emprunt"],
  ["d'empreint", "d'emprunt"],
  ["empreint bancaire", "emprunt bancaire"],
  ["empreint immobilier", "emprunt immobilier"],
  // "bayer aux corneilles" (to gape idly), not "bâiller" (to yawn).
  ...[
    ["bâiller", "bailler", "bayer"],
    ["bâille", "baille", "baye"],
    ["bâilles", "bailles", "bayes"],
    ["bâillent", "baillent", "bayent"],
    ["bâillez", "baillez", "bayez"],
    ["bâillait", "baillait", "bayait"],
    ["bâillaient", "baillaient", "bayaient"],
    ["bâillé", "baillé", "bayé"],
  ].map(([accented, plain, fixed]): PhraseRow => [
    [`${accented} aux corneilles`, `${plain} aux corneilles`],
    `${fixed} aux corneilles`,
  ]),
  [["de hauts en bas", "de hautes en bas"], "de haut en bas"],
  ["çà et la", "çà et là"],
  [["en toutes hâtes", "en toute hâtes", "en toutes hâte"], "en toute hâte"],
  ["toute proportion gardée", "toutes proportions gardées"],
  ["hauts placés", "haut placés"],
  ["hautes placées", "haut placées"],
  ["haute placée", "haut placée"],
  ...style.PHRASES,
];

// Compound numbers below a hundred take hyphens ("vingt-deux", "quatre-vingt-dix"); "et un"
// and "et onze" keep their spaces.
const UNITS = ["deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf"];
const NUMBERS: PhraseRow[] = [
  ...["vingt", "trente", "quarante", "cinquante", "soixante"].flatMap((ten) =>
    UNITS.map((unit): PhraseRow => [`${ten} ${unit}`, `${ten}-${unit}`]),
  ),
  ...["sept", "huit", "neuf"].map((unit): PhraseRow => [`dix ${unit}`, `dix-${unit}`]),
  ["soixante dix", "soixante-dix"],
  ...["douze", "treize", "quatorze", "quinze", "seize"].map((teen): PhraseRow => [
    `soixante ${teen}`,
    `soixante-${teen}`,
  ]),
  ["quatre vingt", "quatre-vingt"],
  ["quatre vingts", "quatre-vingts"],
  ...[...UNITS, "un", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"].map(
    (unit): PhraseRow => [`quatre vingt ${unit}`, `quatre-vingt-${unit}`],
  ),
  ...[...UNITS, "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"].map(
    (unit): PhraseRow => [`quatre-vingt ${unit}`, `quatre-vingt-${unit}`],
  ),
];

/** Rows for englishClosedCompounds: hyphens a compound needs, or must not have. */
export const COMPOUNDS: readonly PhraseRow[] = [
  ...NUMBERS,
  // Imperative + pronoun.
  ...[
    "dis",
    "dites",
    "excuse",
    "excusez",
    "laisse",
    "laissez",
    "écoute",
    "écoutez",
    "regarde",
    "regardez",
    "attends",
    "attendez",
    "donne",
    "donnez",
    "montre",
    "montrez",
    "aide",
    "aidez",
    "crois",
    "croyez",
    "rappelle",
    "rappelez",
  ].map((verb): PhraseRow => [`${verb} moi`, `${verb}-moi`]),
  ...["dépêche", "tais", "calme", "lève", "assieds", "sers"].map((verb): PhraseRow => [
    `${verb} toi`,
    `${verb}-toi`,
  ]),
  ...["vas", "allez", "allons"].map((verb): PhraseRow => [`${verb} y`, `${verb}-y`]),
  // Emphatic pronouns.
  ...["moi", "toi", "lui", "soi"].map((pronoun): PhraseRow => [
    `${pronoun} même`,
    `${pronoun}-même`,
  ]),
  ...["nous", "eux", "elles"].map((pronoun): PhraseRow => [`${pronoun} mêmes`, `${pronoun}-mêmes`]),
  ["quelques uns", "quelques-uns"],
  ["quelques unes", "quelques-unes"],
  // Fixed compounds written apart.
  ["grand mère", "grand-mère"],
  ["grand père", "grand-père"],
  ["grands parents", "grands-parents"],
  ["arc en ciel", "arc-en-ciel"],
  ["chef d'œuvre", "chef-d'œuvre"],
  ["chef d'oeuvre", "chef-d'œuvre"],
  ["après midi", "après-midi"],
  ["week end", "week-end"],
  ["week ends", "week-ends"],
  ["là haut", "là-haut"],
  ["là dessus", "là-dessus"],
  ["là dessous", "là-dessous"],
  ["là dedans", "là-dedans"],
  ["ci dessus", "ci-dessus"],
  ["ci dessous", "ci-dessous"],
  ["ci joint", "ci-joint"],
  ["ci jointe", "ci-jointe"],
  ["ci après", "ci-après"],
  ["la bas", "là-bas"],
  ["la haut", "là-haut"],
  ["porte monnaie", "porte-monnaie"],
  ["porte clés", "porte-clés"],
  ["tire bouchon", "tire-bouchon"],
  ["sous sol", "sous-sol"],
  ["sans abri", "sans-abri"],
  ["demi heure", "demi-heure"],
  ["demi journée", "demi-journée"],
  ["demi douzaine", "demi-douzaine"],
  ["à mi chemin", "à mi-chemin"],
  ["pare brise", "pare-brise"],
  ["pare chocs", "pare-chocs"],
  ["qu'est ce que", "qu'est-ce que"],
  ["qu'est ce qui", "qu'est-ce qui"],
  ["peu-être", "peut-être"],
  ...["un", "le", "mon", "ton", "son", "votre", "notre", "au", "du", "ce"].map((det): PhraseRow => [
    `${det} rendez vous`,
    `${det} rendez-vous`,
  ]),
  ...["le", "du", "son", "leur", "votre", "notre"].map((det): PhraseRow => [
    `${det} savoir faire`,
    `${det} savoir-faire`,
  ]),
  ...["le", "du", "son", "leur", "votre", "notre"].map((det): PhraseRow => [
    `${det} bien être`,
    `${det} bien-être`,
  ]),
  // Hyphens these never take.
  ["compte-rendu", "compte rendu"],
  ["compte-tenu", "compte tenu"],
  ["pomme-de-terre", "pomme de terre"],
  ["pommes-de-terre", "pommes de terre"],
  ["bande-dessinée", "bande dessinée"],
  ["bandes-dessinées", "bandes dessinées"],
  ["petit-ami", "petit ami"],
  ["petite-amie", "petite amie"],
  ["lieu-commun", "lieu commun"],
  ["état-civil", "état civil"],
  ["en-dessous", "en dessous"],
  ["en-dessus", "en dessus"],
  ["tout-à-fait", "tout à fait"],
  ["ici-même", "ici même"],
  ["entre-eux", "entre eux"],
  ["entre-elles", "entre elles"],
  ["porte-feuille", "portefeuille"],
  ["marche-pied", "marchepied"],
];

/** Every form of a phrase whose first word is inflected: [forms, rest, replacement forms]. */
const forms = (typed: string[], rest: string, fixed: string[] = typed): PhraseRow[] =>
  typed.map((form, i): PhraseRow => [`${form} ${rest}`, fixed[i]]);

/**
 * Rows for stylePhrasing (opt-in): pleonasms that say one thing twice, and phrasings calqued on
 * English that French says otherwise.
 */
export const STYLE: readonly PhraseRow[] = [
  // Pleonasms: the second part repeats the first.
  ["seul et unique", ["seul", "unique"]],
  ["seule et unique", ["seule", "unique"]],
  ...["réservé", "réservée", "réservés", "réservées"].map((f): PhraseRow => [
    `exclusivement ${f}`,
    f,
  ]),
  ...forms(["suffit", "suffisait", "suffira", "suffirait", "suffire"], "juste"),
  ...forms(["suffit", "suffisait", "suffira", "suffirait", "suffire"], "simplement"),
  ...forms(["préfère", "préfères", "préférons", "préférez", "préfèrent", "préférer"], "plutôt"),
  ...forms(["optimiser", "optimise", "optimisent", "optimisé"], "au maximum"),
  ...forms(["optimiser", "optimise", "optimisent", "optimisé"], "un maximum"),
  ...forms(["descendre", "descends", "descend", "descendons", "descendez", "descendent"], "en bas"),
  ...forms(["ajouter", "ajoute", "ajoutez", "ajoutent", "ajouté", "ajoutera"], "en plus"),
  ...forms(["rajouter", "rajoute", "rajoutez", "rajoutent", "rajouté"], "en plus"),
  ...forms(["recommencer", "recommence", "recommencent", "recommencé"], "à nouveau"),
  ...forms(["recommencer", "recommence", "recommencent", "recommencé"], "de nouveau"),
  ...forms(["refaire", "refait", "refont"], "à nouveau"),
  ...forms(["redemander", "redemande", "redemandé"], "de nouveau"),
  ...forms(["réserver", "réserve", "réservez", "réservé"], "à l'avance"),
  ...forms(["réserver", "réserve", "réservez", "réservé"], "d'avance"),
  ...forms(["planifier", "planifie", "planifié"], "à l'avance"),
  ...forms(["préparer", "prépare", "préparé"], "à l'avance"),
  ...forms(["prévenir", "préviens", "prévient", "prévenu"], "à l'avance"),
  ...forms(["suivre", "suis", "suit", "suivent", "suivi"], "derrière"),
  ...forms(["achever", "achève", "achevé"], "complètement"),
  ...forms(["abolir", "abolit", "aboli"], "complètement"),
  ...forms(["abolir", "abolit", "aboli"], "entièrement"),
  ...forms(["détruire", "détruit", "détruisent"], "complètement"),
  ...forms(["détruire", "détruit", "détruisent"], "entièrement"),
  ...forms(["comparer", "compare", "comparé"], "entre eux"),
  ...forms(["se réunir", "se réunit", "se réunissent"], "ensemble"),
  // Not "marche": "la marche à pied" is a noun phrase.
  ...forms(["marcher", "marchent", "marchait", "marchaient"], "à pied"),
  ...forms(["reporter", "reporte", "reporté"], "à plus tard"),
  ...forms(["s'esclaffer", "s'esclaffe", "s'esclaffent"], "de rire"),
  ...forms(["prédire", "prédit", "prédisent"], "l'avenir"),
  ["mais pourtant", ["mais", "pourtant"]],
  ["mais cependant", ["mais", "cependant"]],
  ["mais néanmoins", ["mais", "néanmoins"]],
  ["mais toutefois", ["mais", "toutefois"]],
  ["mais par contre", ["mais", "par contre"]],
  ["donc par conséquent", ["donc", "par conséquent"]],
  ["ainsi donc par conséquent", ["ainsi", "par conséquent"]],
  ["car effectivement", ["car", "effectivement"]],
  ["puis après", ["puis", "après"]],
  ["voire même", "voire"],
  ["dorénavant à l'avenir", "dorénavant"],
  ["au grand maximum", "au maximum"],
  ["au grand minimum", "au minimum"],
  ["but final", "but"],
  ["tollé général", "tollé"],
  ["panacée universelle", "panacée"],
  ["première priorité", "priorité"],
  ["risque potentiel", "risque"],
  ["risques potentiels", "risques"],
  ["apanage exclusif", "apanage"],
  ["monopole exclusif", "monopole"],
  ["krach boursier", "krach"],
  ["campus universitaire", "campus"],
  ["prothèse artificielle", "prothèse"],
  ["faux prétexte", "prétexte"],
  ["crue des eaux", "crue"],
  ["dune de sable", "dune"],
  ["surprise inattendue", "surprise"],
  ["hasard imprévu", "hasard"],
  ["heure de temps", "heure"],
  ["unanimité totale", "unanimité"],
  ["manuscrit écrit à la main", "manuscrit"],
  ["manuellement à la main", "manuellement"],
  ...["soi", "toi", "lui", "vous", "nous", "eux"].map((p): PhraseRow => [
    `bel avenir devant ${p}`,
    "bel avenir",
  ]),
  ...forms(["applaudir", "applaudit", "applaudissent"], "des deux mains"),
  ["pallier à", "pallier"],
  // Moving out, up, back or in says where already.
  ...forms(["sors", "sort", "sortons", "sortez", "sortent", "sorti", "sortie"], "dehors"),
  ...forms(["recule", "reculons", "reculez", "reculent", "reculé"], "en arrière"),
  ...forms(["avancer", "avance", "avançons", "avancez", "avancent", "avancé"], "en avant"),
  ...forms(["entrer", "entre", "entrons", "entrez", "entrent", "entré"], "à l'intérieur"),
  ...forms(["rentrer", "rentre", "rentrons", "rentrez", "rentrent", "rentré"], "à l'intérieur"),
  ...forms(["sortir", "sors", "sort", "sortent", "sorti"], "à l'extérieur"),
  // Doing again, together or twice.
  ...forms(["répéter", "répète", "répètent", "répété"], "deux fois"),
  ...forms(["refaire", "refait", "refont"], "de nouveau"),
  ...forms(
    ["continuer", "continue", "continuons", "continuez", "continuent", "continué"],
    "encore",
  ),
  ...forms(["collabore", "collaborons", "collaborez", "collaborent"], "ensemble"),
  ...forms(["s'entraident", "nous entraidons", "vous entraidez"], "mutuellement"),
  ...forms(["prévoit", "prévoient", "prévu"], "à l'avance"),
  ["retour en arrière", "retour"],
  // Spoken contractions written out.
  ["t'as", "tu as"],
  ["t'es", "tu es"],
  ["t'étais", "tu étais"],
  ["t'avais", "tu avais"],
  ["tous unanimes", "unanimes"],
  ["toutes unanimes", "unanimes"],
  ["divers et variés", ["divers", "variés"]],
  ["diverses et variées", ["diverses", "variées"]],
  ["maintenant à présent", "maintenant"],
  ["petite maisonnette", "maisonnette"],
  ["somme d'argent", "somme"],
  ["bip sonore", "bip"],
  ["secousse sismique", "secousse"],
  ["opposé exact", "opposé"],
  ["exact opposé", "opposé"],
  // Calques of English phrasings.
  ...forms(["faire", "fait", "font"], "du sens", ["avoir du sens", "a du sens", "ont du sens"]),
  ["ça fait sens", "ça a du sens"],
  ...forms(["être", "est", "sont", "suis", "es"], "en charge de", [
    "être chargé de",
    "est chargé de",
    "sont chargés de",
    "suis chargé de",
    "es chargé de",
  ]),
  ...forms(["appliquer", "applique", "appliqué"], "pour un poste", [
    "postuler à un poste",
    "postule à un poste",
    "postulé à un poste",
  ]),
  ...forms(["mettre", "mis", "mise", "met"], "à date", [
    "mettre à jour",
    "mis à jour",
    "mise à jour",
    "met à jour",
  ]),
  ...forms(["prendre", "prend", "pris"], "pour acquis", [
    "tenir pour acquis",
    "tient pour acquis",
    "tenu pour acquis",
  ]),
  ...forms(["demander", "demande", "demandé"], "une question", [
    "poser une question",
    "pose une question",
    "posé une question",
  ]),
  ...forms(["prendre", "prend", "pris"], "une marche", [
    "faire une promenade",
    "fait une promenade",
    "fait une promenade",
  ]),
  ...forms(["prendre", "prend", "pris"], "une chance", [
    "courir un risque",
    "court un risque",
    "couru un risque",
  ]),
  ["au meilleur de ma connaissance", "à ma connaissance"],
  ["au meilleur de notre connaissance", "à notre connaissance"],
  ["au meilleur de mes capacités", "de mon mieux"],
  ["en autant que", ["pourvu que", "dans la mesure où"]],
  ["termes et conditions", "conditions générales"],
  ["combien loin", "à quelle distance"],
  ["salle à dîner", "salle à manger"],
  ["cuillère à thé", "cuillère à café"],
  ["pour faire une longue histoire courte", "bref"],
  ["être supposé être", "être censé être"],
  ["est supposé être", "est censé être"],
  ["sont supposés être", "sont censés être"],
  ["réaliser que", "se rendre compte que"],
  ["réalise que", "se rend compte que"],
  ["réalisé que", "rendu compte que"],
  // English words with a plain French equivalent.
  ["meeting", "réunion"],
  ["meetings", "réunions"],
  ["deadline", "date limite"],
  ["deadlines", "dates limites"],
  ["feedback", "retour"],
  ["brainstorming", "remue-méninges"],
  ["checker", "vérifier"],
  ["booker", "réserver"],
  ["forwarder", "transférer"],
  ["canceller", "annuler"],
  ["céduler", "planifier"],
  // More English loanwords with a French word of their own.
  ["challenge", "défi"],
  ["challenges", "défis"],
  ["timing", "calendrier"],
  [["back-up", "backup"], "sauvegarde"],
  ["newsletter", "lettre d'information"],
  ["newsletters", "lettres d'information"],
  ["follower", "abonné"],
  ["followers", "abonnés"],
  ["hashtag", "mot-dièse"],
  ["hashtags", "mots-dièse"],
  ["fake news", "infox"],
  ["staff", "personnel"],
  ["briefing", "réunion d'information"],
  ["debriefing", "compte rendu"],
  ["workshop", "atelier"],
  ["workshops", "ateliers"],
  [["checklist", "check-list"], "liste de contrôle"],
  [["checklists", "check-lists"], "listes de contrôle"],
  ["roadmap", "feuille de route"],
  ["kick-off", "lancement"],
  ["slides", "diapositives"],
  ["follow-up", "suivi"],
  ["soft skills", "savoir-être"],
  ["know-how", "savoir-faire"],
  ["best practices", "bonnes pratiques"],
  ["e-learning", "formation en ligne"],
  ["packaging", "emballage"],
  ["sponsoriser", "parrainer"],
  ["sponsorisé", "parrainé"],
  ["sponsorisée", "parrainée"],
  ["flyer", "prospectus"],
  ["flyers", "prospectus"],
  [["e-mail", "email"], "courriel"],
  [["e-mails", "emails"], "courriels"],
  ["uploader", "téléverser"],
  ["downloader", "télécharger"],
  ["liker", "aimer"],
  ["liké", "aimé"],
  ["checké", "vérifié"],
  ["booké", "réservé"],
  ["forwardé", "transféré"],
  ["cancellé", "annulé"],
  ["updater", "mettre à jour"],
  ["asap", "dès que possible"],
  ["anyway", "de toute façon"],
  ["brainstorm", "remue-méninges"],
  ["faire du shopping", "faire les magasins"],
  // More calques of English phrasings.
  ...forms(["suis", "es", "est", "sommes", "êtes", "sont", "être"], "sous l'impression", [
    "ai l'impression",
    "as l'impression",
    "a l'impression",
    "avons l'impression",
    "avez l'impression",
    "ont l'impression",
    "avoir l'impression",
  ]),
  ["sur une base régulière", "régulièrement"],
  ["sur une base quotidienne", "quotidiennement"],
  ["sur une base hebdomadaire", "chaque semaine"],
  ["sur une base mensuelle", "chaque mois"],
  ["sur une base annuelle", "chaque année"],
  ["sur une base volontaire", "volontairement"],
  ["à l'année longue", "toute l'année"],
  ["à la journée longue", "toute la journée"],
  ["à la semaine longue", "toute la semaine"],
  ["laissez-moi savoir", "faites-moi savoir"],
  ["laisse-moi savoir", "fais-moi savoir"],
  ["laissez-nous savoir", "faites-nous savoir"],
  ["laisse-nous savoir", "fais-nous savoir"],
  ["jusqu'à date", "jusqu'à présent"],
  ...forms(["me sens", "te sens", "se sent", "nous sentons", "vous sentez"], "confortable", [
    "me sens à l'aise",
    "te sens à l'aise",
    "se sent à l'aise",
    "nous sentons à l'aise",
    "vous sentez à l'aise",
  ]),
  ["se sentent confortables", "se sentent à l'aise"],
  ["se sentir confortable", "se sentir à l'aise"],
  ...forms(["paver", "pave", "pavent", "pavé"], "la voie", [
    "ouvrir la voie",
    "ouvre la voie",
    "ouvrent la voie",
    "ouvert la voie",
  ]),
  ...forms(["prendre", "prend", "prennent", "pris", "prenez"], "avantage de", [
    "tirer parti de",
    "tire parti de",
    "tirent parti de",
    "tiré parti de",
    "tirez parti de",
  ]),
  ...forms(["faire", "fait", "font"], "du temps supplémentaire", [
    "faire des heures supplémentaires",
    "fait des heures supplémentaires",
    "font des heures supplémentaires",
  ]),
  ["à toutes fins pratiques", "en pratique"],
  ["de façon à ce que", "de façon que"],
  ["de manière à ce que", "de manière que"],
  ["faire face à la musique", "assumer les conséquences"],
  ["à tout événement", "en tout cas"],
  ["à l'effet que", ["voulant que", "selon laquelle", "selon lequel"]],
  ...forms(["mettre", "met", "mettent", "mis", "mets", "mettons", "mettez"], "l'emphase sur", [
    "mettre l'accent sur",
    "met l'accent sur",
    "mettent l'accent sur",
    "mis l'accent sur",
    "mets l'accent sur",
    "mettons l'accent sur",
    "mettez l'accent sur",
  ]),
  ...forms(["sauver", "sauve", "sauvent", "sauvé", "sauvez"], "du temps", [
    "gagner du temps",
    "gagne du temps",
    "gagnent du temps",
    "gagné du temps",
    "gagnez du temps",
  ]),
  ...forms(["sauver", "sauve", "sauvent", "sauvé", "sauvez"], "de l'argent", [
    "économiser de l'argent",
    "économise de l'argent",
    "économisent de l'argent",
    "économisé de l'argent",
    "économisez de l'argent",
  ]),
  ...forms(["dépenser", "dépense", "dépensent", "dépensé"], "du temps", [
    "passer du temps",
    "passe du temps",
    "passent du temps",
    "passé du temps",
  ]),
  ...forms(["appliquer", "applique", "appliqué"], "à un poste", [
    "postuler à un poste",
    "postule à un poste",
    "postulé à un poste",
  ]),
  ...forms(["appliquer", "applique", "appliqué"], "sur un poste", [
    "postuler à un poste",
    "postule à un poste",
    "postulé à un poste",
  ]),
  ["avoir un bon temps", "passer du bon temps"],
  ...forms(["passer", "passe", "passez", "passé"], "un bon temps", [
    "passer du bon temps",
    "passe du bon temps",
    "passez du bon temps",
    "passé du bon temps",
  ]),
  ["il me fait plaisir de", "j'ai le plaisir de"],
  ["il nous fait plaisir de", "nous avons le plaisir de"],
  ["breuvage", "boisson"],
  ["breuvages", "boissons"],
  // More pleonasms.
  ...forms(["entrer", "entre", "entrons", "entrez", "entrent", "entré"], "dedans"),
  ...forms(["unir", "unit", "unissent", "uni", "joindre", "joint", "joignent"], "ensemble"),
  ...forms(["assembler", "assemble", "assemblent", "assemblé"], "ensemble"),
  ...forms(["fusionner", "fusionne", "fusionnent", "fusionné"], "ensemble"),
  ...forms(["associer", "associe", "associent", "associé"], "ensemble"),
  ...forms(["cohabiter", "cohabite", "cohabitent", "coexister", "coexiste"], "ensemble"),
  ["hémorragie de sang", "hémorragie"],
  ["taux d'alcoolémie", "alcoolémie"],
  ["petite fillette", "fillette"],
  ["petites fillettes", "fillettes"],
  ["petit garçonnet", "garçonnet"],
  ["petits garçonnets", "garçonnets"],
  ["opinion personnelle", "opinion"],
  ["opinions personnelles", "opinions"],
  ["vers environ", ["vers", "environ"]],
  ["environ à peu près", ["environ", "à peu près"]],
  ["à peu près environ", ["à peu près", "environ"]],
  ...["excellent", "excellente", "excellents", "excellentes", "magnifique", "magnifiques"].map(
    (f): PhraseRow => [`très ${f}`, f],
  ),
  ...["extraordinaire", "extraordinaires", "exceptionnel", "exceptionnelle"].map((f): PhraseRow => [
    `très ${f}`,
    f,
  ]),
  ...["exceptionnels", "exceptionnelles"].map((f): PhraseRow => [`très ${f}`, f]),
  ...forms(["redire", "redit", "redis", "relire", "relit", "relu"], "à nouveau"),
  ...forms(["rouvrir", "rouvre", "rouvert", "revoir", "revois", "revu"], "à nouveau"),
  ...forms(["réitérer", "réitère", "réitéré"], "à nouveau"),
  ...forms(["réitérer", "réitère", "réitéré"], "de nouveau"),
  ...forms(["réitérer", "réitère", "réitéré"], "encore"),
  ["enfin finalement", ["enfin", "finalement"]],
  ["d'abord en premier", ["d'abord", "en premier"]],
  ["premiers débuts", "débuts"],
  ["bref résumé", "résumé"],
  ["brefs résumés", "résumés"],
  ["s'avère vrai", ["s'avère exact", "se vérifie"]],
  ["s'avèrent vrais", ["s'avèrent exacts", "se vérifient"]],
  ["s'avérer vrai", ["s'avérer exact", "se vérifier"]],
  ["avéré vrai", "avéré exact"],
  ...forms(["ajourner", "ajourne", "ajourné", "différer", "diffère", "différé"], "à plus tard"),
  ...forms(["prévoir", "prévois", "prévoit", "prévu", "prévenir", "prévenu"], "d'avance"),
  ...forms(["prédire", "prédit", "prédisent"], "à l'avance"),
  ...forms(["anticiper", "anticipe", "anticipent", "anticipé"], "à l'avance"),
  ["s'envoler dans les airs", "s'envoler"],
  ["s'envole dans les airs", "s'envole"],
  ["s'envolent dans les airs", "s'envolent"],
  ...forms(["voler", "vole", "volent"], "dans les airs"),
  ["consensus général", "consensus"],
  ...forms(["importer", "importe", "importent", "importé", "importés"], "de l'étranger"),
  ...forms(["exporter", "exporte", "exportent", "exporté", "exportés"], "à l'étranger"),
  ["cadeau gratuit", "cadeau"],
  ["cadeaux gratuits", "cadeaux"],
  ["quotidien de tous les jours", "quotidien"],
  ["actuellement en cours", "en cours"],
  ...["les uns", "les unes"].flatMap((who) =>
    forms(["se succéder", "se succèdent", "se succédaient"], `${who} après les autres`, [
      "se succéder",
      "se succèdent",
      "se succédaient",
    ]),
  ),
  ["suffisamment assez", ["suffisamment", "assez"]],
  ["assez suffisamment", ["assez", "suffisamment"]],
  ["plus préférable", "préférable"],
  ["encore à nouveau", ["encore", "à nouveau"]],
  ["aussi également", ["aussi", "également"]],
  ["également aussi", ["également", "aussi"]],
  ...style.STYLE,
];
