import type { PhraseRow } from "../englishPhraseTables";

// Sound-alike small words inside frames where only one spelling is French. Every row's typed
// form is never correct as written; frames that need the context of a verb or a subject live in
// homophones.ts.

/** One row per frame: `~` stands for the typed word, replaced by the intended one. */
const one = (frames: string[], typed: string, fixed: string): PhraseRow[] =>
  frames.map((frame) => [frame.replace("~", typed), frame.replace("~", fixed)]);

/** Rows for englishPhraseCorrections (contextual grammar). */
export const PHRASES: readonly PhraseRow[] = [
  // "à": prepositional locutions whose "a" can never be the verb.
  ...one(
    [
      "tout ~ fait",
      "tout ~ coup",
      "tout ~ l'heure",
      "grâce ~ toi",
      "grâce ~ vous",
      "grâce ~ lui",
      "grâce ~ eux",
      "face ~ face",
      "quant ~",
      "jusqu'~",
      "suite ~ votre",
      "suite ~ ton",
      "suite ~ notre",
      "par rapport ~",
      "contrairement ~",
      "pas ~ pas",
      "peu ~ peu",
      "petit ~ petit",
      "côte ~ côte",
      "nez ~ nez",
      "goutte ~ goutte",
      "mise ~ jour",
      "au fur et ~ mesure",
      "de temps ~ autre",
      "~ cause de",
      "~ cause du",
      "~ cause des",
      "~ partir de",
      "~ partir du",
      "~ travers",
      "~ côté de",
      "~ côté du",
      "~ peu près",
      "~ propos de",
      "~ condition que",
      "~ l'égard de",
      "~ l'instar de",
      "~ la hâte",
      "~ l'aveuglette",
      "~ la rescousse",
      "~ l'improviste",
      "~ contrecœur",
      "~ vol d'oiseau",
      "~ temps plein",
      "~ temps partiel",
      "~ plein temps",
      "~ coup sûr",
      "garde ~ vue",
      "machine ~ laver",
      "machines ~ laver",
      "fer ~ repasser",
      "salle ~ manger",
      "bonjour ~ tous",
      "merci ~ tous",
      "rien ~ voir",
    ],
    "a",
    "à",
  ),
  ["a tort et a travers", "à tort et à travers"],
  // "où": "d'ou", "par ou", "jusqu'ou" and "n'importe ou" never mean "or".
  ...one(
    [
      "d'~",
      "jusqu'~",
      "n'importe ~",
      "au moment ~",
      "à l'instant ~",
      "dans la mesure ~",
      "au cas ~",
    ],
    "ou",
    "où",
  ),
  ["plus où moins", "plus ou moins"],
  // "sûr": certain.
  ...one(
    [
      "bien ~,",
      "j'en suis ~",
      "en suis-je ~",
      "~ et certain",
      "à coup ~",
      "en lieu ~",
      "est ~ de lui",
      "est ~ d'elle",
      "suis ~ de moi",
      "es ~ de toi",
      "suis ~ que",
      "es ~ que",
      "est ~ que",
      "pas ~ que",
      "~ de soi",
    ],
    "sur",
    "sûr",
  ),
  ...one(["suis ~ que", "es ~ que", "est ~ que", "est ~ d'elle", "~ d'elle-même"], "sure", "sûre"),
  ...one(["sont ~ que", "sommes ~ que", "êtes ~ que", "sont ~ d'eux"], "surs", "sûrs"),
  ...one(["sont ~ que", "sommes ~ que", "êtes ~ que", "sources ~", "mains ~"], "sures", "sûres"),
  // "sont", "ont", "on" after a subject pronoun.
  ...one(
    ["ils ~", "elles ~", "ne ~ pas", "ne ~ plus", "ne ~ jamais", "ne ~ guère", "ne ~ que"],
    "son",
    "sont",
  ),
  ...one(["ils ~", "elles ~"], "on", "ont"),
  ...one(["si ~ peut", "si ~ veut", "si ~ doit", "si ~ va"], "ont", "on"),
  // "se" / "ce", "s'est" / "c'est".
  ...one(
    ["~ qui", "~ que", "~ qu'il", "~ qu'elle", "~ qu'on", "tout ~ qui", "tout ~ que"],
    "se",
    "ce",
  ),
  ...one(["~ matin", "~ soir", "~ week-end", "~ jour-là", "~ moment-là"], "se", "ce"),
  // "Elle c'est ma sœur" dislocates without a comma: only "il" and "on" are never stressed.
  ...one(["il ~", "on ~", "il ne ~", "elle ne ~", "on ne ~"], "c'est", "s'est"),
  ...one(["il ~", "on ~"], "c'était", "s'était"),
  // "ça" before a pronoun or a negation: a possessive never comes there.
  ...one(
    ["~ me", "~ m'", "~ te", "~ t'", "~ se", "~ s'", "~ ne", "~ n'", "~ y est", "~ fait mal"],
    "sa",
    "ça",
  ),
  // "dû": owed to, had to.
  ...one(["est ~ à", "est ~ au", "était ~ à", "était ~ au", "sera ~ à"], "du", "dû"),
  // "dès": from, as soon as.
  ...one(
    [
      "~ que",
      "~ qu'il",
      "~ qu'elle",
      "~ qu'on",
      "~ lors",
      "~ aujourd'hui",
      "~ demain",
      "~ maintenant",
      "~ à présent",
      "~ le début",
      "~ la fin",
      "~ l'aube",
      "~ le départ",
      "~ la naissance",
    ],
    "des",
    "dès",
  ),
  ...one(["~ que", "~ qu'il", "~ à présent", "~ lors"], "dés", "dès"),
  // "peu" / "peut" / "peux".
  // "l'un peut", "quelqu'un peut": "un" there is a pronoun.
  ...one(
    [
      "un ~ de",
      "un ~ plus",
      "un ~ moins",
      "un ~ trop",
      "très ~",
      "à ~ près",
      "il y a ~ de",
      "~ à peu",
    ],
    "peut",
    "peu",
  ),
  ...one(["il ~", "elle ~", "on ~", "il ne ~", "on ne ~"], "peu", "peut"),
  ...one(["je ~", "tu ~", "je ne ~", "tu ne ~"], "peu", "peux"),
  // "leur" before a verb is the pronoun: it never takes an s.
  ...one(
    ["je ~", "tu ~", "il ~", "elle ~", "on ~", "ils ~", "elles ~", "ne ~", "je ne ~"],
    "leurs",
    "leur",
  ),
  // "quant à" / "quand".
  ...one(
    ["~ à moi", "~ à toi", "~ à lui", "~ à elle", "~ à nous", "~ à vous", "~ à eux", "~ à elles"],
    "quand",
    "quant",
  ),
  ...one(
    [
      "~ il",
      "~ elle",
      "~ on",
      "~ je",
      "~ j'",
      "~ tu",
      "~ nous",
      "~ ils",
      "~ elles",
      "~ même",
      "~ bien même",
    ],
    "quant",
    "quand",
  ),
  // "as" / "a" after the subject.
  ...one(["tu ~"], "a", "as"),
  ...one(["il ~", "elle ~", "on ~"], "as", "a"),
  // "est" fixed in "qui plus est", "n'en est rien", "m'est égal".
  ...one(["qui plus ~", "m'~ égal", "t'~ égal"], "ait", "est"),
  // "voilà": "voila" is the past of "voiler" ("elle se voila le visage"), so only frames.
  ...one(
    [
      "et ~",
      "que ~",
      "me ~",
      "te ~",
      "nous ~",
      "vous ~",
      "le ~",
      "les ~",
      "en ~",
      "~ pourquoi",
      "~ tout",
      "~ qui",
      "~ ce que",
      "~ ce qui",
    ],
    "voila",
    "voilà",
  ),
  // "jusque" elides before "à" and its contractions.
  ["jusque à", "jusqu'à"],
  ["jusque au", "jusqu'au"],
  ["jusque aux", "jusqu'aux"],
  // Sound-alike nouns inside fixed phrases: "de bonne foi", "tenir compte", "point de vue".
  ...one(
    ["de bonne ~", "de mauvaise ~", "sans ~ ni loi", "digne de ~", "ma ~ !", "profession de ~"],
    "foie",
    "foi",
  ),
  ["foie en Dieu", "foi en Dieu"],
  ["foi gras", "foie gras"],
  ...one(["une ~", "à la ~", "il était une ~", "chaque ~"], "foie", "fois"),
  ["chaque foi", "chaque fois"],
  ...one(
    [
      "~ agréer",
      "~ trouver",
      "~ me",
      "~ m'",
      "~ nous",
      "~ excuser",
      "~ noter",
      "~ patienter",
      "~ accepter",
      "~ recevoir",
      "~ croire",
    ],
    "veillez",
    "veuillez",
  ),
  ...one(["~ à ce que", "~ sur", "~ bien à"], "veuillez", "veillez"),
  ...one(["à la ~", "~ ingrate", "~ ardue", "~ difficile"], "tache", "tâche"),
  ...one(
    ["~ de café", "~ de vin", "~ de sang", "~ de graisse", "~ d'encre", "~ de rousseur"],
    "tâche",
    "tache",
  ),
  ["tâches de rousseur", "taches de rousseur"],
  ...one(
    [
      "à bon ~",
      "en fin de ~",
      "en ligne de ~",
      "~ tenu",
      "tenir ~",
      "tient ~",
      "rendre ~",
      "rend ~",
      "~ en banque",
      "tout ~ fait",
      "au bout du ~",
    ],
    "conte",
    "compte",
  ),
  ...one(["règlement de ~", "règlements de ~", "cour des ~"], "contes", "comptes"),
  ["compte de fées", "conte de fées"],
  ["comptes de fées", "contes de fées"],
  ...one(["confiance en ~", "va de ~", "chez ~"], "soit", "soi"),
  ["ver à soi", "ver à soie"],
  ["soit disant", "soi-disant"],
  ["soit-disant", "soi-disant"],
  ["soit-même", "soi-même"],
  ...one(["~ à tout"], "près", "prêt"),
  ...one(["à peu ~", "tout ~"], "prés", "près"),
  ["fin près", "fin prêt"],
  ...one(
    ["à ~ de", "de ~", "du ~ de", "d'un ~", "de l'autre ~", "à son ~", "~ gauche", "~ droit"],
    "coté",
    "côté",
  ),
  ["à ses cotés", "à ses côtés"],
  ["cote à cote", "côte à côte"],
  ["cote de bœuf", "côte de bœuf"],
  ...one(
    ["à ~ d'œil", "à perte de ~", "garde à ~", "en ~ de", "point de ~", "à première ~"],
    "vu",
    "vue",
  ),
  ...one(["faire ~ honorable", "mis à l'~", "mise à l'~"], "amande", "amende"),
  ...one(["pâte d'~", "lait d'~"], "amende", "amande"),
  ["au cour de", "au cours de"],
  ["à cour terme", "à court terme"],
  ...one(["à ~ terme", "coupe ~", "couper ~", "tourner ~", "prendre de ~"], "cours", "court"),
  ["cours-circuit", "court-circuit"],
  ...one(["par ~ de conséquence", "en ~ de", "~ ferrée", "~ sans issue"], "voix", "voie"),
  ...one(["~ off", "à haute ~", "à ~ basse"], "voie", "voix"),
  ...one(["~ café", "~-café", "~ déjeuner"], "pose", "pause"),
  ...one(
    [
      "de ma ~",
      "de ta ~",
      "de sa ~",
      "de votre ~",
      "de leur ~",
      "de la ~ de",
      "pour ma ~",
      "nulle ~",
      "quelque ~",
      "d'autre ~",
      "à ~ ça",
    ],
    "par",
    "part",
  ),
  ...one(["faire ~ de", "fait ~ de", "fais ~ de"], "par", "part"),
  ...one(
    ["~ contre", "~ rapport", "~ exemple", "~ ailleurs", "~ hasard", "~ conséquent"],
    "part",
    "par",
  ),
  ...one(
    ["~ être", "~ faire", "~ avoir", "~ savoir", "~ aller", "~ venir", "~ partir", "~ arriver"],
    "sensé",
    "censé",
  ),
  ...one(["~ être", "~ faire", "~ avoir"], "sensée", "censée"),
  ...one(["~ être", "~ faire", "~ avoir"], "sensés", "censés"),
  ...one(["~ être", "~ faire", "~ avoir"], "sensées", "censées"),
  ...one(
    [
      "~ les jours",
      "~ les deux",
      "~ les ans",
      "~ les matins",
      "~ les soirs",
      "~ les mois",
      "~ les gens",
    ],
    "tout",
    "tous",
  ),
  ["de tout côtés", "de tous côtés"],
  ["temps pis", "tant pis"],
  ["temps mieux", "tant mieux"],
  // "de temps en temps que" is fine: only "en temps que tel(le)".
  ["en temps que tel", "en tant que tel"],
  ["en temps que telle", "en tant que telle"],
  ["de tant en tant", "de temps en temps"],
  ...one(["~ que prévu", "le ~ possible", "au ~"], "plutôt", "plus tôt"),
  ["m'en fou", "m'en fous"],
  ["s'en fou", "s'en fout"],
  ["au dépend de", "aux dépens de"],
  ["aux dépend de", "aux dépens de"],
  ["aux dépends de", "aux dépens de"],
  ...one(
    ["faire ~ de", "fait ~ de", "font ~ de", "faisait ~ de", "fais ~ de", "faisant ~ de"],
    "parti",
    "partie",
  ),
  ["au font", "au fond"],
  ["à font", "à fond"],
  // Subject + elided "ne" or object glued to the auxiliary.
  ...one(["il ~", "elle ~", "on ~", "qui ~"], "na", "n'a"),
  ...one(["ils ~", "elles ~", "qui ~"], "mont", "m'ont"),
];

// Compound numbers below a hundred take hyphens ("vingt-deux", "quatre-vingt-dix"); "et un"
// and "et onze" keep their spaces.
const UNITS = ["deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf"];
const NUMBERS: PhraseRow[] = [
  ...["vingt", "trente", "quarante", "cinquante", "soixante"].flatMap((ten) =>
    UNITS.map((unit): PhraseRow => [`${ten} ${unit}`, `${ten}-${unit}`]),
  ),
  ...["sept", "huit", "neuf"].map((unit): PhraseRow => [`dix ${unit}`, `dix-${unit}`]),
  ["soixante dix", "soixante-dix"],
  ...["douze", "treize", "quatorze", "quinze", "seize"].map((teen): PhraseRow => [
    `soixante ${teen}`,
    `soixante-${teen}`,
  ]),
  ["quatre vingt", "quatre-vingt"],
  ["quatre vingts", "quatre-vingts"],
  ...[...UNITS, "un", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"].map(
    (unit): PhraseRow => [`quatre vingt ${unit}`, `quatre-vingt-${unit}`],
  ),
  ...[...UNITS, "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize"].map(
    (unit): PhraseRow => [`quatre-vingt ${unit}`, `quatre-vingt-${unit}`],
  ),
];

/** Rows for englishClosedCompounds: hyphens a compound needs, or must not have. */
export const COMPOUNDS: readonly PhraseRow[] = [
  ...NUMBERS,
  // Imperative + pronoun.
  ...[
    "dis",
    "dites",
    "excuse",
    "excusez",
    "laisse",
    "laissez",
    "écoute",
    "écoutez",
    "regarde",
    "regardez",
    "attends",
    "attendez",
    "donne",
    "donnez",
    "montre",
    "montrez",
    "aide",
    "aidez",
    "crois",
    "croyez",
    "rappelle",
    "rappelez",
  ].map((verb): PhraseRow => [`${verb} moi`, `${verb}-moi`]),
  ...["dépêche", "tais", "calme", "lève", "assieds", "sers"].map((verb): PhraseRow => [
    `${verb} toi`,
    `${verb}-toi`,
  ]),
  ...["vas", "allez", "allons"].map((verb): PhraseRow => [`${verb} y`, `${verb}-y`]),
  // Emphatic pronouns.
  ...["moi", "toi", "lui", "soi"].map((pronoun): PhraseRow => [
    `${pronoun} même`,
    `${pronoun}-même`,
  ]),
  ...["nous", "eux", "elles"].map((pronoun): PhraseRow => [`${pronoun} mêmes`, `${pronoun}-mêmes`]),
  ["quelques uns", "quelques-uns"],
  ["quelques unes", "quelques-unes"],
  // Fixed compounds written apart.
  ["grand mère", "grand-mère"],
  ["grand père", "grand-père"],
  ["grands parents", "grands-parents"],
  ["arc en ciel", "arc-en-ciel"],
  ["chef d'œuvre", "chef-d'œuvre"],
  ["chef d'oeuvre", "chef-d'œuvre"],
  ["après midi", "après-midi"],
  ["week end", "week-end"],
  ["week ends", "week-ends"],
  ["là haut", "là-haut"],
  ["là dessus", "là-dessus"],
  ["là dessous", "là-dessous"],
  ["là dedans", "là-dedans"],
  ["ci dessus", "ci-dessus"],
  ["ci dessous", "ci-dessous"],
  ["ci joint", "ci-joint"],
  ["ci jointe", "ci-jointe"],
  ["ci après", "ci-après"],
  ["la bas", "là-bas"],
  ["la haut", "là-haut"],
  ["porte monnaie", "porte-monnaie"],
  ["porte clés", "porte-clés"],
  ["tire bouchon", "tire-bouchon"],
  ["sous sol", "sous-sol"],
  ["sans abri", "sans-abri"],
  ["demi heure", "demi-heure"],
  ["demi journée", "demi-journée"],
  ["demi douzaine", "demi-douzaine"],
  ["à mi chemin", "à mi-chemin"],
  ["pare brise", "pare-brise"],
  ["pare chocs", "pare-chocs"],
  ["qu'est ce que", "qu'est-ce que"],
  ["qu'est ce qui", "qu'est-ce qui"],
  ["peu-être", "peut-être"],
  ...["un", "le", "mon", "ton", "son", "votre", "notre", "au", "du", "ce"].map((det): PhraseRow => [
    `${det} rendez vous`,
    `${det} rendez-vous`,
  ]),
  ...["le", "du", "son", "leur", "votre", "notre"].map((det): PhraseRow => [
    `${det} savoir faire`,
    `${det} savoir-faire`,
  ]),
  ...["le", "du", "son", "leur", "votre", "notre"].map((det): PhraseRow => [
    `${det} bien être`,
    `${det} bien-être`,
  ]),
  // Hyphens these never take.
  ["compte-rendu", "compte rendu"],
  ["compte-tenu", "compte tenu"],
  ["pomme-de-terre", "pomme de terre"],
  ["pommes-de-terre", "pommes de terre"],
  ["bande-dessinée", "bande dessinée"],
  ["bandes-dessinées", "bandes dessinées"],
  ["petit-ami", "petit ami"],
  ["petite-amie", "petite amie"],
  ["lieu-commun", "lieu commun"],
  ["état-civil", "état civil"],
  ["en-dessous", "en dessous"],
  ["en-dessus", "en dessus"],
  ["tout-à-fait", "tout à fait"],
  ["ici-même", "ici même"],
  ["entre-eux", "entre eux"],
  ["entre-elles", "entre elles"],
  ["porte-feuille", "portefeuille"],
  ["marche-pied", "marchepied"],
];
