import { SUPPORTED_LANGUAGES } from "../shared/lang.ts";
import { isWhiteSpace } from "../shared/utils.ts";
import { SpacingRulesHandler, Spacing, SPACING_RULES } from "./spacingRulesHandler.ts";
import { Capitalization } from "./capitalizationHelper.ts";
import { PredictionInputProcessor } from "./predictionInputProcessor.ts";
import { TemplateExpander } from "./TemplateExpander.ts";
import { UserDictionaryManager } from "./UserDictionaryManager.ts";
import { TextExpansionManager } from "./TextExpansionManager.ts";

const SUGGESTION_COUNT = 5;
const MIN_WORD_LENGTH_TO_PREDICT = 1;

class PresageHandler {
  /**
   * Creates a new instance of the PresageManager class
   * @constructor
   * @param {Object} Module - The module object containing the Presage and PresageCallback classes
   */
  constructor(Module) {
    // Set the module object
    this.Module = Module;

    // Initialize variables
    this.lastPrediction = {}; // Last presage prediction per language
    this.libPresage = {}; // libPresage module per language
    this.libPresageCallback = {}; // PresageCallback implementation per language
    this.libPresageCallbackImpl = {}; // PresageCallback implementation object per language
    this.numSuggestions = SUGGESTION_COUNT; // Number of suggestions generated by presage engine
    this.minWordLengthToPredict = MIN_WORD_LENGTH_TO_PREDICT; // Minimum characters typed by user to start prediction
    this.predictNextWordAfterSeparatorChar = MIN_WORD_LENGTH_TO_PREDICT === 0; // Predict next word after separator char
    this.insertSpaceAfterAutocomplete = true; // Automatically insert space after autocomplete
    this.autoCapitalize = true; // Capitalize the first word of each sentence
    this.applySpacingRules = false; // Apply spacing rules
    this.textExpansions = []; // Text expander config
    this.userDictionaryList = []; // User dictionary
    this.spacingHandler = {} // Spacing rules handler
    this.predictionInputProcessor = new PredictionInputProcessor(
      MIN_WORD_LENGTH_TO_PREDICT,
      this.autoCapitalize
    );


    // Precompiled regular expressions
    this.separatorCharRegEx =
      /\s+|!|"|#|\$|%|&|\(|\)|\*|\+|,|-|\.|\/|:|;|<|=|>|\?|@|\[|\\|\]|\^|_|`|{|\||}|~/;
    this.keepPredCharRegEx = /\[|\(|{|<|\/|-|\*|\+|=|"/; // Subset of separatorCharRegEx - keep predicting after those chars
    this.whiteSpaceRegEx = /\s+/;
    this.whiteSpaceRegExExcludeNewLine = /[^\S\r\n]+/;
    this.letterRegEx = /^\p{L}/u;

    // Initialize Presage and PresageCallback objects for each supported language
    for (const [lang] of Object.entries(SUPPORTED_LANGUAGES)) {
      if (lang === "auto_detect") continue;
      try {
        // Initialize the lastPrediction object for the language
        this.lastPrediction[lang] = { pastStream: "", predictions: [] };

        // Initialize the libPresageCallback object for the language
        this.libPresageCallback[lang] = {
          pastStream: "",

          /**
           * Gets the past stream for the PresageCallback object
           * @returns {string} The past stream
           */
          get_past_stream: function () {
            return this.pastStream;
          },

          /**
           * Gets the future stream for the PresageCallback object
           * @returns {string} An empty string
           */
          get_future_stream: function () {
            return "";
          },
        };

        // Implement the libPresageCallback object for the language
        this.libPresageCallbackImpl[lang] =
          this.Module.PresageCallback.implement(this.libPresageCallback[lang]);

        // Initialize the libPresage object for the language
        this.libPresage[lang] = new this.Module.Presage(
          this.libPresageCallbackImpl[lang],
          "resources_js/" + lang + "/presage.xml",
        );
      } catch (error) {
        console.log(
          "Failed to create Presage instance for %s language: %s",
          lang,
          error,
        );
      }
    }

    // Initialize managers
    this.textExpansionManager = new TextExpansionManager(this.Module, this.libPresage);
    this.userDictionaryManager = new UserDictionaryManager(this.Module, this.libPresage);
  }

  /**
    Sets the configuration for the Presage engine.
    @param {number} numSuggestions - The number of suggestions to generate.
    @param {number} minWordLengthToPredict - The minimum number of characters that the user must type before the engine starts predicting.
    @param {boolean} insertSpaceAfterAutocomplete - Whether to insert a space after the autocomplete suggestion.
    @param {boolean} autoCapitalize - Whether to capitalize the first word of each sentence.
    @param {boolean} applySpacingRules - Whether to apply spacing rules.
    @param {Array} textExpansions - An array of text expansions to configure the engine.
    */
  setConfig(
    numSuggestions,
    minWordLengthToPredict,
    insertSpaceAfterAutocomplete,
    autoCapitalize,
    applySpacingRules,
    textExpansions,
    variableExpansion,
    timeFormat,
    dateFormat,
    userDictionaryList,
  ) {
    this.numSuggestions = numSuggestions;
    this.minWordLengthToPredict = Math.max(0, minWordLengthToPredict);
    this.predictNextWordAfterSeparatorChar = this.minWordLengthToPredict === 0;
    this.insertSpaceAfterAutocomplete = insertSpaceAfterAutocomplete;
    this.autoCapitalize = autoCapitalize;
    this.applySpacingRules = applySpacingRules;
    this.textExpansions = textExpansions;
    this.variableExpansion = variableExpansion;
    this.timeFormat = timeFormat;
    this.dateFormat = dateFormat;
    this.userDictionaryList = userDictionaryList;
    this.textExpansionManager.setTextExpansions(textExpansions);
    this.userDictionaryManager.setUserDictionaryList(userDictionaryList);
    this.spacingHandler = new SpacingRulesHandler(insertSpaceAfterAutocomplete);
    for (const [, libPresage] of Object.entries(this.libPresage)) {
      libPresage.config(
        "Presage.Selector.SUGGESTIONS",
        this.numSuggestions.toString(),
      );
    }
  }

  parseStringTemplate(str, obj) {
    return TemplateExpander.parseStringTemplate(str, obj);
  }

  /**
   * Expand template variables
   *
   * @param {string} lang The language to use for prediction.
   * @returns {Object} An expanded template variables
   */
  getExpandedVariables(lang) {
    return TemplateExpander.getExpandedVariables(
      lang,
      this.variableExpansion,
      this.timeFormat,
      this.dateFormat
    );
  }

  /**
   * Remove the previous sentence from a given array of words.
   * @param {string[]} wordArrayOrig - The original array of words to be modified.
   * @returns {object} An object containing the modified array of words and a boolean value indicating whether a new sentence was found.
   */
  removePrevSentence(wordArrayOrig) {
    // Use the new PredictionInputProcessor utility
    return this.predictionInputProcessor.removePrevSentence(wordArrayOrig);
  }

  /**
  Checks if prediction should be run based on the last word and whether it ends with space
  @param {string} lastWord - The last word in the input string
  @param {boolean} endsWithSpace - Indicates if the input string ends with a space character
  @returns {boolean} - Whether or not to run prediction
  */
  checkDoPrediction(lastWord, endsWithSpace) {
    // Use the new PredictionInputProcessor utility
    return this.predictionInputProcessor.checkDoPrediction(
      lastWord,
      endsWithSpace,
      this.numSuggestions,
      this.predictNextWordAfterSeparatorChar
    );
  }

  /**
   * Processes input for prediction by modifying the input string and setting
   * flags to indicate whether to perform auto-capitalization and prediction.
   *
   * @param {string} predictionInput - The input string to process.
   * @param {string} language - The language of the input string.
   * @returns {object} - An object containing the processed input string, last word,
   *                     a flag indicating whether to perform prediction, and
   *                     a flag indicating whether to perform auto-capitalization.
   */
  processInput(predictionInput, language) {
    // Use the new PredictionInputProcessor utility
    return this.predictionInputProcessor.processInput(
      predictionInput,
      language,
      this.numSuggestions,
      this.predictNextWordAfterSeparatorChar
    );
  }

  /**
   * Handles predictions for a given input and language.
   *
   * @param {string} predictionInput The input to predict on.
   * @param {string} lang The language to use for prediction.
   * @returns {Array} An array of predicted results.
   */
  doPredictionHandler(predictionInput, lang) {
    // If the input is the same as the previous prediction input, return the previous prediction results
    if (predictionInput === this.lastPrediction[lang].pastStream) {
      return this.lastPrediction[lang].predictions.slice();
    }

    // Perform prediction
    this.libPresageCallback[lang].pastStream = predictionInput;
    const predictions = [];
    const predictionsNative = this.libPresage[lang].predictWithProbability();

    const expandedTemplateVariables = this.getExpandedVariables(lang);

    // Loop through the predicted results and add them to the predictions array
    for (let i = 0; i < predictionsNative.size(); i++) {
      const result = predictionsNative.get(i);
      let text = null;
      try {
        text = JSON.parse(result.prediction);
      } catch {
        text = result.prediction;
      }

      if (text) {
        text = this.parseStringTemplate(text, expandedTemplateVariables);
        predictions.push(text);
      }
      //result.probability
    }

    // Update the last prediction with the current input and results
    this.lastPrediction[lang] = {
      pastStream: predictionInput,
      predictions: predictions.slice(),
    };

    // Return the predicted results
    return predictions;
  }

  /**
   * Runs prediction for a given input text, next character and language.
   *
   * @param {string} text The input text to predict on.
   * @param {string} nextChar The next character after the input text.
   * @param {string} lang The language to use for prediction.
   * @returns {Object} An object containing predictions and a boolean indicating if a force replacement is needed.
   */
  runPrediction(text, nextChar, lang) {
    let predictions = [];
    let forceReplace = null;

    // Process the input text to get the prediction input, prediction flag and capitalization flag
    const { predictionInput, doPrediction, doCapitalize } = this.processInput(
      text,
      lang,
    );

    // Apply spacing rules if necessary
    if (this.applySpacingRules) {
      forceReplace = this.spacingHandler.applySpacingRules(text);
    }

    // If the Presage library for the given language does not exist, do nothing and return empty predictions
    if (!this.libPresage[lang]) {
      // Do nothing, reply with empty predictions
    }
    // If forceReplace is not set and prediction is necessary, perform the prediction
    else if (!forceReplace && doPrediction) {
      predictions = this.doPredictionHandler(predictionInput, lang);
    }

    // If insertSpaceAfterAutocomplete is true, add a space after each prediction if necessary
    if (this.insertSpaceAfterAutocomplete) {
      if (
        !isWhiteSpace(nextChar, false) &&
        (!(nextChar in SPACING_RULES) ||
          SPACING_RULES[nextChar].spaceBefore === Spacing.INSERT_SPACE)
      ) {
        predictions = predictions.map((pred) => `${pred}\xA0`);
      }
    }

    // Depending on the capitalization flag, modify the predictions accordingly
    switch (doCapitalize) {
      case Capitalization.FirstLetter:
        predictions = predictions.map(
          (pred) => pred.charAt(0).toUpperCase() + pred.slice(1),
        );
        break;
      case Capitalization.WholeWord:
        predictions = predictions.map((pred) => pred.toUpperCase());
        break;
      case Capitalization.None:
      default:
    }

    // Return the predictions and forceReplace flag
    return { predictions, forceReplace };
  }
}

export { PresageHandler };
