/**
 * Fixed English phrases whose conventional form is not in doubt. A row is
 * [typed forms, replacements]; several replacements mean the writer chooses.
 * Matching is whole-word and case-insensitive with any run of spaces between
 * words, so a row stays out whenever its typed form is also ordinary English
 * ("every one of them", "keep on going", "in the other hand she held…").
 */
export type PhraseRow = readonly [
  typed: string | readonly string[],
  replacement: string | readonly string[],
];

export type Pair = string | readonly [typed: string, replacement: string];
/**
 * One row per pair: `~` stands for the pair's first word in the typed forms and
 * for its second in the replacements ("get", or ["flaunt", "flout"]).
 */
export const each = (
  pairs: readonly Pair[],
  typed: string | readonly string[],
  replacement: string | readonly string[],
): PhraseRow[] =>
  pairs.map((pair) => {
    const [from, to] = typeof pair === "string" ? [pair, pair] : pair;
    return [
      [typed].flat().map((form) => form.replace("~", from)),
      [replacement].flat().map((form) => form.replace("~", to)),
    ];
  });
export const POSSESSIVES = ["my", "your", "his", "her", "our", "their"];
export const OWNERS = ["my", "your", "his", "her", "its", "our", "their"];
export const TAKE = ["take", "takes", "took", "taken", "taking"];

/** Eggcorns, misheard idioms and fixed phrases with a wrong word. */
export const PHRASE_CORRECTIONS: readonly PhraseRow[] = [
  [["all of the sudden", "all the sudden", "all of sudden"], "all of a sudden"],
  ["without further adieu", "without further ado"],
  ["much adieu about", "much ado about"],
  [["nip it in the butt", "nip this in the butt"], "nip it in the bud"],
  [["nipped it in the butt", "nipped this in the butt"], "nipped it in the bud"],
  ["tow the line", "toe the line"],
  ["tows the line", "toes the line"],
  ["towed the line", "toed the line"],
  ["towing the line", "toeing the line"],
  ["baited breath", "bated breath"],
  ["case and point", "case in point"],
  [["doggy dog world", "doggie dog world"], "dog-eat-dog world"],
  [["mute point", "moo point"], "moot point"],
  [["old wise tale", "old wives tale", "old wive's tale"], "old wives' tale"],
  [["old wise tales", "old wives tales"], "old wives' tales"],
  ["sneak peak", "sneak peek"],
  ["sneak peaks", "sneak peeks"],
  ["free reign", "free rein"],
  [["deep seeded", "deep-seeded"], "deep-seated"],
  [["wreck havoc", "reek havoc"], "wreak havoc"],
  [["wrecks havoc", "reeks havoc"], "wreaks havoc"],
  [["wrecked havoc", "reeked havoc"], "wreaked havoc"],
  [["wrecking havoc", "reeking havoc"], "wreaking havoc"],
  ...each(POSSESSIVES, "wet ~ appetite", "whet ~ appetite"),
  ["piece of mind", "peace of mind"],
  ["tongue and cheek", "tongue in cheek"],
  ["tongue-and-cheek", "tongue-in-cheek"],
  [["one foul swoop", "one fowl swoop"], "one fell swoop"],
  ["damp squid", "damp squib"],
  ["slight of hand", "sleight of hand"],
  [["statue of limitations", "statue of limitation"], "statute of limitations"],
  ["all intensive purposes", "all intents and purposes"],
  ["unchartered territory", "uncharted territory"],
  ["unchartered waters", "uncharted waters"],
  ["vocal chords", "vocal cords"],
  ["a whole nother", "a whole other"],
  ["extract revenge", "exact revenge"],
  ["hunger pains", "hunger pangs"],
  ...each(POSSESSIVES, "biting ~ time", "biding ~ time"),
  ["bare in mind", "bear in mind"],
  ["bares in mind", "bears in mind"],
  ["bare with me", "bear with me"],
  ["bare with us", "bear with us"],
  ["by in large", "by and large"],
  ["pass mustard", "pass muster"],
  ["dire straights", "dire straits"],
  ["eek out", "eke out"],
  ["eeked out", "eked out"],
  ["eeking out", "eking out"],
  ["by the waste side", "by the wayside"],
  ["in the same vain,", "in the same vein,"],
  ["in the same vain as", "in the same vein as"],
  [["first come, first serve", "first come first serve"], "first come, first served"],
  [["hair's breath", "hairs breath"], "hair's breadth"],
  ["hay day", "heyday"],
  ["make due with", "make do with"],
  [["mind bottling", "mind-bottling"], "mind-boggling"],
  [
    ["nerve wrecking", "nerve-wrecking"],
    ["nerve-racking", "nerve-wracking"],
  ],
  [["on tender hooks", "on tenderhooks"], "on tenterhooks"],
  ["per say", "per se"],
  ["prostrate cancer", "prostate cancer"],
  ["prostrate gland", "prostate gland"],
  [["scott free", "scott-free"], "scot-free"],
  ["shoe-in", "shoo-in"],
  ["through the ringer", "through the wringer"],
  [["worse case scenario", "worse-case scenario"], "worst-case scenario"],
  ["beckon call", "beck and call"],
  ["do diligence", "due diligence"],
  ["on the same token", "by the same token"],
  [["pre-madonna", "pre madonna"], "prima donna"],
  ["irregardless", "regardless"],
  [["visa versa", "vise versa"], "vice versa"],
  ["all be it", "albeit"],
  ["take affect", "take effect"],
  ["takes affect", "takes effect"],
  ["took affect", "took effect"],
  ["taken affect", "taken effect"],
  ...["put", "go", "goes", "went", "come", "came"].map((verb): PhraseRow => [
    `${verb} into affect`,
    `${verb} into effect`,
  ]),
  [["for arguments sake", "for argument sake"], "for argument's sake"],
  ["as oppose to", "as opposed to"],
  ["in regards to", ["regarding", "in regard to"]],
  ["with regards to", ["with regard to", "regarding"]],
  ["a couple of more", "a couple more"],
  ["as if though", ["as if", "as though"]],
  ["in the end of the day", "at the end of the day"],
  ["every since", "ever since"],
  [["pedal to the medal", "peddle to the metal"], "pedal to the metal"],
  ["max exodus", "mass exodus"],
  ["formidable years", "formative years"],
  ["a fare bit", "a fair bit"],
  ["blanketed statement", "blanket statement"],
  [["half hazard", "half-hazard", "halfhazard"], "haphazard"],
  [["half hazardly", "halfhazardly"], "haphazardly"],
  [["rod iron", "rot iron"], "wrought iron"],
  ["scandally clad", "scantily clad"],
  ["more that likely", "more than likely"],
  [["jar dropping", "jar-dropping"], "jaw-dropping"],
  ["sort of speak", "so to speak"],
  [["take it for granite", "take for granite"], "take it for granted"],
  ["taken for granite", "taken for granted"],
  ["low and behold", "lo and behold"],
  ...each(POSSESSIVES, "peak ~ interest", "pique ~ interest"),
  ...each(POSSESSIVES, "peaks ~ interest", "piques ~ interest"),
  ...each(POSSESSIVES, "peaked ~ interest", "piqued ~ interest"),
  ...each(POSSESSIVES, "peaking ~ interest", "piquing ~ interest"),
  ["chalk full of", "chock-full of"],
  ["expresso", "espresso"],
  ["make ends meat", "make ends meet"],
  ["was lead to believe", "was led to believe"],
  ["were lead to believe", "were led to believe"],
  ["been lead to believe", "been led to believe"],
  ["to loose weight", "to lose weight"],
  ["loosing weight", "losing weight"],
  ["breathe of fresh air", "breath of fresh air"],
  ["take a breathe", "take a breath"],
  ["took a breathe", "took a breath"],
  ["tough road to hoe", "tough row to hoe"],
  ["hard road to hoe", "hard row to hoe"],
  ["wreckless", "reckless"],
  ["play it by year", "play it by ear"],
  ["blessing in the skies", "blessing in disguise"],
  ["beyond the pail", "beyond the pale"],
  ["neck in the woods", "neck of the woods"],
  ["jist", "gist"],
  ["ad nauseum", "ad nauseam"],
  ["de rigor", "de rigueur"],
  ["en mass", "en masse"],
  ["bon a fide", "bona fide"],
  ["carte blanc", "carte blanche"],
  ["coup de gras", "coup de grâce"],
  ["status quote", "status quo"],
  ["self-depreciating", "self-deprecating"],
  ["undo influence", "undue influence"],
  ["undo stress", "undue stress"],
  ["undo burden", "undue burden"],
  [["an another", "a another"], "another"],
  ["in hurry", "in a hurry"],
  ["along time ago", "a long time ago"],
  ["between you and I", "between you and me"],
  ["and etc", "etc"],
  ["emphasize on", "emphasize"],
  ["emphasise on", "emphasise"],
  ["emphasized on", "emphasized"],
  ["emphasised on", "emphasised"],
  ["emphasizes on", "emphasizes"],
  ["emphasises on", "emphasises"],
  ["emphasizing on", "emphasizing"],
  ["emphasising on", "emphasising"],
  ["cope up with", "cope with"],
  ["do a mistake", "make a mistake"],
  ["did a mistake", "made a mistake"],
  ["doing a mistake", "making a mistake"],
  ["at the other hand", "on the other hand"],
  [["on the meantime", "at the meantime"], "in the meantime"],
  ["each and everyone", "each and every one"],
  [
    ["await for", "awaits for"],
    ["await", "wait for"],
  ],
  ["awaited for", ["awaited", "waited for"]],
  ["awaiting for", ["awaiting", "waiting for"]],
];

/** Words written apart that are one word (or joined, hyphenated, split as shown). */
export const CLOSED_COMPOUNDS: readonly PhraseRow[] = [
  ["back ground", "background"],
  ["by pass", "bypass"],
  ["chalk board", "chalkboard"],
  ["check list", "checklist"],
  ["check lists", "checklists"],
  ["code base", "codebase"],
  ["code bases", "codebases"],
  ["data base", "database"],
  ["data bases", "databases"],
  ["dead line", "deadline"],
  ["dead lines", "deadlines"],
  ["down load", "download"],
  ["down loaded", "downloaded"],
  ["down loads", "downloads"],
  ["down loading", "downloading"],
  ["up load", "upload"],
  ["up loaded", "uploaded"],
  ["up loads", "uploads"],
  ["up loading", "uploading"],
  ["else where", "elsewhere"],
  ["every where", "everywhere"],
  ["some where", "somewhere"],
  ["any where", "anywhere"],
  ["no where", "nowhere"],
  ["further more,", "furthermore,"],
  ["hence forth", "henceforth"],
  ["how ever", "however"],
  ["in so far", "insofar"],
  ["in stead", "instead"],
  ...[
    "is",
    "are",
    "was",
    "were",
    "remain",
    "remains",
    "remained",
    "still",
    "fully",
    "left",
    "kept",
  ].map((word): PhraseRow => [`${word} in tact`, `${word} intact`]),
  ["it self", "itself"],
  ["him self", "himself"],
  ["them selves", "themselves"],
  ["our selves", "ourselves"],
  ["your selves", "yourselves"],
  ["key stroke", "keystroke"],
  ["key strokes", "keystrokes"],
  ["lap top", "laptop"],
  ["lap tops", "laptops"],
  ["mean while", "meanwhile"],
  ["in the mean time", "in the meantime"],
  ["middle ware", "middleware"],
  ["miss understand", "misunderstand"],
  ["miss understood", "misunderstood"],
  ["multi media", "multimedia"],
  ["never the less", "nevertheless"],
  ["none the less", "nonetheless"],
  ["not with standing", "notwithstanding"],
  ["out come", "outcome"],
  ["out comes", "outcomes"],
  ["post pone", "postpone"],
  ["post poned", "postponed"],
  ["proof read", "proofread"],
  ["proof reading", "proofreading"],
  ["short coming", "shortcoming"],
  ["short comings", "shortcomings"],
  ["some how", "somehow"],
  ...["a", "is", "was", "very", "pretty", "fairly", "quite", "more"].map((word): PhraseRow => [
    `${word} straight forward`,
    `${word} straightforward`,
  ]),
  ["through out", "throughout"],
  ["time line", "timeline"],
  ["time lines", "timelines"],
  ["up coming", "upcoming"],
  ["what so ever", "whatsoever"],
  ["when ever", "whenever"],
  ["where ever", "wherever"],
  ["wide spread", "widespread"],
  ["with out", "without"],
  ["worth while", "worthwhile"],
  ["web site", "website"],
  ["web sites", "websites"],
  ["screen shot", "screenshot"],
  ["screen shots", "screenshots"],
  ["life style", "lifestyle"],
  ["life time", "lifetime"],
  ["news paper", "newspaper"],
  ["note book", "notebook"],
  ["head line", "headline"],
  ["head lines", "headlines"],
  ["grand father", "grandfather"],
  ["grand mother", "grandmother"],
  ["grand parents", "grandparents"],
  ["week end", "weekend"],
  ["birth day", "birthday"],
  ["eye sight", "eyesight"],
  ["bed room", "bedroom"],
  ["bath room", "bathroom"],
  ["class room", "classroom"],
  ["class mate", "classmate"],
  ["class mates", "classmates"],
  ["room mate", "roommate"],
  ["team mate", "teammate"],
  ["team mates", "teammates"],
  ["work place", "workplace"],
  ["work shop", "workshop"],
  ["work load", "workload"],
  ["work flow", "workflow"],
  ["work flows", "workflows"],
  ["frame work", "framework"],
  ["frame works", "frameworks"],
  ["soft ware", "software"],
  ["hard ware", "hardware"],
  ["firm ware", "firmware"],
  ["spread sheet", "spreadsheet"],
  ["book mark", "bookmark"],
  ["book marks", "bookmarks"],
  ["hand book", "handbook"],
  ["guide line", "guideline"],
  ["guide lines", "guidelines"],
  ["all though", "although"],
  ["multi threading", "multithreading"],
  ["sub par", "subpar"],
  ["bonafide", "bona fide"],
  ["atleast", "at least"],
  ["infact", "in fact"],
  ["incase", "in case"],
  ["eachother", "each other"],
  ["noone", "no one"],
  ["alittle", "a little"],
  ["abit", "a bit"],
  ["infront", "in front"],
  ["ontop", "on top"],
  ["ofcourse", "of course"],
  ["incharge", "in charge"],
  ["inspite", "in spite"],
  ["inbetween", "in between"],
  ["everytime", "every time"],
  ["aswell", "as well"],
  ["thankyou", ["thank you", "thank-you"]],
  ["upto", "up to"],
  ["moreso", "more so"],
  ["ontime", "on time"],
  ["sofar", "so far"],
  ["eventhough", "even though"],
  ["evenif", "even if"],
  ["nomatter", "no matter"],
  ["atall", "at all"],
  ["atlast", "at last"],
  ["scot free", "scot-free"],
  ["from the get go", "from the get-go"],
  ["dog eat dog", "dog-eat-dog"],
  ...["mother", "father", "brother", "sister", "son", "daughter"].flatMap(
    (relative): PhraseRow[] => [
      [`${relative} in law`, `${relative}-in-law`],
      [`${relative}s in law`, `${relative}s-in-law`],
    ],
  ),
  ["merry go round", "merry-go-round"],
  ["happy go lucky", "happy-go-lucky"],
  ["hand me downs", "hand-me-downs"],
  ["eagle eyed", "eagle-eyed"],
  ["ever present", "ever-present"],
];

/**
 * Chat abbreviations whose ALL-CAPS form means only the chat phrase. The rest
 * abstain in capitals: "IMO" is also an organization, "IRL" a country code,
 * "NVM" memory.
 */
export const UNAMBIGUOUS_CAPS_ABBREVIATIONS: ReadonlySet<string> = new Set([
  ...["btw", "fyi", "imho", "afaik", "afaict", "tbh", "idk", "iirc", "asap", "lmk"],
  ...["brb", "ttyl", "otoh", "icymi", "fwiw", "ptal"],
]);

/** Optional style advice: chat abbreviations and wordy or redundant phrasing. */
export const STYLE_PHRASES: readonly PhraseRow[] = [
  ["btw", "by the way"],
  ["fyi", "for your information"],
  ["imo", "in my opinion"],
  ["imho", "in my humble opinion"],
  ["afaik", "as far as I know"],
  ["afaict", "as far as I can tell"],
  ["tbh", "to be honest"],
  ["idk", "I don't know"],
  ["iirc", "if I recall correctly"],
  ["asap", "as soon as possible"],
  ["lmk", "let me know"],
  ["brb", "be right back"],
  ["ttyl", "talk to you later"],
  ["nvm", "never mind"],
  ["irl", "in real life"],
  ["otoh", "on the other hand"],
  ["icymi", "in case you missed it"],
  ["fwiw", "for what it's worth"],
  ["ptal", "please take a look"],
  ["in order to", "to"],
  ["due to the fact that", ["because", "since"]],
  [
    ["in spite of the fact that", "despite the fact that"],
    ["although", "even though"],
  ],
  ["at this point in time", ["now", "at this point"]],
  ["at the present time", ["now", "currently"]],
  ["in the event that", "if"],
  ["each and every", ["each", "every"]],
  ["absolutely essential", "essential"],
  ["added bonus", "bonus"],
  ["advance warning", "warning"],
  ["basic fundamentals", "fundamentals"],
  ["in close proximity to", "near"],
  ["close proximity", "proximity"],
  ["completely eliminate", "eliminate"],
  ["end result", "result"],
  ["final outcome", "outcome"],
  ["free gift", "gift"],
  ["future plans", "plans"],
  ["past history", "history"],
  ["unexpected surprise", "surprise"],
  ["revert back", "revert"],
  ["reverted back", "reverted"],
  ["return back", "return"],
  ["repeat again", "repeat"],
  ["reply back", "reply"],
  ["join together", "join"],
  ["merge together", "merge"],
  ["combine together", "combine"],
  ["collaborate together", "collaborate"],
  ["true fact", "fact"],
  ["new innovation", "innovation"],
  ["general consensus", "consensus"],
  ["consensus of opinion", "consensus"],
  ["the reason is because", "the reason is that"],
  ["a large number of", "many"],
  ["the vast majority of", "most"],
  ["has the ability to", "can"],
  ["have the ability to", "can"],
  ["with the exception of", "except"],
  ["prior to", "before"],
  ["subsequent to", "after"],
  ["in excess of", "more than"],
  ["on a daily basis", "daily"],
  ["on a weekly basis", "weekly"],
  ["on a monthly basis", "monthly"],
  ["on a regular basis", "regularly"],
  ["as of yet", "yet"],
  ["in the near future", "soon"],
  ["very unique", "unique"],
  ["still remains", "remains"],
  ["sum total", "total"],
  ["brief summary", "summary"],
  ["mutual cooperation", "cooperation"],
  ["may possibly", "may"],
  ["might possibly", "might"],
  ["first began", "began"],
  ["over exaggerate", "exaggerate"],
  ["overexaggerate", "exaggerate"],
];

/** Multi-word place and product names that are never ordinary phrases. */
export const NAME_CASING: readonly string[] = [
  "New York",
  "New Jersey",
  "New Mexico",
  "New Hampshire",
  "New Orleans",
  "New Delhi",
  "New Zealand",
  "Los Angeles",
  "Las Vegas",
  "San Francisco",
  "San Diego",
  "Salt Lake City",
  "Rhode Island",
  "North Carolina",
  "South Carolina",
  "North Dakota",
  "South Dakota",
  "West Virginia",
  "United States",
  "United Kingdom",
  "United Nations",
  "United Arab Emirates",
  "European Union",
  "South Africa",
  "South Korea",
  "North Korea",
  "Saudi Arabia",
  "Sri Lanka",
  "Costa Rica",
  "Puerto Rico",
  "El Salvador",
  "Hong Kong",
  "Buenos Aires",
  "Rio de Janeiro",
  "Tel Aviv",
  "Kuala Lumpur",
  "Abu Dhabi",
  "Cape Town",
  "Mexico City",
  "Czech Republic",
  "Dominican Republic",
  "Middle East",
  "Southeast Asia",
  "Silicon Valley",
  "Pacific Ocean",
  "Atlantic Ocean",
  "Indian Ocean",
  "Arctic Ocean",
  "Mediterranean Sea",
  "Caribbean Sea",
  "Baltic Sea",
  "Google Docs",
  "Google Drive",
  "Google Chrome",
  "Google Maps",
  "Google Sheets",
  "Microsoft Teams",
  "Microsoft Excel",
  "Microsoft Word",
  "Microsoft Office",
  "Microsoft Edge",
  "Visual Studio",
  "South America",
  "North America",
  "Central America",
  "Latin America",
  "Southern Ocean",
  "South China Sea",
  "Baton Rouge",
  "Khmer Rouge",
  "Gilded Age",
  "MacBook Pro",
  "MacBook Air",
  "Mac Pro",
  "Mac Mini",
  "AirPods Pro",
  "AirPods Max",
];
