import type { PhraseRow } from "./englishPhraseTables";
import { TABLES as GREEK_TABLES } from "./greek/tables";
import { TABLES as SWEDISH_TABLES } from "./swedish/tables";
import { TABLES as ARABIC_TABLES } from "./arabic/tables";
import { PORTUGUESE_PHRASES, PORTUGUESE_STYLE } from "./portuguese/phrases";
import { POLISH_TABLES } from "./polish";

/**
 * The English phrase checks for the other review languages, by language code.
 * Same row format and matching as the English tables; a row is only here when
 * its typed form is never correct in that language, or is narrowed to a frame
 * where it cannot be. Merged words that are always two live in
 * `multilingualLexicon.ts` (`englishAlotCorrection`).
 */
export interface LanguagePhraseTables {
  /** Misspelled words (`englishPhraseCorrections`). */
  words?: readonly PhraseRow[];
  /** A wrong word form inside a fixed frame (`englishPhraseCorrections`). */
  phrases?: readonly PhraseRow[];
  /** Compounds written apart or without their hyphens (`englishClosedCompounds`). */
  compounds?: readonly PhraseRow[];
  /** Optional wording advice: pleonasms (`stylePhrasing`). */
  style?: readonly PhraseRow[];
}

export const LANGUAGE_PHRASE_TABLES: Readonly<Record<string, LanguagePhraseTables>> = {
  de: {
    words: [
      ["Standart", "Standard"],
      ["Standarts", "Standards"],
      ["standartmäßig", "standardmäßig"],
      ["wiederspiegeln", "widerspiegeln"],
      ["wiederspiegelt", "widerspiegelt"],
      ["wiederspiegelte", "widerspiegelte"],
      ["nähmlich", "nämlich"],
      [["Rythmus", "Rhytmus"], "Rhythmus"],
      ["vorraus", "voraus"],
      ["vorrausgesetzt", "vorausgesetzt"],
      ["Vorraussetzung", "Voraussetzung"],
      ["Vorraussetzungen", "Voraussetzungen"],
      ["vorraussichtlich", "voraussichtlich"],
      ["Addresse", "Adresse"],
      ["Maschiene", "Maschine"],
      ["Maschienen", "Maschinen"],
      ["Wiederstand", "Widerstand"],
      ["Widerholung", "Wiederholung"],
      ["Reperatur", "Reparatur"],
      ["entgültig", "endgültig"],
      ["Ergebniss", "Ergebnis"],
      ["vieleicht", "vielleicht"],
      ["interresant", "interessant"],
      ["Terasse", "Terrasse"],
      ["Rückrad", "Rückgrat"],
      ["Stehgreif", "Stegreif"],
      ["dilletantisch", "dilettantisch"],
      ["Agression", "Aggression"],
      ["Karierre", "Karriere"],
      ["tollerant", "tolerant"],
      ["Wehrmutstropfen", "Wermutstropfen"],
      ["seperat", "separat"],
      ["Rethorik", "Rhetorik"],
    ],
    phrases: [
      // Genitive or "nach" with the dative: the two are blended.
      ["meines Wissens nach", ["meines Wissens", "meinem Wissen nach"]],
      ["unseres Wissens nach", ["unseres Wissens", "unserem Wissen nach"]],
    ],
    compounds: [
      ["aufwiedersehen", "auf Wiedersehen"],
      ["zuende", "zu Ende"],
      ["nichts desto trotz", "nichtsdestotrotz"],
      ["nichts desto weniger", "nichtsdestoweniger"],
      ["das selbe", "dasselbe"],
      ["der selbe", "derselbe"],
      ["die selbe", "dieselbe"],
      ["den selben", "denselben"],
      ["dem selben", "demselben"],
      ["des selben", "desselben"],
      ["zu erst", "zuerst"],
      ["zu mindest", "zumindest"],
      ["in so fern", "insofern"],
      ["in wie fern", "inwiefern"],
      ["irgend etwas", "irgendetwas"],
      ["irgend jemand", "irgendjemand"],
      ["irgend wann", "irgendwann"],
      ["irgend wo", "irgendwo"],
    ],
    style: [
      ["bereits schon", ["bereits", "schon"]],
      ["tote Leiche", "Leiche"],
      ["runder Kreis", "Kreis"],
      ["neu renoviert", "renoviert"],
    ],
  },
  fr: {
    words: [
      ["language", "langage"],
      ["languages", "langages"],
      ["connection", "connexion"],
      ["connections", "connexions"],
      ["dévelopement", "développement"],
      ["parmis", "parmi"],
      [["apeller", "appeller"], "appeler"],
      ["rapeller", "rappeler"],
      ["addresse", "adresse"],
      ["apartement", "appartement"],
      ["cauchemard", "cauchemar"],
      ["dilemne", "dilemme"],
      ["occurence", "occurrence"],
      ["malgrès", "malgré"],
      ["néamoins", "néanmoins"],
      ["notament", "notamment"],
      ["pécunier", "pécuniaire"],
      ["infractus", "infarctus"],
      ["aréoport", "aéroport"],
      ["comission", "commission"],
      ["professionel", "professionnel"],
      ["traditionel", "traditionnel"],
    ],
    phrases: [
      // "quel" agrees with the subject after "être": the writer picks the gender.
      ["quelque soit", ["quel que soit", "quelle que soit"]],
      [
        ["quelque soient", "quelques soient"],
        ["quels que soient", "quelles que soient"],
      ],
      ["comme même", "quand même"],
      ["en faite", "en fait"],
      ["sa va", "ça va"],
    ],
    compounds: [
      ["vis à vis", "vis-à-vis"],
      ["au delà", "au-delà"],
      ["au dessus", "au-dessus"],
      ["au dessous", "au-dessous"],
      ["là bas", "là-bas"],
      ["c'est à dire", "c'est-à-dire"],
      ["celui ci", "celui-ci"],
      ["celle ci", "celle-ci"],
      ["ceux ci", "ceux-ci"],
      ["celles ci", "celles-ci"],
      ["celui là", "celui-là"],
      ["celle là", "celle-là"],
      ["ceux là", "ceux-là"],
      ["celles là", "celles-là"],
    ],
    // "monter en haut de la tour" names a destination: left out.
    style: [
      ["au jour d'aujourd'hui", "aujourd'hui"],
      ["sortir dehors", "sortir"],
      ["reculer en arrière", "reculer"],
      ["prévoir à l'avance", "prévoir"],
      ["collaborer ensemble", "collaborer"],
      ["s'entraider mutuellement", "s'entraider"],
      ["comme par exemple", ["comme", "par exemple"]],
      ["puis ensuite", ["puis", "ensuite"]],
      ["car en effet", ["car", "en effet"]],
    ],
  },
  es: {
    // "vistes" (present of "vestir") and "iva" (the tax) are words: left out.
    words: [
      ["haiga", "haya"],
      ["haigas", "hayas"],
      ["haigan", "hayan"],
      ["haigamos", "hayamos"],
      [["nadien", "nadies"], "nadie"],
      ["dijistes", "dijiste"],
      ["hicistes", "hiciste"],
      ["fuistes", "fuiste"],
      ["tuvistes", "tuviste"],
      ["estuvistes", "estuviste"],
      ["pudistes", "pudiste"],
      ["vinistes", "viniste"],
      ["preveer", "prever"],
      ["mounstro", "monstruo"],
      ["mounstros", "monstruos"],
      ["dentrífico", "dentífrico"],
      ["cocreta", "croqueta"],
      ["andé", "anduve"],
      ["andó", "anduvo"],
      ["satisfació", "satisfizo"],
      ["conducí", "conduje"],
      ["traducí", "traduje"],
      ["exhuberante", "exuberante"],
      ["expontáneo", "espontáneo"],
      ["idiosincracia", "idiosincrasia"],
      ["aereopuerto", "aeropuerto"],
      ["vagamundo", "vagabundo"],
    ],
    // Existential "haber" is singular; "hubieron de" and "habían llegado" are not matched.
    phrases: [
      ["hubieron muchos", "hubo muchos"],
      ["hubieron muchas", "hubo muchas"],
      ["hubieron varios", "hubo varios"],
      ["hubieron varias", "hubo varias"],
      ["habían muchos", "había muchos"],
      ["habían muchas", "había muchas"],
      ["habían varios", "había varios"],
      ["habían varias", "había varias"],
    ],
    compounds: [
      ["tam bien", "también"],
      ["porsupuesto", "por supuesto"],
      ["asique", "así que"],
    ],
    style: [
      ["subir arriba", "subir"],
      ["bajar abajo", "bajar"],
      ["salir afuera", "salir"],
      ["entrar adentro", "entrar"],
      ["hace años atrás", ["hace años", "años atrás"]],
    ],
  },
  pt: {
    words: [
      ["seje", "seja"],
      ["esteje", "esteja"],
      ["menas", "menos"],
      ["excessão", "exceção"],
      ["excessões", "exceções"],
      ["previlégio", "privilégio"],
      ["beneficiente", "beneficente"],
      ["mortandela", "mortadela"],
      ["asterístico", "asterisco"],
      ["impecilho", "empecilho"],
      ["cabeleleiro", "cabeleireiro"],
      ["mendingo", "mendigo"],
      ["advinhar", "adivinhar"],
      ["própio", "próprio"],
      ["discusão", "discussão"],
      ["ancioso", "ansioso"],
      ["iorgute", "iogurte"],
      ["apezar", "apesar"],
    ],
    // Existential "haver" is singular.
    phrases: [
      ["houveram muitos", "houve muitos"],
      ["houveram muitas", "houve muitas"],
      ["houveram vários", "houve vários"],
      ["houveram várias", "houve várias"],
      ...PORTUGUESE_PHRASES,
    ],
    style: [
      ["subir para cima", "subir"],
      ["descer para baixo", "descer"],
      ["entrar para dentro", "entrar"],
      ["sair para fora", "sair"],
      ["elo de ligação", "elo"],
      ["encarar de frente", "encarar"],
      ["há anos atrás", ["há anos", "anos atrás"]],
      ...PORTUGUESE_STYLE,
    ],
  },
  pl: {
    // Feminine "poszłam" is correct; only the masculine blends are listed.
    words: [
      ["wziąść", "wziąć"],
      ["poszłem", "poszedłem"],
      ["przyszłem", "przyszedłem"],
      ["wyszłem", "wyszedłem"],
      ["weszłem", "wszedłem"],
      ["doszłem", "doszedłem"],
      ["włanczać", "włączać"],
      ["włanczam", "włączam"],
      ["wyłanczać", "wyłączać"],
      ["wyłanczam", "wyłączam"],
      ["orginalny", "oryginalny"],
      ["orginalnie", "oryginalnie"],
      ["orginał", "oryginał"],
      ["rozumię", "rozumiem"],
      ["umię", "umiem"],
      ["bierzę", "biorę"],
      ["nadzieji", "nadziei"],
      ["przyjacielami", "przyjaciółmi"],
      ["cudzysłowiu", "cudzysłowie"],
      ...POLISH_TABLES.words,
    ],
    // "półtora" goes with masculine and neuter nouns, "półtorej" with feminine ones.
    phrases: [
      ["półtorej roku", "półtora roku"],
      ["półtorej miesiąca", "półtora miesiąca"],
      ["półtorej tygodnia", "półtora tygodnia"],
      ["półtora godziny", "półtorej godziny"],
      ["półtora minuty", "półtorej minuty"],
      ["w każdym bądź razie", "w każdym razie"],
      ...POLISH_TABLES.phrases,
    ],
    compounds: [
      ["z pośród", "spośród"],
      ["z pod", "spod"],
      ["z nad", "znad"],
      ["z przed", "sprzed"],
      ["z za", "zza"],
      ["w śród", "wśród"],
      ["po za tym", "poza tym"],
      ["po mimo", "pomimo"],
      ["na przeciwko", "naprzeciwko"],
      ["z tąd", "stąd"],
      ["z kąd", "skąd"],
      ["z nikąd", "znikąd"],
      [["spowrotem", "zpowrotem"], "z powrotem"],
      ...POLISH_TABLES.compounds,
    ],
    style: [
      ["w dniu dzisiejszym", ["dziś", "dzisiaj"]],
      ["akwen wodny", "akwen"],
      ["cofać się do tyłu", "cofać się"],
      ["cofnąć się do tyłu", "cofnąć się"],
      ["wracać z powrotem", "wracać"],
      ["wrócić z powrotem", "wrócić"],
      ["fakt autentyczny", "fakt"],
      ...POLISH_TABLES.style,
    ],
  },
  hr: {
    words: [
      ["uopče", "uopće"],
      ["opčenito", "općenito"],
      ["zakljućak", "zaključak"],
      ["ćestitam", "čestitam"],
      ["ljepo", "lijepo"],
      ["djete", "dijete"],
      ["gdije", "gdje"],
    ],
    compounds: [
      ["bi smo", "bismo"],
      ["bi ste", "biste"],
      ["sobzirom", "s obzirom"],
    ],
  },
  sv: SWEDISH_TABLES,
  el: GREEK_TABLES,
  ar: ARABIC_TABLES,
};
