import type { PhraseRow } from "./englishPhraseTables";

/**
 * The English phrase checks for the other review languages, by language code.
 * Same row format and matching as the English tables; a row is only here when
 * its typed form is never correct in that language, or is narrowed to a frame
 * where it cannot be. Merged words that are always two live in
 * `multilingualLexicon.ts` (`englishAlotCorrection`).
 */
export interface LanguagePhraseTables {
  /** Misspelled words (`englishPhraseCorrections`). */
  words?: readonly PhraseRow[];
  /** A wrong word form inside a fixed frame (`englishPhraseCorrections`). */
  phrases?: readonly PhraseRow[];
  /** Compounds written apart or without their hyphens (`englishClosedCompounds`). */
  compounds?: readonly PhraseRow[];
  /** Optional wording advice: pleonasms (`stylePhrasing`). */
  style?: readonly PhraseRow[];
}

export const LANGUAGE_PHRASE_TABLES: Readonly<Record<string, LanguagePhraseTables>> = {
  de: {
    words: [
      ["Standart", "Standard"],
      ["Standarts", "Standards"],
      ["standartmäßig", "standardmäßig"],
      ["wiederspiegeln", "widerspiegeln"],
      ["wiederspiegelt", "widerspiegelt"],
      ["wiederspiegelte", "widerspiegelte"],
      ["nähmlich", "nämlich"],
      [["Rythmus", "Rhytmus"], "Rhythmus"],
      ["vorraus", "voraus"],
      ["vorrausgesetzt", "vorausgesetzt"],
      ["Vorraussetzung", "Voraussetzung"],
      ["Vorraussetzungen", "Voraussetzungen"],
      ["vorraussichtlich", "voraussichtlich"],
      ["Addresse", "Adresse"],
      ["Maschiene", "Maschine"],
      ["Maschienen", "Maschinen"],
      ["Wiederstand", "Widerstand"],
      ["Widerholung", "Wiederholung"],
      ["Reperatur", "Reparatur"],
      ["entgültig", "endgültig"],
      ["Ergebniss", "Ergebnis"],
      ["vieleicht", "vielleicht"],
      ["interresant", "interessant"],
      ["Terasse", "Terrasse"],
      ["Rückrad", "Rückgrat"],
      ["Stehgreif", "Stegreif"],
      ["dilletantisch", "dilettantisch"],
      ["Agression", "Aggression"],
      ["Karierre", "Karriere"],
      ["tollerant", "tolerant"],
      ["Wehrmutstropfen", "Wermutstropfen"],
      ["seperat", "separat"],
      ["Rethorik", "Rhetorik"],
    ],
    phrases: [
      // Genitive or "nach" with the dative: the two are blended.
      ["meines Wissens nach", ["meines Wissens", "meinem Wissen nach"]],
      ["unseres Wissens nach", ["unseres Wissens", "unserem Wissen nach"]],
      // Look-alike words inside fixed phrases.
      ["Gesetz den Fall", "Gesetzt den Fall"],
      ["letztes Endes", "letzten Endes"],
      ["Vielen danke", "Vielen Dank"],
      ["zu Neige", "zur Neige"],
      ["Was lange wehrt", "Was lange währt"],
      ["Feuer und Flame", "Feuer und Flamme"],
      ["wieder Willen", "wider Willen"],
      ["wieder besseres Wissen", "wider besseres Wissen"],
      ["das Für und Wieder", "das Für und Wider"],
      ["Angaben ohne Gewehr", "Angaben ohne Gewähr"],
      ["zu späht", "zu spät"],
      ["ich siehe", "ich sehe"],
      ["wider einmal", "wieder einmal"],
      ["im Enddefekt", "im Endeffekt"],
      ["auf jeden Falls", "auf jeden Fall"],
      ["in aller Regeln", "in aller Regel"],
      ["Hallo Heer", "Hallo Herr"],
      ["geehrter Heer", "geehrter Herr"],
      ["größer wie", "größer als"],
      ["schneller wie", "schneller als"],
      ["älter wie", "älter als"],
      ["kleiner wie", "kleiner als"],
    ],
    compounds: [
      ["aufwiedersehen", "auf Wiedersehen"],
      ["zuende", "zu Ende"],
      ["nichts desto trotz", "nichtsdestotrotz"],
      ["nichts desto weniger", "nichtsdestoweniger"],
      ["das selbe", "dasselbe"],
      ["der selbe", "derselbe"],
      ["die selbe", "dieselbe"],
      ["den selben", "denselben"],
      ["dem selben", "demselben"],
      ["des selben", "desselben"],
      ["zu erst", "zuerst"],
      ["zu mindest", "zumindest"],
      ["in so fern", "insofern"],
      ["in wie fern", "inwiefern"],
      ["irgend etwas", "irgendetwas"],
      ["irgend jemand", "irgendjemand"],
      ["irgend wann", "irgendwann"],
      ["irgend wo", "irgendwo"],
      ["irgend wie", "irgendwie"],
      ["irgend welche", "irgendwelche"],
      ["in zwischen", "inzwischen"],
      ["über haupt", "überhaupt"],
      ["in Mitten", "inmitten"],
      ["statt dessen", "stattdessen"],
      ["aller Hand", "allerhand"],
    ],
    style: [
      ["bereits schon", ["bereits", "schon"]],
      ["tote Leiche", "Leiche"],
      ["runder Kreis", "Kreis"],
      ["neu renoviert", "renoviert"],
      // Doubled meaning: the acronym already names the noun, or the adjective is implied.
      ["schon bereits", ["schon", "bereits"]],
      ["PIN-Nummer", "PIN"],
      ["TAN-Nummer", "TAN"],
      ["ISBN-Nummer", "ISBN"],
      ["LCD-Display", "LCD"],
      ["HIV-Virus", "HIV"],
      ["ABS-System", "ABS"],
      ["SMS-Nachricht", "SMS"],
      ["runde Kugel", "Kugel"],
      ["runden Kugeln", "Kugeln"],
      ["weißer Schimmel", "Schimmel"],
      ["alter Greis", "Greis"],
      ["andere Alternative", "Alternative"],
      ["anderen Alternativen", "Alternativen"],
      ["finanziellen Geldprobleme", "Geldprobleme"],
      ["zurück erstatten", "erstatten"],
      ["Rückantwort", "Antwort"],
      ["Gratisgeschenk", "Geschenk"],
      ["Zukunftsprognose", "Prognose"],
      ["einander gegenseitig", "einander"],
      ["plötzlich auf einmal", ["plötzlich", "auf einmal"]],
      ["vielleicht eventuell", ["vielleicht", "eventuell"]],
      ["bald demnächst", ["bald", "demnächst"]],
      ["nur ausschließlich", ["nur", "ausschließlich"]],
      ["also folglich", ["also", "folglich"]],
      // The recommended one of two allowed spellings (Duden).
      ["mit Hilfe", "mithilfe"],
      ["in Frage", "infrage"],
      ["zu Grunde", "zugrunde"],
      ["zu Stande", "zustande"],
      ["im Stande", "imstande"],
      ["zu Rate", "zurate"],
      ["zu Schulden", "zuschulden"],
      ["zu Gunsten", "zugunsten"],
      ["zu Lasten", "zulasten"],
      ["von Seiten", "vonseiten"],
      ["auf Seiten", "aufseiten"],
      ["hier zu Lande", "hierzulande"],
      ["so dass", "sodass"],
      ["so genannte", "sogenannte"],
      ["so genannten", "sogenannten"],
      ["Hand voll", "Handvoll"],
      ["kennen lernen", "kennenlernen"],
      ["kennen zu lernen", "kennenzulernen"],
      // "Sinn machen" is borrowed from English; "Sinn ergeben" is the German phrase.
      ["macht Sinn", "ergibt Sinn"],
      ["machen Sinn", "ergeben Sinn"],
      ["Sinn macht", "Sinn ergibt"],
      ["Sinn machen", "Sinn ergeben"],
      ["machte Sinn", "ergab Sinn"],
      ["macht keinen Sinn", "ergibt keinen Sinn"],
      ["macht es Sinn", "ergibt es Sinn"],
    ],
  },
  fr: {
    words: [
      ["language", "langage"],
      ["languages", "langages"],
      ["connection", "connexion"],
      ["connections", "connexions"],
      ["dévelopement", "développement"],
      ["parmis", "parmi"],
      [["apeller", "appeller"], "appeler"],
      ["rapeller", "rappeler"],
      ["addresse", "adresse"],
      ["apartement", "appartement"],
      ["cauchemard", "cauchemar"],
      ["dilemne", "dilemme"],
      ["occurence", "occurrence"],
      ["malgrès", "malgré"],
      ["néamoins", "néanmoins"],
      ["notament", "notamment"],
      ["pécunier", "pécuniaire"],
      ["infractus", "infarctus"],
      ["aréoport", "aéroport"],
      ["comission", "commission"],
      ["professionel", "professionnel"],
      ["traditionel", "traditionnel"],
    ],
    phrases: [
      // "quel" agrees with the subject after "être": the writer picks the gender.
      ["quelque soit", ["quel que soit", "quelle que soit"]],
      [
        ["quelque soient", "quelques soient"],
        ["quels que soient", "quelles que soient"],
      ],
      ["comme même", "quand même"],
      ["en faite", "en fait"],
      ["sa va", "ça va"],
    ],
    compounds: [
      ["vis à vis", "vis-à-vis"],
      ["au delà", "au-delà"],
      ["au dessus", "au-dessus"],
      ["au dessous", "au-dessous"],
      ["là bas", "là-bas"],
      ["c'est à dire", "c'est-à-dire"],
      ["celui ci", "celui-ci"],
      ["celle ci", "celle-ci"],
      ["ceux ci", "ceux-ci"],
      ["celles ci", "celles-ci"],
      ["celui là", "celui-là"],
      ["celle là", "celle-là"],
      ["ceux là", "ceux-là"],
      ["celles là", "celles-là"],
    ],
    // "monter en haut de la tour" names a destination: left out.
    style: [
      ["au jour d'aujourd'hui", "aujourd'hui"],
      ["sortir dehors", "sortir"],
      ["reculer en arrière", "reculer"],
      ["prévoir à l'avance", "prévoir"],
      ["collaborer ensemble", "collaborer"],
      ["s'entraider mutuellement", "s'entraider"],
      ["comme par exemple", ["comme", "par exemple"]],
      ["puis ensuite", ["puis", "ensuite"]],
      ["car en effet", ["car", "en effet"]],
    ],
  },
  es: {
    // "vistes" (present of "vestir") and "iva" (the tax) are words: left out.
    words: [
      ["haiga", "haya"],
      ["haigas", "hayas"],
      ["haigan", "hayan"],
      ["haigamos", "hayamos"],
      [["nadien", "nadies"], "nadie"],
      ["dijistes", "dijiste"],
      ["hicistes", "hiciste"],
      ["fuistes", "fuiste"],
      ["tuvistes", "tuviste"],
      ["estuvistes", "estuviste"],
      ["pudistes", "pudiste"],
      ["vinistes", "viniste"],
      ["preveer", "prever"],
      ["mounstro", "monstruo"],
      ["mounstros", "monstruos"],
      ["dentrífico", "dentífrico"],
      ["cocreta", "croqueta"],
      ["andé", "anduve"],
      ["andó", "anduvo"],
      ["satisfació", "satisfizo"],
      ["conducí", "conduje"],
      ["traducí", "traduje"],
      ["exhuberante", "exuberante"],
      ["expontáneo", "espontáneo"],
      ["idiosincracia", "idiosincrasia"],
      ["aereopuerto", "aeropuerto"],
      ["vagamundo", "vagabundo"],
    ],
    // Existential "haber" is singular; "hubieron de" and "habían llegado" are not matched.
    phrases: [
      ["hubieron muchos", "hubo muchos"],
      ["hubieron muchas", "hubo muchas"],
      ["hubieron varios", "hubo varios"],
      ["hubieron varias", "hubo varias"],
      ["habían muchos", "había muchos"],
      ["habían muchas", "había muchas"],
      ["habían varios", "había varios"],
      ["habían varias", "había varias"],
    ],
    compounds: [
      ["tam bien", "también"],
      ["porsupuesto", "por supuesto"],
      ["asique", "así que"],
    ],
    style: [
      ["subir arriba", "subir"],
      ["bajar abajo", "bajar"],
      ["salir afuera", "salir"],
      ["entrar adentro", "entrar"],
      ["hace años atrás", ["hace años", "años atrás"]],
    ],
  },
  pt: {
    words: [
      ["seje", "seja"],
      ["esteje", "esteja"],
      ["menas", "menos"],
      ["excessão", "exceção"],
      ["excessões", "exceções"],
      ["previlégio", "privilégio"],
      ["beneficiente", "beneficente"],
      ["mortandela", "mortadela"],
      ["asterístico", "asterisco"],
      ["impecilho", "empecilho"],
      ["cabeleleiro", "cabeleireiro"],
      ["mendingo", "mendigo"],
      ["advinhar", "adivinhar"],
      ["própio", "próprio"],
      ["discusão", "discussão"],
      ["ancioso", "ansioso"],
      ["iorgute", "iogurte"],
      ["apezar", "apesar"],
    ],
    // Existential "haver" is singular.
    phrases: [
      ["houveram muitos", "houve muitos"],
      ["houveram muitas", "houve muitas"],
      ["houveram vários", "houve vários"],
      ["houveram várias", "houve várias"],
    ],
    style: [
      ["subir para cima", "subir"],
      ["descer para baixo", "descer"],
      ["entrar para dentro", "entrar"],
      ["sair para fora", "sair"],
      ["elo de ligação", "elo"],
      ["encarar de frente", "encarar"],
      ["há anos atrás", ["há anos", "anos atrás"]],
    ],
  },
  pl: {
    // Feminine "poszłam" is correct; only the masculine blends are listed.
    words: [
      ["wziąść", "wziąć"],
      ["poszłem", "poszedłem"],
      ["przyszłem", "przyszedłem"],
      ["wyszłem", "wyszedłem"],
      ["weszłem", "wszedłem"],
      ["doszłem", "doszedłem"],
      ["włanczać", "włączać"],
      ["włanczam", "włączam"],
      ["wyłanczać", "wyłączać"],
      ["wyłanczam", "wyłączam"],
      ["orginalny", "oryginalny"],
      ["orginalnie", "oryginalnie"],
      ["orginał", "oryginał"],
      ["rozumię", "rozumiem"],
      ["umię", "umiem"],
      ["bierzę", "biorę"],
      ["nadzieji", "nadziei"],
      ["przyjacielami", "przyjaciółmi"],
      ["cudzysłowiu", "cudzysłowie"],
    ],
    // "półtora" goes with masculine and neuter nouns, "półtorej" with feminine ones.
    phrases: [
      ["półtorej roku", "półtora roku"],
      ["półtorej miesiąca", "półtora miesiąca"],
      ["półtorej tygodnia", "półtora tygodnia"],
      ["półtora godziny", "półtorej godziny"],
      ["półtora minuty", "półtorej minuty"],
      ["w każdym bądź razie", "w każdym razie"],
    ],
    compounds: [
      ["z pośród", "spośród"],
      ["z pod", "spod"],
      ["z nad", "znad"],
      ["z przed", "sprzed"],
      ["z za", "zza"],
      ["w śród", "wśród"],
      ["po za tym", "poza tym"],
      ["po mimo", "pomimo"],
      ["na przeciwko", "naprzeciwko"],
      ["z tąd", "stąd"],
      ["z kąd", "skąd"],
      ["z nikąd", "znikąd"],
      [["spowrotem", "zpowrotem"], "z powrotem"],
    ],
    style: [
      ["w dniu dzisiejszym", ["dziś", "dzisiaj"]],
      ["akwen wodny", "akwen"],
      ["cofać się do tyłu", "cofać się"],
      ["cofnąć się do tyłu", "cofnąć się"],
      ["wracać z powrotem", "wracać"],
      ["wrócić z powrotem", "wrócić"],
      ["fakt autentyczny", "fakt"],
    ],
  },
  hr: {
    words: [
      ["uopče", "uopće"],
      ["opčenito", "općenito"],
      ["zakljućak", "zaključak"],
      ["ćestitam", "čestitam"],
      ["ljepo", "lijepo"],
      ["djete", "dijete"],
      ["gdije", "gdje"],
    ],
    compounds: [
      ["bi smo", "bismo"],
      ["bi ste", "biste"],
      ["sobzirom", "s obzirom"],
    ],
  },
  sv: {
    words: [
      ["igentligen", "egentligen"],
      ["antligen", "äntligen"],
      ["alldrig", "aldrig"],
      ["intresant", "intressant"],
      ["komunikation", "kommunikation"],
      ["sammarbete", "samarbete"],
      ["tillsamans", "tillsammans"],
      ["definitift", "definitivt"],
      ["skilnad", "skillnad"],
      ["sjävklart", "självklart"],
      ["anorlunda", "annorlunda"],
      ["rekomendera", "rekommendera"],
      ["resturang", "restaurang"],
    ],
  },
  el: {
    // Monosyllables take no accent; "μία" (the numeral) and "ευχάριστο" are words.
    words: [
      ["εντάξη", "εντάξει"],
      ["ευχαριστό", "ευχαριστώ"],
      ["παρακαλό", "παρακαλώ"],
      ["καλήτερα", "καλύτερα"],
      ["αφτό", "αυτό"],
      ["πιό", "πιο"],
      ["γιά", "για"],
      ["μιά", "μια"],
    ],
  },
};
