import { localizeReviewText, type Translations } from "./reviewLocale";
import type { PageMessageKey } from "./reviewMessages";
import type { ReviewMessageKey } from "./types";

/*
 * What each Review finding means, in every UI language. Only the background
 * (and the options page) load this table: a scan or typing-time proposal
 * answers with the explanations it needs, resolved in the page's UI language,
 * so content scripts never parse it. The explanations of findings the page
 * builds itself stay in reviewMessages.ts.
 */
const EXPLANATIONS: Record<Exclude<ReviewMessageKey, PageMessageKey>, Translations> = {
  review_msg_phrase_correction: [
    "Use the conventional form of this fixed English phrase.",
    "Utilisez la forme usuelle de cette expression figée anglaise.",
    "Upotrijebite uobičajeni oblik ovog ustaljenog engleskog izraza.",
    "Use la forma habitual de esta expresión fija en inglés.",
    "Χρησιμοποιήστε τη συνήθη μορφή αυτής της στερεότυπης αγγλικής φράσης.",
    "Använd den vedertagna formen av detta fasta engelska uttryck.",
    "Verwenden Sie die übliche Form dieser festen englischen Wendung.",
    "Użyj utartej formy tego stałego wyrażenia angielskiego.",
    "Use a forma habitual desta expressão fixa em inglês.",
  ],
  review_msg_closed_compound: [
    "Write this compound the standard way: joined, split or hyphenated as shown.",
    "Écrivez ce composé de la façon standard : soudé, séparé ou avec un trait d’union, comme indiqué.",
    "Napišite ovu složenicu na standardni način: sastavljeno, rastavljeno ili sa spojnicom, kao što je prikazano.",
    "Escriba este compuesto de la forma estándar: junto, separado o con guion, como se muestra.",
    "Γράψτε αυτή τη σύνθετη λέξη με τον καθιερωμένο τρόπο: ενωμένη, χωριστά ή με ενωτικό, όπως φαίνεται.",
    "Skriv sammansättningen på standardsättet: ihop, isär eller med bindestreck, som visas.",
    "Schreiben Sie diese Zusammensetzung in der üblichen Form: zusammen, getrennt oder mit Bindestrich, wie gezeigt.",
    "Zapisz to złożenie w standardowy sposób: łącznie, rozdzielnie lub z łącznikiem, jak pokazano.",
    "Escreva este composto da forma padrão: junto, separado ou com hífen, como indicado.",
  ],
  review_msg_style_phrasing: [
    "Optional style advice: a shorter or more formal wording is available.",
    "Conseil de style facultatif : une formulation plus courte ou plus soutenue est possible.",
    "Neobavezni stilski savjet: dostupna je kraća ili formalnija formulacija.",
    "Consejo de estilo opcional: hay una redacción más breve o más formal.",
    "Προαιρετική συμβουλή ύφους: υπάρχει συντομότερη ή πιο επίσημη διατύπωση.",
    "Valfritt stilråd: det finns en kortare eller mer formell formulering.",
    "Optionaler Stilhinweis: Es gibt eine kürzere oder förmlichere Formulierung.",
    "Opcjonalna wskazówka stylistyczna: dostępne jest krótsze lub bardziej formalne sformułowanie.",
    "Conselho de estilo opcional: existe uma formulação mais curta ou mais formal.",
  ],
  review_msg_name_casing: [
    "Use the established capitalization of this name.",
    "Utilisez les majuscules établies pour ce nom.",
    "Upotrijebite ustaljena velika slova u ovom nazivu.",
    "Use las mayúsculas establecidas para este nombre.",
    "Χρησιμοποιήστε την καθιερωμένη γραφή κεφαλαίων για αυτό το όνομα.",
    "Använd den etablerade skrivningen med stor bokstav för detta namn.",
    "Verwenden Sie die etablierte Großschreibung dieses Namens.",
    "Użyj ustalonej pisowni wielkimi literami w tej nazwie.",
    "Use as maiúsculas estabelecidas para este nome.",
  ],
  review_msg_style_redundancy: [
    "Optional style advice: the acronym already includes this word.",
    "Conseil de style facultatif : le sigle inclut déjà ce mot.",
    "Neobavezni stilski savjet: kratica već uključuje ovu riječ.",
    "Consejo de estilo opcional: la sigla ya incluye esta palabra.",
    "Προαιρετική συμβουλή ύφους: το ακρωνύμιο περιλαμβάνει ήδη αυτή τη λέξη.",
    "Valfritt stilråd: förkortningen innehåller redan detta ord.",
    "Optionaler Stilhinweis: Das Akronym enthält dieses Wort bereits.",
    "Opcjonalna wskazówka stylistyczna: skrót już zawiera to słowo.",
    "Conselho de estilo opcional: a sigla já inclui esta palavra.",
  ],
  review_msg_style_long_sentence: [
    "Optional readability advice: this sentence exceeds your chosen word threshold. No split is suggested.",
    "Conseil de lisibilité facultatif : cette phrase dépasse votre seuil de mots. Aucune division n’est proposée.",
    "Neobavezni savjet za čitljivost: ova rečenica prelazi vaš prag broja riječi. Ne predlaže se podjela.",
    "Consejo de legibilidad opcional: esta oración supera su límite de palabras. No se propone dividirla.",
    "Προαιρετική συμβουλή αναγνωσιμότητας: αυτή η πρόταση υπερβαίνει το όριο λέξεων που επιλέξατε. Δεν προτείνεται διαίρεση.",
    "Valfritt läsbarhetsråd: meningen överskrider din valda ordgräns. Ingen uppdelning föreslås.",
    "Optionaler Lesbarkeitshinweis: Dieser Satz überschreitet Ihre gewählte Wortgrenze. Es wird keine Aufteilung vorgeschlagen.",
    "Opcjonalna wskazówka czytelności: zdanie przekracza wybrany limit słów. Nie proponujemy podziału.",
    "Conselho de legibilidade opcional: esta frase excede o limite de palavras escolhido. Não é proposta uma divisão.",
  ],
  review_msg_preferred_terminology: [
    "Your preferred terminology (user-authored advice).",
    "Votre terminologie préférée (conseil rédigé par vous).",
    "Vaše željeno nazivlje (vaš vlastiti savjet).",
    "Su terminología preferida (consejo definido por usted).",
    "Η προτιμώμενη ορολογία σας (δική σας συμβουλή).",
    "Din föredragna terminologi (råd som du har skrivit).",
    "Ihre bevorzugte Terminologie (selbst verfasster Hinweis).",
    "Twoja preferowana terminologia (własna wskazówka).",
    "Sua terminologia preferida (conselho definido por você).",
  ],
  review_msg_canonical_casing: [
    "Use the established capitalization of this brand or technology name.",
    "Utilisez les majuscules et minuscules établies pour ce nom de marque ou de technologie.",
    "Upotrijebite ustaljena velika i mala slova u ovom nazivu marke ili tehnologije.",
    "Use las mayúsculas y minúsculas establecidas para este nombre de marca o tecnología.",
    "Χρησιμοποιήστε την καθιερωμένη γραφή κεφαλαίων και πεζών για αυτή την επωνυμία ή τεχνολογία.",
    "Använd den etablerade skrivningen med stora och små bokstäver för detta varumärke eller tekniknamn.",
    "Verwenden Sie die etablierte Groß- und Kleinschreibung dieses Marken- oder Technologienamens.",
    "Użyj ustalonej pisowni wielkich i małych liter w tej nazwie marki lub technologii.",
    "Use as maiúsculas e minúsculas estabelecidas para este nome de marca ou tecnologia.",
  ],
  review_msg_quotation_balance: [
    "Check for unclosed quotation marks.",
    "Vérifiez les guillemets non fermés.",
    "Provjerite nezatvorene navodnike.",
    "Revise las comillas sin cerrar.",
    "Ελέγξτε για εισαγωγικά που δεν έχουν κλείσει.",
    "Kontrollera oavslutade citattecken.",
    "Prüfen Sie nicht geschlossene Anführungszeichen.",
    "Sprawdź niedomknięte cudzysłowy.",
    "Verifique aspas não fechadas.",
  ],
  review_msg_unclosed_quote: [
    "This opening quotation mark has no matching closing mark in the complete text.",
    "Ce guillemet ouvrant n’a pas de guillemet fermant correspondant dans le texte complet.",
    "Ovaj početni navodnik nema odgovarajući završni navodnik u cijelom tekstu.",
    "Esta comilla de apertura no tiene una comilla de cierre correspondiente en el texto completo.",
    "Αυτό το εισαγωγικό ανοίγματος δεν έχει αντίστοιχο κλείσιμο στο πλήρες κείμενο.",
    "Det här inledande citattecknet saknar ett motsvarande avslutande tecken i hela texten.",
    "Zu diesem öffnenden Anführungszeichen fehlt im vollständigen Text das schließende Zeichen.",
    "Ten cudzysłów otwierający nie ma odpowiednika zamykającego w pełnym tekście.",
    "Esta aspa de abertura não tem uma aspa de fechamento correspondente no texto completo.",
  ],
  review_msg_quote_spacing: [
    "Add a space outside this quotation mark.",
    "Ajoutez une espace à l’extérieur de ce guillemet.",
    "Dodajte razmak s vanjske strane ovog navodnika.",
    "Añada un espacio por fuera de estas comillas.",
    "Προσθέστε κενό έξω από αυτό το εισαγωγικό.",
    "Lägg till ett mellanslag utanför citattecknet.",
    "Setzen Sie außerhalb dieses Anführungszeichens ein Leerzeichen.",
    "Dodaj spację na zewnątrz tego cudzysłowu.",
    "Adicione um espaço do lado de fora destas aspas.",
  ],
  review_msg_prime_symbols: [
    "Optional typography: use prime marks (′ ″) for feet, inches, minutes and seconds.",
    "Typographie facultative : utilisez les primes (′ ″) pour les pieds, pouces, minutes et secondes.",
    "Neobavezna tipografija: za stope, inče, minute i sekunde koristite oznake ′ ″.",
    "Tipografía opcional: use las primas (′ ″) para pies, pulgadas, minutos y segundos.",
    "Προαιρετική τυπογραφία: χρησιμοποιήστε τόνους (′ ″) για πόδια, ίντσες, λεπτά και δευτερόλεπτα.",
    "Valfri typografi: använd primtecken (′ ″) för fot, tum, minuter och sekunder.",
    "Optionale Typografie: Verwenden Sie Striche (′ ″) für Fuß, Zoll, Minuten und Sekunden.",
    "Opcjonalna typografia: użyj znaków prim (′ ″) dla stóp, cali, minut i sekund.",
    "Tipografia opcional: use os sinais de linha (′ ″) para pés, polegadas, minutos e segundos.",
  ],
  review_msg_usage_phrases: [
    "Check established phrases in context.",
    "Vérifiez les expressions établies en contexte.",
    "Provjerite ustaljene izraze u kontekstu.",
    "Revise las expresiones establecidas en contexto.",
    "Ελέγξτε τις καθιερωμένες εκφράσεις στο πλαίσιο.",
    "Kontrollera etablerade uttryck i sitt sammanhang.",
    "Prüfen Sie feste Wendungen im Kontext.",
    "Sprawdź utrwalone zwroty w kontekście.",
    "Verifique as expressões estabelecidas no contexto.",
  ],
  review_msg_intents_purposes: [
    "The established expression is ‘for all intents and purposes’.",
    "L’expression établie est « for all intents and purposes ».",
    "Ustaljeni izraz je „for all intents and purposes”.",
    "La expresión establecida es «for all intents and purposes».",
    "Η καθιερωμένη έκφραση είναι «for all intents and purposes».",
    "Det etablerade uttrycket är ”for all intents and purposes”.",
    "Die feste Wendung lautet „for all intents and purposes“.",
    "Utrwalony zwrot to „for all intents and purposes”.",
    "A expressão estabelecida é «for all intents and purposes».",
  ],
  review_msg_one_same: [
    "Use ‘one and the same’ when saying that two things are identical.",
    "Utilisez « one and the same » pour dire que deux choses sont identiques.",
    "Upotrijebite „one and the same” kada kažete da su dvije stvari iste.",
    "Use «one and the same» para decir que dos cosas son idénticas.",
    "Χρησιμοποιήστε το «one and the same» όταν λέτε ότι δύο πράγματα είναι ίδια.",
    "Använd ”one and the same” när du säger att två saker är identiska.",
    "Verwenden Sie „one and the same“, wenn zwei Dinge identisch sind.",
    "Użyj „one and the same”, gdy stwierdzasz, że dwie rzeczy są identyczne.",
    "Use «one and the same» para dizer que duas coisas são idênticas.",
  ],
  review_msg_pique_interest: [
    "Use ‘pique’ for arousing interest, keeping the verb’s tense.",
    "Utilisez « pique » pour éveiller l’intérêt, en conservant le temps du verbe.",
    "Za pobuđivanje zanimanja upotrijebite „pique”, uz očuvanje glagolskog vremena.",
    "Use «pique» para despertar interés y conserve el tiempo verbal.",
    "Χρησιμοποιήστε το «pique» για την πρόκληση ενδιαφέροντος, διατηρώντας τον χρόνο του ρήματος.",
    "Använd ”pique” för att väcka intresse och behåll verbets tempus.",
    "Verwenden Sie „pique“, um Interesse zu wecken, und behalten Sie die Zeitform bei.",
    "Użyj „pique” dla wzbudzania zainteresowania, zachowując czas czasownika.",
    "Use «pique» para despertar interesse, mantendo o tempo verbal.",
  ],
  review_msg_doubled_degree: [
    "This word already expresses the degree of comparison; remove the redundant marker.",
    "Ce mot exprime déjà le degré de comparaison ; supprimez le marqueur redondant.",
    "Ova riječ već izražava stupanj usporedbe; uklonite suvišnu oznaku.",
    "Esta palabra ya expresa el grado de comparación; quite el marcador redundante.",
    "Αυτή η λέξη εκφράζει ήδη τον βαθμό σύγκρισης· αφαιρέστε τον περιττό δείκτη.",
    "Ordet uttrycker redan jämförelsegraden; ta bort den överflödiga markören.",
    "Dieses Wort drückt bereits die Vergleichsstufe aus; entfernen Sie die überflüssige Steigerung.",
    "To słowo już wyraża stopień porównania; usuń zbędny określnik.",
    "Esta palavra já expressa o grau de comparação; remova o marcador redundante.",
  ],
  review_msg_countability: [
    "Check noun countability in ordinary prose.",
    "Vérifiez les noms dénombrables dans la prose courante.",
    "Provjerite brojivost imenica u običnom tekstu.",
    "Revise los sustantivos contables en la prosa común.",
    "Ελέγξτε τα μετρήσιμα ουσιαστικά στον καθημερινό λόγο.",
    "Kontrollera substantivs räknebarhet i vanlig text.",
    "Prüfen Sie die Zählbarkeit von Substantiven in Alltagstexten.",
    "Sprawdź policzalność rzeczowników w zwykłym tekście.",
    "Verifique os substantivos contáveis na prosa comum.",
  ],
  review_msg_contextual_grammar: [
    "Check this grammatical form in this construction.",
    "Vérifiez cette forme grammaticale dans cette construction.",
    "Provjerite ovaj gramatički oblik u ovoj konstrukciji.",
    "Revisa esta forma gramatical en esta construcción.",
    "Ελέγξτε αυτόν τον γραμματικό τύπο σε αυτή τη σύνταξη.",
    "Kontrollera den grammatiska formen i den här konstruktionen.",
    "Prüfe diese grammatische Form in dieser Konstruktion.",
    "Sprawdź tę formę gramatyczną w tej konstrukcji.",
    "Verifique esta forma gramatical nesta construção.",
  ],
  review_msg_mass_noun: [
    "This noun normally has no plural ending in this ordinary-prose context.",
    "Dans ce contexte courant, ce nom ne prend normalement pas de marque du pluriel.",
    "U ovom običnom kontekstu ova imenica obično nema nastavak za množinu.",
    "En este contexto común, este sustantivo normalmente no lleva terminación plural.",
    "Σε αυτό το καθημερινό πλαίσιο, το ουσιαστικό συνήθως δεν παίρνει κατάληξη πληθυντικού.",
    "I det här vanliga sammanhanget har substantivet normalt ingen pluraländelse.",
    "In diesem alltäglichen Kontext hat dieses Substantiv normalerweise keine Pluralendung.",
    "W tym zwykłym kontekście ten rzeczownik zazwyczaj nie ma końcówki liczby mnogiej.",
    "Neste contexto comum, este substantivo normalmente não tem terminação de plural.",
  ],
  review_msg_countable_number: [
    "Use the noun form that matches the stated number.",
    "Utilisez la forme du nom correspondant au nombre indiqué.",
    "Upotrijebite oblik imenice koji odgovara navedenom broju.",
    "Use la forma del sustantivo que corresponde al número indicado.",
    "Χρησιμοποιήστε τη μορφή του ουσιαστικού που αντιστοιχεί στον αριθμό.",
    "Använd substantivformen som passar det angivna antalet.",
    "Verwenden Sie die Substantivform, die zur angegebenen Zahl passt.",
    "Użyj formy rzeczownika zgodnej z podaną liczbą.",
    "Use a forma do substantivo que corresponde ao número indicado.",
  ],
  review_msg_compounds: [
    "Check compound words in context.",
    "Vérifiez les mots composés en contexte.",
    "Provjerite složenice u kontekstu.",
    "Revise las palabras compuestas en contexto.",
    "Ελέγξτε τις σύνθετες λέξεις στο συμφραζόμενο.",
    "Kontrollera sammansättningar i sitt sammanhang.",
    "Zusammensetzungen im Kontext prüfen.",
    "Sprawdź wyrazy złożone w kontekście.",
    "Verifique as palavras compostas no contexto.",
  ],
  review_msg_everyday_adjective: [
    "Before a noun, the adjective “everyday” (ordinary) is one word.",
    "Devant un nom, l’adjectif « everyday » (ordinaire) s’écrit en un mot.",
    "Ispred imenice pridjev „everyday” (svakodnevni) piše se kao jedna riječ.",
    "Delante de un sustantivo, el adjetivo «everyday» (cotidiano) va en una palabra.",
    "Πριν από ουσιαστικό, το επίθετο «everyday» (καθημερινός) γράφεται ως μία λέξη.",
    "Före ett substantiv skrivs adjektivet ”everyday” (vardaglig) i ett ord.",
    "Vor einem Nomen wird das Adjektiv „everyday“ (alltäglich) zusammengeschrieben.",
    "Przed rzeczownikiem przymiotnik „everyday” (codzienny) pisze się łącznie.",
    "Antes de um substantivo, o adjetivo “everyday” (cotidiano) é uma só palavra.",
  ],
  review_msg_double_negative: [
    "The verb is already negative; standard English uses “any” here.",
    "Le verbe est déjà négatif ; l’anglais standard emploie ici « any ».",
    "Glagol je već niječan; standardni engleski ovdje koristi „any”.",
    "El verbo ya es negativo; el inglés estándar usa aquí «any».",
    "Το ρήμα είναι ήδη αρνητικό· τα τυπικά αγγλικά χρησιμοποιούν εδώ «any».",
    "Verbet är redan negerat; standardengelska använder ”any” här.",
    "Das Verb ist bereits verneint; Standardenglisch verwendet hier „any“.",
    "Czasownik jest już przeczący; standardowy angielski używa tu „any”.",
    "O verbo já é negativo; o inglês padrão usa “any” aqui.",
  ],
  review_msg_a_few: [
    "“A few … ago” means some time ago; without “a”, “few” means hardly any.",
    "« A few … ago » signifie il y a quelque temps ; sans « a », « few » signifie presque aucun.",
    "„A few … ago” znači prije nekog vremena; bez „a” riječ „few” znači gotovo nijedan.",
    "«A few … ago» significa hace un tiempo; sin «a», «few» significa casi ninguno.",
    "Το «a few … ago» σημαίνει πριν από λίγο καιρό· χωρίς «a», το «few» σημαίνει σχεδόν κανένας.",
    "”A few … ago” betyder för en tid sedan; utan ”a” betyder ”few” nästan inga.",
    "„A few … ago“ bedeutet vor einiger Zeit; ohne „a“ heißt „few“ kaum welche.",
    "„A few … ago” znaczy jakiś czas temu; bez „a” słowo „few” znaczy prawie żaden.",
    "“A few … ago” significa há algum tempo; sem “a”, “few” significa quase nenhum.",
  ],
  review_msg_since_duration: [
    "“Since” takes a starting point; a length of time takes “for”.",
    "« Since » introduit un point de départ ; une durée demande « for ».",
    "„Since” uvodi početnu točku; trajanje traži „for”.",
    "«Since» indica un punto de partida; una duración requiere «for».",
    "Το «since» δηλώνει σημείο έναρξης· η διάρκεια θέλει «for».",
    "”Since” anger en startpunkt; en tidslängd kräver ”for”.",
    "„Since“ nennt einen Anfangspunkt; eine Zeitdauer verlangt „for“.",
    "„Since” wskazuje punkt początkowy; okres czasu wymaga „for”.",
    "“Since” indica um ponto de partida; uma duração pede “for”.",
  ],
  review_msg_every_day: [
    "Use “every day” for how often this action happens.",
    "Utilisez « every day » pour la fréquence de cette action.",
    "Za učestalost ove radnje upotrijebite „every day”.",
    "Use «every day» para indicar la frecuencia de esta acción.",
    "Χρησιμοποιήστε «every day» για τη συχνότητα αυτής της ενέργειας.",
    "Använd ”every day” för hur ofta handlingen sker.",
    "Verwenden Sie „every day“, um die Häufigkeit dieser Handlung anzugeben.",
    "Użyj „every day”, aby określić częstotliwość tej czynności.",
    "Use “every day” para indicar a frequência desta ação.",
  ],
  review_msg_log_in: [
    "This verb position calls for “log in”; “login” is a noun or modifier.",
    "Cette position verbale demande « log in » ; « login » est un nom ou un qualificatif.",
    "Na ovom glagolskom mjestu upotrijebite „log in”; „login” je imenica ili atribut.",
    "Esta posición verbal requiere «log in»; «login» es un nombre o modificador.",
    "Αυτή η ρηματική θέση χρειάζεται «log in»· το «login» είναι ουσιαστικό ή προσδιορισμός.",
    "Den här verbpositionen kräver ”log in”; ”login” är ett substantiv eller en bestämning.",
    "An dieser Verbstelle steht „log in“; „login“ ist ein Substantiv oder Attribut.",
    "W tej pozycji czasownika użyj „log in”; „login” jest rzeczownikiem lub określeniem.",
    "Esta posição verbal pede “log in”; “login” é um nome ou modificador.",
  ],
  review_msg_set_up: [
    "This verb position calls for “set up”; “setup” names an arrangement.",
    "Cette position verbale demande « set up » ; « setup » désigne une configuration.",
    "Na ovom glagolskom mjestu upotrijebite „set up”; „setup” označuje postavu.",
    "Esta posición verbal requiere «set up»; «setup» designa una configuración.",
    "Αυτή η ρηματική θέση χρειάζεται «set up»· το «setup» ονομάζει μια διάταξη.",
    "Den här verbpositionen kräver ”set up”; ”setup” betecknar en uppställning.",
    "An dieser Verbstelle steht „set up“; „setup“ bezeichnet eine Anordnung.",
    "W tej pozycji czasownika użyj „set up”; „setup” nazywa konfigurację.",
    "Esta posição verbal pede “set up”; “setup” designa uma configuração.",
  ],
  review_msg_noun_count: [
    "Keep the stated count and use the matching noun form.",
    "Conservez le nombre indiqué et accordez le nom.",
    "Zadržite navedeni broj i upotrijebite odgovarajući oblik imenice.",
    "Conserve la cantidad indicada y use la forma nominal correspondiente.",
    "Διατηρήστε τον αριθμό και χρησιμοποιήστε την αντίστοιχη μορφή του ουσιαστικού.",
    "Behåll det angivna antalet och använd rätt substantivform.",
    "Behalten Sie die angegebene Anzahl bei und passen Sie die Substantivform an.",
    "Zachowaj podaną liczbę i dopasuj formę rzeczownika.",
    "Mantenha a quantidade indicada e use a forma nominal correspondente.",
  ],
  review_msg_noun_choice: [
    "Choose singular or plural according to your intended meaning.",
    "Choisissez le singulier ou le pluriel selon le sens voulu.",
    "Odaberite jedninu ili množinu prema željenom značenju.",
    "Elija singular o plural según el significado deseado.",
    "Επιλέξτε ενικό ή πληθυντικό σύμφωνα με το νόημα που θέλετε.",
    "Välj singular eller plural efter vad du menar.",
    "Wählen Sie je nach beabsichtigter Bedeutung Singular oder Plural.",
    "Wybierz liczbę pojedynczą lub mnogą zgodnie z zamierzonym znaczeniem.",
    "Escolha singular ou plural conforme o significado pretendido.",
  ],
  review_msg_demonstrative_number: [
    "Match the demonstrative and noun to the number indicated by the verb.",
    "Accordez le démonstratif et le nom avec le nombre indiqué par le verbe.",
    "Uskladite pokaznu zamjenicu i imenicu s brojem koji označuje glagol.",
    "Haga concordar el demostrativo y el nombre con el número indicado por el verbo.",
    "Συμφωνήστε το δεικτικό και το ουσιαστικό με τον αριθμό του ρήματος.",
    "Anpassa demonstrativet och substantivet till det antal verbet anger.",
    "Passen Sie Demonstrativ und Substantiv an die vom Verb angezeigte Zahl an.",
    "Dopasuj zaimek wskazujący i rzeczownik do liczby wynikającej z czasownika.",
    "Faça concordar o demonstrativo e o nome com o número indicado pelo verbo.",
  ],
  review_msg_one_of: [
    "“One of the” selects one member of a plural group; keep the outer subject singular.",
    "« One of the » sélectionne un membre d’un groupe pluriel ; gardez le sujet au singulier.",
    "„One of the” odabire jednog člana množinske skupine; zadržite subjekt u jednini.",
    "«One of the» selecciona un miembro de un grupo plural; conserve el sujeto en singular.",
    "Το «one of the» επιλέγει ένα μέλος μιας ομάδας· κρατήστε το υποκείμενο στον ενικό.",
    "”One of the” väljer en medlem ur en grupp; behåll subjektet i singular.",
    "„One of the“ wählt ein Mitglied einer Gruppe; das äußere Subjekt bleibt im Singular.",
    "„One of the” wybiera jeden element grupy; zachowaj podmiot w liczbie pojedynczej.",
    "“One of the” seleciona um membro de um grupo plural; mantenha o sujeito no singular.",
  ],
  review_msg_decade_plural: [
    "A decade or a round number in the plural takes no apostrophe: “the 1990s”, “the ’80s”, “100s of”.",
    "Une décennie ou un nombre rond au pluriel s’écrit sans apostrophe : « the 1990s », « the ’80s », « 100s of ».",
    "Desetljeće ili okrugli broj u množini piše se bez apostrofa: „the 1990s”, „the ’80s”, „100s of”.",
    "Una década o un número redondo en plural no lleva apóstrofo: «the 1990s», «the ’80s», «100s of».",
    "Μια δεκαετία ή ένας στρογγυλός αριθμός στον πληθυντικό γράφεται χωρίς απόστροφο: «the 1990s», «the ’80s», «100s of».",
    "Ett decennium eller ett jämnt tal i plural skrivs utan apostrof: ”the 1990s”, ”the ’80s”, ”100s of”.",
    "Ein Jahrzehnt oder eine runde Zahl im Plural steht ohne Apostroph: „the 1990s“, „the ’80s“, „100s of“.",
    "Dekada lub okrągła liczba w liczbie mnogiej nie ma apostrofu: „the 1990s”, „the ’80s”, „100s of”.",
    "Uma década ou um número redondo no plural não leva apóstrofo: “the 1990s”, “the ’80s”, “100s of”.",
  ],
  review_msg_perfect_participle: [
    "This perfect-tense construction needs the past participle; keep the auxiliary and tense.",
    "Cette construction au parfait demande le participe passé ; conservez l’auxiliaire et le temps.",
    "Ova konstrukcija perfekta zahtijeva particip prošli; zadržite pomoćni glagol i vrijeme.",
    "Esta construcción de tiempo perfecto requiere el participio pasado; conserve el auxiliar y el tiempo.",
    "Αυτή η σύνταξη συντελεσμένου χρόνου χρειάζεται μετοχή παρακειμένου· διατηρήστε το βοηθητικό ρήμα και τον χρόνο.",
    "Den här perfektkonstruktionen behöver perfekt particip; behåll hjälpverbet och tempus.",
    "Diese Perfektkonstruktion benötigt das Partizip Perfekt; Hilfsverb und Zeitform bleiben erhalten.",
    "Ta konstrukcja czasu perfect wymaga imiesłowu przeszłego; zachowaj czasownik pomocniczy i czas.",
    "Esta construção de tempo perfeito pede o particípio passado; mantenha o auxiliar e o tempo.",
  ],
  review_msg_progressive_be: [
    "An -ing verb after a subject needs “be” (“I'm looking”), or “have been” for an ongoing action.",
    "Un verbe en -ing après le sujet demande « be » (« I'm looking ») ou « have been » pour une action en cours.",
    "Glagol na -ing nakon subjekta traži „be” („I'm looking”) ili „have been” za radnju koja traje.",
    "Un verbo en -ing tras el sujeto requiere «be» («I'm looking») o «have been» para una acción en curso.",
    "Ένα ρήμα σε -ing μετά το υποκείμενο θέλει «be» («I'm looking») ή «have been» για συνεχιζόμενη πράξη.",
    "Ett -ing-verb efter subjektet kräver ”be” (”I'm looking”) eller ”have been” för en pågående handling.",
    "Ein Verb auf -ing nach dem Subjekt braucht „be“ („I'm looking“) oder „have been“ für eine andauernde Handlung.",
    "Czasownik z -ing po podmiocie wymaga „be” („I'm looking”) lub „have been” dla trwającej czynności.",
    "Um verbo em -ing após o sujeito pede “be” (“I'm looking”) ou “have been” para uma ação em curso.",
  ],
  review_msg_be_participle: [
    "After “be”, a passive or perfect needs the past participle (“was taken”, not “was took”).",
    "Après « be », le passif ou le parfait demande le participe passé (« was taken », pas « was took »).",
    "Nakon „be” pasiv ili perfekt traži particip prošli („was taken”, ne „was took”).",
    "Tras «be», la pasiva o el perfecto requieren el participio pasado («was taken», no «was took»).",
    "Μετά το «be», η παθητική φωνή ή ο συντελεσμένος χρόνος θέλει μετοχή παρακειμένου («was taken», όχι «was took»).",
    "Efter ”be” kräver passiv eller perfekt perfekt particip (”was taken”, inte ”was took”).",
    "Nach „be“ braucht Passiv oder Perfekt das Partizip Perfekt („was taken“, nicht „was took“).",
    "Po „be” strona bierna lub czas perfect wymaga imiesłowu przeszłego („was taken”, nie „was took”).",
    "Depois de “be”, a passiva ou o perfeito pede o particípio passado (“was taken”, não “was took”).",
  ],
  review_msg_had_or_would: [
    "“'d” is had or would: had takes the past participle (“I'd gone”), would the base verb (“I'd go”).",
    "« 'd » vaut had ou would : had demande le participe passé (« I'd gone »), would la base verbale (« I'd go »).",
    "„'d” je had ili would: had traži particip prošli („I'd gone”), would osnovni glagol („I'd go”).",
    "«'d» es had o would: had pide el participio pasado («I'd gone»), would el verbo en forma base («I'd go»).",
    "Το «'d» είναι had ή would: το had θέλει μετοχή παρακειμένου («I'd gone»), το would το βασικό ρήμα («I'd go»).",
    "”'d” är had eller would: had kräver perfekt particip (”I'd gone”), would grundformen (”I'd go”).",
    "„'d“ steht für had oder would: had braucht das Partizip Perfekt („I'd gone“), would die Grundform („I'd go“).",
    "„'d” to had albo would: had wymaga imiesłowu przeszłego („I'd gone”), would formy podstawowej („I'd go”).",
    "“'d” é had ou would: had pede o particípio passado (“I'd gone”), would o verbo na forma base (“I'd go”).",
  ],
  review_msg_be_base: [
    "A base verb after am/is/are needs -ing (“I am going”), or drop “be” for the simple present (“I go”).",
    "Un verbe à la base après am/is/are demande -ing (« I am going »), ou retirez « be » pour le présent simple (« I go »).",
    "Osnovni glagol nakon am/is/are traži -ing („I am going”) ili izostavite „be” za jednostavni prezent („I go”).",
    "Un verbo en forma base tras am/is/are requiere -ing («I am going»), o quite «be» para el presente simple («I go»).",
    "Ένα ρήμα στη βασική μορφή μετά από am/is/are θέλει -ing («I am going»), ή αφαιρέστε το «be» για απλό ενεστώτα («I go»).",
    "Ett grundverb efter am/is/are kräver -ing (”I am going”), eller ta bort ”be” för enkel presens (”I go”).",
    "Ein Verb in der Grundform nach am/is/are braucht -ing („I am going“), oder „be“ entfällt für das Simple Present („I go“).",
    "Czasownik w formie podstawowej po am/is/are wymaga -ing („I am going”) albo usuń „be” dla czasu present simple („I go”).",
    "Um verbo na forma base depois de am/is/are pede -ing (“I am going”), ou retire “be” para o presente simples (“I go”).",
  ],
  review_msg_verb_complements: [
    "Check infinitive and gerund complements.",
    "Vérifiez les compléments infinitifs et en -ing.",
    "Provjerite infinitivne i gerundne dopune.",
    "Revise los complementos de infinitivo y gerundio.",
    "Ελέγξτε τα απαρέμφατα και τα συμπληρώματα σε -ing.",
    "Kontrollera infinitiv- och gerundiumkomplement.",
    "Infinitiv- und Gerundiumergänzungen prüfen.",
    "Sprawdź dopełnienia bezokolicznikowe i formy -ing.",
    "Verifique os complementos de infinitivo e gerúndio.",
  ],
  review_msg_missing_to: [
    "This complete verb construction needs “to” before the following action.",
    "Cette construction verbale complète demande « to » avant l’action suivante.",
    "Ova potpuna glagolska konstrukcija zahtijeva „to” prije sljedeće radnje.",
    "Esta construcción verbal completa requiere «to» antes de la acción siguiente.",
    "Αυτή η πλήρης ρηματική σύνταξη χρειάζεται «to» πριν από την επόμενη ενέργεια.",
    "Den här fullständiga verbkonstruktionen behöver ”to” före nästa handling.",
    "Diese vollständige Verbkonstruktion benötigt „to“ vor der folgenden Handlung.",
    "Ta pełna konstrukcja czasownikowa wymaga „to” przed następującą czynnością.",
    "Esta construção verbal completa pede “to” antes da ação seguinte.",
  ],
  review_msg_forward_gerund: [
    "After “look forward to”, use the action’s -ing form.",
    "Après « look forward to », utilisez la forme en -ing de l’action.",
    "Nakon „look forward to” upotrijebite oblik radnje na -ing.",
    "Después de «look forward to», use la forma en -ing de la acción.",
    "Μετά το «look forward to», χρησιμοποιήστε τη μορφή της ενέργειας σε -ing.",
    "Efter ”look forward to” används handlingens -ing-form.",
    "Verwenden Sie nach „look forward to“ die -ing-Form der Handlung.",
    "Po „look forward to” użyj formy czynności z końcówką -ing.",
    "Depois de “look forward to”, use a forma em -ing da ação.",
  ],
  review_msg_worth_gerund: [
    "After “worth”, use the action’s -ing form.",
    "Après « worth », utilisez la forme en -ing de l’action.",
    "Nakon „worth” upotrijebite oblik radnje na -ing.",
    "Después de «worth», use la forma en -ing de la acción.",
    "Μετά το «worth», χρησιμοποιήστε τη μορφή της ενέργειας σε -ing.",
    "Efter ”worth” används handlingens -ing-form.",
    "Verwenden Sie nach „worth“ die -ing-Form der Handlung.",
    "Po „worth” użyj formy czynności z końcówką -ing.",
    "Depois de “worth”, use a forma em -ing da ação.",
  ],
  review_msg_causative_base: [
    "After “let”, “make” or “help” and its object, use the plain base form of the verb.",
    "Après « let », « make » ou « help » suivi de son complément, utilisez la base verbale simple.",
    "Nakon „let”, „make” ili „help” i objekta upotrijebite osnovni oblik glagola.",
    "Después de «let», «make» o «help» y su objeto, use la forma base del verbo.",
    "Μετά το «let», «make» ή «help» και το αντικείμενό του, χρησιμοποιήστε τη βασική μορφή του ρήματος.",
    "Efter ”let”, ”make” eller ”help” och dess objekt används verbets grundform.",
    "Verwenden Sie nach „let“, „make“ oder „help“ mit Objekt die Grundform des Verbs.",
    "Po „let”, „make” lub „help” i dopełnieniu użyj podstawowej formy czasownika.",
    "Depois de “let”, “make” ou “help” e o seu objeto, use a forma base do verbo.",
  ],
  review_msg_allow_object: [
    "“Allow” and “enable” need an object before “to”, or the action’s -ing form.",
    "« Allow » et « enable » demandent un complément avant « to », ou la forme en -ing de l’action.",
    "„Allow” i „enable” zahtijevaju objekt prije „to” ili oblik radnje na -ing.",
    "«Allow» y «enable» necesitan un objeto antes de «to» o la forma en -ing de la acción.",
    "Τα «allow» και «enable» χρειάζονται αντικείμενο πριν από το «to» ή τη μορφή της ενέργειας σε -ing.",
    "”Allow” och ”enable” behöver ett objekt före ”to” eller handlingens -ing-form.",
    "„Allow“ und „enable“ brauchen vor „to“ ein Objekt oder die -ing-Form der Handlung.",
    "„Allow” i „enable” wymagają dopełnienia przed „to” albo formy czynności z końcówką -ing.",
    "“Allow” e “enable” pedem um objeto antes de “to” ou a forma em -ing da ação.",
  ],
  review_msg_ahead_and_tense: [
    "After “went ahead and” or “go ahead and”, keep the second verb in the same tense.",
    "Après « went ahead and » ou « go ahead and », gardez le second verbe au même temps.",
    "Nakon „went ahead and” ili „go ahead and” drugi glagol ostaje u istom vremenu.",
    "Después de «went ahead and» o «go ahead and», mantenga el segundo verbo en el mismo tiempo.",
    "Μετά το «went ahead and» ή «go ahead and», κρατήστε το δεύτερο ρήμα στον ίδιο χρόνο.",
    "Efter ”went ahead and” eller ”go ahead and” står det andra verbet i samma tempus.",
    "Setzen Sie nach „went ahead and“ oder „go ahead and“ das zweite Verb in dieselbe Zeitform.",
    "Po „went ahead and” lub „go ahead and” drugi czasownik zachowuje ten sam czas.",
    "Depois de “went ahead and” ou “go ahead and”, mantenha o segundo verbo no mesmo tempo.",
  ],
  review_msg_gerund_complement: [
    "This verb takes the action’s -ing form, not “to” and the base form.",
    "Ce verbe se construit avec la forme en -ing de l’action, pas avec « to » et la base verbale.",
    "Ovaj glagol traži oblik radnje na -ing, a ne „to” i osnovni oblik.",
    "Este verbo lleva la forma en -ing de la acción, no «to» y la forma base.",
    "Αυτό το ρήμα θέλει τη μορφή της ενέργειας σε -ing, όχι «to» και τη βασική μορφή.",
    "Det här verbet tar handlingens -ing-form, inte ”to” och grundformen.",
    "Dieses Verb verlangt die -ing-Form der Handlung, nicht „to“ und die Grundform.",
    "Ten czasownik wymaga formy czynności z końcówką -ing, a nie „to” i formy podstawowej.",
    "Este verbo pede a forma em -ing da ação, não “to” e a forma base.",
  ],
  review_msg_fixed_prepositions: [
    "Check prepositions in established constructions.",
    "Vérifiez les prépositions dans les constructions établies.",
    "Provjerite prijedloge u ustaljenim konstrukcijama.",
    "Revise las preposiciones en construcciones establecidas.",
    "Ελέγξτε τις προθέσεις σε καθιερωμένες συντάξεις.",
    "Kontrollera prepositioner i etablerade uttryck.",
    "Präpositionen in festen Konstruktionen prüfen.",
    "Sprawdź przyimki w ustalonych konstrukcjach.",
    "Verifique as preposições em construções estabelecidas.",
  ],
  review_msg_despite_of: [
    "Use “despite” directly before this noun phrase, without “of”.",
    "Utilisez « despite » directement devant ce groupe nominal, sans « of ».",
    "Upotrijebite „despite” izravno ispred ove imenske skupine, bez „of”.",
    "Use «despite» directamente antes de este grupo nominal, sin «of».",
    "Χρησιμοποιήστε «despite» πριν από αυτή την ονοματική φράση, χωρίς «of».",
    "Använd ”despite” direkt före denna substantivfras, utan ”of”.",
    "Verwenden Sie „despite“ direkt vor dieser Nominalgruppe, ohne „of“.",
    "Użyj „despite” bezpośrednio przed tą frazą rzeczownikową, bez „of”.",
    "Use “despite” diretamente antes desta expressão nominal, sem “of”.",
  ],
  review_msg_discuss_about: [
    "“Discuss” takes this topic directly, without “about”.",
    "« Discuss » prend ce sujet directement, sans « about ».",
    "Uz „discuss” ova tema dolazi izravno, bez „about”.",
    "«Discuss» lleva este tema directamente, sin «about».",
    "Το «discuss» συνδέεται απευθείας με αυτό το θέμα, χωρίς «about».",
    "”Discuss” följs direkt av detta ämne, utan ”about”.",
    "Nach „discuss“ steht dieses Thema direkt, ohne „about“.",
    "Po „discuss” podaj ten temat bezpośrednio, bez „about”.",
    "“Discuss” recebe este assunto diretamente, sem “about”.",
  ],
  review_msg_interested_on: [
    "Use “interested in” for this activity or topic.",
    "Utilisez « interested in » pour cette activité ou ce sujet.",
    "Za ovu aktivnost ili temu upotrijebite „interested in”.",
    "Use «interested in» para esta actividad o tema.",
    "Χρησιμοποιήστε «interested in» για αυτή τη δραστηριότητα ή το θέμα.",
    "Använd ”interested in” för denna aktivitet eller detta ämne.",
    "Verwenden Sie „interested in“ für diese Tätigkeit oder dieses Thema.",
    "Dla tej czynności lub tematu użyj „interested in”.",
    "Use “interested in” para esta atividade ou assunto.",
  ],
  review_msg_its_possessive: [
    "This noun phrase needs possessive “its”, without an apostrophe.",
    "Ce groupe nominal demande le possessif « its », sans apostrophe.",
    "Ova imenska skupina zahtijeva posvojno „its”, bez apostrofa.",
    "Este grupo nominal requiere el posesivo «its», sin apóstrofo.",
    "Αυτή η ονοματική φράση χρειάζεται το κτητικό «its», χωρίς απόστροφο.",
    "Den här substantivfrasen behöver possessivt ”its”, utan apostrof.",
    "Diese Nominalgruppe benötigt das besitzanzeigende „its“ ohne Apostroph.",
    "Ta fraza wymaga dzierżawczego „its”, bez apostrofu.",
    "Esta expressão nominal pede o possessivo “its”, sem apóstrofo.",
  ],
  review_msg_its_contraction: [
    "This clause needs “it is” or “it has”, contracted as “it’s”.",
    "Cette proposition demande « it is » ou « it has », abrégé en « it’s ».",
    "Ova surečenica zahtijeva „it is” ili „it has”, skraćeno „it’s”.",
    "Esta oración requiere «it is» o «it has», contraído como «it’s».",
    "Αυτή η πρόταση χρειάζεται «it is» ή «it has», σε σύντμηση «it’s».",
    "Den här satsen behöver ”it is” eller ”it has”, förkortat ”it’s”.",
    "Dieser Satz benötigt „it is“ oder „it has“, verkürzt zu „it’s“.",
    "To zdanie wymaga „it is” lub „it has”, w skrócie „it’s”.",
    "Esta oração pede “it is” ou “it has”, contraído como “it’s”.",
  ],
  review_msg_lets_contraction: [
    "This suggestion means “let us”, contracted as “let’s”.",
    "Cette suggestion signifie « let us », abrégé en « let’s ».",
    "Ovaj prijedlog znači „let us”, skraćeno „let’s”.",
    "Esta sugerencia significa «let us», contraído como «let’s».",
    "Αυτή η πρόταση σημαίνει «let us», σε σύντμηση «let’s».",
    "Det här förslaget betyder ”let us”, förkortat ”let’s”.",
    "Dieser Vorschlag bedeutet „let us“, verkürzt zu „let’s“.",
    "Ta propozycja oznacza „let us”, w skrócie „let’s”.",
    "Esta sugestão significa “let us”, contraído como “let’s”.",
  ],
  review_msg_else_possessive: [
    "Use “else’s” to mark possession after this indefinite pronoun.",
    "Utilisez « else’s » pour marquer la possession après ce pronom indéfini.",
    "Upotrijebite „else’s” za posvojnost nakon ove neodređene zamjenice.",
    "Use «else’s» para indicar posesión después de este pronombre indefinido.",
    "Χρησιμοποιήστε «else’s» για κτήση μετά από αυτή την αόριστη αντωνυμία.",
    "Använd ”else’s” för att markera ägande efter detta obestämda pronomen.",
    "Verwenden Sie „else’s“, um Besitz nach diesem Indefinitpronomen auszudrücken.",
    "Użyj „else’s”, aby wyrazić przynależność po tym zaimku nieokreślonym.",
    "Use “else’s” para indicar posse após este pronome indefinido.",
  ],
  review_msg_existential_agreement: [
    "Use a verb that agrees with the stated number of nouns after “there”.",
    "Accordez le verbe avec le nombre indiqué après « there ».",
    "Uskladite glagol s navedenim brojem imenica nakon „there”.",
    "Use un verbo que concuerde con la cantidad indicada después de «there».",
    "Χρησιμοποιήστε ρήμα που συμφωνεί με τον αριθμό μετά το «there».",
    "Använd ett verb som stämmer med det angivna antalet efter ”there”.",
    "Passen Sie das Verb an die angegebene Anzahl nach „there“ an.",
    "Dopasuj czasownik do podanej liczby rzeczowników po „there”.",
    "Use um verbo que concorde com a quantidade indicada depois de “there”.",
  ],
  review_msg_then_than: [
    "This comparison calls for “than”.",
    "Cette comparaison demande « than ».",
    "U ovoj usporedbi upotrijebite „than”.",
    "Esta comparación requiere «than».",
    "Σε αυτή τη σύγκριση χρειάζεται το «than».",
    "Den här jämförelsen kräver ”than”.",
    "Dieser Vergleich erfordert „than“.",
    "W tym porównaniu użyj „than”.",
    "Esta comparação pede “than”.",
  ],
  review_msg_your_you_are: [
    "This construction calls for “you are”.",
    "Cette construction demande « you are ».",
    "Ova konstrukcija zahtijeva „you are”.",
    "Esta construcción requiere «you are».",
    "Αυτή η σύνταξη χρειάζεται το «you are».",
    "Den här konstruktionen kräver ”you are”.",
    "Diese Konstruktion erfordert „you are“.",
    "Ta konstrukcja wymaga „you are”.",
    "Esta construção pede “you are”.",
  ],
  review_msg_they_are: [
    "This construction calls for “they are”.",
    "Cette construction demande « they are ».",
    "Ova konstrukcija zahtijeva „they are”.",
    "Esta construcción requiere «they are».",
    "Αυτή η σύνταξη χρειάζεται το «they are».",
    "Den här konstruktionen kräver ”they are”.",
    "Diese Konstruktion erfordert „they are“.",
    "Ta konstrukcja wymaga „they are”.",
    "Esta construção pede “they are”.",
  ],
  review_msg_your_possessive: [
    "This noun phrase calls for the possessive “your”.",
    "Ce groupe nominal demande le possessif « your ».",
    "Ova imenska skupina zahtijeva posvojno „your”.",
    "Este grupo nominal requiere el posesivo «your».",
    "Αυτή η ονοματική φράση χρειάζεται το κτητικό «your».",
    "Den här nominalfrasen kräver possessivt ”your”.",
    "Diese Nominalgruppe erfordert das besitzanzeigende „your“.",
    "Ta fraza rzeczownikowa wymaga formy dzierżawczej „your”.",
    "Este grupo nominal pede o possessivo “your”.",
  ],
  review_msg_their_possessive: [
    "This noun phrase calls for the possessive “their”.",
    "Ce groupe nominal demande le possessif « their ».",
    "Ova imenska skupina zahtijeva posvojno „their”.",
    "Este grupo nominal requiere el posesivo «their».",
    "Αυτή η ονοματική φράση χρειάζεται το κτητικό «their».",
    "Den här nominalfrasen kräver possessivt ”their”.",
    "Diese Nominalgruppe erfordert das besitzanzeigende „their“.",
    "Ta fraza rzeczownikowa wymaga formy dzierżawczej „their”.",
    "Este grupo nominal pede o possessivo “their”.",
  ],
  review_msg_then_than_temporal: [
    "A point in time takes “then”; “than” only compares.",
    "Un moment dans le temps demande « then » ; « than » sert seulement à comparer.",
    "Vremenska odrednica traži „then”; „than” služi samo za usporedbu.",
    "Un momento en el tiempo requiere «then»; «than» solo compara.",
    "Για χρονική στιγμή χρειάζεται το «then»· το «than» χρησιμοποιείται μόνο σε σύγκριση.",
    "En tidpunkt kräver ”then”; ”than” används bara i jämförelser.",
    "Ein Zeitpunkt verlangt „then“; „than“ steht nur in Vergleichen.",
    "Punkt w czasie wymaga „then”; „than” służy tylko do porównań.",
    "Um momento no tempo pede “then”; “than” só compara.",
  ],
  review_msg_ever_every: [
    "Between an auxiliary and its verb, “ever” means “at any time”; “every” needs a noun.",
    "Entre un auxiliaire et son verbe, « ever » signifie « à un moment quelconque » ; « every » demande un nom.",
    "Između pomoćnog glagola i glagola „ever” znači „ikada”; „every” traži imenicu.",
    "Entre un auxiliar y su verbo, «ever» significa «alguna vez»; «every» requiere un sustantivo.",
    "Ανάμεσα σε βοηθητικό ρήμα και ρήμα, το «ever» σημαίνει «ποτέ»· το «every» θέλει ουσιαστικό.",
    "Mellan ett hjälpverb och dess verb betyder ”ever” ”någonsin”; ”every” kräver ett substantiv.",
    "Zwischen Hilfsverb und Verb bedeutet „ever“ „jemals“; „every“ braucht ein Nomen.",
    "Między czasownikiem posiłkowym a czasownikiem „ever” znaczy „kiedykolwiek”; „every” wymaga rzeczownika.",
    "Entre um auxiliar e o seu verbo, “ever” significa “alguma vez”; “every” pede um substantivo.",
  ],
  review_msg_to_infinitive: [
    "Before a verb, a noun phrase or a pronoun, use “to”; “too” means “also” or “excessively”.",
    "Devant un verbe, un groupe nominal ou un pronom, utilisez « to » ; « too » signifie « aussi » ou « trop ».",
    "Ispred glagola, imenske skupine ili zamjenice upotrijebite „to”; „too” znači „također” ili „previše”.",
    "Ante un verbo, un sintagma nominal o un pronombre, use «to»; «too» significa «también» o «demasiado».",
    "Πριν από ρήμα, ονοματική φράση ή αντωνυμία χρησιμοποιήστε «to»· το «too» σημαίνει «επίσης» ή «υπερβολικά».",
    "Före ett verb, en nominalfras eller ett pronomen används ”to”; ”too” betyder ”också” eller ”för”.",
    "Vor einem Verb, einer Nominalphrase oder einem Pronomen steht „to“; „too“ bedeutet „auch“ oder „zu sehr“.",
    "Przed czasownikiem, frazą rzeczownikową lub zaimkiem użyj „to”; „too” znaczy „też” lub „zbyt”.",
    "Antes de um verbo, de um sintagma nominal ou de um pronome, use “to”; “too” significa “também” ou “demais”.",
  ],
  review_msg_were_where: [
    "Use “were” for the past of “be” and “where” for a place or an indirect question.",
    "Utilisez « were » pour le passé de « be » et « where » pour un lieu ou une question indirecte.",
    "Upotrijebite „were” za prošlo vrijeme glagola „be”, a „where” za mjesto ili neizravno pitanje.",
    "Use «were» para el pasado de «be» y «where» para un lugar o una pregunta indirecta.",
    "Χρησιμοποιήστε «were» για τον αόριστο του «be» και «where» για τόπο ή πλάγια ερώτηση.",
    "Använd ”were” för preteritum av ”be” och ”where” för en plats eller en indirekt fråga.",
    "Verwenden Sie „were“ für die Vergangenheit von „be“ und „where“ für einen Ort oder eine indirekte Frage.",
    "Użyj „were” dla czasu przeszłego „be”, a „where” dla miejsca lub pytania zależnego.",
    "Use “were” para o passado de “be” e “where” para um lugar ou uma pergunta indireta.",
  ],
  review_msg_to_too: [
    "Here “too” describes an excessive degree.",
    "Ici, « too » exprime un degré excessif.",
    "Ovdje „too” označava prevelik stupanj.",
    "Aquí «too» indica un grado excesivo.",
    "Εδώ το «too» δηλώνει υπερβολικό βαθμό.",
    "Här anger ”too” en alltför hög grad.",
    "Hier bezeichnet „too“ ein übermäßiges Maß.",
    "Tutaj „too” oznacza nadmierny stopień.",
    "Aqui “too” indica um grau excessivo.",
  ],
  review_msg_auxiliary_base: [
    "Use the base form of the verb after this auxiliary.",
    "Utilisez la forme de base du verbe après cet auxiliaire.",
    "Nakon ovog pomoćnog glagola upotrijebite osnovni oblik glagola.",
    "Use la forma base del verbo después de este auxiliar.",
    "Μετά από αυτό το βοηθητικό ρήμα χρησιμοποιήστε τη βασική μορφή του ρήματος.",
    "Använd verbets grundform efter detta hjälpverb.",
    "Nach diesem Hilfsverb steht die Grundform des Verbs.",
    "Po tym czasowniku pomocniczym użyj podstawowej formy czasownika.",
    "Use a forma base do verbo depois deste auxiliar.",
  ],
  review_msg_modal_be: [
    "After a modal verb, use the base form, or add “be” for a continuous or passive meaning.",
    "Après un verbe modal, utilisez la forme de base, ou ajoutez « be » pour un sens progressif ou passif.",
    "Nakon modalnog glagola upotrijebite osnovni oblik ili dodajte „be” za trajno ili pasivno značenje.",
    "Después de un verbo modal, use la forma base o añada «be» para un sentido continuo o pasivo.",
    "Μετά από τροπικό ρήμα χρησιμοποιήστε τη βασική μορφή ή προσθέστε «be» για διαρκή ή παθητική σημασία.",
    "Efter ett modalt hjälpverb används grundformen, eller lägg till ”be” för pågående eller passiv betydelse.",
    "Nach einem Modalverb steht die Grundform, oder „be“ für eine Verlaufs- oder Passivbedeutung.",
    "Po czasowniku modalnym użyj formy podstawowej albo dodaj „be” dla znaczenia ciągłego lub biernego.",
    "Depois de um verbo modal, use a forma base ou acrescente “be” para um sentido contínuo ou passivo.",
  ],
  review_msg_to_base: [
    "In this infinitive, use the base form of the verb after “to”.",
    "Dans cet infinitif, utilisez la forme de base du verbe après « to ».",
    "U ovom infinitivu nakon „to” upotrijebite osnovni oblik glagola.",
    "En este infinitivo, use la forma base del verbo después de «to».",
    "Σε αυτό το απαρέμφατο χρησιμοποιήστε τη βασική μορφή του ρήματος μετά το «to».",
    "I den här infinitiven används verbets grundform efter ”to”.",
    "In diesem Infinitiv steht nach „to“ die Grundform des Verbs.",
    "W tym bezokoliczniku po „to” użyj podstawowej formy czasownika.",
    "Neste infinitivo, use a forma base do verbo depois de “to”.",
  ],
  review_msg_to_noun: [
    "“to” needs a verb here; to make this noun the object, drop “to” or use “the”.",
    "Ici, « to » demande un verbe ; pour faire de ce nom le complément, supprimez « to » ou utilisez « the ».",
    "Ovdje „to” traži glagol; da ova imenica bude objekt, izostavite „to” ili upotrijebite „the”.",
    "Aquí «to» exige un verbo; para que este sustantivo sea el objeto, quite «to» o use «the».",
    "Εδώ το «to» θέλει ρήμα· για να γίνει αυτό το ουσιαστικό αντικείμενο, αφαιρέστε το «to» ή χρησιμοποιήστε «the».",
    "Här kräver ”to” ett verb; för att göra substantivet till objekt, ta bort ”to” eller använd ”the”.",
    "Hier verlangt „to“ ein Verb; damit dieses Nomen das Objekt ist, „to“ streichen oder „the“ verwenden.",
    "Tutaj „to” wymaga czasownika; aby ten rzeczownik był dopełnieniem, usuń „to” lub użyj „the”.",
    "Aqui “to” pede um verbo; para que este substantivo seja o objeto, retire “to” ou use “the”.",
  ],
  review_msg_pronoun_subject_case: [
    "This is the subject of the verb, so use the subject form of the pronoun (I, he, she, they).",
    "C’est le sujet du verbe : utilisez la forme sujet du pronom (I, he, she, they).",
    "Ovo je subjekt glagola, pa upotrijebite subjektni oblik zamjenice (I, he, she, they).",
    "Es el sujeto del verbo: use la forma de sujeto del pronombre (I, he, she, they).",
    "Αυτό είναι το υποκείμενο του ρήματος· χρησιμοποιήστε την ονομαστική της αντωνυμίας (I, he, she, they).",
    "Det här är verbets subjekt, så använd pronomenets subjektsform (I, he, she, they).",
    "Das ist das Subjekt des Verbs, daher steht die Subjektform des Pronomens (I, he, she, they).",
    "To jest podmiot czasownika, więc użyj formy podmiotowej zaimka (I, he, she, they).",
    "Este é o sujeito do verbo, por isso use a forma de sujeito do pronome (I, he, she, they).",
  ],
  review_msg_pronoun_object_case: [
    "This pronoun is the object of a preposition, so use the object form (me, him, her, us, them).",
    "Ce pronom est complément d’une préposition : utilisez la forme complément (me, him, her, us, them).",
    "Ova je zamjenica objekt prijedloga, pa upotrijebite objektni oblik (me, him, her, us, them).",
    "Este pronombre es complemento de una preposición: use la forma de complemento (me, him, her, us, them).",
    "Αυτή η αντωνυμία είναι αντικείμενο πρόθεσης· χρησιμοποιήστε τον τύπο αντικειμένου (me, him, her, us, them).",
    "Pronomenet styrs av en preposition, så använd objektsformen (me, him, her, us, them).",
    "Dieses Pronomen ist Objekt einer Präposition, daher steht die Objektform (me, him, her, us, them).",
    "Ten zaimek jest dopełnieniem przyimka, więc użyj formy dopełnienia (me, him, her, us, them).",
    "Este pronome é complemento de uma preposição, por isso use a forma de complemento (me, him, her, us, them).",
  ],
  review_msg_who_subject: [
    "Use “who” as the subject of a verb; “whom” is for objects.",
    "Utilisez « who » comme sujet d’un verbe ; « whom » sert de complément.",
    "Kao subjekt glagola upotrijebite „who”; „whom” je za objekt.",
    "Use «who» como sujeto de un verbo; «whom» es para el complemento.",
    "Χρησιμοποιήστε «who» ως υποκείμενο ρήματος· το «whom» είναι για αντικείμενο.",
    "Använd ”who” som subjekt för ett verb; ”whom” används för objekt.",
    "Verwenden Sie „who“ als Subjekt eines Verbs; „whom“ steht für Objekte.",
    "Użyj „who” jako podmiotu czasownika; „whom” służy jako dopełnienie.",
    "Use “who” como sujeito de um verbo; “whom” é para objetos.",
  ],
  review_msg_sentence_structure: [
    "Check the structure of this sentence.",
    "Vérifiez la structure de cette phrase.",
    "Provjerite strukturu ove rečenice.",
    "Revise la estructura de esta oración.",
    "Ελέγξτε τη δομή αυτής της πρότασης.",
    "Kontrollera meningens struktur.",
    "Prüfen Sie den Aufbau dieses Satzes.",
    "Sprawdź budowę tego zdania.",
    "Verifique a estrutura desta frase.",
  ],
  review_msg_confused_word: [
    "This word is easily confused with a similar one; the sentence needs the suggested word.",
    "Ce mot se confond facilement avec un mot proche ; la phrase demande le mot proposé.",
    "Ova se riječ lako zamijeni sa sličnom; rečenica traži predloženu riječ.",
    "Esta palabra se confunde fácilmente con otra parecida; la oración necesita la palabra sugerida.",
    "Αυτή η λέξη συγχέεται εύκολα με μια παρόμοια· η πρόταση χρειάζεται την προτεινόμενη λέξη.",
    "Ordet förväxlas lätt med ett liknande ord; meningen behöver det föreslagna ordet.",
    "Dieses Wort wird leicht mit einem ähnlichen verwechselt; der Satz braucht das vorgeschlagene Wort.",
    "To słowo łatwo pomylić z podobnym; zdanie wymaga proponowanego słowa.",
    "Esta palavra confunde-se facilmente com outra parecida; a frase pede a palavra sugerida.",
  ],
  review_msg_double_subject: [
    "Two subject pronouns in a row; keep the one you mean.",
    "Deux pronoms sujets se suivent : gardez celui qui convient.",
    "Dvije subjektne zamjenice zaredom: zadržite onu koju mislite.",
    "Hay dos pronombres sujeto seguidos: conserve el que corresponda.",
    "Δύο αντωνυμίες-υποκείμενα στη σειρά· κρατήστε αυτήν που εννοείτε.",
    "Två subjektspronomen i rad: behåll det du menar.",
    "Zwei Subjektpronomen hintereinander: Behalten Sie das gemeinte.",
    "Dwa zaimki podmiotowe z rzędu: zostaw ten, o który chodzi.",
    "Dois pronomes sujeito seguidos: mantenha o que pretende.",
  ],
  review_msg_pronoun_sequence: [
    "These pronouns cannot stand side by side; one is probably left over from an edit.",
    "Ces pronoms ne peuvent pas se suivre : l’un d’eux est sans doute un reste de modification.",
    "Ove zamjenice ne mogu stajati jedna do druge; jedna je vjerojatno ostala nakon izmjene.",
    "Estos pronombres no pueden ir juntos; probablemente uno quedó de una edición.",
    "Αυτές οι αντωνυμίες δεν μπορούν να στέκονται δίπλα-δίπλα· μία μάλλον έμεινε από διόρθωση.",
    "De här pronomenen kan inte stå bredvid varandra; ett av dem är troligen kvar efter en ändring.",
    "Diese Pronomen können nicht nebeneinanderstehen; eines ist wohl von einer Änderung übrig.",
    "Te zaimki nie mogą stać obok siebie; jeden to zapewne pozostałość po edycji.",
    "Estes pronomes não podem ficar lado a lado; um deles provavelmente sobrou de uma edição.",
  ],
  review_msg_determiner_clash: [
    "An article and a possessive cannot both introduce this noun; keep one.",
    "Un article et un possessif ne peuvent pas introduire ensemble ce nom : gardez-en un.",
    "Član i posvojna riječ ne mogu zajedno stajati uz ovu imenicu: zadržite jedno.",
    "Un artículo y un posesivo no pueden introducir juntos este sustantivo: conserve uno.",
    "Άρθρο και κτητικό δεν μπορούν να συνοδεύουν μαζί αυτό το ουσιαστικό· κρατήστε ένα.",
    "En artikel och ett possessivt ord kan inte båda inleda substantivet: behåll ett.",
    "Artikel und Possessivbegleiter können nicht zusammen vor diesem Nomen stehen: Behalten Sie eines.",
    "Przedimek i zaimek dzierżawczy nie mogą razem poprzedzać tego rzeczownika: zostaw jedno.",
    "Um artigo e um possessivo não podem introduzir juntos este substantivo: mantenha um.",
  ],
  review_msg_double_modal: [
    "Two modal verbs in a row are regional; standard English uses one.",
    "Deux verbes modaux à la suite relèvent d’un usage régional ; l’anglais standard n’en emploie qu’un.",
    "Dva modalna glagola zaredom regionalna su; standardni engleski koristi jedan.",
    "Dos verbos modales seguidos son regionales; el inglés estándar usa uno.",
    "Δύο τροπικά ρήματα στη σειρά είναι τοπική χρήση· τα πρότυπα αγγλικά χρησιμοποιούν ένα.",
    "Två modala hjälpverb i rad är regionalt; standardengelska använder ett.",
    "Zwei Modalverben hintereinander sind regional; Standardenglisch verwendet eines.",
    "Dwa czasowniki modalne z rzędu są regionalizmem; standardowy angielski używa jednego.",
    "Dois verbos modais seguidos são regionais; o inglês padrão usa apenas um.",
  ],
  review_msg_missing_be: [
    "A modal verb needs “be” before an adjective.",
    "Un verbe modal demande « be » devant un adjectif.",
    "Modalni glagol ispred pridjeva treba „be”.",
    "Un verbo modal necesita «be» antes de un adjetivo.",
    "Ένα τροπικό ρήμα χρειάζεται «be» πριν από επίθετο.",
    "Ett modalt hjälpverb behöver ”be” före ett adjektiv.",
    "Ein Modalverb braucht vor einem Adjektiv „be“.",
    "Czasownik modalny wymaga „be” przed przymiotnikiem.",
    "Um verbo modal precisa de “be” antes de um adjetivo.",
  ],
  review_msg_couple_of: [
    "In standard English, a quantity such as “a couple” or “a lot” takes “of” before a noun.",
    "En anglais standard, une quantité comme « a couple » ou « a lot » prend « of » devant un nom.",
    "U standardnom engleskom količina poput „a couple” ili „a lot” ispred imenice dobiva „of”.",
    "En inglés estándar, una cantidad como «a couple» o «a lot» lleva «of» antes de un sustantivo.",
    "Στα πρότυπα αγγλικά, μια ποσότητα όπως «a couple» ή «a lot» παίρνει «of» πριν από ουσιαστικό.",
    "I standardengelska tar en mängd som ”a couple” eller ”a lot” ”of” före ett substantiv.",
    "Im Standardenglischen steht nach Mengenangaben wie „a couple“ oder „a lot“ vor einem Nomen „of“.",
    "W standardowym angielskim określenie ilości, takie jak „a couple” czy „a lot”, wymaga „of” przed rzeczownikiem.",
    "Em inglês padrão, uma quantidade como “a couple” ou “a lot” leva “of” antes de um substantivo.",
  ],
  review_msg_partitive_of: [
    "Before a plural noun with no determiner, drop “of” or add “the”.",
    "Devant un nom pluriel sans déterminant, supprimez « of » ou ajoutez « the ».",
    "Ispred imenice u množini bez determinatora izostavite „of” ili dodajte „the”.",
    "Ante un sustantivo plural sin determinante, quite «of» o añada «the».",
    "Πριν από ουσιαστικό πληθυντικού χωρίς προσδιοριστή, αφαιρέστε το «of» ή προσθέστε «the».",
    "Före ett substantiv i plural utan bestämningsord: ta bort ”of” eller lägg till ”the”.",
    "Vor einem Nomen im Plural ohne Begleiter entfällt „of“, oder es braucht „the“.",
    "Przed rzeczownikiem w liczbie mnogiej bez określnika usuń „of” albo dodaj „the”.",
    "Antes de um substantivo plural sem determinante, retire “of” ou acrescente “the”.",
  ],
  review_msg_not_only_inversion: [
    "After a sentence-initial “not only”, put the auxiliary before the subject.",
    "Après « not only » en tête de phrase, placez l’auxiliaire avant le sujet.",
    "Nakon „not only” na početku rečenice pomoćni glagol stavite ispred subjekta.",
    "Tras «not only» al inicio de la oración, coloque el auxiliar antes del sujeto.",
    "Μετά το «not only» στην αρχή της πρότασης, βάλτε το βοηθητικό ρήμα πριν από το υποκείμενο.",
    "Efter ”not only” i början av en mening står hjälpverbet före subjektet.",
    "Nach „not only“ am Satzanfang steht das Hilfsverb vor dem Subjekt.",
    "Po „not only” na początku zdania postaw czasownik posiłkowy przed podmiotem.",
    "Depois de “not only” no início da frase, coloque o auxiliar antes do sujeito.",
  ],
  review_msg_repeated_words: [
    "This word may have been repeated accidentally.",
    "Ce mot a peut-être été répété par accident.",
    "Ova je riječ možda slučajno ponovljena.",
    "Puede que esta palabra se haya repetido por accidente.",
    "Αυτή η λέξη ίσως επαναλήφθηκε κατά λάθος.",
    "Det här ordet kan ha upprepats av misstag.",
    "Dieses Wort wurde möglicherweise versehentlich wiederholt.",
    "To słowo mogło zostać przypadkowo powtórzone.",
    "Esta palavra pode ter sido repetida por engano.",
  ],
  review_msg_sentence_start: [
    "Start a sentence with a capital letter.",
    "Commencez la phrase par une majuscule.",
    "Rečenicu započnite velikim slovom.",
    "Empiece la oración con mayúscula.",
    "Ξεκινήστε την πρόταση με κεφαλαίο γράμμα.",
    "Börja meningen med stor bokstav.",
    "Beginnen Sie den Satz mit einem Großbuchstaben.",
    "Zacznij zdanie wielką literą.",
    "Comece a frase com letra maiúscula.",
  ],
  review_msg_line_start: [
    "This line starts a new sentence; capitalize its first letter.",
    "Cette ligne commence une nouvelle phrase : mettez une majuscule.",
    "Ovaj redak započinje novu rečenicu: napišite prvo slovo velikim.",
    "Esta línea empieza una oración nueva: use mayúscula.",
    "Η γραμμή ξεκινά νέα πρόταση: γράψτε το πρώτο γράμμα κεφαλαίο.",
    "Raden börjar en ny mening: skriv första bokstaven stor.",
    "Diese Zeile beginnt einen neuen Satz: Großbuchstabe am Anfang.",
    "Ten wiersz zaczyna nowe zdanie: użyj wielkiej litery.",
    "Esta linha começa uma nova frase: use letra maiúscula.",
  ],
  review_msg_pronoun_i: [
    "The pronoun “I” is always capitalized.",
    "Le pronom anglais « I » s'écrit toujours en majuscule.",
    "Engleska zamjenica „I” uvijek se piše velikim slovom.",
    "El pronombre inglés «I» siempre va en mayúscula.",
    "Η αγγλική αντωνυμία «I» γράφεται πάντα κεφαλαία.",
    "Det engelska pronomenet ”I” skrivs alltid med stor bokstav.",
    "Das englische Pronomen „I“ wird immer großgeschrieben.",
    "Angielski zaimek „I” zawsze piszemy wielką literą.",
    "O pronome inglês “I” é sempre maiúsculo.",
  ],
  review_msg_contraction: [
    "This contraction is missing its apostrophe.",
    "Il manque l'apostrophe de cette contraction.",
    "Ovom skraćenom obliku nedostaje apostrof.",
    "A esta contracción le falta el apóstrofo.",
    "Στη σύντμηση λείπει η απόστροφος.",
    "Sammandragningen saknar apostrof.",
    "Bei dieser Kurzform fehlt der Apostroph.",
    "W tej formie skróconej brakuje apostrofu.",
    "Falta o apóstrofo nesta contração.",
  ],
  review_msg_apostrophe_mark: [
    "Use an apostrophe here, not an accent or another mark.",
    "Utilisez ici une apostrophe, pas un accent ni un autre signe.",
    "Ovdje upotrijebite apostrof, a ne naglasak ili drugi znak.",
    "Use aquí un apóstrofo, no un acento ni otro signo.",
    "Χρησιμοποιήστε εδώ απόστροφο, όχι τόνο ή άλλο σημάδι.",
    "Använd en apostrof här, inte en accent eller ett annat tecken.",
    "Verwenden Sie hier einen Apostroph, keinen Akzent oder ein anderes Zeichen.",
    "Użyj tu apostrofu, a nie akcentu ani innego znaku.",
    "Use aqui um apóstrofo, não um acento ou outro sinal.",
  ],
  review_msg_typo: [
    "This is a common misspelling.",
    "C'est une faute de frappe courante.",
    "Ovo je česta pogreška u pisanju.",
    "Es un error ortográfico frecuente.",
    "Συνηθισμένο ορθογραφικό λάθος.",
    "Detta är ett vanligt stavfel.",
    "Das ist ein häufiger Tippfehler.",
    "To częsta literówka.",
    "Este é um erro de digitação comum.",
  ],
  review_msg_modal_of: [
    "After could, would, should or must, use “have”, not “of”.",
    "Après could, would, should ou must, utilisez « have », pas « of ».",
    "Nakon could, would, should ili must koristite „have”, a ne „of”.",
    "Tras could, would, should o must, use «have», no «of».",
    "Μετά τα could, would, should ή must γράφεται «have», όχι «of».",
    "Efter could, would, should eller must skrivs ”have”, inte ”of”.",
    "Nach could, would, should oder must steht „have“, nicht „of“.",
    "Po could, would, should lub must piszemy „have”, nie „of”.",
    "Depois de could, would, should ou must, use “have”, não “of”.",
  ],
  review_msg_your_welcome: [
    "The reply is “you're welcome”; “your” shows possession.",
    "La réponse est « you're welcome » ; « your » indique la possession.",
    "Odgovor je „you're welcome”; „your” označava posvojnost.",
    "La respuesta es «you're welcome»; «your» indica posesión.",
    "Η απάντηση είναι «you're welcome»· το «your» δηλώνει κτήση.",
    "Svaret är ”you're welcome”; ”your” anger ägande.",
    "Die Antwort lautet „you're welcome“; „your“ ist besitzanzeigend.",
    "Odpowiedź to „you're welcome”; „your” oznacza przynależność.",
    "A resposta é “you're welcome”; “your” indica posse.",
  ],
  review_msg_their_there: [
    "Use “there” before is, are, was or were; “their” shows possession.",
    "Utilisez « there » devant is, are, was ou were ; « their » indique la possession.",
    "Ispred is, are, was ili were ide „there”; „their” označava posvojnost.",
    "Use «there» ante is, are, was o were; «their» indica posesión.",
    "Πριν από is, are, was ή were γράφεται «there»· το «their» δηλώνει κτήση.",
    "Före is, are, was eller were skrivs ”there”; ”their” anger ägande.",
    "Vor is, are, was oder were steht „there“; „their“ ist besitzanzeigend.",
    "Przed is, are, was lub were piszemy „there”; „their” oznacza przynależność.",
    "Use “there” antes de is, are, was ou were; “their” indica posse.",
  ],
  review_msg_alot: [
    "“A lot” is written as two words.",
    "« A lot » s'écrit en deux mots.",
    "„A lot” piše se odvojeno.",
    "«A lot» se escribe en dos palabras.",
    "Το «a lot» γράφεται ως δύο λέξεις.",
    "”A lot” skrivs som två ord.",
    "„A lot“ schreibt man getrennt.",
    "„A lot” piszemy osobno.",
    "“A lot” escreve-se em duas palavras.",
  ],
  review_msg_pronoun_verb: [
    "The verb doesn't agree with its subject.",
    "Le verbe ne s'accorde pas avec son sujet.",
    "Glagol se ne slaže sa subjektom.",
    "El verbo no concuerda con el sujeto.",
    "Το ρήμα δεν συμφωνεί με το υποκείμενο.",
    "Verbet stämmer inte med subjektet.",
    "Das Verb passt nicht zum Subjekt.",
    "Czasownik nie zgadza się z podmiotem.",
    "O verbo não concorda com o sujeito.",
  ],
  review_msg_article: [
    "Use “an” before a vowel sound and “a” before a consonant sound.",
    "« an » devant un son voyelle, « a » devant un son consonne.",
    "„an” ide ispred samoglasničkog, a „a” ispred suglasničkog glasa.",
    "«an» ante sonido vocálico y «a» ante sonido consonántico.",
    "«an» πριν από φωνήεν και «a» πριν από σύμφωνο (στον ήχο).",
    "”an” före vokalljud och ”a” före konsonantljud.",
    "„an“ vor Vokallaut, „a“ vor Konsonantlaut.",
    "„an” przed głoską samogłoskową, „a” przed spółgłoskową.",
    "“an” antes de som de vogal e “a” antes de som de consoante.",
  ],
  review_msg_ordinal: [
    "This ordinal number has the wrong suffix.",
    "Ce nombre ordinal a le mauvais suffixe.",
    "Ovaj redni broj ima pogrešan nastavak.",
    "Este ordinal tiene el sufijo incorrecto.",
    "Λάθος κατάληξη τακτικού αριθμητικού.",
    "Ordningstalet har fel ändelse.",
    "Diese Ordnungszahl hat die falsche Endung.",
    "Ta liczba porządkowa ma złą końcówkę.",
    "Este ordinal tem o sufixo errado.",
  ],
  review_msg_ordinal_case: [
    "Write the ordinal suffix in lowercase.",
    "Écrivez le suffixe ordinal en minuscules.",
    "Nastavak rednog broja pišite malim slovima.",
    "Escriba el sufijo ordinal en minúsculas.",
    "Γράψτε την κατάληξη του τακτικού αριθμού με πεζά.",
    "Skriv ordningstalets ändelse med gemener.",
    "Schreiben Sie die Ordnungszahl-Endung klein.",
    "Zapisz końcówkę liczebnika porządkowego małymi literami.",
    "Escreva o sufixo ordinal em minúsculas.",
  ],
  review_msg_proper_noun: [
    "Days, months, holidays and continents are capitalized.",
    "Les jours, mois, fêtes et continents anglais prennent une majuscule.",
    "Engleski dani, mjeseci, blagdani i kontinenti pišu se velikim slovom.",
    "En inglés, días, meses, fiestas y continentes van con mayúscula.",
    "Στα αγγλικά ημέρες, μήνες, γιορτές και ήπειροι γράφονται με κεφαλαίο.",
    "På engelska skrivs dagar, månader, högtider och kontinenter med stor bokstav.",
    "Englische Tage, Monate, Feiertage und Kontinente werden großgeschrieben.",
    "Po angielsku dni, miesiące, święta i kontynenty piszemy wielką literą.",
    "Em inglês, dias, meses, feriados e continentes levam maiúscula.",
  ],
  review_msg_space_before_comma: [
    "Remove the space before the comma.",
    "Supprimez l'espace avant la virgule.",
    "Uklonite razmak ispred zareza.",
    "Quite el espacio antes de la coma.",
    "Αφαιρέστε το κενό πριν από το κόμμα.",
    "Ta bort mellanslaget före kommatecknet.",
    "Entfernen Sie das Leerzeichen vor dem Komma.",
    "Usuń spację przed przecinkiem.",
    "Remova o espaço antes da vírgula.",
  ],
  review_msg_space_after_comma: [
    "Add a space after the comma.",
    "Ajoutez une espace après la virgule.",
    "Dodajte razmak iza zareza.",
    "Añada un espacio después de la coma.",
    "Προσθέστε κενό μετά το κόμμα.",
    "Lägg till ett mellanslag efter kommatecknet.",
    "Setzen Sie nach dem Komma ein Leerzeichen.",
    "Dodaj spację po przecinku.",
    "Adicione um espaço depois da vírgula.",
  ],
  review_msg_wide_comma: [
    "Use a regular comma in this text.",
    "Utilisez une virgule ordinaire dans ce texte.",
    "U ovom tekstu koristite običan zarez.",
    "Use una coma normal en este texto.",
    "Χρησιμοποιήστε κανονικό κόμμα σε αυτό το κείμενο.",
    "Använd ett vanligt kommatecken i den här texten.",
    "Verwenden Sie in diesem Text ein normales Komma.",
    "Użyj w tym tekście zwykłego przecinka.",
    "Use uma vírgula normal neste texto.",
  ],
  review_msg_space_after_opening_mark: [
    "Remove the space after this opening mark.",
    "Supprimez l'espace après ce signe d'ouverture.",
    "Uklonite razmak iza ovog početnog znaka.",
    "Quite el espacio después de este signo de apertura.",
    "Αφαιρέστε το κενό μετά από αυτό το εναρκτήριο σημείο.",
    "Ta bort mellanslaget efter det inledande tecknet.",
    "Entfernen Sie das Leerzeichen nach diesem öffnenden Zeichen.",
    "Usuń spację po tym znaku otwierającym.",
    "Remova o espaço depois deste sinal de abertura.",
  ],
  review_msg_split_words: [
    "This is written as two words.",
    "Cela s'écrit en deux mots.",
    "Ovo se piše odvojeno.",
    "Esto se escribe en dos palabras.",
    "Αυτό γράφεται ως δύο λέξεις.",
    "Detta skrivs som två ord.",
    "Das wird getrennt geschrieben.",
    "To pisze się osobno.",
    "Isto se escreve separado.",
  ],
  review_msg_german_noun_capital: [
    "In German, days and months are nouns and start with a capital letter.",
    "En allemand, les jours et les mois sont des noms et prennent une majuscule.",
    "U njemačkom su dani i mjeseci imenice i pišu se velikim početnim slovom.",
    "En alemán, los días y los meses son sustantivos y se escriben con mayúscula.",
    "Στα γερμανικά οι ημέρες και οι μήνες είναι ουσιαστικά και γράφονται με κεφαλαίο.",
    "På tyska är dagar och månader substantiv och skrivs med stor bokstav.",
    "Wochentage und Monate sind Substantive und werden großgeschrieben.",
    "W języku niemieckim dni i miesiące są rzeczownikami i pisze się je wielką literą.",
    "Em alemão, dias e meses são substantivos e começam com letra maiúscula.",
  ],
  review_msg_space_before_mark: [
    "Remove the space before this punctuation mark.",
    "Supprimez l'espace avant ce signe de ponctuation.",
    "Uklonite razmak ispred ovog interpunkcijskog znaka.",
    "Quite el espacio antes de este signo.",
    "Αφαιρέστε το κενό πριν από αυτό το σημείο στίξης.",
    "Ta bort mellanslaget före skiljetecknet.",
    "Entfernen Sie das Leerzeichen vor diesem Satzzeichen.",
    "Usuń spację przed tym znakiem interpunkcyjnym.",
    "Remova o espaço antes deste sinal de pontuação.",
  ],
  review_msg_repeated_spaces: [
    "Use a single space here.",
    "Utilisez une seule espace ici.",
    "Ovdje koristite jedan razmak.",
    "Use un solo espacio aquí.",
    "Χρησιμοποιήστε ένα μόνο κενό εδώ.",
    "Använd bara ett mellanslag här.",
    "Verwenden Sie hier nur ein Leerzeichen.",
    "Użyj tu jednej spacji.",
    "Use um único espaço aqui.",
  ],
  review_msg_duplicate_punctuation: [
    "This punctuation mark is repeated.",
    "Ce signe de ponctuation est répété.",
    "Ovaj interpunkcijski znak je ponovljen.",
    "Este signo de puntuación está repetido.",
    "Το σημείο στίξης επαναλαμβάνεται.",
    "Skiljetecknet är upprepat.",
    "Dieses Satzzeichen ist doppelt.",
    "Ten znak interpunkcyjny się powtarza.",
    "Este sinal de pontuação está repetido.",
  ],
  review_msg_ellipsis_length: [
    "An ellipsis has three dots.",
    "Des points de suspension comptent trois points.",
    "Trotočje ima tri točke.",
    "Los puntos suspensivos son tres puntos.",
    "Τα αποσιωπητικά έχουν τρεις τελείες.",
    "En ellips har tre punkter.",
    "Auslassungspunkte bestehen aus drei Punkten.",
    "Wielokropek ma trzy kropki.",
    "As reticências têm três pontos.",
  ],
  review_msg_ellipsis_character: [
    "Optional typography: use the single ellipsis character (…).",
    "Typographie facultative : utilisez le caractère unique des points de suspension (…).",
    "Neobavezna tipografija: upotrijebite jedan znak za trotočje (…).",
    "Tipografía opcional: use el carácter único de puntos suspensivos (…).",
    "Προαιρετική τυπογραφία: χρησιμοποιήστε τον ενιαίο χαρακτήρα αποσιωπητικών (…).",
    "Valfri typografi: använd det enskilda ellipstecknet (…).",
    "Optionale Typografie: Verwenden Sie das einzelne Auslassungszeichen (…).",
    "Opcjonalna typografia: użyj pojedynczego znaku wielokropka (…).",
    "Tipografia opcional: use o caractere único de reticências (…).",
  ],
  review_msg_typed_dash: [
    "Optional typography: use a dash instead of hyphens.",
    "Typographie facultative : utilisez un tiret plutôt que des traits d’union.",
    "Neobavezna tipografija: upotrijebite crticu umjesto spojnica.",
    "Tipografía opcional: use una raya o un guion largo en lugar de guiones.",
    "Προαιρετική τυπογραφία: χρησιμοποιήστε παύλα αντί για ενωτικά.",
    "Valfri typografi: använd ett tankstreck i stället för bindestreck.",
    "Optionale Typografie: Verwenden Sie einen Gedankenstrich statt Bindestrichen.",
    "Opcjonalna typografia: użyj myślnika zamiast łączników.",
    "Tipografia opcional: use um travessão em vez de hífens.",
  ],
  review_msg_measurement_spacing: [
    "Separate the number from its unit.",
    "Séparez le nombre de son unité.",
    "Odvojite broj od mjerne jedinice.",
    "Separe el número de su unidad.",
    "Χωρίστε τον αριθμό από τη μονάδα.",
    "Skilj talet från enheten.",
    "Trennen Sie Zahl und Einheit.",
    "Oddziel liczbę od jednostki.",
    "Separe o número da unidade.",
  ],
  review_msg_kelvin_degree: [
    "Kelvin takes no degree sign: write K.",
    "Le kelvin s’écrit sans signe de degré : K.",
    "Kelvin se piše bez znaka stupnja: K.",
    "El kelvin se escribe sin signo de grado: K.",
    "Το κέλβιν γράφεται χωρίς σύμβολο βαθμού: K.",
    "Kelvin skrivs utan gradtecken: K.",
    "Kelvin wird ohne Gradzeichen geschrieben: K.",
    "Kelwin zapisuje się bez znaku stopnia: K.",
    "O kelvin se escreve sem o sinal de grau: K.",
  ],
  review_msg_currency_spacing: [
    "Separate the amount from its currency.",
    "Séparez le montant de la devise.",
    "Odvojite iznos od valute.",
    "Separe el importe de la moneda.",
    "Χωρίστε το ποσό από το νόμισμα.",
    "Skilj beloppet från valutan.",
    "Trennen Sie Betrag und Währung.",
    "Oddziel kwotę od waluty.",
    "Separe o valor da moeda.",
  ],
  review_msg_currency_placement: [
    "In English, this currency symbol goes before the amount (the cent sign after it).",
    "En anglais, ce symbole monétaire se place avant le montant (le signe cent après).",
    "U engleskom se ovaj simbol valute piše ispred iznosa (znak centa iza).",
    "En inglés, este símbolo de moneda va antes del importe (el de centavo, después).",
    "Στα αγγλικά, αυτό το σύμβολο νομίσματος μπαίνει πριν από το ποσό (το σεντ μετά).",
    "På engelska står den här valutasymbolen före beloppet (centtecknet efter).",
    "Im Englischen steht dieses Währungszeichen vor dem Betrag (das Centzeichen danach).",
    "W angielskim ten symbol waluty stoi przed kwotą (znak centa po niej).",
    "Em inglês, este símbolo de moeda vem antes do valor (o do centavo, depois).",
  ],
  review_msg_irregular_form: [
    "This word has an irregular form: “children”, “ate”.",
    "Ce mot a une forme irrégulière : « children », « ate ».",
    "Ova riječ ima nepravilan oblik: „children”, „ate”.",
    "Esta palabra tiene una forma irregular: «children», «ate».",
    "Αυτή η λέξη έχει ανώμαλο τύπο: «children», «ate».",
    "Ordet har en oregelbunden form: ”children”, ”ate”.",
    "Dieses Wort hat eine unregelmäßige Form: „children“, „ate“.",
    "To słowo ma nieregularną formę: „children”, „ate”.",
    "Esta palavra tem uma forma irregular: “children”, “ate”.",
  ],
  review_msg_noun_possessive: [
    "A noun that owns the next one takes an apostrophe: “the cat’s tail”, “the students’ books”.",
    "Un nom qui possède le suivant prend une apostrophe : « the cat’s tail », « the students’ books ».",
    "Imenica koja posjeduje sljedeću dobiva apostrof: „the cat’s tail”, „the students’ books”.",
    "Un sustantivo que posee al siguiente lleva apóstrofo: «the cat’s tail», «the students’ books».",
    "Ένα ουσιαστικό που κατέχει το επόμενο παίρνει απόστροφο: «the cat’s tail», «the students’ books».",
    "Ett substantiv som äger nästa får apostrof: ”the cat’s tail”, ”the students’ books”.",
    "Ein Nomen, dem das nächste gehört, bekommt einen Apostroph: „the cat’s tail“, „the students’ books“.",
    "Rzeczownik, do którego należy następny, wymaga apostrofu: „the cat’s tail”, „the students’ books”.",
    "Um substantivo que possui o seguinte leva apóstrofo: “the cat’s tail”, “the students’ books”.",
  ],
  review_msg_word_boundary: [
    "The space in these words looks misplaced or extra.",
    "L’espace dans ces mots semble mal placée ou en trop.",
    "Razmak u ovim riječima čini se pogrešno postavljenim ili suvišnim.",
    "El espacio en estas palabras parece mal colocado o sobrante.",
    "Το κενό σε αυτές τις λέξεις φαίνεται λάθος τοποθετημένο ή περιττό.",
    "Mellanslaget i de här orden verkar felplacerat eller överflödigt.",
    "Das Leerzeichen in diesen Wörtern scheint falsch gesetzt oder überflüssig.",
    "Spacja w tych słowach wydaje się źle postawiona lub zbędna.",
    "O espaço nestas palavras parece mal colocado ou a mais.",
  ],
  review_msg_space_after_mark: [
    "Add a space after this punctuation mark.",
    "Ajoutez une espace après ce signe de ponctuation.",
    "Dodajte razmak iza ovog interpunkcijskog znaka.",
    "Añada un espacio después de este signo de puntuación.",
    "Προσθέστε κενό μετά από αυτό το σημείο στίξης.",
    "Lägg till ett mellanslag efter det här skiljetecknet.",
    "Setzen Sie nach diesem Satzzeichen ein Leerzeichen.",
    "Dodaj spację po tym znaku interpunkcyjnym.",
    "Adicione um espaço depois deste sinal de pontuação.",
  ],
  review_msg_avoid_contractions: [
    "Optional formal style: write this contraction out in full.",
    "Style soutenu facultatif : écrivez cette contraction en entier.",
    "Neobavezni formalni stil: napišite ovo skraćivanje u punom obliku.",
    "Estilo formal opcional: escriba esta contracción completa.",
    "Προαιρετικό επίσημο ύφος: γράψτε αυτή τη συναίρεση ολόκληρη.",
    "Valfri formell stil: skriv ut sammandragningen i sin helhet.",
    "Optionaler formeller Stil: Schreiben Sie diese Kurzform aus.",
    "Opcjonalny styl formalny: zapisz tę formę ściągniętą w pełnej postaci.",
    "Estilo formal opcional: escreva esta contração por extenso.",
  ],
  review_msg_oxford_comma: [
    "Optional list style: add a serial (Oxford) comma before the last item.",
    "Style de liste facultatif : ajoutez une virgule de série (d’Oxford) avant le dernier élément.",
    "Neobavezni stil popisa: dodajte serijski (oksfordski) zarez prije posljednje stavke.",
    "Estilo de lista opcional: añada una coma serial (de Oxford) antes del último elemento.",
    "Προαιρετικό ύφος λίστας: προσθέστε κόμμα σειράς (της Οξφόρδης) πριν από το τελευταίο στοιχείο.",
    "Valfri liststil: lägg till ett seriekommatecken (Oxfordkomma) före det sista ledet.",
    "Optionaler Listenstil: Setzen Sie vor dem letzten Element ein serielles (Oxford-)Komma.",
    "Opcjonalny styl wyliczeń: dodaj przecinek seryjny (oksfordzki) przed ostatnim elementem.",
    "Estilo de lista opcional: adicione uma vírgula serial (de Oxford) antes do último item.",
  ],
  review_msg_no_oxford_comma: [
    "Optional list style: leave out the serial (Oxford) comma before the last item.",
    "Style de liste facultatif : omettez la virgule de série (d’Oxford) avant le dernier élément.",
    "Neobavezni stil popisa: izostavite serijski (oksfordski) zarez prije posljednje stavke.",
    "Estilo de lista opcional: omita la coma serial (de Oxford) antes del último elemento.",
    "Προαιρετικό ύφος λίστας: παραλείψτε το κόμμα σειράς (της Οξφόρδης) πριν από το τελευταίο στοιχείο.",
    "Valfri liststil: utelämna seriekommatecknet (Oxfordkomma) före det sista ledet.",
    "Optionaler Listenstil: Lassen Sie das serielle (Oxford-)Komma vor dem letzten Element weg.",
    "Opcjonalny styl wyliczeń: pomiń przecinek seryjny (oksfordzki) przed ostatnim elementem.",
    "Estilo de lista opcional: omita a vírgula serial (de Oxford) antes do último item.",
  ],
  review_msg_alternative_phrasing: [
    "Optional style: this phrase has another accepted form; use it if you prefer it.",
    "Style facultatif : cette expression a une autre forme admise ; utilisez-la si vous la préférez.",
    "Neobavezni stil: ovaj izraz ima i drugi prihvaćeni oblik; upotrijebite ga ako vam je draži.",
    "Estilo opcional: esta expresión tiene otra forma aceptada; úsela si la prefiere.",
    "Προαιρετικό ύφος: αυτή η φράση έχει και άλλη αποδεκτή μορφή· χρησιμοποιήστε την αν την προτιμάτε.",
    "Valfri stil: uttrycket har en annan godtagen form; använd den om du föredrar den.",
    "Optionaler Stil: Diese Wendung hat eine weitere anerkannte Form; verwenden Sie sie, wenn Sie sie bevorzugen.",
    "Opcjonalny styl: to wyrażenie ma też inną przyjętą formę; użyj jej, jeśli ją wolisz.",
    "Estilo opcional: esta expressão tem outra forma aceite; use-a se a preferir.",
  ],
  review_msg_possible_error: [
    "Possible mistake: this wording is usually an error, but it can be correct. Check it.",
    "Erreur possible : cette formulation est souvent fautive, mais elle peut être correcte. Vérifiez-la.",
    "Moguća pogreška: ova je formulacija obično pogrešna, ali može biti i ispravna. Provjerite je.",
    "Posible error: esta redacción suele ser un error, pero puede ser correcta. Revísela.",
    "Πιθανό λάθος: αυτή η διατύπωση είναι συνήθως λάθος, αλλά μπορεί να είναι σωστή. Ελέγξτε την.",
    "Möjligt fel: formuleringen är oftast fel men kan vara korrekt. Kontrollera den.",
    "Möglicher Fehler: Diese Formulierung ist meist falsch, kann aber richtig sein. Prüfen Sie sie.",
    "Możliwy błąd: to sformułowanie zwykle jest błędne, ale może być poprawne. Sprawdź je.",
    "Possível erro: esta formulação costuma ser um erro, mas pode estar correta. Verifique-a.",
  ],
  review_msg_quoted_mention: [
    "Possible mistake in quoted text: the quoted wording has a usual corrected form. Keep it if you quote it on purpose.",
    "Erreur possible dans un texte cité : la formulation citée a une forme corrigée usuelle. Gardez-la si vous la citez exprès.",
    "Moguća pogreška u citiranom tekstu: citirana formulacija ima uobičajeni ispravljeni oblik. Zadržite je ako je citirate namjerno.",
    "Posible error en un texto citado: la redacción citada tiene una forma corregida habitual. Consérvela si la cita a propósito.",
    "Πιθανό λάθος σε κείμενο σε εισαγωγικά: η παρατιθέμενη διατύπωση έχει συνήθη διορθωμένη μορφή. Κρατήστε την αν την παραθέτετε σκόπιμα.",
    "Möjligt fel i citerad text: den citerade formuleringen har en vanlig rättad form. Behåll den om du citerar den med avsikt.",
    "Möglicher Fehler im zitierten Text: Die zitierte Formulierung hat eine übliche korrigierte Form. Behalten Sie sie, wenn Sie sie absichtlich zitieren.",
    "Możliwy błąd w cytowanym tekście: cytowane sformułowanie ma zwykłą poprawioną formę. Zachowaj je, jeśli cytujesz je celowo.",
    "Possível erro em texto citado: a formulação citada tem uma forma corrigida habitual. Mantenha-a se a citar de propósito.",
  ],
  review_msg_american_spelling: [
    "Optional dialect: use the American English spelling, word or idiom.",
    "Variante facultative : utilisez l’orthographe, le mot ou l’expression de l’anglais américain.",
    "Neobavezna varijanta: upotrijebite američki engleski pravopis, riječ ili izraz.",
    "Variante opcional: use la ortografía, la palabra o la expresión del inglés estadounidense.",
    "Προαιρετική διάλεκτος: χρησιμοποιήστε την αμερικανική αγγλική ορθογραφία, λέξη ή έκφραση.",
    "Valfri variant: använd amerikansk-engelsk stavning, ord eller uttryck.",
    "Optionale Variante: Verwenden Sie die amerikanisch-englische Schreibung, das Wort oder die Wendung.",
    "Opcjonalna odmiana: użyj pisowni, słowa lub zwrotu z amerykańskiej angielszczyzny.",
    "Variante opcional: use a grafia, a palavra ou a expressão do inglês americano.",
  ],
  review_msg_british_spelling: [
    "Optional dialect: use the British English spelling, word or idiom.",
    "Variante facultative : utilisez l’orthographe, le mot ou l’expression de l’anglais britannique.",
    "Neobavezna varijanta: upotrijebite britanski engleski pravopis, riječ ili izraz.",
    "Variante opcional: use la ortografía, la palabra o la expresión del inglés británico.",
    "Προαιρετική διάλεκτος: χρησιμοποιήστε τη βρετανική αγγλική ορθογραφία, λέξη ή έκφραση.",
    "Valfri variant: använd brittisk-engelsk stavning, ord eller uttryck.",
    "Optionale Variante: Verwenden Sie die britisch-englische Schreibung, das Wort oder die Wendung.",
    "Opcjonalna odmiana: użyj pisowni, słowa lub zwrotu z brytyjskiej angielszczyzny.",
    "Variante opcional: use a grafia, a palavra ou a expressão do inglês britânico.",
  ],
  review_msg_word_choice: [
    "Optional word choice: write the full or more precise word.",
    "Choix de mot facultatif : écrivez le mot complet ou plus précis.",
    "Neobavezan izbor riječi: napišite punu ili precizniju riječ.",
    "Elección de palabras opcional: escriba la palabra completa o más precisa.",
    "Προαιρετική επιλογή λέξης: γράψτε την πλήρη ή πιο ακριβή λέξη.",
    "Valfritt ordval: skriv det fullständiga eller mer exakta ordet.",
    "Optionale Wortwahl: Schreiben Sie das vollständige oder genauere Wort.",
    "Opcjonalny dobór słów: napisz pełne lub bardziej precyzyjne słowo.",
    "Escolha de palavras opcional: escreva a palavra completa ou mais precisa.",
  ],
  review_msg_spelled_numbers: [
    "Optional number style: spell out a small number in running text.",
    "Style numérique facultatif : écrivez en toutes lettres un petit nombre dans le texte courant.",
    "Neobavezan stil brojeva: mali broj u tekstu napišite slovima.",
    "Estilo numérico opcional: escriba con letras un número pequeño en el texto corrido.",
    "Προαιρετικό ύφος αριθμών: γράψτε ολογράφως έναν μικρό αριθμό μέσα στο κείμενο.",
    "Valfri sifferstil: skriv ut ett litet tal med bokstäver i löpande text.",
    "Optionaler Zahlenstil: Schreiben Sie eine kleine Zahl im Fließtext aus.",
    "Opcjonalny styl liczb: małą liczbę w tekście zapisz słownie.",
    "Estilo numérico opcional: escreva por extenso um número pequeno no texto corrido.",
  ],
  // German-only Review checks (review/german/).
  review_msg_german_noun_case: [
    "In German, every noun starts with a capital letter.",
    "En allemand, tous les noms prennent une majuscule.",
    "U njemačkom se sve imenice pišu velikim početnim slovom.",
    "En alemán, todos los sustantivos se escriben con mayúscula inicial.",
    "Στα γερμανικά όλα τα ουσιαστικά γράφονται με κεφαλαίο αρχικό.",
    "På tyska skrivs alla substantiv med stor bokstav.",
    "Substantive werden großgeschrieben.",
    "W języku niemieckim wszystkie rzeczowniki pisze się wielką literą.",
    "Em alemão, todos os substantivos começam com letra maiúscula.",
  ],
  review_msg_german_preposition_case: [
    "This German preposition takes another case: change the article (and its noun) to match.",
    "Cette préposition allemande régit un autre cas : accordez l'article (et son nom).",
    "Ovaj njemački prijedlog traži drugi padež: prilagodite član (i imenicu).",
    "Esta preposición alemana rige otro caso: adapte el artículo (y su sustantivo).",
    "Αυτή η γερμανική πρόθεση συντάσσεται με άλλη πτώση: προσαρμόστε το άρθρο (και το ουσιαστικό).",
    "Den här tyska prepositionen styr ett annat kasus: anpassa artikeln (och substantivet).",
    "Diese Präposition verlangt einen anderen Fall: Passen Sie den Artikel (und das Nomen) an.",
    "Ten niemiecki przyimek wymaga innego przypadku: dopasuj rodzajnik (i rzeczownik).",
    "Esta preposição alemã rege outro caso: ajuste o artigo (e o substantivo).",
  ],
};

/**
 * A finding's explanation in the UI language `lang` (English when it has
 * none); "" for the findings the page explains itself (see isPageMessageKey).
 */
export function reviewExplanation(key: ReviewMessageKey, lang: string): string {
  return Object.hasOwn(EXPLANATIONS, key)
    ? localizeReviewText(EXPLANATIONS[key as keyof typeof EXPLANATIONS], lang)
    : "";
}

/**
 * The explanations the page lacks for `keys`, in `lang`, once per key. Keys
 * the page explains itself, and unknown ones, are left out.
 */
export function reviewExplanations(
  keys: Iterable<string>,
  lang: string,
): Partial<Record<ReviewMessageKey, string>> {
  const texts: Partial<Record<ReviewMessageKey, string>> = {};
  for (const key of keys) {
    if (Object.hasOwn(EXPLANATIONS, key)) {
      texts[key as ReviewMessageKey] ??= reviewExplanation(key as ReviewMessageKey, lang);
    }
  }
  return texts;
}
