import type { GrammarRuleCatalogEntry, GrammarRuleId } from "./types";

export const GRAMMAR_RULE_CATALOG: readonly GrammarRuleCatalogEntry[] = [
  {
    id: "englishSubjectVerbAgreement",
    typing: false,
    name: "Subject and verb agreement",
    titleI18nKey: "review_msg_pronoun_verb",
    descriptionI18nKey: "review_msg_pronoun_verb",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 163,
  },
  {
    id: "englishPhraseCorrections",
    typing: false,
    name: "Fixed phrase corrections",
    titleI18nKey: "review_msg_phrase_correction",
    descriptionI18nKey: "review_msg_phrase_correction",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    // Lowest priorities: a more specific rule proposing the same edit explains it.
    priority: 3,
  },
  {
    id: "englishClosedCompounds",
    typing: false,
    name: "Split and joined compounds",
    titleI18nKey: "review_msg_closed_compound",
    descriptionI18nKey: "review_msg_closed_compound",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 2,
  },
  {
    id: "styleRedundancy",
    typing: false,
    name: "Optional redundancy advice",
    titleI18nKey: "review_msg_style_redundancy",
    descriptionI18nKey: "review_msg_style_redundancy",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 162,
  },
  {
    id: "styleLongSentence",
    typing: false,
    name: "Optional long-sentence advice",
    titleI18nKey: "review_msg_style_long_sentence",
    descriptionI18nKey: "review_msg_style_long_sentence",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 161,
  },
  {
    id: "stylePhrasing",
    typing: false,
    name: "Optional wording advice",
    titleI18nKey: "review_msg_style_phrasing",
    descriptionI18nKey: "review_msg_style_phrasing",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  // Opt-in register and list-punctuation styles; the two serial-comma styles oppose each other.
  {
    id: "styleContractions",
    typing: false,
    name: "Optional formal register: no contractions",
    titleI18nKey: "review_msg_avoid_contractions",
    descriptionI18nKey: "review_msg_avoid_contractions",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  {
    id: "styleOxfordComma",
    typing: false,
    name: "Optional serial (Oxford) comma",
    titleI18nKey: "review_msg_oxford_comma",
    descriptionI18nKey: "review_msg_oxford_comma",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  {
    id: "styleNoOxfordComma",
    typing: false,
    name: "Optional list style without the serial comma",
    titleI18nKey: "review_msg_no_oxford_comma",
    descriptionI18nKey: "review_msg_no_oxford_comma",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  // Opt-in: the other accepted form of a phrase whose usual form stylePhrasing may suggest.
  {
    id: "styleAlternativePhrasing",
    typing: false,
    name: "Optional alternative form of a phrase",
    titleI18nKey: "review_msg_alternative_phrasing",
    descriptionI18nKey: "review_msg_alternative_phrasing",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  // Opt-in: wording that is usually a mistake but can be correct, and quoted mentions.
  {
    id: "englishPossibleErrors",
    typing: false,
    name: "Optional check for possible mistakes",
    titleI18nKey: "review_msg_possible_error",
    descriptionI18nKey: "review_msg_possible_error",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  // Opt-in dialects: each converts the other's spellings, words and idioms.
  {
    id: "englishAmericanSpelling",
    typing: false,
    name: "Optional American English spelling",
    titleI18nKey: "review_msg_american_spelling",
    descriptionI18nKey: "review_msg_american_spelling",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  {
    id: "englishBritishSpelling",
    typing: false,
    name: "Optional British English spelling",
    titleI18nKey: "review_msg_british_spelling",
    descriptionI18nKey: "review_msg_british_spelling",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  // Opt-in house style: full words and spelled-out small numbers.
  {
    id: "styleWordChoice",
    typing: false,
    name: "Optional full or more precise words",
    titleI18nKey: "review_msg_word_choice",
    descriptionI18nKey: "review_msg_word_choice",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  {
    id: "styleSpelledNumbers",
    typing: false,
    name: "Optional spelled-out small numbers",
    titleI18nKey: "review_msg_spelled_numbers",
    descriptionI18nKey: "review_msg_spelled_numbers",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 1,
  },
  {
    id: "preferredTerminology",
    typing: false,
    name: "Your preferred terminology",
    titleI18nKey: "review_msg_preferred_terminology",
    descriptionI18nKey: "review_msg_preferred_terminology",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 160,
  },
  {
    id: "englishCanonicalCasing",
    typing: false,
    name: "Canonical brand and acronym casing",
    titleI18nKey: "review_msg_canonical_casing",
    descriptionI18nKey: "review_msg_canonical_casing",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 159,
  },
  {
    id: "quoteSpacing",
    typing: false,
    name: "Space outside quotation marks",
    titleI18nKey: "review_msg_quote_spacing",
    descriptionI18nKey: "review_msg_quote_spacing",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 171,
  },
  {
    id: "primeSymbols",
    typing: false,
    name: "Prime marks for feet, inches, minutes and seconds",
    titleI18nKey: "review_msg_prime_symbols",
    descriptionI18nKey: "review_msg_prime_symbols",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 172,
  },
  {
    id: "greekFinalNu",
    typing: false,
    name: "Greek final ν and κι before the next sound",
    titleI18nKey: "review_msg_greek_final_nu",
    descriptionI18nKey: "review_msg_greek_final_nu",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 173,
  },
  {
    id: "greekStrictFinalNu",
    typing: false,
    name: "Greek strict final ν",
    titleI18nKey: "review_msg_greek_strict_final_nu",
    descriptionI18nKey: "review_msg_greek_strict_final_nu",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 174,
  },
  {
    id: "greekQuestionAccent",
    typing: false,
    name: "Greek interrogative πού and πώς",
    titleI18nKey: "review_msg_greek_question_accent",
    descriptionI18nKey: "review_msg_greek_question_accent",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 175,
  },
  {
    id: "greekPunctuation",
    typing: false,
    name: "Greek punctuation conventions",
    titleI18nKey: "review_msg_greek_intro_comma",
    descriptionI18nKey: "review_msg_greek_intro_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 176,
  },
  {
    id: "swedishTypography",
    typing: false,
    name: "Swedish ordinals, acronym genitives, days and months",
    titleI18nKey: "review_msg_swedish_typography",
    descriptionI18nKey: "review_msg_swedish_typography",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  {
    id: "polishCaseAgreement",
    typing: false,
    name: "Polish noun cases after prepositions, demonstratives and numerals",
    titleI18nKey: "review_msg_pl_agreement",
    descriptionI18nKey: "review_msg_pl_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 178,
  },
  {
    id: "polishTypography",
    typing: false,
    name: "Polish typesetting: dashes, symbols, spacing",
    titleI18nKey: "review_msg_pl_typography",
    descriptionI18nKey: "review_msg_pl_typography",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 179,
  },
  {
    id: "polishQuotes",
    typing: false,
    name: "Polish quotation marks („…”)",
    titleI18nKey: "review_msg_pl_quotes",
    descriptionI18nKey: "review_msg_pl_quotes",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 180,
  },
  {
    id: "polishCapitalization",
    typing: false,
    name: "Polish capitals: weekdays, months, holidays, seas",
    titleI18nKey: "review_msg_pl_capitals",
    descriptionI18nKey: "review_msg_pl_capitals",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 181,
  },
  {
    id: "swedishAgreement",
    typing: false,
    name: "Swedish en/ett agreement",
    titleI18nKey: "review_msg_swedish_agreement",
    descriptionI18nKey: "review_msg_swedish_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 178,
  },
  {
    id: "frenchAdjectiveAgreement",
    typing: false,
    name: "French adjective and participle agreement",
    titleI18nKey: "review_msg_fr_adjective_agreement",
    descriptionI18nKey: "review_msg_fr_adjective_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  {
    id: "frenchTout",
    typing: false,
    name: "French tout / tous / toute(s)",
    titleI18nKey: "review_msg_fr_tout",
    descriptionI18nKey: "review_msg_fr_tout",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  {
    id: "frenchMood",
    typing: false,
    name: "French subjunctive and conditional",
    titleI18nKey: "review_msg_fr_subjunctive",
    descriptionI18nKey: "review_msg_fr_subjunctive",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  {
    id: "frenchMissingNe",
    typing: false,
    name: "French negation without ne",
    titleI18nKey: "review_msg_fr_missing_ne",
    descriptionI18nKey: "review_msg_fr_missing_ne",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 150,
  },
  {
    id: "frenchCommas",
    typing: false,
    name: "French commas",
    titleI18nKey: "review_msg_fr_stray_comma",
    descriptionI18nKey: "review_msg_fr_stray_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 150,
  },
  {
    id: "frenchOrdinals",
    typing: false,
    name: "French ordinal abbreviations",
    titleI18nKey: "review_msg_fr_ordinal",
    descriptionI18nKey: "review_msg_fr_ordinal",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 150,
  },
  {
    id: "arabicAgreement",
    typing: false,
    name: "Arabic demonstrative and number agreement",
    titleI18nKey: "review_msg_arabic_agreement",
    descriptionI18nKey: "review_msg_arabic_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 179,
  },
  {
    id: "frenchNounGender",
    typing: false,
    name: "French determiner and noun gender",
    titleI18nKey: "review_msg_fr_noun_gender",
    descriptionI18nKey: "review_msg_fr_noun_gender",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 178,
  },
  {
    id: "arabicCaseEndings",
    typing: false,
    name: "Arabic case and mood endings",
    titleI18nKey: "review_msg_arabic_case_endings",
    descriptionI18nKey: "review_msg_arabic_case_endings",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 180,
  },
  {
    id: "arabicDates",
    typing: false,
    name: "Arabic date checks",
    titleI18nKey: "review_msg_arabic_dates",
    descriptionI18nKey: "review_msg_arabic_dates",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 181,
  },
  {
    id: "unclosedQuotation",
    typing: false,
    name: "Unclosed quotation marks",
    titleI18nKey: "review_msg_quotation_balance",
    descriptionI18nKey: "review_msg_quotation_balance",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 158,
  },
  {
    id: "englishUsagePhrases",
    typing: false,
    name: "Established usage phrases",
    titleI18nKey: "review_msg_usage_phrases",
    descriptionI18nKey: "review_msg_usage_phrases",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 157,
  },
  {
    id: "englishDoubledDegree",
    typing: false,
    name: "Doubled comparatives and superlatives",
    titleI18nKey: "review_msg_doubled_degree",
    descriptionI18nKey: "review_msg_doubled_degree",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 156,
  },
  {
    id: "englishCountability",
    typing: false,
    name: "Countability in ordinary prose",
    titleI18nKey: "review_msg_countability",
    descriptionI18nKey: "review_msg_countability",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 155,
  },
  {
    id: "englishContextualCompounds",
    typing: false,
    name: "Contextual compound words",
    titleI18nKey: "review_msg_compounds",
    descriptionI18nKey: "review_msg_compounds",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 154,
  },
  {
    id: "englishNounNumber",
    typing: false,
    name: "Demonstratives and noun number",
    titleI18nKey: "review_msg_demonstrative_number",
    descriptionI18nKey: "review_msg_demonstrative_number",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 153,
  },
  {
    id: "englishPerfectParticiples",
    typing: false,
    name: "Verb forms after have and be",
    titleI18nKey: "review_msg_perfect_participle",
    descriptionI18nKey: "review_msg_perfect_participle",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 152,
  },
  {
    id: "englishVerbComplements",
    typing: false,
    name: "Verb complement constructions",
    titleI18nKey: "review_msg_verb_complements",
    descriptionI18nKey: "review_msg_verb_complements",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 151,
  },
  {
    id: "englishFixedPrepositions",
    typing: false,
    name: "Fixed preposition constructions",
    titleI18nKey: "review_msg_fixed_prepositions",
    descriptionI18nKey: "review_msg_fixed_prepositions",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 150,
  },
  {
    id: "englishItsContext",
    typing: false,
    name: "Its and it is in context",
    titleI18nKey: "review_msg_its_contraction",
    descriptionI18nKey: "review_msg_its_contraction",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 147,
  },
  {
    id: "englishLetsContext",
    typing: false,
    name: "Lets and let us in context",
    titleI18nKey: "review_msg_lets_contraction",
    descriptionI18nKey: "review_msg_lets_contraction",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 148,
  },
  {
    id: "englishElsePossessive",
    typing: false,
    name: "Indefinite-pronoun possessives",
    titleI18nKey: "review_msg_else_possessive",
    descriptionI18nKey: "review_msg_else_possessive",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 149,
  },
  {
    id: "englishExistentialAgreement",
    typing: false,
    name: "Existential noun agreement",
    titleI18nKey: "review_msg_existential_agreement",
    descriptionI18nKey: "review_msg_existential_agreement",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 146,
  },
  {
    id: "englishThenThan",
    typing: false,
    name: "Comparison then/than",
    titleI18nKey: "review_msg_then_than",
    descriptionI18nKey: "review_msg_then_than",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 142,
  },
  {
    id: "englishYourYouAre",
    typing: false,
    name: "Your and you are in context",
    titleI18nKey: "review_msg_your_you_are",
    descriptionI18nKey: "review_msg_your_you_are",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 143,
  },
  {
    id: "englishTheirThereTheyAre",
    typing: false,
    name: "Their, there and they are in context",
    titleI18nKey: "review_msg_their_possessive",
    descriptionI18nKey: "review_msg_their_possessive",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 144,
  },
  {
    id: "englishToToo",
    typing: false,
    name: "Intensifier to/too",
    titleI18nKey: "review_msg_to_too",
    descriptionI18nKey: "review_msg_to_too",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 145,
  },
  {
    id: "englishWereWhere",
    typing: false,
    name: "Were and where in context",
    titleI18nKey: "review_msg_were_where",
    descriptionI18nKey: "review_msg_were_where",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 164,
  },
  {
    id: "englishIrregularForms",
    typing: false,
    name: "Irregular plurals and past forms",
    titleI18nKey: "review_msg_irregular_form",
    descriptionI18nKey: "review_msg_irregular_form",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    // Below englishUsagePhrases, whose framed "finded" fix explains the same edit better.
    priority: 137,
  },
  {
    id: "englishPossessiveNouns",
    typing: false,
    name: "Possessive apostrophes on nouns",
    titleI18nKey: "review_msg_noun_possessive",
    descriptionI18nKey: "review_msg_noun_possessive",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 138,
  },
  {
    id: "englishDateConsistency",
    typing: false,
    name: "Weekdays and impossible dates",
    titleI18nKey: "review_msg_weekday_mismatch",
    descriptionI18nKey: "review_msg_weekday_mismatch",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 139,
  },
  {
    id: "englishTenseConsistency",
    typing: false,
    name: "Tense against time words and dates",
    titleI18nKey: "review_msg_tense_time_word",
    descriptionI18nKey: "review_msg_tense_time_word",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 139,
  },
  {
    id: "englishSentenceFragment",
    typing: false,
    name: "Sentence fragments",
    titleI18nKey: "review_msg_sentence_fragment",
    descriptionI18nKey: "review_msg_sentence_fragment",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 40,
  },
  // English tables and typography (review/english/, en-tables2).
  {
    id: "englishApostrophes",
    typing: false,
    name: "Apostrophes in plurals, verbs and possessives",
    titleI18nKey: "review_msg_plural_apostrophe",
    descriptionI18nKey: "review_msg_plural_apostrophe",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 140,
  },
  {
    id: "englishNotation",
    typing: false,
    name: "English numbers, initialisms and degrees",
    titleI18nKey: "review_msg_english_digit_groups",
    descriptionI18nKey: "review_msg_english_digit_groups",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 141,
  },
  {
    id: "englishTypography",
    typing: false,
    name: "Typographic symbols, quotes and dashes",
    titleI18nKey: "review_msg_typographic_symbol",
    descriptionI18nKey: "review_msg_typographic_symbol",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 142,
  },
  {
    id: "stylePassiveVoice",
    typing: false,
    name: "Passive voice",
    titleI18nKey: "review_msg_passive_voice",
    descriptionI18nKey: "review_msg_passive_voice",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 143,
  },
  {
    id: "englishPunctuation",
    typing: false,
    name: "Stray commas",
    titleI18nKey: "review_msg_stray_comma",
    descriptionI18nKey: "review_msg_stray_comma",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 144,
  },
  {
    id: "styleIntroductoryComma",
    typing: false,
    name: "Comma after an opening phrase",
    titleI18nKey: "review_msg_introductory_comma",
    descriptionI18nKey: "review_msg_introductory_comma",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 145,
  },
  {
    id: "styleClauseComma",
    typing: false,
    name: "Comma between joined clauses",
    titleI18nKey: "review_msg_clause_comma",
    descriptionI18nKey: "review_msg_clause_comma",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 145,
  },
  // Polish-only Review checks (review/polish/); languages are set in reviewCatalog.
  {
    id: "polishNumerals",
    typing: false,
    name: "Polish numbers: endings, hyphens and noun forms",
    titleI18nKey: "review_msg_pl_numeral_suffix",
    descriptionI18nKey: "review_msg_pl_numeral_suffix",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 173,
  },
  {
    id: "polishDates",
    typing: false,
    name: "Polish dates",
    titleI18nKey: "review_msg_pl_impossible_date",
    descriptionI18nKey: "review_msg_pl_impossible_date",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 174,
  },
  {
    id: "polishMisplacedComma",
    typing: false,
    name: "Polish misplaced commas",
    titleI18nKey: "review_msg_pl_misplaced_comma",
    descriptionI18nKey: "review_msg_pl_misplaced_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 175,
  },
  {
    id: "polishMissingComma",
    typing: false,
    name: "Polish comma before a subordinate clause",
    titleI18nKey: "review_msg_pl_missing_comma",
    descriptionI18nKey: "review_msg_pl_missing_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 176,
  },
  {
    id: "polishPrepositionForms",
    typing: false,
    name: "Polish preposition forms (w/we, z/ze, od/ode)",
    titleI18nKey: "review_msg_pl_preposition_form",
    descriptionI18nKey: "review_msg_pl_preposition_form",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  // French (review/french/)
  {
    id: "frenchVerbForms",
    typing: false,
    name: "French -é / -er / -ez verb endings",
    titleI18nKey: "review_msg_fr_infinitive",
    descriptionI18nKey: "review_msg_fr_infinitive",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 173,
  },
  {
    id: "frenchHomophones",
    typing: false,
    name: "French sound-alike small words",
    titleI18nKey: "review_msg_fr_homophone",
    descriptionI18nKey: "review_msg_fr_homophone",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 174,
  },
  {
    id: "frenchHyphenation",
    typing: false,
    name: "French inversion and peut-être hyphens",
    titleI18nKey: "review_msg_fr_hyphen",
    descriptionI18nKey: "review_msg_fr_hyphen",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 175,
  },
  {
    id: "frenchSubjectVerbAgreement",
    typing: false,
    name: "French pronoun and verb agreement",
    titleI18nKey: "review_msg_fr_subject_verb",
    descriptionI18nKey: "review_msg_fr_subject_verb",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 176,
  },
  {
    id: "frenchElision",
    typing: false,
    name: "French elision",
    titleI18nKey: "review_msg_fr_elision",
    descriptionI18nKey: "review_msg_fr_elision",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 177,
  },
  {
    id: "frenchDates",
    typing: false,
    name: "French impossible dates",
    titleI18nKey: "review_msg_fr_date",
    descriptionI18nKey: "review_msg_fr_date",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 178,
  },
  {
    id: "frenchNounNumber",
    typing: false,
    name: "French determiner and noun number",
    titleI18nKey: "review_msg_fr_noun_number",
    descriptionI18nKey: "review_msg_fr_noun_number",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 179,
  },

  {
    id: "englishPronounCase",
    typing: false,
    name: "Pronoun case in subjects",
    titleI18nKey: "review_msg_pronoun_subject_case",
    descriptionI18nKey: "review_msg_pronoun_subject_case",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 165,
  },
  {
    id: "englishSentenceStructure",
    typing: false,
    name: "Sentence structure slips",
    titleI18nKey: "review_msg_sentence_structure",
    descriptionI18nKey: "review_msg_sentence_structure",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 166,
  },
  {
    id: "englishConfusedWords",
    typing: false,
    name: "Easily confused words in context",
    titleI18nKey: "review_msg_confused_word",
    descriptionI18nKey: "review_msg_confused_word",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 120,
  },
  {
    id: "englishAuxiliaryBaseVerb",
    typing: false,
    name: "Base verb after auxiliaries and infinitive to",
    titleI18nKey: "review_msg_auxiliary_base",
    descriptionI18nKey: "review_msg_auxiliary_base",
    exampleI18nKey: "",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 141,
  },
  {
    id: "englishRepeatedWords",
    typing: false,
    name: "Accidental repeated words",
    titleI18nKey: "review_msg_repeated_words",
    descriptionI18nKey: "review_msg_repeated_words",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 140,
  },
  {
    id: "capitalizeSentenceStart",
    name: "Capitalize sentence starts",
    titleI18nKey: "grammar_rule_capitalize_sentence_start",
    descriptionI18nKey: "grammar_rule_capitalize_sentence_start_desc",
    exampleI18nKey: "grammar_rule_capitalize_sentence_start_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 10,
  },
  {
    id: "capitalizeAfterLineBreak",
    name: "Capitalize after line breaks",
    titleI18nKey: "grammar_rule_capitalize_line_break",
    descriptionI18nKey: "grammar_rule_capitalize_line_break_desc",
    exampleI18nKey: "grammar_rule_capitalize_line_break_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 20,
  },
  {
    id: "englishPronounICapitalization",
    name: "Capitalize English pronoun I",
    titleI18nKey: "grammar_rule_english_pronoun_i",
    descriptionI18nKey: "grammar_rule_english_pronoun_i_desc",
    exampleI18nKey: "grammar_rule_english_pronoun_i_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 25,
  },
  {
    id: "englishContractionNormalization",
    name: "Normalize English contractions",
    titleI18nKey: "grammar_rule_english_contractions",
    descriptionI18nKey: "grammar_rule_english_contractions_desc",
    exampleI18nKey: "grammar_rule_english_contractions_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 26,
  },
  {
    id: "englishTypoWhitelistCorrection",
    name: "Correct common English typos",
    titleI18nKey: "grammar_rule_english_typos",
    descriptionI18nKey: "grammar_rule_english_typos_desc",
    exampleI18nKey: "grammar_rule_english_typos_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 27,
  },
  {
    id: "doubleSpaceToPeriod",
    name: "Convert double-space to period",
    titleI18nKey: "grammar_rule_double_space_to_period",
    descriptionI18nKey: "grammar_rule_double_space_to_period_desc",
    exampleI18nKey: "grammar_rule_double_space_to_period_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 28,
  },
  {
    id: "englishModalOfCorrection",
    name: "Fix modal verb phrase could of",
    titleI18nKey: "grammar_rule_english_modal_of",
    descriptionI18nKey: "grammar_rule_english_modal_of_desc",
    exampleI18nKey: "grammar_rule_english_modal_of_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 29,
  },
  {
    id: "englishYourWelcomeCorrection",
    name: "Fix your welcome phrase",
    titleI18nKey: "grammar_rule_english_your_welcome",
    descriptionI18nKey: "grammar_rule_english_your_welcome_desc",
    exampleI18nKey: "grammar_rule_english_your_welcome_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 30,
  },
  {
    id: "englishTheirThereBeVerb",
    name: "Fix their is to there is",
    titleI18nKey: "grammar_rule_english_their_there_be",
    descriptionI18nKey: "grammar_rule_english_their_there_be_desc",
    exampleI18nKey: "grammar_rule_english_their_there_be_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 31,
  },
  {
    id: "englishAlotCorrection",
    name: "Correct alot to a lot",
    titleI18nKey: "grammar_rule_english_alot",
    descriptionI18nKey: "grammar_rule_english_alot_desc",
    exampleI18nKey: "grammar_rule_english_alot_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 32,
  },
  {
    id: "englishPronounVerbWhitelistAgreement",
    name: "Fix common pronoun-verb mismatches",
    titleI18nKey: "grammar_rule_english_pronoun_verb_agreement",
    descriptionI18nKey: "grammar_rule_english_pronoun_verb_agreement_desc",
    exampleI18nKey: "grammar_rule_english_pronoun_verb_agreement_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 33,
  },
  {
    id: "englishArticleAnCorrection",
    name: "Correct a versus an",
    titleI18nKey: "grammar_rule_english_article_an",
    descriptionI18nKey: "grammar_rule_english_article_an_desc",
    exampleI18nKey: "grammar_rule_english_article_an_example",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 34,
  },
  {
    id: "englishOrdinalSuffix",
    name: "Fix ordinal suffixes",
    titleI18nKey: "grammar_rule_english_ordinal_suffix",
    descriptionI18nKey: "grammar_rule_english_ordinal_suffix_desc",
    exampleI18nKey: "grammar_rule_english_ordinal_suffix_example",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 35,
  },
  {
    id: "englishProperNounCapitalization",
    name: "Capitalize days, months and holidays",
    titleI18nKey: "grammar_rule_english_proper_nouns",
    descriptionI18nKey: "grammar_rule_english_proper_nouns_desc",
    exampleI18nKey: "grammar_rule_english_proper_nouns_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 36,
  },
  {
    id: "technicalTokenCompaction",
    name: "Compact technical token spacing",
    titleI18nKey: "grammar_rule_technical_compaction",
    descriptionI18nKey: "grammar_rule_technical_compaction_desc",
    exampleI18nKey: "grammar_rule_technical_compaction_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 40,
  },
  {
    id: "mathOperatorSpacing",
    name: "Math operator spacing",
    titleI18nKey: "grammar_rule_math_operator_spacing",
    descriptionI18nKey: "grammar_rule_math_operator_spacing_desc",
    exampleI18nKey: "grammar_rule_math_operator_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 50,
  },
  {
    id: "measurementUnitFormatting",
    name: "Format measurement units",
    titleI18nKey: "grammar_rule_measurement_unit_formatting",
    descriptionI18nKey: "grammar_rule_measurement_unit_formatting_desc",
    exampleI18nKey: "grammar_rule_measurement_unit_formatting_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 55,
  },
  {
    id: "currencySpacing",
    name: "Currency spacing",
    titleI18nKey: "grammar_rule_currency_spacing",
    descriptionI18nKey: "grammar_rule_currency_spacing_desc",
    exampleI18nKey: "grammar_rule_currency_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 56,
  },
  {
    id: "slashContextSpacing",
    name: "Slash context spacing",
    titleI18nKey: "grammar_rule_slash_context_spacing",
    descriptionI18nKey: "grammar_rule_slash_context_spacing_desc",
    exampleI18nKey: "grammar_rule_slash_context_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 60,
  },
  {
    id: "openingBracketSpacing",
    name: "Opening bracket spacing",
    titleI18nKey: "grammar_rule_opening_bracket_spacing",
    descriptionI18nKey: "grammar_rule_opening_bracket_spacing_desc",
    exampleI18nKey: "grammar_rule_opening_bracket_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 70,
  },
  {
    id: "closingBracketSpacing",
    name: "Closing bracket spacing",
    titleI18nKey: "grammar_rule_closing_bracket_spacing",
    descriptionI18nKey: "grammar_rule_closing_bracket_spacing_desc",
    exampleI18nKey: "grammar_rule_closing_bracket_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 80,
  },
  {
    id: "commaPeriodSpacing",
    name: "Comma and period spacing",
    titleI18nKey: "grammar_rule_comma_period_spacing",
    descriptionI18nKey: "grammar_rule_comma_period_spacing_desc",
    exampleI18nKey: "grammar_rule_comma_period_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 90,
  },
  {
    id: "collapseRepeatedSpaces",
    name: "Collapse repeated spaces",
    titleI18nKey: "grammar_rule_collapse_repeated_spaces",
    descriptionI18nKey: "grammar_rule_collapse_repeated_spaces_desc",
    exampleI18nKey: "grammar_rule_collapse_repeated_spaces_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 100,
  },
  {
    id: "trimSpaceBeforeLineBreak",
    name: "Trim spaces before line breaks",
    titleI18nKey: "grammar_rule_trim_space_before_line_break",
    descriptionI18nKey: "grammar_rule_trim_space_before_line_break_desc",
    exampleI18nKey: "grammar_rule_trim_space_before_line_break_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 110,
  },
  {
    id: "ellipsisShortcut",
    name: "Replace three dots with ellipsis",
    titleI18nKey: "grammar_rule_ellipsis_shortcut",
    descriptionI18nKey: "grammar_rule_ellipsis_shortcut_desc",
    exampleI18nKey: "grammar_rule_ellipsis_shortcut_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 130,
  },
  {
    id: "emdashShortcut",
    name: "Replace double hyphen with em dash",
    titleI18nKey: "grammar_rule_emdash_shortcut",
    descriptionI18nKey: "grammar_rule_emdash_shortcut_desc",
    exampleI18nKey: "grammar_rule_emdash_shortcut_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 131,
  },
  {
    id: "smartQuoteNormalization",
    name: "Normalize straight quotes",
    titleI18nKey: "grammar_rule_smart_quote_normalization",
    descriptionI18nKey: "grammar_rule_smart_quote_normalization_desc",
    exampleI18nKey: "grammar_rule_smart_quote_normalization_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 132,
  },
  {
    id: "frenchPunctuationSpacing",
    name: "French punctuation spacing",
    titleI18nKey: "grammar_rule_french_punctuation_spacing",
    descriptionI18nKey: "grammar_rule_french_punctuation_spacing_desc",
    exampleI18nKey: "grammar_rule_french_punctuation_spacing_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 133,
  },
  {
    id: "duplicatePunctuationCollapse",
    name: "Collapse accidental duplicate punctuation",
    titleI18nKey: "grammar_rule_duplicate_punctuation_collapse",
    descriptionI18nKey: "grammar_rule_duplicate_punctuation_collapse_desc",
    exampleI18nKey: "grammar_rule_duplicate_punctuation_collapse_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 134,
  },
  {
    id: "autoBracketClose",
    name: "Auto-close brackets and quotes",
    titleI18nKey: "grammar_rule_auto_bracket_close",
    descriptionI18nKey: "grammar_rule_auto_bracket_close_desc",
    exampleI18nKey: "grammar_rule_auto_bracket_close_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 135,
    codeSafe: true,
  },
  // Portuguese Review checks (review/portuguese/).
  {
    id: "portugueseAccentParonyms",
    typing: false,
    name: "Portuguese accent after articles and prepositions",
    titleI18nKey: "review_msg_pt_accent_paronym",
    descriptionI18nKey: "review_msg_pt_accent_paronym",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 310,
  },
  {
    id: "portugueseConfusions",
    typing: false,
    name: "Portuguese crase, por que and lookalike words",
    titleI18nKey: "review_msg_pt_confusions",
    descriptionI18nKey: "review_msg_pt_confusions",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 311,
  },
  {
    id: "portugueseContractions",
    typing: false,
    name: "Portuguese preposition and article contractions",
    titleI18nKey: "review_msg_pt_contraction",
    descriptionI18nKey: "review_msg_pt_contraction",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 312,
  },
  {
    id: "portugueseNumberFormat",
    typing: false,
    name: "Portuguese hours, ordinals, degrees and unit symbols",
    titleI18nKey: "review_msg_pt_number_format",
    descriptionI18nKey: "review_msg_pt_number_format",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 313,
  },
  {
    id: "portugueseTypographyStyle",
    typing: false,
    name: "Portuguese multiplication sign and chemical formulas",
    titleI18nKey: "review_msg_pt_typography_style",
    descriptionI18nKey: "review_msg_pt_typography_style",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 314,
  },
  {
    id: "portugueseCliticPlacement",
    typing: false,
    name: "Portuguese pronoun before the verb after não, que and similar words",
    titleI18nKey: "review_msg_pt_proclisis",
    descriptionI18nKey: "review_msg_pt_proclisis",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 315,
  },
  {
    id: "portugueseAO90",
    typing: false,
    name: "Portuguese 1990 spelling agreement: prefixes, months and weekdays",
    titleI18nKey: "review_msg_pt_ao90",
    descriptionI18nKey: "review_msg_pt_ao90",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 316,
  },
  {
    id: "portugueseDates",
    typing: false,
    name: "Portuguese dates that do not exist",
    titleI18nKey: "review_msg_pt_invalid_date",
    descriptionI18nKey: "review_msg_pt_invalid_date",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 317,
  },
  {
    id: "portugueseCommas",
    typing: false,
    name: "Portuguese commas around asides and before a name",
    titleI18nKey: "review_msg_pt_comma",
    descriptionI18nKey: "review_msg_pt_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 318,
  },
  {
    id: "portugueseAgreement",
    typing: false,
    name: "Portuguese agreement of verbs of existing, próprio and neuter pronouns",
    titleI18nKey: "review_msg_pt_agreement",
    descriptionI18nKey: "review_msg_pt_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 319,
  },
  // Spanish Review checks (review/spanish/).
  {
    id: "spanishAccents",
    typing: false,
    name: "Spanish written accents",
    titleI18nKey: "review_msg_spanish_accent",
    descriptionI18nKey: "review_msg_spanish_accent",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 166,
  },
  {
    id: "spanishConfusions",
    typing: false,
    name: "Spanish confused words",
    titleI18nKey: "review_msg_spanish_confusion",
    descriptionI18nKey: "review_msg_spanish_confusion",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 167,
  },
  {
    id: "spanishTypography",
    typing: false,
    name: "Spanish writing conventions",
    titleI18nKey: "review_msg_spanish_conjunction",
    descriptionI18nKey: "review_msg_spanish_conjunction",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 168,
  },
  {
    id: "spanishAgreement",
    typing: false,
    name: "Spanish noun-phrase agreement",
    titleI18nKey: "review_msg_spanish_agreement",
    descriptionI18nKey: "review_msg_spanish_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 169,
  },
  {
    id: "spanishQuotes",
    typing: false,
    name: "Spanish quotation marks",
    titleI18nKey: "review_msg_spanish_quotes",
    descriptionI18nKey: "review_msg_spanish_quotes",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 170,
  },
  // German-only Review checks (review/german/).
  {
    id: "germanNounCasing",
    typing: false,
    name: "German nouns are capitalized",
    titleI18nKey: "review_msg_german_noun_case",
    descriptionI18nKey: "review_msg_german_noun_case",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 37,
  },
  {
    id: "germanPrepositionCase",
    typing: false,
    name: "Case after German prepositions",
    titleI18nKey: "review_msg_german_preposition_case",
    descriptionI18nKey: "review_msg_german_preposition_case",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 160,
  },
  {
    id: "germanConfusedWords",
    typing: false,
    name: "Confused German words",
    titleI18nKey: "review_msg_contextual_grammar",
    descriptionI18nKey: "review_msg_contextual_grammar",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 150,
  },
  {
    id: "germanAdjectiveForms",
    typing: false,
    name: "German adjective endings",
    titleI18nKey: "review_msg_german_adjective_ending",
    descriptionI18nKey: "review_msg_german_adjective_ending",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 155,
  },
  {
    id: "germanSuspendedHyphen",
    typing: false,
    name: "Hyphen on a shortened compound part",
    titleI18nKey: "review_msg_german_suspended_hyphen",
    descriptionI18nKey: "review_msg_german_suspended_hyphen",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 120,
  },
  {
    id: "germanAbbreviations",
    typing: false,
    name: "German abbreviation dots and spaces",
    titleI18nKey: "review_msg_german_abbreviation",
    descriptionI18nKey: "review_msg_german_abbreviation",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 110,
  },
  {
    id: "germanQuotes",
    typing: false,
    name: "German quotation marks",
    titleI18nKey: "review_msg_german_quotes",
    descriptionI18nKey: "review_msg_german_quotes",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 100,
  },
  {
    id: "germanAbbreviationSpacing",
    typing: false,
    name: "Spaces in German abbreviations",
    titleI18nKey: "review_msg_german_abbreviation_spacing",
    descriptionI18nKey: "review_msg_german_abbreviation_spacing",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 105,
  },
  {
    id: "germanDates",
    typing: false,
    name: "German dates",
    titleI18nKey: "review_msg_german_invalid_date",
    descriptionI18nKey: "review_msg_german_invalid_date",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 115,
  },
  {
    id: "germanCompounds",
    typing: false,
    name: "German compounds and joined forms",
    titleI18nKey: "review_msg_closed_compound",
    descriptionI18nKey: "review_msg_closed_compound",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 125,
  },
  {
    id: "germanCommas",
    typing: false,
    name: "Commas before German clauses",
    titleI18nKey: "review_msg_german_comma",
    descriptionI18nKey: "review_msg_german_comma",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 110,
  },
  {
    id: "germanVerbAgreement",
    typing: false,
    name: "German verb agreement",
    titleI18nKey: "review_msg_german_verb_agreement",
    descriptionI18nKey: "review_msg_german_verb_agreement",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 120,
  },
  {
    id: "germanArticleGender",
    typing: false,
    name: "German article and noun gender",
    titleI18nKey: "review_msg_german_article_gender",
    descriptionI18nKey: "review_msg_german_article_gender",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 158,
  },
  {
    id: "germanQuestionMarks",
    typing: false,
    name: "German questions ending in a full stop",
    titleI18nKey: "review_msg_german_question_mark",
    descriptionI18nKey: "review_msg_german_question_mark",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 100,
  },
  {
    id: "germanNumbers",
    typing: false,
    name: "German numbers in words",
    titleI18nKey: "review_msg_german_numbers",
    descriptionI18nKey: "review_msg_german_numbers",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 120,
  },
  {
    id: "germanStraightQuotes",
    typing: false,
    name: "Straight quotes in German text",
    titleI18nKey: "review_msg_german_quotes",
    descriptionI18nKey: "review_msg_german_quotes",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 95,
  },
  {
    id: "germanColloquial",
    typing: false,
    name: "Colloquial German short forms",
    titleI18nKey: "review_msg_german_colloquial",
    descriptionI18nKey: "review_msg_german_colloquial",
    exampleI18nKey: "",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 60,
  },
] as const;

export type CatalogRuleId = (typeof GRAMMAR_RULE_CATALOG)[number]["id"];

export const TYPING_RULE_CATALOG = GRAMMAR_RULE_CATALOG.filter(
  (entry): entry is GrammarRuleCatalogEntry & { id: GrammarRuleId } => entry.typing !== false,
);

export const TYPING_RULE_IDS = TYPING_RULE_CATALOG.map((entry) => entry.id);

export const GRAMMAR_RULE_IDS: CatalogRuleId[] = GRAMMAR_RULE_CATALOG.map((entry) => entry.id);

// Historical snapshots below are exact stored values, compared against real
// stored settings by the V4-V6 migrations. They may name retired rules
// ("neutralPunctuationPolicy"), so they are plain strings, never edited.
export const RECOMMENDED_V1_GRAMMAR_RULES: string[] = [
  "capitalizeSentenceStart",
  "capitalizeAfterLineBreak",
  "technicalTokenCompaction",
  "mathOperatorSpacing",
  "slashContextSpacing",
  "openingBracketSpacing",
  "closingBracketSpacing",
  "commaPeriodSpacing",
  "collapseRepeatedSpaces",
  "trimSpaceBeforeLineBreak",
  "neutralPunctuationPolicy",
];

// This is the pre-v3 recommended set (current users migrated by V5).
export const RECOMMENDED_V2_GRAMMAR_RULES: string[] = [
  ...RECOMMENDED_V1_GRAMMAR_RULES.slice(0, 2),
  "englishPronounICapitalization",
  "englishContractionNormalization",
  "englishTypoWhitelistCorrection",
  ...RECOMMENDED_V1_GRAMMAR_RULES.slice(2),
];

// Historical snapshots used by V6 migration. Keep these exact when the live catalog grows.
export const DEFAULT_V3_GRAMMAR_RULES: string[] = [
  "capitalizeSentenceStart",
  "capitalizeAfterLineBreak",
  "englishPronounICapitalization",
  "englishContractionNormalization",
  "englishTypoWhitelistCorrection",
  "doubleSpaceToPeriod",
  "englishModalOfCorrection",
  "englishYourWelcomeCorrection",
  "englishTheirThereBeVerb",
  "englishAlotCorrection",
  "englishPronounVerbWhitelistAgreement",
  "technicalTokenCompaction",
  "mathOperatorSpacing",
  "slashContextSpacing",
  "openingBracketSpacing",
  "closingBracketSpacing",
  "commaPeriodSpacing",
  "collapseRepeatedSpaces",
  "trimSpaceBeforeLineBreak",
  "neutralPunctuationPolicy",
];

export const DEFAULT_CURRENT_GRAMMAR_RULES: CatalogRuleId[] = TYPING_RULE_CATALOG.filter(
  (entry) => entry.defaultRollout === "on",
).map((entry) => entry.id);

const CODE_SAFE_RULE_IDS: ReadonlySet<string> = new Set(
  GRAMMAR_RULE_CATALOG.filter((entry) => entry.codeSafe).map((entry) => entry.id),
);

export function isCodeSafeGrammarRule(ruleId: string): boolean {
  return CODE_SAFE_RULE_IDS.has(ruleId);
}

/** Code mode keeps only the rules that never rewrite code. */
export function filterCodeSafeGrammarRules(ruleIds: readonly string[]): string[] {
  return ruleIds.filter(isCodeSafeGrammarRule);
}

export const RECOMMENDED_CURRENT_GRAMMAR_RULES: CatalogRuleId[] = TYPING_RULE_CATALOG.filter(
  (entry) => entry.recommended,
).map((entry) => entry.id);

/** Opt-in preset: the recommended rules plus language-aware quotes and punctuation. */
const TYPOGRAPHY_EXTRA_RULES: CatalogRuleId[] = [
  "smartQuoteNormalization",
  "frenchPunctuationSpacing",
  "ellipsisShortcut",
];
export const TYPOGRAPHY_GRAMMAR_RULES: CatalogRuleId[] = GRAMMAR_RULE_IDS.filter(
  (id) => RECOMMENDED_CURRENT_GRAMMAR_RULES.includes(id) || TYPOGRAPHY_EXTRA_RULES.includes(id),
);

const LEGACY_RULE_MAP: Record<string, CatalogRuleId[]> = {
  spacingRule: [
    "commaPeriodSpacing",
    "openingBracketSpacing",
    "closingBracketSpacing",
    "slashContextSpacing",
    "mathOperatorSpacing",
    "technicalTokenCompaction",
  ],
  capitalizeFirstLetter: ["capitalizeSentenceStart", "capitalizeAfterLineBreak"],
};

export function isCatalogRuleId(value: string): value is CatalogRuleId {
  return GRAMMAR_RULE_IDS.includes(value as CatalogRuleId);
}

export function normalizeGrammarRuleSelection(selection: unknown): CatalogRuleId[] {
  const selected = Array.isArray(selection) ? selection.map((item) => String(item)) : [];
  const expanded: CatalogRuleId[] = [];

  for (const ruleId of selected) {
    if (isCatalogRuleId(ruleId)) {
      expanded.push(ruleId);
      continue;
    }

    const mapped = LEGACY_RULE_MAP[ruleId];
    if (mapped) {
      expanded.push(...mapped);
    }
  }

  const unique = new Set(expanded);
  return TYPING_RULE_IDS.filter((id) => unique.has(id));
}
