import type { GrammarRuleCatalogEntry, GrammarRuleId } from "./types";

/** A native Review-only check: off by default, one message for its title and description. */
function reviewOnly(
  id: GrammarRuleCatalogEntry["id"],
  name: string,
  messageKey: string,
  priority: number,
  languageScope: GrammarRuleCatalogEntry["languageScope"] = "all",
): GrammarRuleCatalogEntry {
  return {
    id,
    typing: false,
    name,
    titleI18nKey: messageKey,
    descriptionI18nKey: messageKey,
    exampleI18nKey: "",
    languageScope,
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority,
  };
}

export const GRAMMAR_RULE_CATALOG: readonly GrammarRuleCatalogEntry[] = [
  reviewOnly(
    "englishSubjectVerbAgreement",
    "Subject and verb agreement",
    "review_msg_pronoun_verb",
    163,
    "en_US",
  ),
  // Lowest priorities: a more specific rule proposing the same edit explains it.
  reviewOnly(
    "englishPhraseCorrections",
    "Fixed phrase corrections",
    "review_msg_phrase_correction",
    3,
    "en_US",
  ),
  reviewOnly(
    "englishClosedCompounds",
    "Split and joined compounds",
    "review_msg_closed_compound",
    2,
    "en_US",
  ),
  reviewOnly(
    "styleRedundancy",
    "Optional redundancy advice",
    "review_msg_style_redundancy",
    162,
    "en_US",
  ),
  reviewOnly(
    "styleLongSentence",
    "Optional long-sentence advice",
    "review_msg_style_long_sentence",
    161,
  ),
  reviewOnly("stylePhrasing", "Optional wording advice", "review_msg_style_phrasing", 1, "en_US"),
  // Opt-in register and list-punctuation styles; the two serial-comma styles oppose each other.
  reviewOnly(
    "styleContractions",
    "Optional formal register: no contractions",
    "review_msg_avoid_contractions",
    1,
    "en_US",
  ),
  reviewOnly(
    "styleOxfordComma",
    "Optional serial (Oxford) comma",
    "review_msg_oxford_comma",
    1,
    "en_US",
  ),
  reviewOnly(
    "styleNoOxfordComma",
    "Optional list style without the serial comma",
    "review_msg_no_oxford_comma",
    1,
    "en_US",
  ),
  // Opt-in: the other accepted form of a phrase whose usual form stylePhrasing may suggest.
  reviewOnly(
    "styleAlternativePhrasing",
    "Optional alternative form of a phrase",
    "review_msg_alternative_phrasing",
    1,
    "en_US",
  ),
  // Opt-in: wording that is usually a mistake but can be correct, and quoted mentions.
  reviewOnly(
    "englishPossibleErrors",
    "Optional check for possible mistakes",
    "review_msg_possible_error",
    1,
    "en_US",
  ),
  // Opt-in dialects: each converts the other's spellings, words and idioms.
  reviewOnly(
    "englishAmericanSpelling",
    "Optional American English spelling",
    "review_msg_american_spelling",
    1,
    "en_US",
  ),
  reviewOnly(
    "englishBritishSpelling",
    "Optional British English spelling",
    "review_msg_british_spelling",
    1,
    "en_US",
  ),
  reviewOnly(
    "englishOxfordSpelling",
    "Optional Oxford spelling (-ize)",
    "review_msg_oxford_spelling",
    1,
    "en_US",
  ),
  reviewOnly(
    "englishMissingArticle",
    "Missing article before a count noun",
    "review_msg_missing_article",
    1,
    "en_US",
  ),
  // Opt-in house style: full words and spelled-out small numbers.
  reviewOnly(
    "styleWordChoice",
    "Optional full or more precise words",
    "review_msg_word_choice",
    1,
    "en_US",
  ),
  reviewOnly(
    "styleSpelledNumbers",
    "Optional spelled-out small numbers",
    "review_msg_spelled_numbers",
    1,
    "en_US",
  ),
  reviewOnly(
    "preferredTerminology",
    "Your preferred terminology",
    "review_msg_preferred_terminology",
    160,
  ),
  reviewOnly(
    "englishCanonicalCasing",
    "Canonical brand and acronym casing",
    "review_msg_canonical_casing",
    159,
  ),
  reviewOnly("quoteSpacing", "Space outside quotation marks", "review_msg_quote_spacing", 171),
  reviewOnly(
    "primeSymbols",
    "Prime marks for feet, inches, minutes and seconds",
    "review_msg_prime_symbols",
    172,
  ),
  reviewOnly(
    "greekFinalNu",
    "Greek final ν and κι before the next sound",
    "review_msg_greek_final_nu",
    173,
  ),
  reviewOnly("greekStrictFinalNu", "Greek strict final ν", "review_msg_greek_strict_final_nu", 174),
  reviewOnly(
    "greekQuestionAccent",
    "Greek interrogative πού and πώς",
    "review_msg_greek_question_accent",
    175,
  ),
  reviewOnly(
    "greekPunctuation",
    "Greek punctuation conventions",
    "review_msg_greek_intro_comma",
    176,
  ),
  reviewOnly(
    "swedishTypography",
    "Swedish ordinals, acronym genitives, days and months",
    "review_msg_swedish_typography",
    177,
  ),
  reviewOnly(
    "polishCaseAgreement",
    "Polish noun cases after prepositions, demonstratives and numerals",
    "review_msg_pl_agreement",
    178,
  ),
  reviewOnly(
    "polishTypography",
    "Polish typesetting: dashes, symbols, spacing",
    "review_msg_pl_typography",
    179,
  ),
  reviewOnly("polishQuotes", "Polish quotation marks („…”)", "review_msg_pl_quotes", 180),
  reviewOnly(
    "polishCapitalization",
    "Polish capitals: weekdays, months, holidays, seas",
    "review_msg_pl_capitals",
    181,
  ),
  reviewOnly("swedishAgreement", "Swedish en/ett agreement", "review_msg_swedish_agreement", 178),
  reviewOnly(
    "frenchAdjectiveAgreement",
    "French adjective and participle agreement",
    "review_msg_fr_adjective_agreement",
    177,
  ),
  reviewOnly("frenchTout", "French tout / tous / toute(s)", "review_msg_fr_tout", 177),
  reviewOnly("frenchMood", "French subjunctive and conditional", "review_msg_fr_subjunctive", 177),
  reviewOnly("frenchMissingNe", "French negation without ne", "review_msg_fr_missing_ne", 150),
  reviewOnly("frenchCommas", "French commas", "review_msg_fr_stray_comma", 150),
  reviewOnly("frenchOrdinals", "French ordinal abbreviations", "review_msg_fr_ordinal", 150),
  reviewOnly(
    "arabicAgreement",
    "Arabic demonstrative and number agreement",
    "review_msg_arabic_agreement",
    179,
  ),
  reviewOnly(
    "frenchNounGender",
    "French determiner and noun gender",
    "review_msg_fr_noun_gender",
    178,
  ),
  reviewOnly(
    "arabicCaseEndings",
    "Arabic case and mood endings",
    "review_msg_arabic_case_endings",
    180,
  ),
  reviewOnly("dateTenseConsistency", "Verb tense against a date", "review_msg_date_tense", 139),
  reviewOnly("arabicDates", "Arabic date checks", "review_msg_arabic_dates", 181),
  reviewOnly("unclosedQuotation", "Unclosed quotation marks", "review_msg_quotation_balance", 158),
  reviewOnly(
    "typographicQuotes",
    "Typographic quotes and apostrophes",
    "review_msg_typographic_quotes",
    90,
  ),
  reviewOnly(
    "englishUsagePhrases",
    "Established usage phrases",
    "review_msg_usage_phrases",
    157,
    "en_US",
  ),
  reviewOnly(
    "englishDoubledDegree",
    "Doubled comparatives and superlatives",
    "review_msg_doubled_degree",
    156,
    "en_US",
  ),
  reviewOnly(
    "englishCountability",
    "Countability in ordinary prose",
    "review_msg_countability",
    155,
    "en_US",
  ),
  reviewOnly(
    "englishContextualCompounds",
    "Contextual compound words",
    "review_msg_compounds",
    154,
    "en_US",
  ),
  reviewOnly(
    "englishNounNumber",
    "Demonstratives and noun number",
    "review_msg_demonstrative_number",
    153,
    "en_US",
  ),
  reviewOnly(
    "englishPerfectParticiples",
    "Verb forms after have and be",
    "review_msg_perfect_participle",
    152,
    "en_US",
  ),
  reviewOnly(
    "englishVerbComplements",
    "Verb complement constructions",
    "review_msg_verb_complements",
    151,
    "en_US",
  ),
  reviewOnly(
    "englishFixedPrepositions",
    "Fixed preposition constructions",
    "review_msg_fixed_prepositions",
    150,
    "en_US",
  ),
  reviewOnly(
    "englishItsContext",
    "Its and it is in context",
    "review_msg_its_contraction",
    147,
    "en_US",
  ),
  reviewOnly(
    "englishLetsContext",
    "Lets and let us in context",
    "review_msg_lets_contraction",
    148,
    "en_US",
  ),
  reviewOnly(
    "englishElsePossessive",
    "Indefinite-pronoun possessives",
    "review_msg_else_possessive",
    149,
    "en_US",
  ),
  reviewOnly(
    "englishExistentialAgreement",
    "Existential noun agreement",
    "review_msg_existential_agreement",
    146,
    "en_US",
  ),
  reviewOnly("englishThenThan", "Comparison then/than", "review_msg_then_than", 142, "en_US"),
  reviewOnly(
    "englishYourYouAre",
    "Your and you are in context",
    "review_msg_your_you_are",
    143,
    "en_US",
  ),
  reviewOnly(
    "englishTheirThereTheyAre",
    "Their, there and they are in context",
    "review_msg_their_possessive",
    144,
    "en_US",
  ),
  reviewOnly("englishToToo", "Intensifier to/too", "review_msg_to_too", 145, "en_US"),
  reviewOnly(
    "englishWereWhere",
    "Were and where in context",
    "review_msg_were_where",
    164,
    "en_US",
  ),
  // Below englishUsagePhrases, whose framed "finded" fix explains the same edit better.
  reviewOnly(
    "englishIrregularForms",
    "Irregular plurals and past forms",
    "review_msg_irregular_form",
    137,
    "en_US",
  ),
  reviewOnly(
    "englishPossessiveNouns",
    "Possessive apostrophes on nouns",
    "review_msg_noun_possessive",
    138,
    "en_US",
  ),
  reviewOnly(
    "englishDateConsistency",
    "Weekdays and impossible dates",
    "review_msg_weekday_mismatch",
    139,
    "en_US",
  ),
  reviewOnly(
    "englishTenseConsistency",
    "Tense against time words and dates",
    "review_msg_tense_time_word",
    139,
    "en_US",
  ),
  reviewOnly(
    "englishSentenceFragment",
    "Sentence fragments",
    "review_msg_sentence_fragment",
    40,
    "en_US",
  ),
  // English tables and typography (review/english/, en-tables2).
  reviewOnly(
    "englishApostrophes",
    "Apostrophes in plurals, verbs and possessives",
    "review_msg_plural_apostrophe",
    140,
    "en_US",
  ),
  reviewOnly(
    "englishNotation",
    "English numbers, initialisms and degrees",
    "review_msg_english_digit_groups",
    141,
    "en_US",
  ),
  reviewOnly(
    "englishTypography",
    "Typographic symbols, quotes and dashes",
    "review_msg_typographic_symbol",
    142,
    "en_US",
  ),
  reviewOnly("stylePassiveVoice", "Passive voice", "review_msg_passive_voice", 143, "en_US"),
  reviewOnly("englishPunctuation", "Stray commas", "review_msg_stray_comma", 144, "en_US"),
  reviewOnly(
    "styleIntroductoryComma",
    "Comma after an opening phrase",
    "review_msg_introductory_comma",
    145,
    "en_US",
  ),
  reviewOnly(
    "styleClauseComma",
    "Comma between joined clauses",
    "review_msg_clause_comma",
    145,
    "en_US",
  ),
  // Polish-only Review checks (review/polish/); languages are set in reviewCatalog.
  reviewOnly(
    "polishNumerals",
    "Polish numbers: endings, hyphens and noun forms",
    "review_msg_pl_numeral_suffix",
    173,
  ),
  reviewOnly("polishDates", "Polish dates", "review_msg_pl_impossible_date", 174),
  reviewOnly(
    "polishMisplacedComma",
    "Polish misplaced commas",
    "review_msg_pl_misplaced_comma",
    175,
  ),
  reviewOnly(
    "polishMissingComma",
    "Polish comma before a subordinate clause",
    "review_msg_pl_missing_comma",
    176,
  ),
  reviewOnly(
    "polishPrepositionForms",
    "Polish preposition forms (w/we, z/ze, od/ode)",
    "review_msg_pl_preposition_form",
    177,
  ),
  // French (review/french/)
  reviewOnly(
    "frenchVerbForms",
    "French -é / -er / -ez verb endings",
    "review_msg_fr_infinitive",
    173,
  ),
  reviewOnly("frenchHomophones", "French sound-alike small words", "review_msg_fr_homophone", 174),
  reviewOnly(
    "frenchHyphenation",
    "French inversion and peut-être hyphens",
    "review_msg_fr_hyphen",
    175,
  ),
  reviewOnly(
    "frenchSubjectVerbAgreement",
    "French pronoun and verb agreement",
    "review_msg_fr_subject_verb",
    176,
  ),
  reviewOnly("frenchElision", "French elision", "review_msg_fr_elision", 177),
  reviewOnly("frenchDates", "French impossible dates", "review_msg_fr_date", 178),
  reviewOnly(
    "frenchNounNumber",
    "French determiner and noun number",
    "review_msg_fr_noun_number",
    179,
  ),

  reviewOnly(
    "englishPronounCase",
    "Pronoun case in subjects",
    "review_msg_pronoun_subject_case",
    165,
    "en_US",
  ),
  reviewOnly(
    "englishSentenceStructure",
    "Sentence structure slips",
    "review_msg_sentence_structure",
    166,
    "en_US",
  ),
  reviewOnly(
    "englishConfusedWords",
    "Easily confused words in context",
    "review_msg_confused_word",
    120,
    "en_US",
  ),
  reviewOnly(
    "englishAuxiliaryBaseVerb",
    "Base verb after auxiliaries and infinitive to",
    "review_msg_auxiliary_base",
    141,
    "en_US",
  ),
  reviewOnly("englishRepeatedWords", "Accidental repeated words", "review_msg_repeated_words", 140),
  {
    id: "capitalizeSentenceStart",
    name: "Capitalize sentence starts",
    titleI18nKey: "grammar_rule_capitalize_sentence_start",
    descriptionI18nKey: "grammar_rule_capitalize_sentence_start_desc",
    exampleI18nKey: "grammar_rule_capitalize_sentence_start_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 10,
  },
  {
    id: "capitalizeAfterLineBreak",
    name: "Capitalize after line breaks",
    titleI18nKey: "grammar_rule_capitalize_line_break",
    descriptionI18nKey: "grammar_rule_capitalize_line_break_desc",
    exampleI18nKey: "grammar_rule_capitalize_line_break_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 20,
  },
  {
    id: "englishPronounICapitalization",
    name: "Capitalize English pronoun I",
    titleI18nKey: "grammar_rule_english_pronoun_i",
    descriptionI18nKey: "grammar_rule_english_pronoun_i_desc",
    exampleI18nKey: "grammar_rule_english_pronoun_i_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 25,
  },
  {
    id: "englishContractionNormalization",
    name: "Normalize English contractions",
    titleI18nKey: "grammar_rule_english_contractions",
    descriptionI18nKey: "grammar_rule_english_contractions_desc",
    exampleI18nKey: "grammar_rule_english_contractions_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 26,
  },
  {
    id: "englishTypoWhitelistCorrection",
    name: "Correct common English typos",
    titleI18nKey: "grammar_rule_english_typos",
    descriptionI18nKey: "grammar_rule_english_typos_desc",
    exampleI18nKey: "grammar_rule_english_typos_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 27,
  },
  {
    id: "doubleSpaceToPeriod",
    name: "Convert double-space to period",
    titleI18nKey: "grammar_rule_double_space_to_period",
    descriptionI18nKey: "grammar_rule_double_space_to_period_desc",
    exampleI18nKey: "grammar_rule_double_space_to_period_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 28,
  },
  {
    id: "englishModalOfCorrection",
    name: "Fix modal verb phrase could of",
    titleI18nKey: "grammar_rule_english_modal_of",
    descriptionI18nKey: "grammar_rule_english_modal_of_desc",
    exampleI18nKey: "grammar_rule_english_modal_of_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 29,
  },
  {
    id: "englishYourWelcomeCorrection",
    name: "Fix your welcome phrase",
    titleI18nKey: "grammar_rule_english_your_welcome",
    descriptionI18nKey: "grammar_rule_english_your_welcome_desc",
    exampleI18nKey: "grammar_rule_english_your_welcome_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 30,
  },
  {
    id: "englishTheirThereBeVerb",
    name: "Fix their is to there is",
    titleI18nKey: "grammar_rule_english_their_there_be",
    descriptionI18nKey: "grammar_rule_english_their_there_be_desc",
    exampleI18nKey: "grammar_rule_english_their_there_be_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 31,
  },
  {
    id: "englishAlotCorrection",
    name: "Correct alot to a lot",
    titleI18nKey: "grammar_rule_english_alot",
    descriptionI18nKey: "grammar_rule_english_alot_desc",
    exampleI18nKey: "grammar_rule_english_alot_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 32,
  },
  {
    id: "englishPronounVerbWhitelistAgreement",
    name: "Fix common pronoun-verb mismatches",
    titleI18nKey: "grammar_rule_english_pronoun_verb_agreement",
    descriptionI18nKey: "grammar_rule_english_pronoun_verb_agreement_desc",
    exampleI18nKey: "grammar_rule_english_pronoun_verb_agreement_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 33,
  },
  {
    id: "englishArticleAnCorrection",
    name: "Correct a versus an",
    titleI18nKey: "grammar_rule_english_article_an",
    descriptionI18nKey: "grammar_rule_english_article_an_desc",
    exampleI18nKey: "grammar_rule_english_article_an_example",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 34,
  },
  {
    id: "englishOrdinalSuffix",
    name: "Fix ordinal suffixes",
    titleI18nKey: "grammar_rule_english_ordinal_suffix",
    descriptionI18nKey: "grammar_rule_english_ordinal_suffix_desc",
    exampleI18nKey: "grammar_rule_english_ordinal_suffix_example",
    languageScope: "en_US",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 35,
  },
  {
    id: "englishProperNounCapitalization",
    name: "Capitalize days, months and holidays",
    titleI18nKey: "grammar_rule_english_proper_nouns",
    descriptionI18nKey: "grammar_rule_english_proper_nouns_desc",
    exampleI18nKey: "grammar_rule_english_proper_nouns_example",
    languageScope: "en_US",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 36,
  },
  {
    id: "technicalTokenCompaction",
    name: "Compact technical token spacing",
    titleI18nKey: "grammar_rule_technical_compaction",
    descriptionI18nKey: "grammar_rule_technical_compaction_desc",
    exampleI18nKey: "grammar_rule_technical_compaction_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 40,
  },
  {
    id: "mathOperatorSpacing",
    name: "Math operator spacing",
    titleI18nKey: "grammar_rule_math_operator_spacing",
    descriptionI18nKey: "grammar_rule_math_operator_spacing_desc",
    exampleI18nKey: "grammar_rule_math_operator_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 50,
  },
  {
    id: "measurementUnitFormatting",
    name: "Format measurement units",
    titleI18nKey: "grammar_rule_measurement_unit_formatting",
    descriptionI18nKey: "grammar_rule_measurement_unit_formatting_desc",
    exampleI18nKey: "grammar_rule_measurement_unit_formatting_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 55,
  },
  {
    id: "currencySpacing",
    name: "Currency spacing",
    titleI18nKey: "grammar_rule_currency_spacing",
    descriptionI18nKey: "grammar_rule_currency_spacing_desc",
    exampleI18nKey: "grammar_rule_currency_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 56,
  },
  {
    id: "slashContextSpacing",
    name: "Slash context spacing",
    titleI18nKey: "grammar_rule_slash_context_spacing",
    descriptionI18nKey: "grammar_rule_slash_context_spacing_desc",
    exampleI18nKey: "grammar_rule_slash_context_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 60,
  },
  {
    id: "openingBracketSpacing",
    name: "Opening bracket spacing",
    titleI18nKey: "grammar_rule_opening_bracket_spacing",
    descriptionI18nKey: "grammar_rule_opening_bracket_spacing_desc",
    exampleI18nKey: "grammar_rule_opening_bracket_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 70,
  },
  {
    id: "closingBracketSpacing",
    name: "Closing bracket spacing",
    titleI18nKey: "grammar_rule_closing_bracket_spacing",
    descriptionI18nKey: "grammar_rule_closing_bracket_spacing_desc",
    exampleI18nKey: "grammar_rule_closing_bracket_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 80,
  },
  {
    id: "commaPeriodSpacing",
    name: "Comma and period spacing",
    titleI18nKey: "grammar_rule_comma_period_spacing",
    descriptionI18nKey: "grammar_rule_comma_period_spacing_desc",
    exampleI18nKey: "grammar_rule_comma_period_spacing_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 90,
  },
  {
    id: "collapseRepeatedSpaces",
    name: "Collapse repeated spaces",
    titleI18nKey: "grammar_rule_collapse_repeated_spaces",
    descriptionI18nKey: "grammar_rule_collapse_repeated_spaces_desc",
    exampleI18nKey: "grammar_rule_collapse_repeated_spaces_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 100,
  },
  {
    id: "trimSpaceBeforeLineBreak",
    name: "Trim spaces before line breaks",
    titleI18nKey: "grammar_rule_trim_space_before_line_break",
    descriptionI18nKey: "grammar_rule_trim_space_before_line_break_desc",
    exampleI18nKey: "grammar_rule_trim_space_before_line_break_example",
    languageScope: "all",
    safetyTier: "safe",
    defaultRollout: "on",
    recommended: true,
    priority: 110,
  },
  {
    id: "ellipsisShortcut",
    name: "Replace three dots with ellipsis",
    titleI18nKey: "grammar_rule_ellipsis_shortcut",
    descriptionI18nKey: "grammar_rule_ellipsis_shortcut_desc",
    exampleI18nKey: "grammar_rule_ellipsis_shortcut_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 130,
  },
  {
    id: "emdashShortcut",
    name: "Replace double hyphen with em dash",
    titleI18nKey: "grammar_rule_emdash_shortcut",
    descriptionI18nKey: "grammar_rule_emdash_shortcut_desc",
    exampleI18nKey: "grammar_rule_emdash_shortcut_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 131,
  },
  {
    id: "smartQuoteNormalization",
    name: "Normalize straight quotes",
    titleI18nKey: "grammar_rule_smart_quote_normalization",
    descriptionI18nKey: "grammar_rule_smart_quote_normalization_desc",
    exampleI18nKey: "grammar_rule_smart_quote_normalization_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 132,
  },
  {
    id: "frenchPunctuationSpacing",
    name: "French punctuation spacing",
    titleI18nKey: "grammar_rule_french_punctuation_spacing",
    descriptionI18nKey: "grammar_rule_french_punctuation_spacing_desc",
    exampleI18nKey: "grammar_rule_french_punctuation_spacing_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 133,
  },
  {
    id: "duplicatePunctuationCollapse",
    name: "Collapse accidental duplicate punctuation",
    titleI18nKey: "grammar_rule_duplicate_punctuation_collapse",
    descriptionI18nKey: "grammar_rule_duplicate_punctuation_collapse_desc",
    exampleI18nKey: "grammar_rule_duplicate_punctuation_collapse_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 134,
  },
  {
    id: "autoBracketClose",
    name: "Auto-close brackets and quotes",
    titleI18nKey: "grammar_rule_auto_bracket_close",
    descriptionI18nKey: "grammar_rule_auto_bracket_close_desc",
    exampleI18nKey: "grammar_rule_auto_bracket_close_example",
    languageScope: "all",
    safetyTier: "advanced",
    defaultRollout: "off",
    recommended: false,
    priority: 135,
    codeSafe: true,
  },
  // Portuguese Review checks (review/portuguese/).
  reviewOnly(
    "portugueseAccentParonyms",
    "Portuguese accent after articles and prepositions",
    "review_msg_pt_accent_paronym",
    310,
  ),
  reviewOnly(
    "portugueseConfusions",
    "Portuguese crase, por que and lookalike words",
    "review_msg_pt_confusions",
    311,
  ),
  reviewOnly(
    "portugueseContractions",
    "Portuguese preposition and article contractions",
    "review_msg_pt_contraction",
    312,
  ),
  reviewOnly(
    "portugueseNumberFormat",
    "Portuguese hours, ordinals, degrees and unit symbols",
    "review_msg_pt_number_format",
    313,
  ),
  reviewOnly(
    "portugueseTypographyStyle",
    "Portuguese multiplication sign and chemical formulas",
    "review_msg_pt_typography_style",
    314,
  ),
  reviewOnly(
    "portugueseCliticPlacement",
    "Portuguese pronoun before the verb after não, que and similar words",
    "review_msg_pt_proclisis",
    315,
  ),
  reviewOnly(
    "portugueseAO90",
    "Portuguese 1990 spelling agreement: prefixes, months and weekdays",
    "review_msg_pt_ao90",
    316,
  ),
  reviewOnly(
    "portugueseDates",
    "Portuguese dates that do not exist",
    "review_msg_pt_invalid_date",
    317,
  ),
  reviewOnly(
    "portugueseCommas",
    "Portuguese commas around asides and before a name",
    "review_msg_pt_comma",
    318,
  ),
  reviewOnly(
    "portugueseAgreement",
    "Portuguese agreement of verbs of existing, próprio and neuter pronouns",
    "review_msg_pt_agreement",
    319,
  ),
  // Spanish Review checks (review/spanish/).
  reviewOnly("spanishAccents", "Spanish written accents", "review_msg_spanish_accent", 166),
  reviewOnly("spanishConfusions", "Spanish confused words", "review_msg_spanish_confusion", 167),
  reviewOnly(
    "spanishTypography",
    "Spanish writing conventions",
    "review_msg_spanish_conjunction",
    168,
  ),
  reviewOnly(
    "spanishAgreement",
    "Spanish noun-phrase agreement",
    "review_msg_spanish_agreement",
    169,
  ),
  reviewOnly("spanishQuotes", "Spanish quotation marks", "review_msg_spanish_quotes", 170),
  reviewOnly("spanishTypographyStyle", "Spanish decimal comma", "review_msg_spanish_decimal", 171),
  // German-only Review checks (review/german/).
  reviewOnly("germanNounCasing", "German nouns are capitalized", "review_msg_german_noun_case", 37),
  reviewOnly(
    "germanPrepositionCase",
    "Case after German prepositions",
    "review_msg_german_preposition_case",
    160,
  ),
  reviewOnly("germanConfusedWords", "Confused German words", "review_msg_contextual_grammar", 150),
  reviewOnly(
    "germanAdjectiveForms",
    "German adjective endings",
    "review_msg_german_adjective_ending",
    155,
  ),
  reviewOnly(
    "germanSuspendedHyphen",
    "Hyphen on a shortened compound part",
    "review_msg_german_suspended_hyphen",
    120,
  ),
  reviewOnly(
    "germanAbbreviations",
    "German abbreviation dots and spaces",
    "review_msg_german_abbreviation",
    110,
  ),
  reviewOnly("germanQuotes", "German quotation marks", "review_msg_german_quotes", 100),
  reviewOnly(
    "germanAbbreviationSpacing",
    "Spaces in German abbreviations",
    "review_msg_german_abbreviation_spacing",
    105,
  ),
  reviewOnly("germanDates", "German dates", "review_msg_german_invalid_date", 115),
  reviewOnly(
    "germanCompounds",
    "German compounds and joined forms",
    "review_msg_closed_compound",
    125,
  ),
  reviewOnly("germanCommas", "Commas before German clauses", "review_msg_german_comma", 110),
  reviewOnly(
    "germanVerbAgreement",
    "German verb agreement",
    "review_msg_german_verb_agreement",
    120,
  ),
  reviewOnly(
    "germanArticleGender",
    "German article and noun gender",
    "review_msg_german_article_gender",
    158,
  ),
  reviewOnly(
    "germanQuestionMarks",
    "German questions ending in a full stop",
    "review_msg_german_question_mark",
    100,
  ),
  reviewOnly("germanNumbers", "German numbers in words", "review_msg_german_numbers", 120),
  reviewOnly(
    "germanStraightQuotes",
    "Straight quotes in German text",
    "review_msg_german_quotes",
    95,
  ),
  reviewOnly(
    "germanColloquial",
    "Colloquial German short forms",
    "review_msg_german_colloquial",
    60,
  ),
  reviewOnly(
    "germanRecommendedSpelling",
    "Duden-recommended German spellings",
    "review_msg_german_recommended_spelling",
    55,
  ),
  reviewOnly("germanTypography", "German typeset signs", "review_msg_german_typography", 40),
] as const;

export type CatalogRuleId = (typeof GRAMMAR_RULE_CATALOG)[number]["id"];

export const TYPING_RULE_CATALOG = GRAMMAR_RULE_CATALOG.filter(
  (entry): entry is GrammarRuleCatalogEntry & { id: GrammarRuleId } => entry.typing !== false,
);

export const TYPING_RULE_IDS = TYPING_RULE_CATALOG.map((entry) => entry.id);

export const GRAMMAR_RULE_IDS: CatalogRuleId[] = GRAMMAR_RULE_CATALOG.map((entry) => entry.id);

// Historical snapshots below are exact stored values, compared against real
// stored settings by the V4-V6 migrations. They may name retired rules
// ("neutralPunctuationPolicy"), so they are plain strings, never edited.
export const RECOMMENDED_V1_GRAMMAR_RULES: string[] = [
  "capitalizeSentenceStart",
  "capitalizeAfterLineBreak",
  "technicalTokenCompaction",
  "mathOperatorSpacing",
  "slashContextSpacing",
  "openingBracketSpacing",
  "closingBracketSpacing",
  "commaPeriodSpacing",
  "collapseRepeatedSpaces",
  "trimSpaceBeforeLineBreak",
  "neutralPunctuationPolicy",
];

// This is the pre-v3 recommended set (current users migrated by V5).
export const RECOMMENDED_V2_GRAMMAR_RULES: string[] = [
  ...RECOMMENDED_V1_GRAMMAR_RULES.slice(0, 2),
  "englishPronounICapitalization",
  "englishContractionNormalization",
  "englishTypoWhitelistCorrection",
  ...RECOMMENDED_V1_GRAMMAR_RULES.slice(2),
];

// Historical snapshots used by V6 migration. Keep these exact when the live catalog grows.
export const DEFAULT_V3_GRAMMAR_RULES: string[] = [
  "capitalizeSentenceStart",
  "capitalizeAfterLineBreak",
  "englishPronounICapitalization",
  "englishContractionNormalization",
  "englishTypoWhitelistCorrection",
  "doubleSpaceToPeriod",
  "englishModalOfCorrection",
  "englishYourWelcomeCorrection",
  "englishTheirThereBeVerb",
  "englishAlotCorrection",
  "englishPronounVerbWhitelistAgreement",
  "technicalTokenCompaction",
  "mathOperatorSpacing",
  "slashContextSpacing",
  "openingBracketSpacing",
  "closingBracketSpacing",
  "commaPeriodSpacing",
  "collapseRepeatedSpaces",
  "trimSpaceBeforeLineBreak",
  "neutralPunctuationPolicy",
];

export const DEFAULT_CURRENT_GRAMMAR_RULES: CatalogRuleId[] = TYPING_RULE_CATALOG.filter(
  (entry) => entry.defaultRollout === "on",
).map((entry) => entry.id);

const CODE_SAFE_RULE_IDS: ReadonlySet<string> = new Set(
  GRAMMAR_RULE_CATALOG.filter((entry) => entry.codeSafe).map((entry) => entry.id),
);

export function isCodeSafeGrammarRule(ruleId: string): boolean {
  return CODE_SAFE_RULE_IDS.has(ruleId);
}

/** Code mode keeps only the rules that never rewrite code. */
export function filterCodeSafeGrammarRules(ruleIds: readonly string[]): string[] {
  return ruleIds.filter(isCodeSafeGrammarRule);
}

export const RECOMMENDED_CURRENT_GRAMMAR_RULES: CatalogRuleId[] = TYPING_RULE_CATALOG.filter(
  (entry) => entry.recommended,
).map((entry) => entry.id);

/** Opt-in preset: the recommended rules plus language-aware quotes and punctuation. */
const TYPOGRAPHY_EXTRA_RULES: CatalogRuleId[] = [
  "smartQuoteNormalization",
  "frenchPunctuationSpacing",
  "ellipsisShortcut",
];
export const TYPOGRAPHY_GRAMMAR_RULES: CatalogRuleId[] = GRAMMAR_RULE_IDS.filter(
  (id) => RECOMMENDED_CURRENT_GRAMMAR_RULES.includes(id) || TYPOGRAPHY_EXTRA_RULES.includes(id),
);

const LEGACY_RULE_MAP: Record<string, CatalogRuleId[]> = {
  spacingRule: [
    "commaPeriodSpacing",
    "openingBracketSpacing",
    "closingBracketSpacing",
    "slashContextSpacing",
    "mathOperatorSpacing",
    "technicalTokenCompaction",
  ],
  capitalizeFirstLetter: ["capitalizeSentenceStart", "capitalizeAfterLineBreak"],
};

export function isCatalogRuleId(value: string): value is CatalogRuleId {
  return GRAMMAR_RULE_IDS.includes(value as CatalogRuleId);
}

export function normalizeGrammarRuleSelection(selection: unknown): CatalogRuleId[] {
  const selected = Array.isArray(selection) ? selection.map((item) => String(item)) : [];
  const expanded: CatalogRuleId[] = [];

  for (const ruleId of selected) {
    if (isCatalogRuleId(ruleId)) {
      expanded.push(ruleId);
      continue;
    }

    const mapped = LEGACY_RULE_MAP[ruleId];
    if (mapped) {
      expanded.push(...mapped);
    }
  }

  const unique = new Set(expanded);
  return TYPING_RULE_IDS.filter((id) => unique.has(id));
}
