export const STATS_SCHEMA_VERSION = 2;

export const DONATION_MILESTONE_HOURS = [1, 5, 10, 25];
export const DONATION_FIRST_VALUE_ACCEPTS = 20;
export const DONATION_FIRST_VALUE_MINUTES = 15;
export const DONATION_PROMPT_COOLDOWN_DAYS = 7;
export const DONATION_SNOOZE_DAYS = 30;

export const WEEKLY_RECAP_REVEAL_HOUR = 8;

export const TYPING_CHARACTERS_PER_MINUTE = 240;
export const ACCEPTANCE_BONUS_SECONDS = 0.8;
export const EQUIVALENT_TASK_MINUTES = 5;

export const MAX_DAILY_BUCKETS = 400;
