import { expect, test } from "bun:test";
import { englishInitialSound } from "../../src/core/domain/grammar/implementations/helpers/EnglishInitialSound";

const CASES: Record<"vowel" | "consonant" | "either", string[]> = {
  vowel: [
    "apple",
    "Orange",
    "idea",
    // Silent h.
    "hour",
    "hourglass",
    "honest",
    "honorable",
    "honourable",
    "heiress",
    // "un-" as a negation, and u said "uh".
    "unimportant",
    "uninstall",
    "unidentified",
    "unidiomatic",
    "unissued",
    "unitemized",
    "unironic",
    "unusual",
    "unaware",
    "umpire",
    "upgrade",
    "usher",
    "utter",
    "utmost",
    "urgent",
    "Uruguayan",
    "Uber",
    "onerous",
    "Euler",
    // Read letter by letter.
    "A",
    "F",
    "x",
    "FBI",
    "HDMI",
    "MRI",
    "NDA",
    "SSD",
    "XML",
    "RSVP",
    "MP",
    "MP4",
    "HTTPs",
    "SDKs",
    "LLMs",
    "iPad",
    "eBook",
    "IKEA",
    "OPEC",
  ],
  consonant: [
    "book",
    "unidirectional",
    "unison",
    "united",
    "Garden",
    "yellow",
    "university",
    "Unix",
    "uniform",
    "unanimous",
    "user",
    "usual",
    "usage",
    "utensil",
    "Utah",
    "uranium",
    "urine",
    "ubiquitous",
    "Ukrainian",
    "Ugandan",
    "udev",
    "euro",
    "European",
    "eulogy",
    "ewe",
    "one",
    "oneself",
    "OneDrive",
    "once",
    "honey",
    "house",
    "hotel",
    // Read letter by letter, or said as a word starting with a consonant.
    "U",
    "B",
    "USB",
    "UNESCO",
    "UFO",
    "GPU",
    "DVD",
    "GIF",
    "TED",
    "McDonald",
  ],
  either: [
    "SQL",
    "URL",
    "LED",
    "FAQ",
    "herb",
    "Herbal",
    "historic",
    "ukulele",
    "NASA",
    "RAM",
    "SIM",
    "HOUR",
    "8",
    "11th",
    "",
    "-",
    "élan",
  ],
};

for (const [sound, words] of Object.entries(CASES)) {
  for (const word of words) {
    test(`${JSON.stringify(word)} starts with a ${sound} sound`, () =>
      expect(englishInitialSound(word)).toBe(sound as "vowel"));
  }
}
