import { describe, expect, test } from "bun:test";
import { detectReviewDiagnostics } from "../../src/core/domain/grammar/review/reviewDiagnostics";
import { REVIEW_SUPPORTED_RULE_IDS } from "../../src/core/domain/grammar/review/reviewCatalog";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";

const RULES = new Set([
  "englishPhraseCorrections",
  "englishClosedCompounds",
  "englishContextualCompounds",
  "englishCountability",
  "englishSubjectVerbAgreement",
  "englishAuxiliaryBaseVerb",
  "englishVerbComplements",
  "englishItsContext",
  "stylePhrasing",
  "styleRedundancy",
]);
function findings(text: string) {
  return detectReviewDiagnostics(
    { id: "idioms4", text, scope: { start: 0, end: text.length }, protectedRanges: [] },
    {
      lang: "en_US",
      enabledRules: [...REVIEW_SUPPORTED_RULE_IDS],
      userDictionary: [],
      insertSpaceAfterAutocomplete: true,
    },
  ).diagnostics.filter((d) => RULES.has(d.ruleId));
}
const repairsOf = (text: string) =>
  findings(text).flatMap((d) => d.alternatives.map((a) => applyEdits(text, a.edits)));

// [typed, one repaired text the writer can pick]
const repairs: [string, string][] = [
  ["They hunted for a cure against the fever.", "They hunted for a cure for the fever."],
  ["The ointment cures against rashes.", "The ointment cures for rashes."],
  ["The coating is robust against damages.", "The coating is robust against damage."],
  ["The scanner detects damages on the hull.", "The scanner detects damage on the hull."],
  ["Some kinds of damages of bridges go unseen.", "Some kinds of damage of bridges go unseen."],
  ["Who reads paper maps in this day in age?", "Who reads paper maps in this day and age?"],
  ["Nobody faxes at this day and age.", "Nobody faxes in this day and age."],
  ["These days and age, kids text.", "In this day and age, kids text."],
  ["Bread is cheap in these days and ages.", "Bread is cheap in this day and age."],
  ["Phones are vital is this day and age.", "Phones are vital in this day and age."],
  ["Ink is rare this day of age.", "Ink is rare in this day and age."],
  ["She left despite it was raining.", "She left although it was raining."],
  ["We won despite we were tired.", "We won despite the fact that we were tired."],
  ["The game went on despite of the storm.", "The game went on despite the storm."],
  ["I did several mistakes in the essay.", "I made several mistakes in the essay."],
  ["Students often do this mistake.", "Students often make this mistake."],
  ["We have done some mistakes before.", "We have made some mistakes before."],
  ["She was doing the same mistake twice.", "She was making the same mistake twice."],
  ["It was nobody elses fault.", "It was nobody else's fault."],
  ["Is this someone elses coat?", "Is this someone else's coat?"],
  ["All passed with the except of Tom.", "All passed with the exception of Tom."],
  [
    "All rooms, with the rare except of one, were clean.",
    "All rooms, with the rare exception of one, were clean.",
  ],
  ["Everything burned except of the barn.", "Everything burned except for the barn."],
  ["The climber fell 15 feet below and broke a leg.", "The climber fell 15 feet and broke a leg."],
  ["The crate fell ten meters below.", "The crate fell ten meters."],
  ["Far be it for me to judge.", "Far be it from me to judge."],
  ["She was always fascinated about trains.", "She was always fascinated by trains."],
  ["I am fed up of the noise.", "I am fed up with the noise."],
  ["My fellow coworkers like tea.", "My coworkers like tea."],
  ["He thanked a fellow co-author.", "He thanked a co-author."],
  ["Keep a first aid kid in the car.", "Keep a first aid kit in the car."],
  ["The shop sells tool kids.", "The shop sells tool kits."],
  ["The scooter is neither fish nor foul.", "The scooter is neither fish nor fowl."],
  ["It became a full-fleshed product.", "It became a full-fledged product."],
  ["He is a full pledged member now.", "He is a full fledged member now."],
  ["The plan is fully fledged out.", "The plan is fully fleshed out."],
  ["We will fledge out the details.", "We will flesh out the details."],
  ["The draft has a fully fleshed outline.", "The draft has a fully fledged outline."],
  ["They offer lessons for free of charge.", "They offer lessons free of charge."],
  ["We got a card fro grandma.", "We got a card for grandma."],
  ["He quit for personal reason.", "He quit for personal reasons."],
  ["They moved for same reason.", "They moved for the same reason."],
  ["I read the book for third time.", "I read the book for the third time."],
  ["It crashed for umpteenth time today.", "It crashed for the umpteenth time today."],
  ["Entry is fee for children.", "Entry is free for children."],
  ["The museum was totally fee.", "The museum was totally free."],
  ["A cousin of me lives there.", "A cousin of mine lives there."],
  ["Two friends of them came along.", "Two friends of theirs came along."],
  ["The jar was full to the brim of honey.", "The jar was full to the brim with honey."],
  ["The hall was filled to the brim of fans.", "The hall was filled to the brim with fans."],
  ["We finally got pass the gate.", "We finally got past the gate."],
  ["The ball went pass the keeper.", "The ball went past the keeper."],
  ["My keys became missing again.", "My keys went missing again."],
  ["Socks often become missing.", "Socks often go missing."],
  ["She went so far to call the mayor.", "She went so far as to call the mayor."],
  ["The laptop won't go into sleep.", "The laptop won't go to sleep."],
  ["The tribes went on war with each other.", "The tribes went to war with each other."],
  ["I'm not good in chess.", "I'm not good at chess."],
  ["She is very good in drawing faces.", "She is very good at drawing faces."],
  ["He grabbed a hand full of nuts.", "He grabbed a handful of nuts."],
  ["Hand full of coins, he paid.", "Handful of coins, he paid."],
  ["We need a handful of more chairs.", "We need a handful more chairs."],
  ["I had hard time sleeping.", "I had a hard time sleeping."],
  ["She is having extremely hard time.", "She is having an extremely hard time."],
  ["Has they left yet?", "Have they left yet?"],
  ["Halo Maria, how are you?", "Hello Maria, how are you?"],
  ["Halo, everyone.", "Hello, everyone."],
  ["I here by declare the fair open.", "I hereby declare the fair open."],
  ["How does it compares to tea?", "How does it compare to tea?"],
  ["The guide shows how install the printer.", "The guide shows how to install the printer."],
  ["Ask me how fix it.", "Ask me how to fix it."],
  ["If I would've known, I'd have come.", "If I had known, I'd have come."],
  ["If she had of seen it, she'd laugh.", "If she had seen it, she'd laugh."],
  ["We implemented search into the app.", "We implemented search in the app."],
  ["It was an in depth talk.", "It was an in-depth talk."],
  ["Nurses are the most in demand workers.", "Nurses are the most in-demand workers."],
  ["I am in favour waiting a day.", "I am in favour of waiting a day."],
  ["The shop has them on stock.", "The shop has them in stock."],
  ["The bread is back on stock.", "The bread is back in stock."],
  ["We leave in two days from now.", "We leave two days from now."],
  ["He is interested about birds.", "He is interested in birds."],
  ["Are you interested on joining?", "Are you interested in joining?"],
  ["I'm tired, its late for me.", "I'm tired, it's late for me."],
  ["It looks like that the bus is late.", "It looks like the bus is late."],
  ["It seems like that nobody came.", "It seems like nobody came."],
  ["I think I would be a pity to miss it.", "I think it would be a pity to miss it."],
  ["He was jealous from his brother.", "He was jealous of his brother."],
  ["We jumped a gun on that one.", "We jumped the gun on that one."],
  ["Don't jump the guns here.", "Don't jump the gun here."],
  ["The war led rise to new borders.", "The war gave rise to new borders."],
  ["Heat leads rise to storms.", "Heat gives rise to storms."],
  ["Fans left in drones after the loss.", "Fans left in droves after the loss."],
  ["Click the left hand side menu.", "Click the left-hand side menu."],
  ["It sits in the right hand corner.", "It sits in the right-hand corner."],
  ["She nodded, like wise, and left.", "She nodded, likewise, and left."],
  ["It's little known fact that owls nap.", "It's a little known fact that owls nap."],
  ["I bought it long time ago.", "I bought it a long time ago."],
  ["Long time ago, we met.", "A long time ago, we met."],
  ["They look their noses down at us.", "They look down their noses at us."],
  ["She looked her nose down on him.", "She looked down her nose on him."],
  ["We dug under the hood of the report.", "We looked under the hood of the report."],
];

// Correct forms and look-alikes that must stay clean.
const silent = [
  "Exercise protects against the flu.",
  "The court awarded damages to the tenant.",
  "The storm damages roofs every year.",
  "Tablets are common in this day and age.",
  "The phone is slow for this day and age.",
  "Despite it all, we laughed.",
  "Despite the rain, we walked.",
  "Where did the mistake come from?",
  "Did that mistake cost us?",
  "Is it someone else's coat?",
  "Everyone came except Tom.",
  "It works, except of course on Sundays.",
  "Everything burned except the barn.",
  "Nurses are in demand these days.",
  "Coders are more in demand today.",
  "The stone fell 20 feet below the bridge deck.",
  "Far be it from me to judge.",
  "She is fascinated by trains.",
  "I am fed up with the noise.",
  "My coworkers like tea.",
  "The kids played in the yard.",
  "The flag swung to and fro.",
  "He quit for no other reason than boredom.",
  "For some reason it failed.",
  "This is for first-time visitors.",
  "The discount is for first time buyers.",
  "There is fee for parking.",
  "The fee is small.",
  "She is a friend of mine.",
  "A picture of me hangs there.",
  "The pot was full to the brim with soup.",
  "Water reached the brim of the cup.",
  "Let us go pass the time with cards.",
  "Several people have become missing persons.",
  "Children who become missing children are rare.",
  "The road goes so far to the north.",
  "The laptop goes into sleep mode.",
  "They went to war with Spain.",
  "The plan looks good in theory.",
  "She looks very good in red.",
  "It is not good in the long run.",
  "He grabbed a handful of nuts.",
  "Her hand full of rings caught the light.",
  "We hired a handful of more experienced staff.",
  "We had some hard time to spare.",
  "Projects have hard time limits.",
  "Has it ended?",
  "What has you so busy?",
  "Halo is a classic game.",
  "A halo of light surrounded her.",
  "How does it compare to tea?",
  "How will you fix it?",
  "How come the door is open?",
  "How long the trip takes depends on traffic.",
  "Tell me how people react.",
  "The menu shows how form fields are saved.",
  "If you would have a look, I'd be glad.",
  "The team implements Into for the type.",
  "They covered the topic in depth.",
  "Nurses are more in demand than ever.",
  "I am in favour of waiting.",
  "The shoes are in stock.",
  "Prices rose on stock markets.",
  "We leave two days from now.",
  "I am interested in birds.",
  "Are you interested at all?",
  "The cat licked its paw.",
  "The firm and its staff agreed.",
  "It looks like that comes later.",
  "It looks like that would work.",
  "I think I would be a good fit.",
  "She was jealous of her brother.",
  "They stayed jealous from within.",
  "We jumped the gun on that one.",
  "The war gave rise to new borders.",
  "Fans left in droves.",
  "Drones flew in from the coast.",
  "Click the left-hand side menu.",
  "She raised her right hand.",
  "Like wise owls, they waited.",
  "It's a little-known fact.",
  "It happened a long time ago.",
  "It happened a really long time ago.",
  "They look down their noses at us.",
  "We looked under the hood.",
  "Bring a first aid kit.",
  "Don't go in, it's a fully fleshed out plan.",
  "It is a full-fledged product.",
  "We offer lessons free of charge.",
  "We offer free of charge delivery.",
  "I read the book for the third time.",
];

describe("Review idioms4: fixed expressions and their context", () => {
  test.each(repairs)("%s", (typed, repaired) => {
    expect(repairsOf(typed)).toContain(repaired);
  });

  test.each(silent.map((text) => [text]))("stays silent: %s", (text) => {
    expect(findings(text).map((d) => d.ruleId)).toEqual([]);
  });

  test("choices are offered when the writer must pick", () => {
    const [finding] = findings("She left despite it was raining.");
    expect(finding.requiresChoice).toBe(true);
  });

  test("opinions stay opt-in style advice", () => {
    expect(findings("We dug under the hood.").map((d) => d.ruleId)).toEqual(["stylePhrasing"]);
    expect(findings("My fellow coworkers like tea.").map((d) => d.ruleId)).toEqual([
      "styleRedundancy",
    ]);
  });
});
