import { expect, test } from "bun:test";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";
import { ALL_RULES, scan, scanResult } from "./reviewHarness";

// English checks added in the ninth LanguageTool parity wave: english/realWordFrames.ts and
// english/clauseGaps.ts. All sentences are our own. Every supported rule runs.
const review = (text: string) =>
  scan(text, { enabledRules: ALL_RULES }).filter(
    (d) => d.category !== "style" && d.ruleId !== "typographicQuotes",
  );

const REPAIRS: [string, string][] = [
  ["I complaint about the noise every night.", "I complain about the noise every night."],
  ["We life in a small town.", "We live in a small town."],
  ["He departures at noon each day.", "He departs at noon each day."],
  ["She deliveries the mail on foot.", "She delivers the mail on foot."],
  ["He threats me with a lawsuit.", "He threatens me with a lawsuit."],
  ["I left early cause I was tired.", "I left early because I was tired."],
  ["The bug was worse than I though.", "The bug was worse than I thought."],
  ["I'm bit tired today.", "I'm a bit tired today."],
  ["I apologies for the delay.", "I apologize for the delay."],
  ["We would priorities the backlog.", "We would prioritize the backlog."],
  ["I owe you an apologize.", "I owe you an apology."],
  ["He helped carrying the boxes.", "He helped to carry the boxes."],
  ["I'm used to run every morning.", "I'm used to running every morning."],
  ["She is accustomed to speak French.", "She is accustomed to speaking French."],
  ["She wants you to goes there.", "She wants you to go there."],
  ["The door must be replaces soon.", "The door must be replaced soon."],
  ["He will be have a party.", "He will have a party."],
  ["They buy this state of art equipment.", "They buy this state-of-the-art equipment."],
  ["We drove back and fourth all day.", "We drove back and forth all day."],
  ["We meet on a weekly base.", "We meet on a weekly basis."],
  ["Remove the line if is too long.", "Remove the line if it is too long."],
  ["The build broke since was merged late.", "The build broke since it was merged late."],
  ["Call me if should have questions.", "Call me if you should have questions."],
  ["Tell me if need anything else.", "Tell me if you need anything else."],
  ["It failed in either the client nor the proxy.", "It failed in either the client or the proxy."],
  ["I want wanted to thank you.", "I want to thank you."],
  ["She was going go home.", "She was going home."],
  ["The value must be greater that 10.", "The value must be greater than 10."],
  ["The price fell gradually there after.", "The price fell gradually thereafter."],
  ["We walked passed the old mill.", "We walked past the old mill."],
  ["I pic the blue one.", "I pick the blue one."],
  ["The app dose not start.", "The app does not start."],
  ["You can reach it trough the side door.", "You can reach it through the side door."],
  ["She is of Irish decent.", "She is of Irish descent."],
  ["It is my firm believe that we can win.", "It is my firm belief that we can win."],
  ["We met on Friday nigh.", "We met on Friday night."],
  ["I have not slept sine Monday.", "I have not slept since Monday."],
  ["The bus came too son.", "The bus came too soon."],
  ["We can ether walk or take the bus.", "We can either walk or take the bus."],
  ["Hoe does this tool work?", "How does this tool work?"],
  ["She sat besides me.", "She sat beside me."],
  ["He is batter than me at chess.", "He is better than me at chess."],
  ["I have bin there twice.", "I have been there twice."],
  ["I most be dreaming.", "I must be dreaming."],
  ["The kids are being testes today.", "The kids are being tested today."],
  ["The shop is ten minuets away.", "The shop is ten minutes away."],
  ["She is in vacation until May.", "She is on vacation until May."],
  ["Their has to be a fix.", "There has to be a fix."],
  ["Deer Maria, thanks for the card.", "Dear Maria, thanks for the card."],
  ["In principal, I agree with you.", "In principle, I agree with you."],
  ["We stayed over night at a hotel.", "We stayed overnight at a hotel."],
  ["The patch is about to released.", "The patch is about to be released."],
  ["I asked her too clarify it.", "I asked her to clarify it."],
  ["The route of the problem is in the parser.", "The root of the problem is in the parser."],
  ["We need to take case of it.", "We need to take care of it."],
  ["It is a blood born virus.", "It is a bloodborne virus."],
  ["All of sudden it stopped.", "All of a sudden it stopped."],
  ["The patch does not required a restart.", "The patch does not require a restart."],
  ["Pricing will based on demand.", "Pricing will base on demand."],
  ["Can someone wrote the code?", "Can someone write the code?"],
  ["Can Anna sent it to me?", "Can Anna send it to me?"],
  ["I think it make sense.", "I think it makes sense."],
  ["I hope it win the cup.", "I hope it wins the cup."],
  ["If the US try to help, it works.", "If the US tries to help, it works."],
  ["It reads the file and print the result.", "It reads the file and prints the result."],
  ["The coach told them run the drill.", "The coach told them to run the drill."],
  ["I'll be able come tomorrow.", "I'll be able to come tomorrow."],
  ["She explained me the plan.", "She explained to me the plan."],
  ["We cannot afford spending more.", "We cannot afford to spend more."],
  ["It not required here.", "It is not required here."],
  ["We have not including tax.", "We have not included tax."],
  ["It did been fixed.", "It had been fixed."],
  ["There is has been a delay.", "There has been a delay."],
  ["I am surprise that it worked.", "I am surprised that it worked."],
  ["Apps that use to be free cost money.", "Apps that used to be free cost money."],
  ["Is he suppose to win?", "Is he supposed to win?"],
  ["As you maybe aware, it is late.", "As you may be aware, it is late."],
  ["We are thank full for it.", "We are thankful for it."],
  ["I have 1 days left.", "I have 1 day left."],
  ["We added a lot features.", "We added a lot of features."],
  ["It is the worlds best tea.", "It is the world's best tea."],
  ["It is a simply solution.", "It is a simple solution."],
  ["We toured the corporate headquarter.", "We toured the corporate headquarters."],
  ["Is there any chances of rain?", "Are there any chances of rain?"],
  ["Here the specs of the phone.", "Here are the specs of the phone."],
  ["This is a must read book.", "This is a must-read book."],
  ["She stressed the important of sleep.", "She stressed the importance of sleep."],
  ["It dates from the 19 century.", "It dates from the 19th century."],
  ["It caused tension between he and his boss.", "It caused tension between him and his boss."],
  ["It is hard for we parents.", "It is hard for us parents."],
  ["Tell me if there anyone else.", "Tell me if there is anyone else."],
  ["The reports of the outage is wrong.", "The reports of the outage are wrong."],
  ["How is your new shoes?", "How are your new shoes?"],
  ["Some time I read at night.", "Sometimes I read at night."],
  ["There isn't anyway to fix it.", "There isn't any way to fix it."],
  ["I have no been there.", "I have not been there."],
  ["Do you one to come?", "Do you want to come?"],
  ["Please harry up!", "Please hurry up!"],
  ["Open the attach file.", "Open the attached file."],
  ["Please high light the words.", "Please highlight the words."],
  ["I look forward of the trip.", "I look forward to the trip."],
  ["Would it possible to call?", "Would it be possible to call?"],
  ["And the are going home.", "And they are going home."],
  ["That car is one of the kind.", "That car is one of a kind."],
  ["This is the most common errors.", "This is the most common error."],
  ["This is most popular game.", "This is the most popular game."],
  ["This make no sense.", "This makes no sense."],
  ["I hope that look nice.", "I hope that looks nice."],
  ["Peter did went home.", "Peter did go home."],
  ["Sadly, one of our client decided to go.", "Sadly, one of our clients decided to go."],
  ["They sell items of all kind of shapes.", "They sell items of all kinds of shapes."],
  ["The shop has a collection of book.", "The shop has a collection of books."],
  ["We are all animal.", "We are all animals."],
  ["There are a few computer to test.", "There are a few computers to test."],
  ["Tom has already complaint about it.", "Tom has already complained about it."],
  ["He is bagging for mercy.", "He is begging for mercy."],
  ["My begs are full.", "My bags are full."],
  ["I don't now what to do.", "I don't know what to do."],
  ["Let me now if it works.", "Let me know if it works."],
  ["We never disappoint they.", "We never disappoint them."],
  ["I like to help other.", "I like to help others."],
  ["We went shopping an also dancing.", "We went shopping and also dancing."],
  ["His a good friend.", "He's a good friend."],
  ["She was 12 hears old.", "She was 12 years old."],
  ["We lived there for tree years.", "We lived there for three years."],
  ["It sees to happen daily.", "It seems to happen daily."],
  [
    "Toward the end, otherwise know as the finale.",
    "Toward the end, otherwise known as the finale.",
  ],
  ["I have not bean there.", "I have not been there."],
  ["It's a really god show.", "It's a really good show."],
  ["I herd of a new band.", "I heard of a new band."],
  ["That's quiet a list.", "That's quite a list."],
  ["He is in a football teem.", "He is in a football team."],
  ["Houses for sell here.", "Houses for sale here."],
  ["We need to breath fresh air.", "We need to breathe fresh air."],
  ["He has a deadly decease.", "He has a deadly disease."],
  ["Are you adverse to swimming?", "Are you averse to swimming?"],
  ["We need a through review.", "We need a thorough review."],
  ["I was wandering if you could help.", "I was wondering if you could help."],
  ["This is very knew to me.", "This is very new to me."],
  ["This seams wrong to me.", "This seems wrong to me."],
  ["That is not jet decided.", "That is not yet decided."],
  ["Have a niece holiday!", "Have a nice holiday!"],
  ["I would rater stay.", "I would rather stay."],
  ["He road a horse.", "He rode a horse."],
  ["It will he ready soon.", "It will be ready soon."],
  ["I'm unable tor find it.", "I'm unable to find it."],
  ["I cannot effort a car.", "I cannot afford a car."],
  ["It does not mater.", "It does not matter."],
  ["I don't wan to go.", "I don't want to go."],
  ["You seen to know it.", "You seem to know it."],
  ["The class had already begone.", "The class had already begun."],
  ["They set a dangerous precedence.", "They set a dangerous precedent."],
  ["He has been in a comma for days.", "He has been in a coma for days."],
  ["Do not take it for granite.", "Do not take it for granted."],
  ["If it rains, than we stay.", "If it rains, then we stay."],
  ["This should knot happen.", "This should not happen."],
  ["She did it in a hastily manner.", "She did it in a hasty manner."],
  ["It was not possible the be finished.", "It was not possible to be finished."],
  ["Let is know soon.", "Let us know soon."],
  ["It is the tallest tower in the wold.", "It is the tallest tower in the world."],
  ["The wine is red nut white.", "The wine is red not white."],
  ["I will drop by an see what you need.", "I will drop by and see what you need."],
  ["He said he company has grown.", "He said the company has grown."],
  ["The duvet envelopes her.", "The duvet envelops her."],
  ["We evaluated out method today.", "We evaluated our method today."],
];

test.each(REPAIRS)("repairs %s", (input, expected) => {
  const found = review(input);
  expect({ input, count: found.length }).toEqual({ input, count: 1 });
  expect(applyEdits(input, found[0].alternatives[0].edits)).toBe(expected);
  expect(review(expected)).toEqual([]);
});

test("every frame compiles and runs on the repair sentences", () => {
  const text = REPAIRS.map(([input]) => input).join(" ");
  expect(scanResult(text, { enabledRules: ALL_RULES }).coverage.failedRules).toEqual([]);
});

test.each([
  "We developers need better tools.",
  "It is a good cause they support.",
  "Smoking can cause the problem.",
  "Things that cause our pain are many.",
  "I do though.",
  "He though is the best.",
  "Even though about half came, we won.",
  "The dog bit me yesterday.",
  "I got bit by a dog.",
  "Every bit as good as the old one.",
  "Bit rot slowly ruins old disks.",
  "I can't help laughing at it.",
  "I need help getting this to work.",
  "It helps knowing the answer.",
  "The tool is used to run tests.",
  "They are used to define the scope.",
  "We are used to hard work.",
  "The file it points to exists.",
  "Set the flag to disabled.",
  "It will be done soon.",
  "Should it be, please call me.",
  "Wear Type I life jackets.",
  "The state of art in the city is poor.",
  "Do it if need be.",
  "I stayed because will power is all I had.",
  "Neither the client nor the proxy works.",
  "It is not the case either that A holds nor that B holds.",
  "He had had enough.",
  "The test tested nothing.",
  "No one I know knows the way.",
  "We need to connect connected devices.",
  "He is locking locks.",
  "It is better that we leave now.",
  "We got there after lunch.",
  "I'm making trough planters for the yard.",
  "Ether was used as a solvent or a fuel.",
  "On an off day, we rest.",
  "The students too realize it.",
  "The Route of the Problem is a song.",
  "Meters stop working over time.",
  "A dose not exceeding 5 mg is safe.",
  "He sat beside the fire.",
  "We lay in the trough the whole day.",
  "They are decent people.",
  "Water is nigh on impossible to find.",
  "The bin is full.",
  "It is the most beautiful place.",
  "The tests sent to the lab are back.",
  "I set it to disabled.",
  "Don't forget the keys.",
  "The free will made him strong.",
  "A watering can leaked on the floor.",
  "They would found a new school.",
  "How would suggesting people work?",
  "Would this pricing change?",
  "Will Smith played the lead.",
  "Let it go now.",
  "Make it work for us.",
  "It is vital that it run on time.",
  "The United States upset the champions.",
  "She makes us laugh and cry.",
  "He wants you to stay and help.",
  "I told them stories about it.",
  "Jobs are hard come by.",
  "Any feedback would be great thank you.",
  "The tool I use to write code is free.",
  "All you do is worry about it.",
  "There is interest in the plan.",
  "A delight full of surprises.",
  "No one cares about it.",
  "He is twenty one years old.",
  "We watched season one specials.",
  "I had one years ago.",
  "She liked it a lot today.",
  "It has a hugely dominant market share.",
  "Is there any news?",
  "Over there is a shop.",
  "Here the road ends.",
  "Here the water is deep.",
  "Like we developers do, they test.",
  "Ten megabytes of disk space is needed.",
  "The earliest record of birds in the areas of Peru is old.",
  "The are has fallen out of use.",
  "A good bit of luck.",
  "I look forward to the trip.",
  "This is most likely wrong.",
  "It has no signed contract.",
  "This make of car is rare.",
  "That sound was loud.",
  "This felt so wrong.",
  "One of the best is here.",
  "I like the best of all time.",
  "A range of motion is normal.",
  "We are all set.",
  "There are many people here.",
  "There are 101 file sharing tools.",
  "A couple of model predicted values.",
  "I beg of you.",
  "Those standing were all men.",
  "I still don't now.",
  "Each other is fine.",
  "Change the name to Other.",
  "They are quiet a lot of times.",
  "It is not the be all end all.",
  "The tree grew tall.",
  "I'm afraid the pleas fall on deaf ears.",
  "The road is long.",
  "He is not a whit wiser.",
  "Her breath smelled of mint.",
  "The repo is old.",
  "Do you know which envelopes her mother wants?",
  "It is an arts and crafts fair.",
  "He said he first had to leave.",
  "We sorted out names today.",
  "The pecan nut cake is sweet.",
])("leaves %s", (text) => {
  expect(review(text).map((d) => d.original)).toEqual([]);
});

test.each([
  ["We need to obtain visas.", "We need to get visas."],
  ["The majority of users agree.", "Most users agree."],
  ["Not many people know this.", "Few people know this."],
  ["Can you help me to find it?", "Can you help me find it?"],
])("plain-English option: %s", (input, expected) => {
  const found = scan(input, { enabledRules: ALL_RULES }).filter(
    (d) => d.ruleId === "stylePhrasing",
  );
  expect(found).toHaveLength(1);
  expect(applyEdits(input, found[0].alternatives[0].edits)).toBe(expected);
  // Off by default.
  expect(scan(input).filter((d) => d.ruleId === "stylePhrasing")).toEqual([]);
});
