import { expect, test } from "bun:test";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";
import { ALL_RULES, scan, slowestChunkMs } from "./reviewHarness";

// English checks added in the ninth LanguageTool parity wave: english/realWordFrames.ts and
// english/clauseGaps.ts. All sentences are our own. Every supported rule runs.
const review = (text: string) =>
  scan(text, { enabledRules: ALL_RULES }).filter(
    (d) => d.category !== "style" && d.ruleId !== "typographicQuotes",
  );

test.each([
  ["I complaint about the noise every night.", "I complain about the noise every night."],
  ["We life in a small town.", "We live in a small town."],
  ["He departures at noon each day.", "He departs at noon each day."],
  ["She deliveries the mail on foot.", "She delivers the mail on foot."],
  ["He threats me with a lawsuit.", "He threatens me with a lawsuit."],
  ["I left early cause I was tired.", "I left early because I was tired."],
  ["The bug was worse than I though.", "The bug was worse than I thought."],
  ["I'm bit tired today.", "I'm a bit tired today."],
  ["I apologies for the delay.", "I apologize for the delay."],
  ["We would priorities the backlog.", "We would prioritize the backlog."],
  ["I owe you an apologize.", "I owe you an apology."],
  ["He helped carrying the boxes.", "He helped to carry the boxes."],
  ["I'm used to run every morning.", "I'm used to running every morning."],
  ["She is accustomed to speak French.", "She is accustomed to speaking French."],
  ["She wants you to goes there.", "She wants you to go there."],
  ["The door must be replaces soon.", "The door must be replaced soon."],
  ["He will be have a party.", "He will have a party."],
  ["They buy this state of art equipment.", "They buy this state-of-the-art equipment."],
  ["We drove back and fourth all day.", "We drove back and forth all day."],
  ["We meet on a weekly base.", "We meet on a weekly basis."],
  ["Remove the line if is too long.", "Remove the line if it is too long."],
  ["The build broke since was merged late.", "The build broke since it was merged late."],
  ["Call me if should have questions.", "Call me if you should have questions."],
  ["Tell me if need anything else.", "Tell me if you need anything else."],
  ["It failed in either the client nor the proxy.", "It failed in either the client or the proxy."],
  ["I want wanted to thank you.", "I want to thank you."],
  ["She was going go home.", "She was going home."],
  ["The value must be greater that 10.", "The value must be greater than 10."],
  ["The price fell gradually there after.", "The price fell gradually thereafter."],
  ["We walked passed the old mill.", "We walked past the old mill."],
  ["I pic the blue one.", "I pick the blue one."],
  ["The app dose not start.", "The app does not start."],
  ["You can reach it trough the side door.", "You can reach it through the side door."],
  ["She is of Irish decent.", "She is of Irish descent."],
  ["It is my firm believe that we can win.", "It is my firm belief that we can win."],
  ["We met on Friday nigh.", "We met on Friday night."],
  ["I have not slept sine Monday.", "I have not slept since Monday."],
  ["The bus came too son.", "The bus came too soon."],
  ["We can ether walk or take the bus.", "We can either walk or take the bus."],
  ["Hoe does this tool work?", "How does this tool work?"],
  ["She sat besides me.", "She sat beside me."],
  ["He is batter than me at chess.", "He is better than me at chess."],
  ["I have bin there twice.", "I have been there twice."],
  ["I most be dreaming.", "I must be dreaming."],
  ["The kids are being testes today.", "The kids are being tested today."],
  ["The shop is ten minuets away.", "The shop is ten minutes away."],
  ["She is in vacation until May.", "She is on vacation until May."],
  ["Their has to be a fix.", "There has to be a fix."],
  ["Deer Maria, thanks for the card.", "Dear Maria, thanks for the card."],
  ["In principal, I agree with you.", "In principle, I agree with you."],
  ["We stayed over night at a hotel.", "We stayed overnight at a hotel."],
  ["The patch is about to released.", "The patch is about to be released."],
  ["I asked her too clarify it.", "I asked her to clarify it."],
  ["The route of the problem is in the parser.", "The root of the problem is in the parser."],
  ["We need to take case of it.", "We need to take care of it."],
  ["It is a blood born virus.", "It is a bloodborne virus."],
  ["All of sudden it stopped.", "All of a sudden it stopped."],
  ["The patch does not required a restart.", "The patch does not require a restart."],
  ["Pricing will based on demand.", "Pricing will base on demand."],
  ["Can someone wrote the code?", "Can someone write the code?"],
  ["Can Anna sent it to me?", "Can Anna send it to me?"],
  ["I think it make sense.", "I think it makes sense."],
  ["I hope it win the cup.", "I hope it wins the cup."],
  ["If the US try to help, it works.", "If the US tries to help, it works."],
  ["It reads the file and print the result.", "It reads the file and prints the result."],
  ["The coach told them run the drill.", "The coach told them to run the drill."],
  ["I'll be able come tomorrow.", "I'll be able to come tomorrow."],
  ["She explained me the plan.", "She explained to me the plan."],
  ["We cannot afford spending more.", "We cannot afford to spend more."],
  ["It not required here.", "It is not required here."],
  ["We have not including tax.", "We have not included tax."],
  ["It did been fixed.", "It had been fixed."],
  ["There is has been a delay.", "There has been a delay."],
  ["I am surprise that it worked.", "I am surprised that it worked."],
  ["Apps that use to be free cost money.", "Apps that used to be free cost money."],
  ["Is he suppose to win?", "Is he supposed to win?"],
  ["As you maybe aware, it is late.", "As you may be aware, it is late."],
  ["We are thank full for it.", "We are thankful for it."],
  ["I have 1 days left.", "I have 1 day left."],
  ["We added a lot features.", "We added a lot of features."],
  ["It is the worlds best tea.", "It is the world's best tea."],
  ["It is a simply solution.", "It is a simple solution."],
  ["We toured the corporate headquarter.", "We toured the corporate headquarters."],
  ["Is there any chances of rain?", "Are there any chances of rain?"],
  ["Here the specs of the phone.", "Here are the specs of the phone."],
  ["This is a must read book.", "This is a must-read book."],
  ["She stressed the important of sleep.", "She stressed the importance of sleep."],
  ["It dates from the 19 century.", "It dates from the 19th century."],
  ["It caused tension between he and his boss.", "It caused tension between him and his boss."],
  ["It is hard for we parents.", "It is hard for us parents."],
  ["Tell me if there anyone else.", "Tell me if there is anyone else."],
  ["The reports of the outage is wrong.", "The reports of the outage are wrong."],
  ["How is your new shoes?", "How are your new shoes?"],
  ["Some time I read at night.", "Sometimes I read at night."],
  ["There isn't anyway to fix it.", "There isn't any way to fix it."],
  ["I have no been there.", "I have not been there."],
  ["Do you one to come?", "Do you want to come?"],
  ["Please harry up!", "Please hurry up!"],
  ["Open the attach file.", "Open the attached file."],
  ["Please high light the words.", "Please highlight the words."],
  ["I look forward of the trip.", "I look forward to the trip."],
  ["Would it possible to call?", "Would it be possible to call?"],
  ["And the are going home.", "And they are going home."],
  ["That car is one of the kind.", "That car is one of a kind."],
  ["This is the most common errors.", "This is the most common error."],
  ["This is most popular game.", "This is the most popular game."],
])("repairs %s", (input, expected) => {
  const found = review(input);
  expect({ input, count: found.length }).toEqual({ input, count: 1 });
  expect(applyEdits(input, found[0].alternatives[0].edits)).toBe(expected);
  expect(review(expected)).toEqual([]);
});

test.each([
  "We developers need better tools.",
  "It is a good cause they support.",
  "Smoking can cause the problem.",
  "Things that cause our pain are many.",
  "I do though.",
  "He though is the best.",
  "Even though about half came, we won.",
  "The dog bit me yesterday.",
  "I got bit by a dog.",
  "Every bit as good as the old one.",
  "Bit rot slowly ruins old disks.",
  "I can't help laughing at it.",
  "I need help getting this to work.",
  "It helps knowing the answer.",
  "The tool is used to run tests.",
  "They are used to define the scope.",
  "We are used to hard work.",
  "The file it points to exists.",
  "Set the flag to disabled.",
  "It will be done soon.",
  "Should it be, please call me.",
  "Wear Type I life jackets.",
  "The state of art in the city is poor.",
  "Do it if need be.",
  "I stayed because will power is all I had.",
  "Neither the client nor the proxy works.",
  "It is not the case either that A holds nor that B holds.",
  "He had had enough.",
  "The test tested nothing.",
  "No one I know knows the way.",
  "We need to connect connected devices.",
  "He is locking locks.",
  "It is better that we leave now.",
  "We got there after lunch.",
  "I'm making trough planters for the yard.",
  "Ether was used as a solvent or a fuel.",
  "On an off day, we rest.",
  "The students too realize it.",
  "The Route of the Problem is a song.",
  "Meters stop working over time.",
  "A dose not exceeding 5 mg is safe.",
  "He sat beside the fire.",
  "We lay in the trough the whole day.",
  "They are decent people.",
  "Water is nigh on impossible to find.",
  "The bin is full.",
  "It is the most beautiful place.",
  "The tests sent to the lab are back.",
  "I set it to disabled.",
  "Don't forget the keys.",
  "The free will made him strong.",
  "A watering can leaked on the floor.",
  "They would found a new school.",
  "How would suggesting people work?",
  "Would this pricing change?",
  "Will Smith played the lead.",
  "Let it go now.",
  "Make it work for us.",
  "It is vital that it run on time.",
  "The United States upset the champions.",
  "She makes us laugh and cry.",
  "He wants you to stay and help.",
  "I told them stories about it.",
  "Jobs are hard come by.",
  "Any feedback would be great thank you.",
  "The tool I use to write code is free.",
  "All you do is worry about it.",
  "There is interest in the plan.",
  "A delight full of surprises.",
  "No one cares about it.",
  "He is twenty one years old.",
  "We watched season one specials.",
  "I had one years ago.",
  "She liked it a lot today.",
  "It has a hugely dominant market share.",
  "Is there any news?",
  "Over there is a shop.",
  "Here the road ends.",
  "Here the water is deep.",
  "Like we developers do, they test.",
  "Ten megabytes of disk space is needed.",
  "The earliest record of birds in the areas of Peru is old.",
  "The are has fallen out of use.",
  "A good bit of luck.",
  "I look forward to the trip.",
  "This is most likely wrong.",
  "It has no signed contract.",
])("leaves %s", (text) => {
  expect(review(text).map((d) => d.original)).toEqual([]);
});

test("no chunk stalls on runs of this wave's frame words", () => {
  for (const text of [
    "I complaint cause though bit apologies helped carrying used to goes ".repeat(500),
    "if is either nor want wanted greater that 10 there after be replaces ".repeat(500),
    "go went gone going goes ".repeat(800),
  ])
    expect(Math.min(slowestChunkMs(text), slowestChunkMs(text))).toBeLessThan(30);
});
