import { describe, expect, test } from "bun:test";
import { REVIEW_SUPPORTED_RULE_IDS } from "../../src/core/domain/grammar/review/reviewCatalog";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";
import { review } from "./grammarTestUtils";

const RULES = new Set(["englishPhraseCorrections", "englishClosedCompounds", "stylePhrasing"]);
const findings = (text: string) =>
  review(text, {}, { enabledRules: REVIEW_SUPPORTED_RULE_IDS }).diagnostics.filter((d) =>
    RULES.has(d.ruleId),
  );
const repairsOf = (text: string) =>
  findings(text).flatMap((d) => d.alternatives.map((a) => applyEdits(text, a.edits)));

// [typed, one repaired text the writer can pick]
const repairs: [string, string][] = [
  ["Mia stayed true to her words.", "Mia stayed true to her word."],
  ["Be TRUE to your words.", "Be TRUE to your word."],
  ["Whether it rains is here nor there.", "Whether it rains is neither here nor there."],
  ["Honestly, that's here nor there.", "Honestly, that's neither here nor there."],
  ["Please turn it of", "Please turn it off"],
  ["Turn i of.", "Turn it off."],
  [
    "The lamp works, but suffice to say it is ugly.",
    "The lamp works, but suffice it to say it is ugly.",
  ],
  ["Not along after lunch, it rained.", "Not long after lunch, it rained."],
  ["The shop closed not along afterwards.", "The shop closed not long afterwards."],
  ["Be kind to one's self.", "Be kind to oneself."],
  ["The deadline is a ticking time clock.", "The deadline is a ticking clock."],
  ["Copy it to the another folder.", "Copy it to the other folder."],
  ["The clocks drifted out of sink.", "The clocks drifted out of sync."],
  ["The village, now know as Oakdale, grew fast.", "The village, now known as Oakdale, grew fast."],
  ["Our host went through great lengths for us.", "Our host went to great lengths for us."],
  ["She goes to a great length to help.", "She goes to great lengths to help."],
  ["The plan is risky in some degree.", "The plan is risky to some degree."],
  ["Count the read and writes per second.", "Count the reads and writes per second."],
  ["Set the read and writes flags.", "Set the read and write flags."],
  ["We back up files on daily basis.", "We back up files on a daily basis."],
  ["Invoices go out on hourly basis.", "Invoices go out on an hourly basis."],
  ["ON WEEKLY BASIS we meet.", "ON A WEEKLY BASIS we meet."],
  ["They pay on bi-monthly basis.", "They pay on a bi-monthly basis."],
  ["Please don't take it personal.", "Please don't take it personally."],
  ["Write a doubly link list in Rust.", "Write a doubly linked list in Rust."],
  ["The cat hid underneath of the bed.", "The cat hid underneath the bed."],
  ["Her recipe is a highly kept secret.", "Her recipe is a well-kept secret."],
  ["How may of you have cats?", "How many of you have cats?"],
  ["We cooked pasta yesterday night.", "We cooked pasta last night."],
  ["She wrote a lots of tests.", "She wrote lots of tests."],
  ["A lots happened today.", "A lot happened today."],
  ["Lot's of birds sing here.", "Lots of birds sing here."],
  ["Plenty of bugs, lot's to fix.", "Plenty of bugs, lots to fix."],
  ["We baked lot's and lot's of bread.", "We baked lots and lots of bread."],
  ["We should look in to why it broke.", "We should look into why it broke."],
  ["She loved the surrealness of the film.", "She loved the surreality of the film."],
  ["It is not a bug per-se.", "It is not a bug per se."],
  ["It is not wrong per-say.", "It is not wrong per se."],
  ["We met t he next day.", "We met the next day."],
  ["Last but not last, thank you.", "Last but not least, thank you."],
  ["Last but not the least, thank you.", "Last but not least, thank you."],
  ["The kids laughed of him.", "The kids laughed at him."],
  ["Don't laugh of Sam.", "Don't laugh at Sam."],
  ["The patch touches quite many files.", "The patch touches quite a few files."],
  ["Well, thanks lot.", "Well, thanks a lot."],
  ["This task needs spacial attention.", "This task needs special attention."],
  ["She is a very known chef.", "She is a very well-known chef."],
  ["There is more that meets the eye.", "There is more than meets the eye."],
  ["I can't sing, let along dance.", "I can't sing, let alone dance."],
  ["Start with the low hanging fruit.", "Start with the low-hanging fruit."],
  ["Pick the low-hanging fruits first.", "Pick the low-hanging fruit first."],
  ["I very much so enjoyed the trip.", "I very much enjoyed the trip."],
  ["Both sides have valid point of views.", "Both sides have valid points of view."],
  ["My cat is similar like yours.", "My cat is similar to yours."],
  ["You were suppose to call.", "You were supposed to call."],
  ["You're suppose to knock.", "You're supposed to knock."],
  ["What is the different between them?", "What is the difference between them?"],
  ["That is somebody's else problem.", "That is somebody else's problem."],
  ["I bought it in the spur of the moment.", "I bought it on the spur of the moment."],
  ["It fails unless if you restart.", "It fails unless you restart."],
  ["It looks like as if it will rain.", "It looks as if it will rain."],
  ["Doctors leave to Rome tomorrow.", "Doctors leave for Rome tomorrow."],
  ["She left to Oslo in May.", "She left for Oslo in May."],
  ["Coders avoid global state like a plague.", "Coders avoid global state like the plague."],
  ["Two rule of thumbs help here.", "Two rules of thumb help here."],
  ["The crew was comprised of six sailors.", "The crew consisted of six sailors."],
  ["On first glance, it looks fine.", "At first glance, it looks fine."],
  ["Stack the box in top of the crate.", "Stack the box on top of the crate."],
  ["Put it on top off the shelf.", "Put it on top of the shelf."],
  ["It ran ontop off the old engine.", "It ran on top of the old engine."],
  ["It made a last ditch effort to win.", "It made a last-ditch effort to win."],
  ["She took the managerial reigns in May.", "She took the managerial reins in May."],
  ["That is a slippy slope.", "That is a slippery slope."],
  ["They spent like no tomorrow.", "They spent like there's no tomorrow."],
  ["It failed, not without a lack of effort.", "It failed, not for lack of effort."],
  ["We learned by trail and error.", "We learned by trial and error."],
  ["We cut three line of codes.", "We cut three lines of code."],
  ["We cut many lines of codes.", "We cut many lines of code."],
  ["Please send an email to the tutor.", "Please email the tutor."],
  ["She sent an email to me.", "She emailed me."],
  ["Finding it was a strike of luck.", "Finding it was a stroke of luck."],
  ["The idea was a strike of genius.", "The idea was a stroke of genius."],
  ["Keep some the cookies for later.", "Keep some of the cookies for later."],
  ["There is truth to the fact that cats nap.", "There is truth to the claim that cats nap."],
  ["I call home once a while.", "I call home once in a while."],
  ["I swim every once and a while.", "I swim every once in a while."],
  ["Read the entire of the file.", "Read the entirety of the file."],
  ["Plan for the worst case scenario.", "Plan for the worst-case scenario."],
  ["He left without out a word.", "He left without a word."],
  ["I have a sneaky suspicion about it.", "I have a sneaking suspicion about it."],
  ["Kids learn the part of speeches early.", "Kids learn the parts of speech early."],
  ["I don't want you to worried about it.", "I don't want you too worried about it."],
  ["On second though, let's stay.", "On second thought, let's stay."],
  ["My second though is that we wait.", "My second thought is that we wait."],
  ["We had to backout the release.", "We had to back out the release."],
  ["The day was nerve racking.", "The day was nerve-racking."],
  ["The wait was nerve wracking.", "The wait was nerve-racking."],
  ["The exam was nerve-wracking.", "The exam was nerve-racking."],
];

// Correct forms and look-alikes that stay clean.
const silent = [
  "Mia stayed true to her word.",
  "The film stays true to the words of the poet.",
  "That is neither here nor there.",
  "Please turn it off.",
  "A single word will suffice to say it.",
  "Not long after lunch, it rained.",
  "Be kind to oneself.",
  "The clocks drifted out of sync.",
  "We now know as much as they do.",
  "Our host went to great lengths for us.",
  "In some degree programs, a thesis is required.",
  "Count the reads and writes per second.",
  "We back up files on a yearly basis.",
  "We decided on this basis.",
  "Please don't take it personally.",
  "The page has a link list in the footer.",
  "The cat hid underneath the bed.",
  "It may rain today.",
  "We cooked pasta last night.",
  "A lot's changed since then.",
  "The parking lot's on fire.",
  "Look in to the left drawer.",
  "Look into why it broke.",
  "The laugh of a child filled the hall.",
  "Laughs of joy rang out.",
  "Do you like it? Very much so.",
  "Thank you very much so far.",
  "Turn left to Main Street.",
  "The court granted leave to Appeal.",
  "Leave to cool for an hour.",
  "Rumors spread like a plague.",
  "To some the answer is obvious.",
  "I met her once a while back.",
  "Exit once a while loop ends.",
  "Click here to send an email to confirm your address.",
  "I was sent an email to review.",
  "Upon first glance it looked fine.",
  "My second though is cheaper.",
  "Speech writers study parts of speeches by Lincoln.",
  "I spoke to worried parents.",
  "Let's suppose to begin that x is one.",
  "I suppose to some extent it works.",
  "The backout plan is ready.",
  "Last but not least, thank you.",
  "This is similar to that.",
  "What is the difference between them?",
  "Start with the low-hanging fruit.",
  "The worst-case scenario is fine.",
  "Avoid it like the plague.",
];

describe("Review idiom corrections (idioms2)", () => {
  test.each(repairs)("%s", (typed, repaired) => {
    expect(repairsOf(typed)).toContain(repaired);
  });
  test.each(silent)("stays silent: %s", (text) => {
    expect(findings(text)).toEqual([]);
  });
});
