import { expect, test } from "bun:test";
import { detectReviewDiagnostics } from "../../src/core/domain/grammar/review/reviewDiagnostics";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";
import type { CatalogRuleId } from "../../src/core/domain/grammar/ruleCatalog";

const RULES: CatalogRuleId[] = [
  "englishPhraseCorrections",
  "englishContextualCompounds",
  "englishSentenceStructure",
  "englishYourYouAre",
];
function review(text: string, lang = "en_US") {
  return detectReviewDiagnostics(
    { id: "slots", text, scope: { start: 0, end: text.length }, protectedRanges: [] },
    { lang, enabledRules: RULES, userDictionary: [], insertSpaceAfterAutocomplete: true },
  ).diagnostics;
}
const repaired = (text: string) =>
  review(text).map((d) => d.alternatives.map((a) => applyEdits(text, a.edits)));

test.each([
  ["We moved here four moths ago.", "We moved here four months ago."],
  ["It will be ready in a few moths.", "It will be ready in a few months."],
  ["She barley noticed the noise.", "She barely noticed the noise."],
  ["They could barley see the road.", "They could barely see the road."],
  ["We tried anther approach.", "We tried another approach."],
  ["The wold wide web changed news.", "The world wide web changed news."],
  ["This mans everything to us.", "This means everything to us."],
  ["You can due that tomorrow.", "You can do that tomorrow."],
  ["Due they ship abroad?", "Do they ship abroad?"],
  ["Honestly, I couldn't careless about it.", "Honestly, I couldn't care less about it."],
  ["We might has well stay.", "We might as well stay."],
  ["You should us a stronger password.", "You should use a stronger password."],
  ["It event runs on old phones.", "It even runs on old phones."],
  ["Nobody could here us shouting.", "Nobody could hear us shouting."],
  ["Nice to here that you are well.", "Nice to hear that you are well."],
  ["That point bares repeating.", "That point bears repeating."],
  ["We ones lived by the sea.", "We once lived by the sea."],
  ["I sat in he front row.", "I sat in the front row."],
  ["Let's discus the budget today.", "Let's discuss the budget today."],
  ["She discuses the results with us.", "She discusses the results with us."],
  ["Don't loose your ticket.", "Don't lose your ticket."],
  ["He kept loosing track of time.", "He kept losing track of time."],
  ["I was at a lose for words.", "I was at a loss for words."],
  ["We got several complains about it.", "We got several complaints about it."],
  ["The main complain was the price.", "The main complaint was the price."],
  ["He can't swim, yet alone dive.", "He can't swim, let alone dive."],
  ["Of the two plans, the later is cheaper.", "Of the two plans, the latter is cheaper."],
  ["We have all ready paid.", "We have already paid."],
  ["Please attache your receipt.", "Please attach your receipt."],
  ["I knew tat it was late.", "I knew that it was late."],
  ["They have setup the stage.", "They have set up the stage."],
  ["We just backup the files nightly.", "We just back up the files nightly."],
  ["Please login before you post.", "Please log in before you post."],
  ["I guess id rather walk.", "I guess I'd rather walk."],
  ["That is were we met.", "That is where we met."],
  ["Lets just walk home.", "Let's just walk home."],
  ["You laptop is on the desk.", "Your laptop is on the desk."],
  ["Ben wasn't hungry too.", "Ben wasn't hungry either."],
  ["We don't need too.", "We don't need to."],
  ["Could you manager call me?", "Could your manager call me?"],
  ["Thanks for you patience.", "Thanks for your patience."],
  ["We are so curios about it.", "We are so curious about it."],
  ["She has red the report.", "She has read the report."],
  ["You can past it into the box.", "You can paste it into the box."],
  ["It's event harder now.", "It's even harder now."],
  ["The park closed do to the flood.", "The park closed due to the flood."],
  ["We tried so may times.", "We tried so many times."],
  ["Add it to may list.", "Add it to my list."],
  ["They should ave known.", "They should have known."],
  ["Come and visit us soon, he told is.", "Come and visit us soon, he told us."],
  ["She us so kind.", "She is so kind."],
  ["Bye now, take car!", "Bye now, take care!"],
  ["The first to options failed.", "The first two options failed."],
  ["She cam home late.", "She came home late."],
  ["Will you com with me?", "Will you come with me?"],
  ["The test was really hart.", "The test was really hard."],
  ["That was the wurst day ever.", "That was the worst day ever."],
  ["Oh, than you so much!", "Oh, thank you so much!"],
  ["You could ad some salt.", "You could add some salt."],
  ["I still have chores to due.", "I still have chores to do."],
  ["Please be quite!", "Please be quiet!"],
  ["I am quiet sure of it.", "I am quite sure of it."],
  ["He could loss the race.", "He could lose the race."],
  ["She always losses her pen.", "She always loses her pen."],
  ["Pull the lose thread.", "Pull the loose thread."],
  ["We hope to here from you.", "We hope to hear from you."],
  ["I received your massage.", "I received your message."],
  ["It goes against my principals.", "It goes against my principles."],
  ["The trailer peaked my curiosity.", "The trailer piqued my curiosity."],
  ["I did not man to shout.", "I did not mean to shout."],
  ["The best film every made.", "The best film ever made."],
  ["All the bet, Ana", "All the best, Ana"],
  ["As off today, the shop is open.", "As of today, the shop is open."],
  ["The team pulled of a win.", "The team pulled off a win."],
  ["The ice is not save to cross.", "The ice is not safe to cross."],
  ["We are all save and sound.", "We are all safe and sound."],
  ["She safes her money.", "She saves her money."],
  ["Many tanks for the ride!", "Many thanks for the ride!"],
  ["Tank you for coming.", "Thank you for coming."],
  ["We tried anther route.", "We tried another route."],
  ["Learn how to us the oven.", "Learn how to use the oven."],
  ["It is one if the best parks.", "It is one of the best parks."],
  ["I waited a couple if hours.", "I waited a couple of hours."],
  ["Yes, if course.", "Yes, of course."],
  ["Come by an see the garden.", "Come by and see the garden."],
  ["Please fill in this from.", "Please fill in this form."],
  ["We got an email form our bank.", "We got an email from our bank."],
  ["I will look in to it.", "I will look into it."],
  ["The cake was divided in to slices.", "The cake was divided into slices."],
  ["Copying it in any from is banned.", "Copying it in any form is banned."],
  ["The number or cars is growing.", "The number of cars is growing."],
  ["I have no idea were to park.", "I have no idea where to park."],
  ["Were else could it be?", "Where else could it be?"],
  ["The guests where leaving early.", "The guests were leaving early."],
  ["I think there's and error here.", "I think there's an error here."],
  ["Prices rise an then fall.", "Prices rise and then fall."],
  ["Let me now what you think.", "Let me know what you think."],
  ["I need the file right know.", "I need the file right now."],
  ["There is know way to tell.", "There is no way to tell."],
  ["It weighs more that 5 kilos.", "It weighs more than 5 kilos."],
  ["Rust is safer that C.", "Rust is safer than C."],
  ["It was once of the worst days.", "It was one of the worst days."],
  ["Every one in a while we hike.", "Every once in a while we hike."],
  ["Ask them it anyone called.", "Ask them if anyone called."],
  ["Her notes made if clear.", "Her notes made it clear."],
  ["We can all ready see the coast.", "We can already see the coast."],
  ["A neighbour recently complaint about it.", "A neighbour recently complained about it."],
  ["Rent is due per moth.", "Rent is due per month."],
  ["I could jut cry.", "I could just cry."],
  ["It doe not help.", "It does not help."],
  ["The copy bares a close resemblance.", "The copy bears a close resemblance."],
  ["I can't bare the noise.", "I can't bear the noise."],
  ["The later very often wins.", "The latter very often wins."],
  ["Id love a second opinion.", "I'd love a second opinion."],
  ["Members who login daily earn points.", "Members who log in daily earn points."],
  ["Why can't I logout?", "Why can't I log out?"],
  ["She logins every morning.", "She logs in every morning."],
  ["Tell the guests to checkout by noon.", "Tell the guests to check out by noon."],
  ["You should backup your photos.", "You should back up your photos."],
  ["Wait here instead off leaving.", "Wait here instead of leaving."],
  ["He named three basic principals.", "He named three basic principles."],
  ["She met the school principle.", "She met the school principal."],
  ["Kids dislike a tattle-tail.", "Kids dislike a tattle-tale."],
  ["Can you tel me the time?", "Can you tell me the time?"],
  ["I want to tech them chess.", "I want to teach them chess."],
  ["She choices the blue one.", "She chooses the blue one."],
  ["We should ware our helmets.", "We should wear our helmets."],
  ["The file mus be somewhere.", "The file must be somewhere."],
  ["We sill need more chairs.", "We still need more chairs."],
  ["Pleas reply by Friday.", "Please reply by Friday."],
  ["It is nut ready yet.", "It is not ready yet."],
  ["They ran trough the park.", "They ran through the park."],
  ["The soup was vary hot.", "The soup was very hot."],
  ["He took car of the garden.", "He took care of the garden."],
  ["Refill the stationary cupboard.", "Refill the stationery cupboard."],
  ["Start your free trail today.", "Start your free trial today."],
  ["The app shows an error massage.", "The app shows an error message."],
  ["We cold hear the sea.", "We could hear the sea."],
  ["Cold you send the file?", "Could you send the file?"],
  ["Mist began to envelope the hills.", "Mist began to envelop the hills."],
  ["Sales grew from 40 too 55 units.", "Sales grew from 40 to 55 units."],
  ["You should git a new charger.", "You should get a new charger."],
  ["We cab help you tomorrow.", "We can help you tomorrow."],
  ["Whet happened next?", "What happened next?"],
  ["Good lick with the exam!", "Good luck with the exam!"],
  ["I have note tried it.", "I have not tried it."],
  ["That idea sounds goo.", "That idea sounds good."],
  ["She felt very said.", "She felt very sad."],
  ["He sad that it was fine.", "He said that it was fine."],
  ["Always looks the back door.", "Always locks the back door."],
  ["We sell non alcoholic drinks.", "We sell non-alcoholic drinks."],
  ["Thanks you so much.", "Thank you so much."],
  ["The kids look TV after school.", "The kids watch TV after school."],
  ["My laptop scree is dim.", "My laptop screen is dim."],
  ["Please ensue that it runs.", "Please ensure that it runs."],
  ["I felt the lose of my friend.", "I felt the loss of my friend."],
  ["You don't eat meat, are you?", "You don't eat meat, do you?"],
  ["He didn't phone back, was he?", "He didn't phone back, did he?"],
  ["They aren't ready yet, do they?", "They aren't ready yet, are they?"],
  ["I'm not wrong about this, do I?", "I'm not wrong about this, am I?"],
])("repairs %s", (text, fixed) => {
  expect(repaired(text)).toEqual([[fixed]]);
});

test("an our before a time word is an hour", () => {
  expect(repaired("The bus left an our ago.").flat()).toContain("The bus left an hour ago.");
  expect(repaired("We arrived half an our late.").flat()).toContain(
    "We arrived half an hour late.",
  );
});

test("comprise of offers both repairs", () => {
  expect(repaired("Our team will comprise of five people.")).toEqual([
    ["Our team will comprise five people.", "Our team will consist of five people."],
  ]);
});

test.each([
  "Moths gathered around the porch light.",
  "Two moths flew in last night.",
  "The farm grows barley and oats.",
  "Pollen sits on the anther of the flower.",
  "Sheep grazed on the wold above the village.",
  "The old man's hat blew away.",
  "Rent is due next week.",
  "Due to rain, we stayed in.",
  "She told us the truth.",
  "Please give us the keys.",
  "The event starts at noon.",
  "This event gives us hope.",
  "Come here and sit.",
  "We moved to here from Leeds.",
  "He bared his teeth.",
  "Those ones are mine.",
  "He said he first had to leave.",
  "The athlete threw the discus far.",
  "These screws are loose.",
  "Let the dogs loose in the yard.",
  "Win or lose, we tried.",
  "She always complains about noise.",
  "He is not yet alone in this.",
  "See you later.",
  "The later chapters are better.",
  "Sooner or later the later trains stop.",
  "We are all ready to leave.",
  "The cultural attache arrived.",
  "He has a tat on his arm.",
  "The setup is easy.",
  "The login screen froze.",
  "The bikes were the cheapest.",
  "Where did you get this from?",
  "Her red scarf is new.",
  "I told you dad is home.",
  "I like tea, and she likes it too.",
  "They are going too.",
  "What you need is rest.",
  "He cares for you most.",
  "Which if you recall was the best?",
  "You guys rock.",
  "Each of you something small.",
  "We walked past it into town.",
  "The event starts at noon.",
  "What did you do to the lamp?",
  "How may I help you?",
  "Ave Maria was sung.",
  "That is what it is.",
  "Take the car to work.",
  "Our web cam is broken.",
  "The White Hart is a pub.",
  "The wurst is spicy.",
  "She runs faster than you.",
  "The ad to the left is old.",
  "Rent is due to the owner.",
  "Keep quiet a while.",
  "It was a big loss for us.",
  "Walk to here from the gate.",
  "Thanks for the relaxing massage.",
  "The principals of three schools met.",
  "Sales peaked in spring.",
  "The man to ask is Ben.",
  "I bet the bus is late.",
  "Do not do to others what you hate.",
  "First off all guests left.",
  "Tell me who you bought it from.",
  "Pollen forms on the anther.",
  "The stamen, anther, and filament differ.",
  "The tank you filled is leaking.",
  "Tanks crossed the river.",
  "I could not save to the server.",
  "He lets all of us in.",
  "It means a lot to us the most.",
  "Use one if the other fails.",
  "It is an honest answer.",
  "There is no limit to the number or types of files.",
  "We helped form the club.",
  "Where were you?",
  "Students where learning is fun.",
  "We need an already tested plan.",
  "It is more important that others help.",
  "The more that one practices, the better.",
  "We spoke once of the old mill.",
  "This is the one and for all the rest, wait.",
  "I still don't now.",
  "Two moths circled the lamp.",
  "Rocks jut out over the bay.",
  "A doe crossed the road.",
  "She bared her teeth at us.",
  "Tit for tat is fair.",
  "The later the better.",
  "The id column holds numbers.",
  "In Freud the id is the oldest part.",
  "Your login expired.",
  "He went from login to logout in a minute.",
  "Click checkout to pay.",
  "We keep a backup of every file.",
  "First off, thank you.",
  "Fill in any form you like.",
  "The principle of fairness applies.",
  "You don't like it, do you?",
  "I don't know, is it true?",
  "I don't know, is it?",
  "She isn't here, is she?",
  "You don't eat meat, are you sure.",
  "Prices vary widely by region.",
  "The values do not vary greatly.",
  "The cat sat on the window sill.",
  "The court heard their pleas.",
  "Horses drank from the trough.",
  "Pick a choice that suits you.",
  "Multiple users can join.",
  "The bar is nut free.",
  "A stationary bike is quiet.",
  "We followed the hiking trail.",
  "It is cold outside.",
  "Seal the envelope first.",
  "That is too much.",
  "Commit it with git first.",
  "We took a cab home.",
  "Whet the knife on a stone.",
  "Note the new date.",
  "The slime turned to goo.",
  "She is sad today.",
  "We have sad news.",
  "Look at the door.",
  "That was a non sequitur.",
  "Lick the spoon clean.",
  "Win or lose, we play.",
  "The roof took a good lick of paint.",
  "She thanks you for the gift.",
  "Look, the door is open.",
])("leaves %s", (text) => {
  expect(review(text)).toEqual([]);
});

test("is English only", () => {
  expect(review("We moved here four moths ago.", "de_DE")).toEqual([]);
});
