import { describe, expect, test } from "bun:test";
import { CLAUSE_START } from "../../src/core/domain/grammar/review/polish/shared";
import { applyEdits } from "../../src/core/domain/grammar/review/textRanges";
import type { CatalogRuleId } from "../../src/core/domain/grammar/ruleCatalog";
import { scan, slowestChunkMs } from "./reviewHarness";

/** Polish-only Review checks: every positive gets its first fix, every negative stays clean. */
function findings(ruleId: CatalogRuleId, text: string, lang = "pl_PL") {
  return scan(text, { enabledRules: [ruleId], lang }).filter((d) => d.ruleId === ruleId);
}

type Case = { pos: Array<[string, string]>; neg: string[] };

export const POLISH_CASES: Array<[CatalogRuleId, string, Case]> = [
  [
    "englishPhraseCorrections",
    'two prepositions, a misused "bynajmniej" and more look-alikes',
    {
      pos: [
        ["Spotkamy się w od poniedziałku.", "Spotkamy się w poniedziałku."],
        ["Mieszkam w z Gdańsku.", "Mieszkam w Gdańsku."],
        ["To było ciekawe, bynajmniej dla mnie.", "To było ciekawe, przynajmniej dla mnie."],
        ["Ona dala mi książkę.", "Ona dała mi książkę."],
        ["Pieniądze nie ogrywają tu roli.", "Pieniądze nie odgrywają tu roli."],
        [
          "Opisał to w sowich wspomnieniach i w sowim dorobku.",
          "Opisał to w sowich wspomnieniach i w swoim dorobku.",
        ],
        ["Zostało mi dużo do zrobieni.", "Zostało mi dużo do zrobienia."],
        ["Urodził się w litym 1990 roku.", "Urodził się w lutym 1990 roku."],
        ["Według statystk wypadków jest mniej.", "Według statystyk wypadków jest mniej."],
        ["Chodzi o ty, żeby zdążyć.", "Chodzi o to, żeby zdążyć."],
        ["Kierowca siedział przedzie.", "Kierowca siedział na przodzie."],
        ["Rozmawiali o tym i o wym.", "Rozmawiali o tym i o owym."],
        ["Na ekranie było cale miasto.", "Na ekranie było całe miasto."],
        ["Cale życie czekał.", "Całe życie czekał."],
      ],
      neg: [
        "Myśli krążyły w od dawna zmęczonej głowie.",
        "Szli w od lat zamkniętym budynku.",
        "Wcale nie jest to bynajmniej łatwe.",
        "To problem bynajmniej niebłahy.",
        "Bynajmniej!",
        "Patrzył na nich z dala.",
        "Słowo o wym. łan.",
        "Ciasto zaczynia się zakwasem.",
        "Winny sposób na grypę.",
        "Przeszła na z góry ustaloną trasę.",
      ],
    },
  ],
  [
    "stylePhrasing",
    '"nie tyle …, ale", "zarówno …, jak również", "rozumieć pod tym", "bardziej szybko", "20-letni jubileusz"',
    {
      pos: [
        ["Był nie tyle zły, ale zmęczony.", "Był nie tyle zły, ile zmęczony."],
        [
          "Przyszli zarówno rodzice, jak również dzieci.",
          "Przyszli zarówno rodzice, jak i dzieci.",
        ],
        ["Co rozumiesz pod tym pojęciem?", "Co rozumiesz przez to pojęcie?"],
        ["Biegnie bardziej szybko niż brat.", "Biegnie szybciej niż brat."],
        ["Mówił najbardziej cicho z nas.", "Mówił najciszej z nas."],
        ["Najwięcej lubię lody.", "Najbardziej lubię lody."],
      ],
      neg: [
        "Arturze, może nie tyle co, ale kto.",
        "Stał pod tym drzewem.",
        "Im bardziej szybko biegł, tym bardziej się męczył.",
        "Lubię to bardziej niż wczoraj.",
      ],
    },
  ],
  [
    "polishMisplacedComma",
    'commas inside "tym bardziej że", "co do", "Oto jak", "w trakcie którego" and before "się"',
    {
      pos: [
        ["Otóż, wczoraj padał deszcz.", "Otóż wczoraj padał deszcz."],
        ["Dodatkowo, dostał premię.", "Dodatkowo dostał premię."],
        ["Zostanę, tym bardziej, że pada.", "Zostanę, tym bardziej że pada."],
        ["Mam zastrzeżenia, co do planu.", "Mam zastrzeżenia co do planu."],
        ["Oto, jak gotować ryż.", "Oto jak gotować ryż."],
        ["Nie wiem, dlaczego.", "Nie wiem dlaczego."],
        ["To był mecz, podczas, którego padł rekord.", "To był mecz, podczas którego padł rekord."],
        ["Długo rozlegał, się dzwonek.", "Długo rozlegał się dzwonek."],
        ["Nie jest to jednak, dobra wiadomość.", "Nie jest to jednak dobra wiadomość."],
      ],
      neg: [
        "Otóż, jak się okazało, nikt nie przyszedł.",
        "Mam uwagi, co do których nie jestem pewien.",
        "Oto, co znalazłem.",
        "Nie wiem, dlaczego tak zrobił.",
        "Wyszedł w czasie przerwy, którą ogłoszono.",
        "Zostanę, tym bardziej, że jeśli pójdę, zmoknę.",
        "Kiedy wrócił, sięgnął po książkę.",
      ],
    },
  ],
  [
    "polishMissingComma",
    '"a mianowicie", "w miarę jak", "O ile …, o tyle", "innymi słowy", "i koniec", "na to, gdzie"',
    {
      pos: [
        [
          "Powiem tylko jedno a mianowicie to, że wygraliśmy.",
          "Powiem tylko jedno, a mianowicie to, że wygraliśmy.",
        ],
        ["Lubię owoce a zwłaszcza jabłka.", "Lubię owoce, a zwłaszcza jabłka."],
        [
          "Ola w miarę jak rosła, nabierała pewności.",
          "Ola, w miarę jak rosła, nabierała pewności.",
        ],
        [
          "O ile brat lubi kawę o tyle siostra woli herbatę.",
          "O ile brat lubi kawę, o tyle siostra woli herbatę.",
        ],
        ["To jest innymi słowy porażka.", "To jest, innymi słowy, porażka."],
        ["Masz to zjeść i koniec!", "Masz to zjeść, i koniec!"],
        ["Nie patrz na to gdzie mieszka.", "Nie patrz na to, gdzie mieszka."],
      ],
      neg: [
        "Chcę wyglądać w miarę jak najlepiej.",
        "Szedł wolno, choć w miarę jak się rozgrzewał, przyspieszał.",
        "To był początek i koniec.",
        "Pada o tyle, o ile wieje.",
        "Napisał to innymi słowami.",
      ],
    },
  ],
  [
    "englishPhraseCorrections",
    "real-word slips named by a neighbour",
    {
      pos: [
        ["Skłam najlepsze życzenia.", "Składam najlepsze życzenia."],
        ["Widok z wieży był prze piękny.", "Widok z wieży był przepiękny."],
        ["Pies pobiegł prze siebie.", "Pies pobiegł przed siebie."],
        ["Ten tort upieczono prze ze mnie.", "Ten tort upieczono przeze mnie."],
        ["Spacerowali wzdłuż polnej drużki.", "Spacerowali wzdłuż polnej dróżki."],
        ["Z daleka widać kilku wierz kościoła.", "Z daleka widać kilku wież kościoła."],
        ["Kupiłem lakier do podług w hurtowni.", "Kupiłem lakier do podłóg w hurtowni."],
        ["Ten pokój jest jaśniejszy nisz kuchnia.", "Ten pokój jest jaśniejszy niż kuchnia."],
        ["Mówił głośniej nisz zwykle.", "Mówił głośniej niż zwykle."],
        ["Dobrze był oby to sprawdzić.", "Dobrze byłoby to sprawdzić."],
        [
          "Sami naważyli sobie tym razem gorzkiego piwa.",
          "Sami nawarzyli sobie tym razem gorzkiego piwa.",
        ],
        ["Poszedł do sklepu i z potworem.", "Poszedł do sklepu i z powrotem."],
        ["Wszystkie wnioski podleją ocenie.", "Wszystkie wnioski podlegają ocenie."],
        ["Ona nie ma z tym noc wspólnego.", "Ona nie ma z tym nic wspólnego."],
        ["Dodaj pół szklani mleka.", "Dodaj pół szklanki mleka."],
        [
          "Im bardzie się starał, tym gorzej wychodziło.",
          "Im bardziej się starał, tym gorzej wychodziło.",
        ],
        ["Grał bardzie odważnie niż brat.", "Grał bardziej odważnie niż brat."],
        ["U stup góry stał szałas.", "U stóp góry stał szałas."],
        ["Piszę coraz lepie.", "Piszę coraz lepiej."],
        ["Pracował coraz wydajnej.", "Pracował coraz wydajniej."],
        ["Rozmawiali przededniu wyborów.", "Rozmawiali w przededniu wyborów."],
        ["Decyzję wydano podstawie umowy.", "Decyzję wydano na podstawie umowy."],
        ["Czuję się niebyt dobrze.", "Czuję się niezbyt dobrze."],
        ["Spotkajmy się na Dworcu Gównym.", "Spotkajmy się na Dworcu Głównym."],
        ["Ogóle zasady są proste.", "Ogólne zasady są proste."],
        ["Została tylko jena osoba.", "Została tylko jedna osoba."],
        ["Przyjdź o tej potrze jutro.", "Przyjdź o tej porze jutro."],
        ["Popełniłem głupią litrówkę.", "Popełniłem głupią literówkę."],
        ["Dzisiaj boja się o dzieci.", "Dzisiaj boję się o dzieci."],
        ["Koty nie lubą wody.", "Koty nie lubią wody."],
        ["Córka chodzi do żłóbka miejskiego.", "Córka chodzi do żłobka miejskiego."],
        ["Badanie wzorku trwało krótko.", "Badanie wzroku trwało krótko."],
        ["Prokurator przestawił mu zarzuty.", "Prokurator przedstawił mu zarzuty."],
        ["Uśmiechnął si do nas.", "Uśmiechnął się do nas."],
        ["To jest naprawę bardzo ładne.", "To jest naprawdę bardzo ładne."],
        ["Kupiłem kwiaty dal niej.", "Kupiłem kwiaty dla niej."],
        ["Reguły są ścisłe określone.", "Reguły są ściśle określone."],
        ["Mamy wiele rożnych pomysłów.", "Mamy wiele różnych pomysłów."],
        ["Szybko okazałą się zdolną uczennicą.", "Szybko okazała się zdolną uczennicą."],
        ["Lubię nie tylko kawę, alei herbatę.", "Lubię nie tylko kawę, ale i herbatę."],
        ["Plik zwiera wszystkie dane.", "Plik zawiera wszystkie dane."],
        ["Ojciec miął zamiar wyjechać.", "Ojciec miał zamiar wyjechać."],
        ["Nie będę za nich nastawiał karku.", "Nie będę za nich nadstawiał karku."],
        ["Sprawa ma wysoką range.", "Sprawa ma wysoką rangę."],
        ["Straciliśmy znaczą część zapasów.", "Straciliśmy znaczną część zapasów."],
        ["Nie oznacz to, że przegraliśmy.", "Nie oznacza to, że przegraliśmy."],
        ["Pracuje w ośrodku zdrowa.", "Pracuje w ośrodku zdrowia."],
        ["Czytam o postanie styczniowym.", "Czytam o powstanie styczniowym."],
        ["Podszedł do niech powoli.", "Podszedł do nich powoli."],
        ["Szef pozawala sobie na żarty.", "Szef pozwala sobie na żarty."],
        ["Chce stratować w wyborach.", "Chce startować w wyborach."],
        ["Firma poniosła duże starty.", "Firma poniosła duże straty."],
        ["Auto jechało naprzeciwka.", "Auto jechało z naprzeciwka."],
        ["Stanął czele oddziału.", "Stanął na czele oddziału."],
        ["Zróbmy to wespół kolegami.", "Zróbmy to wespół z kolegami."],
        [
          "Nie mam czasu, a związku z tym nie przyjdę.",
          "Nie mam czasu, a w związku z tym nie przyjdę.",
        ],
        ["W lato jeździmy nad morze.", "Latem jeździmy nad morze."],
        ["Jest inny jak brat.", "Jest inny niż brat."],
        ["Mam ochotę na pływać.", "Mam ochotę pływać."],
        ["Spędził tam cale życie.", "Spędził tam całe życie."],
        ["Nikt nie wiedział, czego bał.", "Nikt nie wiedział, czego bał się."],
        ["Długo się wahał się z odpowiedzią.", "Długo się wahał z odpowiedzią."],
      ],
      neg: [
        "Tłum prze naprzód.",
        "Woda prze z całą siłą na tamę.",
        "Drużki szły za panną młodą.",
        "Wiejska drużka niosła kwiaty.",
        "Wierz mi, to prawda.",
        "Podług przepisów nowych firm płacimy mniej.",
        "Szukali coraz ciaśniejszych nisz rynkowych.",
        "Po co ci tyle nisz w ścianie?",
        "Wrócił tam i z powrotem.",
        "Jutro podleją kwiaty w ogrodzie.",
        "Czytałem o bardzie z Avonu.",
        "Mucha siedzi na lepie.",
        "Chodziliśmy wokół buddyjskich stup.",
        "Spotkali się w jej przededniu.",
        "Na jego czele stał generał.",
        "Mowa o Osjanie, bardzie celtyckim.",
        "Leciałem jumbo jetem.",
        "Któż inny jak nie on!",
        "Nikt inny jak on.",
        "Płynął za boją.",
        "Kupiłem pięć drewnianych bali.",
        "Wypłynął na tysiąc mil.",
        "Pojechałam na miesiąc.",
        "Monitor ma 24 cale przekątnej.",
        "Nie miał czasu na zmówienie pacierza.",
        "Po półwieku wrócił do domu.",
        "Dostał rzut rożny.",
        "Bał się, że nie zdąży.",
        "Spotkanie odbyło się w Jenie.",
        "Firma stała się liderem.",
      ],
    },
  ],
  [
    "stylePhrasing",
    'time spans with a numeral, "odnośnie", "tak długo, dopóki", "tam pisało", "kliknij na"',
    {
      pos: [
        ["Dom zbudowano w przeciągu trzech lat.", "Dom zbudowano w ciągu trzech lat."],
        ["Ceny wzrosły na przestrzeni 10 lat.", "Ceny wzrosły w ciągu 10 lat."],
        ["Spłacał kredyt przez przeciąg siedmiu lat.", "Spłacał kredyt w ciągu siedmiu lat."],
        ["Mam pytanie odnośnie tej umowy.", "Mam pytanie odnośnie do tej umowy."],
        ["Czekał tak długo, dopóki nie zasnął.", "Czekał dopóty, dopóki nie zasnął."],
        ["Tam pisało, że sklep jest zamknięty.", "Tam było napisane, że sklep jest zamknięty."],
        ["Na kartce pisało że wrócą jutro.", "Na kartce było napisane że wrócą jutro."],
        ["Kliknij na przycisk poniżej.", "Kliknij przycisk poniżej."],
      ],
      neg: [
        "Stał w przeciągu dwie godziny.",
        "Las rośnie na przestrzeni kilku kilometrów.",
        "Spłacał kredyt przez siedem lat.",
        "Mam pytanie odnośnie do umowy.",
        "Zostań tak długo, jak chcesz.",
        "Dziecko pisało, że tęskni.",
        "Dawniej się tam pisało, że to cud.",
        "Kliknij na dole strony.",
        "Ceny rosły w ciągu 10 lat.",
      ],
    },
  ],
  [
    "stylePhrasing",
    '"dwie lub więcej" with its noun recased, "pełnić rolę", "posiadać brodę"',
    {
      pos: [
        ["Czekał na nią dwie lub więcej godzin.", "Czekał na nią co najmniej dwie godziny."],
        [
          "Pisał o trzech lub więcej ciekawych książek.",
          "Pisał o co najmniej trzech ciekawych książkach.",
        ],
        ["Pomógł czterem lub więcej rodzin.", "Pomógł co najmniej czterem rodzinom."],
        [
          "Opiekował się dwoma lub więcej kotów sąsiadów.",
          "Opiekował się co najmniej dwoma kotami sąsiadów.",
        ],
        ["Przyszło pięć lub więcej osób.", "Przyszło co najmniej pięć osób."],
        ["Weź dwa lub więcej.", "Weź co najmniej dwa."],
        ["Muzyka pełni w filmie ważną rolę.", "Muzyka pełni w filmie ważną funkcję."],
        ["Pełni ona kluczową rolę w zespole.", "Pełni ona kluczową funkcję w zespole."],
        ["Jaką rolę pełni ten przycisk?", "Jaką funkcję pełni ten przycisk?"],
        ["Mój dziadek posiada siwą brodę.", "Mój dziadek ma siwą brodę."],
        ["Posiadając talent, mało ćwiczył.", "Mając talent, mało ćwiczył."],
        ["Ubierz ciepłą kurtkę.", "Włóż ciepłą kurtkę."],
        ["Rano założyła nowe buty.", "Rano włożyła nowe buty."],
        ["Zakładasz ciepły sweter do pracy?", "Wkładasz ciepły sweter do pracy?"],
        ["Po drodze napotkaliśmy na spore trudności.", "Po drodze napotkaliśmy spore trudności."],
      ],
      neg: [
        "Weź dwa albo trzy.",
        "Wypił więcej niż dwie kawy.",
        "Kupił dwie lub trzy bułki.",
        "Pełni funkcję skarbnika.",
        "Odgrywa ważną rolę w zespole.",
        "Posiada dom i dwa samochody.",
        "Mama ubrała dziecko w płaszcz.",
        "Założył okulary i firmę.",
        "Napotkał na swojej drodze wiele trudności.",
        "Obchodzimy piątą rocznicę ślubu.",
      ],
    },
  ],
  [
    "stylePhrasing",
    "officialese, calques and pleonastic adjectives in every case (opt-in)",
    {
      pos: [
        ["Te wiodące marki tanieją.", "Te czołowe marki tanieją."],
        ["To był jego wiodący pomysł.", "To był jego czołowy pomysł."],
        ["Polecam trzy destynacje na zimę.", "Polecam trzy cele podróży na zimę."],
        ["Myśli o pracy w terminach zysku.", "Myśli o pracy w kategoriach zysku."],
        ["Mamy sukcesy na odcinku oświaty.", "Mamy sukcesy w dziedzinie oświaty."],
        ["Upiekła tort na okoliczność imienin.", "Upiekła tort w sprawie imienin."],
        ["Generalnie zgadzam się z tobą.", "Ogólnie zgadzam się z tobą."],
        ["Pytasz, czy warto? Dokładnie tak.", "Pytasz, czy warto? Właśnie tak."],
        ["Mam na to zgodę i/lub podpis szefa.", "Mam na to zgodę lub podpis szefa."],
        ["Badał genezę powstania tej legendy.", "Badał genezę tej legendy."],
        ["Kierowca cofnął się trochę do tyłu.", "Kierowca cofnął się trochę."],
        ["Mówił o złudnym mirażu bogactwa.", "Mówił o mirażu bogactwa."],
        ["Pomagał nałogowym alkoholikom.", "Pomagał alkoholikom."],
        ["Wyprawa skończyła się zupełnym fiaskiem.", "Wyprawa skończyła się fiaskiem."],
        ["Pływali po akwenie wodnym.", "Pływali po akwenie."],
        ["Zebranie odbywa się w każdą środę tygodnia.", "Zebranie odbywa się w każdą środę."],
      ],
      neg: [
        "Ścieżka wiodąca do lasu jest błotnista.",
        "Ta droga wiodąca prosto na plażę jest krótka.",
        "Ta modna destynacja kusi turystów.",
        "Zapłać w terminach podanych na fakturze.",
        "Na odcinku drogi do Radomia trwa remont.",
        "Na każdą okoliczność mamy plan.",
        "Zrobił to dokładnie tak, jak chciał.",
        "Pisał o genezie powstania listopadowego.",
        "Cofnęła się o krok, a on został z tyłu.",
        "Ścieżki i/lub.json to nazwy plików.",
        "Mamy zwodnicze nadzieje.",
      ],
    },
  ],
  [
    "englishClosedCompounds",
    "guarded split words",
    {
      pos: [
        ["Ona na prawdę lubi pływać.", "Ona naprawdę lubi pływać."],
        ["Zrobiliśmy duży krok na przód.", "Zrobiliśmy duży krok naprzód."],
        ["Było śmiesznie i smutne za razem.", "Było śmiesznie i smutne zarazem."],
        ["Wróci za pewne jutro.", "Wróci zapewne jutro."],
        ["Stanął po środku sali.", "Stanął pośrodku sali."],
        ["Kolejka po woli się przesuwa.", "Kolejka powoli się przesuwa."],
        ["Ponad to dostał premię.", "Ponadto dostał premię."],
        ["Nikt z resztą nie pytał.", "Nikt zresztą nie pytał."],
        ["Jest co raz zimniej.", "Jest coraz zimniej."],
        ["Spóźnił się dla tego, że padało.", "Spóźnił się dlatego, że padało."],
        ["Dla czego nie dzwonisz?", "Dlaczego nie dzwonisz?"],
        ["W prawdzie padało, ale poszliśmy.", "Wprawdzie padało, ale poszliśmy."],
        ["Usiadł na tam tym krześle.", "Usiadł na tamtym krześle."],
        ["Nie rób tego dla swojego widzi mi się.", "Nie rób tego dla swojego widzimisię."],
        ["Wyjechała zagranicę na rok.", "Wyjechała za granicę na rok."],
        ["Nie był wstanie odpowiedzieć.", "Nie był w stanie odpowiedzieć."],
        ["Przyjdę jutro popołudniu.", "Przyjdę jutro po południu."],
        ["Krążył na około wieży.", "Krążył naokoło wieży."],
        ["Takie zachowanie jest kary godne.", "Takie zachowanie jest karygodne."],
        ["Tym nie mniej warto spróbować.", "Tym niemniej warto spróbować."],
        ["By najmniej nie żałuję.", "Bynajmniej nie żałuję."],
        ["Za zwyczaj wstaję wcześnie.", "Zazwyczaj wstaję wcześnie."],
        ["To była naj lepsza zabawa roku.", "To była najlepsza zabawa roku."],
        ["Odwiedza nas naj częściej w maju.", "Odwiedza nas najczęściej w maju."],
        ["Gazeta wychodzi co tygodniowo.", "Gazeta wychodzi cotygodniowo."],
        ["Skończę wciągu tygodnia.", "Skończę w ciągu tygodnia."],
        ["To jest kompletnie bezsensu.", "To jest kompletnie bez sensu."],
        ["Zrobił by to bez wahania.", "Zrobiłby to bez wahania."],
        ["Nie mógł bym tak żyć.", "Nie mógłbym tak żyć."],
        ["Chętnie poszła by do kina.", "Chętnie poszłaby do kina."],
        ["Wczoraj zrobili śmy zakupy.", "Wczoraj zrobiliśmy zakupy."],
        ["Wynik był nie zadowalający.", "Wynik był niezadowalający."],
        ["Obiad jest nie gotowy.", "Obiad jest niegotowy."],
        ["Prosimy o nie parkowanie tutaj.", "Prosimy o nieparkowanie tutaj."],
        ["Nie łatwo to przyznać.", "Niełatwo to przyznać."],
        ["Jego obecność była nie potrzebna.", "Jego obecność była niepotrzebna."],
        ["Już nie mogę się do czekać wakacji.", "Już nie mogę się doczekać wakacji."],
        ["Musisz się od stresować po pracy.", "Musisz się odstresować po pracy."],
        ["Mój eks-szef dzwonił.", "Mój eksszef dzwonił."],
        ["Rozmawiałem z v-ce dyrektorem.", "Rozmawiałem z wicedyrektorem."],
      ],
      neg: [
        "Czekamy na prawdę.",
        "Przyszedłem do pięciu osób.",
        "Jest za mało czasu.",
        "Co wy sądzicie o tym?",
        "Kot czai się za węgłem.",
        "To był anty-Polak i quasi-Europejczyk.",
        "Mamy dowód na prawdę tego twierdzenia.",
        "Przesunął się na przód autobusu.",
        "Strzelał raz za razem.",
        "Uznał to za pewne.",
        "Za pewne kwoty można wiele kupić.",
        "Zasnął po środku nasennym.",
        "Mieszkam po Woli i Mokotowie.",
        "Wyszło ponad to, co planowaliśmy.",
        "Wróciłem z resztą rodziny.",
        "To jest dla tego człowieka.",
        "Nie ma dla czego innego żyć.",
        "Żyli w prawdzie i miłości.",
        "Byłem tam tego dnia.",
        "Nie ma tam tych pieniędzy.",
        "Handel z zagranicą rośnie.",
        "Jutro wstanie wcześnie.",
        "W to popołudniu było cicho.",
        "Straty wyceniono na około pięć milionów.",
        "Wynik wyniósł w około połowie przypadków zero.",
        "Był najwyższej kary godny.",
        "W tym nie mniej niż siedem śledzi.",
        "Nie mniej jednak niż trzydzieści złotych.",
        "Staraj się, by najmniej zaszkodzić.",
        "Uważają łapówki za zwyczaj tak powszechny.",
        "Płacą za co miesięcznie trzydzieści franków?",
        "Morze bezsensu nas otacza.",
        "Ryba przykleiła się do wciągu filtra.",
        "Przyszedł by pomóc.",
        "Chciał bym przyszedł wcześniej.",
        "W tej chwili by się przydał.",
        "Krótko trwały te radości.",
        "Nie można tu palić.",
        "Oni nie giną i nie płoną.",
        "On nie cieszy się z tego.",
        "Wójt nie zabrania picia.",
        "To nie zły pomysł.",
        "Był nie dobry, lecz zły.",
        "Czy nie lepiej zostać?",
        "Jest nie lepszy od brata.",
        "Gdyby nie pewna osoba, przegralibyśmy.",
        "Nie zostanie tu długo.",
        "Nie zna nikogo.",
        "Nie inny jak on to zrobił.",
        "To preferencja, a nie ocena jakości.",
      ],
    },
  ],
  [
    "englishPhraseCorrections",
    "look-alike words in context",
    {
      pos: [
        ["Mówiła, ze nic nie wie.", "Mówiła, że nic nie wie."],
        ["Odpisał, ze chce przyjść.", "Odpisał, że chce przyjść."],
        ["Uznano, ze grupa jest za mała.", "Uznano, że grupa jest za mała."],
        ["Ja się tego wcale nie boje.", "Ja się tego wcale nie boję."],
        ["Mamy tak naprawę mało czasu.", "Mamy tak naprawdę mało czasu."],
        ["Był to, rzec jasna, żart.", "Był to, rzecz jasna, żart."],
        ["Zbierali pieniądze na rzec schroniska.", "Zbierali pieniądze na rzecz schroniska."],
        ["Padało, stad też te kałuże.", "Padało, stąd też te kałuże."],
        ["Pies nie dal za wygraną.", "Pies nie dał za wygraną."],
        ["Przedstawiam moją zonę.", "Przedstawiam moją żonę."],
        ["Nie wierze w ani jedno słowo.", "Nie wierzę w ani jedno słowo."],
        ["Mi się to nie podoba.", "Mnie się to nie podoba."],
        ["Ci się tylko tak wydaje.", "Tobie się tylko tak wydaje."],
        ["Przepraszam, ale nic mogę zrobić.", "Przepraszam, ale nic nie mogę zrobić."],
        [
          "Chodzi do Szkoły imieniem Marii Konopnickiej.",
          "Chodzi do Szkoły imienia Marii Konopnickiej.",
        ],
        [
          "Nie zaglądam na fora, bo nie lubię anonimowych for.",
          "Nie zaglądam na fora, bo nie lubię anonimowych forów.",
        ],
        ["Jego nazwisko nie schodzi z łam prasy.", "Jego nazwisko nie schodzi z łamów prasy."],
        ["Powinnam byłam zadzwonić wcześniej.", "Powinnam była zadzwonić wcześniej."],
        ["Ja nie rozumie tego zadania.", "Ja nie rozumiem tego zadania."],
        ["Myślę ze to dobry pomysł.", "Myślę że to dobry pomysł."],
        ["Kupiłem to bezcen.", "Kupiłem to za bezcen."],
        ["Mówi niemiecku bardzo dobrze.", "Mówi po niemiecku bardzo dobrze."],
        ["Szedł ciemku przez las.", "Szedł po ciemku przez las."],
        ["Nie boje się burzy.", "Nie boję się burzy."],
        ["Boje się ciemności.", "Boję się ciemności."],
        ["Padało, wiec zostaliśmy.", "Padało, więc zostaliśmy."],
        ["On tez przyjdzie.", "On też przyjdzie."],
        ["Zapłacił 20% mnie niż ja.", "Zapłacił 20% mniej niż ja."],
        ["Zostało mnie więcej pięć minut.", "Zostało mniej więcej pięć minut."],
        ["To była pierwsza cześć filmu.", "To była pierwsza część filmu."],
        ["Spłynęła na nas boża laska.", "Spłynęła na nas boża łaska."],
        ["Na górze znajduję się pokój gościnny.", "Na górze znajduje się pokój gościnny."],
        ["Musze już iść.", "Muszę już iść."],
        ["Uczniowie maja dziś wolne.", "Uczniowie mają dziś wolne."],
        ["Interesuje się głownie historią.", "Interesuje się głównie historią."],
        ["Stał miedzy nami.", "Stał między nami."],
        ["Problem nadaj występuje.", "Problem nadal występuje."],
        ["Było tam klika osób.", "Było tam kilka osób."],
        ["Był rządny władzy.", "Był żądny władzy."],
        ["Nie zwalniaj tępa pracy.", "Nie zwalniaj tempa pracy."],
        ["Mama karze mu sprzątać.", "Mama każe mu sprzątać."],
        ["Pokarz mi zdjęcia.", "Pokaż mi zdjęcia."],
        ["Jutro pokarzę, jak to działa.", "Jutro pokażę, jak to działa."],
        ["Mój brat jest wyższy jak ojciec.", "Mój brat jest wyższy niż ojciec."],
        ["Spóźnił się na wskutek korków.", "Spóźnił się wskutek korków."],
        ["Obrońcy postawili opór najeźdźcom.", "Obrońcy stawili opór najeźdźcom."],
        ["Jego zachowanie zakrawało o kpinę.", "Jego zachowanie zakrawało na kpinę."],
        ["To brzmi bardzo przekonywująco.", "To brzmi bardzo przekonująco."],
        ["Nie mogła się domyśleć, kto dzwonił.", "Nie mogła się domyślić, kto dzwonił."],
        ["Zarobił więcej jak w zeszłym roku.", "Zarobił więcej niż w zeszłym roku."],
        ["Czym dłużej czekasz, tym trudniej.", "Im dłużej czekasz, tym trudniej."],
        ["Im później, o tyle gorzej.", "Im później, tym gorzej."],
        ["Kupił zarówno chleb i masło.", "Kupił zarówno chleb, jak i masło."],
        ["Mam prezent dla cię.", "Mam prezent dla ciebie."],
        ["Nie mówiłem nic przeciw mu.", "Nie mówiłem nic przeciw niemu."],
        ["Dzieci śmiały się rozpuku.", "Dzieci śmiały się do rozpuku."],
        ["Gości było niemiara.", "Gości było co niemiara."],
        ["Wakacje spędził w Burkina.", "Wakacje spędził w Burkina Faso."],
        ["Bawił się z dziećmi i gościami.", "Bawił się z dziećmi i gośćmi."],
        [
          "Konstytucja Rzeczpospolitej Polski obowiązuje.",
          "Konstytucja Rzeczypospolitej Polskiej obowiązuje.",
        ],
        ["Został doradcą d/s kontaktów z prasą.", "Został doradcą ds. kontaktów z prasą."],
        ["Proszę zwrócić w/w dokumenty.", "Proszę zwrócić ww. dokumenty."],
        ["Ustawcie się w/g wzrostu.", "Ustawcie się wg wzrostu."],
        ["Nie wierze w to.", "Nie wierzę w to."],
        ["Wyszedł tuz przed północą.", "Wyszedł tuż przed północą."],
        ["Nie oto chodzi.", "Nie o to chodzi."],
        ["Moim zadaniem, to błąd.", "Moim zdaniem, to błąd."],
        ["Przyszedł wraz nim.", "Przyszedł wraz z nim."],
        ["Mimo różnić się dogadali.", "Mimo różnic się dogadali."],
        ["Nie jestem skłony do zmian.", "Nie jestem skłonny do zmian."],
        ["Spłacił koszty sadowe.", "Spłacił koszty sądowe."],
        ["Urodził się 3 litego 1990.", "Urodził się 3 lutego 1990."],
        ["Był to, rzecz można, wzór.", "Był to, rzec można, wzór."],
        ["Damy rade bez ciebie.", "Damy radę bez ciebie."],
        ["Jako widać, działa.", "Jak widać, działa."],
        ["Zarówno mama, jak tata pracują.", "Zarówno mama, jak i tata pracują."],
        ["Dokument opatrzył w pieczęć.", "Dokument zaopatrzył w pieczęć."],
        ["Obejrzałem dziś kilka meczy.", "Obejrzałem dziś kilka meczów."],
        ["Ferie spędziłem w Zakopanym.", "Ferie spędziłem w Zakopanem."],
        ["Nie wiem, proszę panią.", "Nie wiem, proszę pani."],
        ["Ani raz nie zadzwonił.", "Ani razu nie zadzwonił."],
        ["W szeregu sprawach miał rację.", "W szeregu spraw miał rację."],
        ["Urodził się w roku dwutysięcznym piątym.", "Urodził się w roku dwa tysiące piątym."],
        ["Możliwym jest szybsze rozwiązanie.", "Możliwe jest szybsze rozwiązanie."],
        ["Zbudowano go na początku XIX.", "Zbudowano go na początku XIX wieku."],
        [
          "Poparło nas trzydzieści % ankietowanych.",
          "Poparło nas trzydzieści procent ankietowanych.",
        ],
        ["Kliknij ten hyperlink.", "Kliknij ten hiperlink."],
        ["Przeczytaj drugą cześć książki.", "Przeczytaj drugą część książki."],
        ["Usiadł na jednaj z ławek.", "Usiadł na jednej z ławek."],
        ["Przyjechało 200 tyś. kibiców.", "Przyjechało 200 tys. kibiców."],
        ["Ile warzy ta walizka?", "Ile waży ta walizka?"],
        ["Koncerty odbywają się zagranicą.", "Koncerty odbywają się za granicą."],
        ["Te przepisy podleją kontroli.", "Te przepisy podlegają kontroli."],
        ["Kielce leża w centrum kraju.", "Kielce leżą w centrum kraju."],
        ["Powiedział to ot tak, a zrobił od tak.", "Powiedział to ot tak, a zrobił ot tak."],
        ["Sami naważyli sobie tego piwa.", "Sami nawarzyli sobie tego piwa."],
      ],
      neg: [
        "Jeszcze raz skłamiesz, a pokarzę cię surowo.",
        "Los pokarze jej synów za tę zbrodnię.",
        "Skopiuj pliki do katalogu /srv/w/w/ na serwerze.",
        "Ścieżka a/d/s/b nie istnieje.",
        "Oceniłem film na 3/5 gwiazdek.",
        "Lepiej jak najszybciej to skończyć.",
        "Rozchorował się na skutek przemęczenia.",
        "Postawił walizkę przy drzwiach.",
        "To zakrawa na żart.",
        "Będzie lepiej jak przyjdziesz wcześniej.",
        "To nic więcej jak żart.",
        "Zarówno czarne i białe koty, jak i psy, lubią mleko.",
        "Czym się teraz zajmujesz?",
        "Gram do mi na pianinie.",
        "Dzięki ci za pomoc.",
        "Mieszka w Burkina Faso od lat.",
        "Koza meczy w zagrodzie.",
        "Proszę panią o chwilę cierpliwości.",
        "Na przełomie XIX i XX wieku miasto rosło.",
        "Zrobiłem to na początku i nie żałuję.",
        "Poparło nas 30% ankietowanych.",
        "Hypokaust ogrzewał rzymskie łaźnie.",
        "Piwowar warzy piwo w piwnicy.",
        "Handel z zagranicą rośnie, a bliską zagranicą nazywa się sąsiadów.",
        "Mieszkam tu od tak dawna.",
        "Oddali zmarłemu ostatnią cześć.",
        "Był godny większej czci.",
        "Cześć i chwała bohaterom!",
        "Zarówno mama, jak wiadomo, jak i tata pracują.",
        "Ranę opatrzono w szpitalu.",
        "Ci ludzie mieszkają obok.",
        "Za nic mam twoje rady.",
        "Nie łam zasad, proszę.",
        "Mnie się to podoba.",
        "Wyszedł ze szkoły po lekcjach.",
        "Zrobił to ze chciwości.",
        "Na jeziorze kołysały się boje.",
        "Patrzyła w dal przez okno.",
        "Rozmawiali o wierze i nadziei.",
        "Stado owiec szło drogą, a za nim inne stada.",
        "Wyszedł ze szkoły wcześnie.",
        "Rozmawiał ze mną długo.",
        "Wrócę ze dwa razy.",
        "Pochodzi ze Lwowa.",
        "Mówi po polsku i angielsku.",
        "Toczyły się boje o miasto.",
        "Zorganizowano wiec poparcia.",
        "Napisał kilka tez programowych.",
        "Dostał ode mnie więcej niż ja od niego.",
        "I coraz mnie mniej.",
        "Cześć jego pamięci!",
        "Oparł się na lasce.",
        "Gdzie się znajduję?",
        "Znajduję się w trudnej sytuacji.",
        "Usiadła na musze.",
        "Wrócili pod koniec maja z urlopu.",
        "Mieszka w Głownie od lat.",
        "Szła wzdłuż miedzy.",
        "Nadaj ten list jutro.",
        "Rządzi nimi klika polityków.",
        "Rządna koalicja przetrwała.",
        "Patrzył tępo w ścianę.",
        "Sąd karze go grzywną.",
        "Pan Bóg nie rychliwy, ale sprawiedliwy, karze złych.",
        "Mieszkam w wierze i nadziei.",
        "Rozdał tuz pik.",
        "Oto chłopiec, o którym mówiłem.",
        "Moim zadaniem jest sprzątanie.",
        "Zgodnie twierdzą, że wygrali.",
        "Ćwiczy skłony do przodu.",
        "Ma sad i sadowe drzewa.",
        "Można rzecz kupić w sklepie.",
        "Sprawił, że się roześmiała.",
      ],
    },
  ],
  [
    "polishNumerals",
    "digits with endings, digit compounds, numeral and noun forms",
    {
      pos: [
        ["Wygrał już 3-ci raz.", "Wygrał już 3. raz."],
        ["Cena wzrosła trzy krotnie.", "Cena wzrosła trzykrotnie."],
        ["Zysk był 4. krotnie wyższy.", "Zysk był 4-krotnie wyższy."],
        ["Zatrudnili 30 - letniego kierowcę.", "Zatrudnili 30-letniego kierowcę."],
        ["Plan 3—letni przyjęto.", "Plan 3-letni przyjęto."],
        ["Przyjechał 12-go czerwca.", "Przyjechał 12 czerwca."],
        ["Moda z lat 80-tych wraca.", "Moda z lat 80. wraca."],
        ["Zaprosiłem 7-miu gości.", "Zaprosiłem siedmiu gości."],
        ["Dostał 6-tkę z matematyki.", "Dostał szóstkę z matematyki."],
        ["Pamiętam XX-go wieku modę.", "Pamiętam XX wieku modę."],
        ["Mamy 8-mio osobowy stół.", "Mamy 8-osobowy stół."],
        ["Była 10 minutowa przerwa.", "Była 10-minutowa przerwa."],
        ["Został 4 krotnym mistrzem.", "Został 4-krotnym mistrzem."],
        ["Ten 15 latek jest zdolny.", "Ten 15-latek jest zdolny."],
        ["Mają trzy dzieci.", "Mają troje dzieci."],
        ["Bilet kosztował 3 złotych.", "Bilet kosztował 3 złote."],
        ["Reszta to 12 grosze.", "Reszta to 12 groszy."],
        ["Dodaj 200 gram mąki.", "Dodaj 200 gramów mąki."],
      ],
      neg: [
        "Ma 5kg nadwagi i 10km do domu.",
        "Pokój 2-osobowy jest wolny.",
        "Obchodzimy 10-lecie firmy.",
        "Kupiłem 2 letnie sukienki.",
        "Porozmawiajmy w cztery oczy.",
        "Zdobył 2 złote medale.",
        "Gram w szachy od 5 lat, a 1 gram to mało.",
        "Wysłał CV-ki do 3 firm.",
        "Mam troje dzieci.",
      ],
    },
  ],
  [
    "polishDates",
    "impossible dates, weekdays and month forms",
    {
      pos: [
        ["Wyjazd 5 marzec 2021.", "Wyjazd 5 marca 2021."],
        ["Spotkanie 3. października.", "Spotkanie 3 października."],
        ["Wpis z 14 Lis 2019.", "Wpis z 14 XI 2019."],
        ["Pierwszy wrzesień był ciepły.", "Pierwszy września był ciepły."],
        ["Od 7 lipiec trwa remont.", "Od 7 lipca trwa remont."],
        ["Moda z lat 1980. wraca.", "Moda z lat 80. XX w. wraca."],
        ["Kocham muzykę lat '70 i więcej.", "Kocham muzykę lat 70. i więcej."],
        ["Bilety na mundial '2018 są drogie.", "Bilety na mundial 2018 są drogie."],
        ["Umowę podpisano 4 III 20019 r.", "Umowę podpisano 4 III 2019 r."],
        ["Remont skończy się w lipcu 20225 roku.", "Remont skończy się w lipcu 2025 roku."],
      ],
      neg: [
        "Urodził się 30 września 1990.",
        "Było to 29 lutego 2024.",
        "Dziś jest czwartek, 1 października 2026.",
        "Panował w latach 1814–1781 p.n.e.",
        "W roku 1962 – 272 000 osób.",
        "Rozdział 31 IX opisuje bitwę.",
        "Święto 1 Maj obchodzimy co roku.",
        "Obowiązuje od 2012-05-01.",
        "Zawody trwają od 1 do 10 lutego.",
        "Do 5 maja 20000 osób oddało głos.",
        "W lipcu 12345 r. to numer akt.",
      ],
    },
  ],
  [
    "polishMisplacedComma",
    "commas inside compound conjunctions and set phrases",
    {
      pos: [
        ["Mimo, że padało, wyszliśmy.", "Mimo że padało, wyszliśmy."],
        ["Zostałem w domu mimo, że chciałem iść.", "Zostałem w domu, mimo że chciałem iść."],
        ["Czytał gazetę podczas, gdy ona spała.", "Czytał gazetę, podczas gdy ona spała."],
        ["Przyjdę chyba, że zachoruję.", "Przyjdę, chyba że zachoruję."],
        ["Jest późno, a, więc idziemy.", "Jest późno, a więc idziemy."],
        ["Podaj numer o, ile go masz.", "Podaj numer, o ile go masz."],
        ["Chcąc, nie chcąc poszedł.", "Chcąc nie chcąc poszedł."],
        ["Kupił jabłka, gruszki, itd.", "Kupił jabłka, gruszki itd."],
        ["Lodówka, jest pusta od tygodnia.", "Lodówka jest pusta od tygodnia."],
        ["Każdy pracownik, dostał premię.", "Każdy pracownik dostał premię."],
        ["Herbata, to mój ulubiony napój.", "Herbata to mój ulubiony napój."],
        ["Kupiłem kilka śliwek, i moreli.", "Kupiłem kilka śliwek i moreli."],
        ["Przeczytał gazetę, oraz wypił kawę.", "Przeczytał gazetę oraz wypił kawę."],
        ["Wybór między kawą, a herbatą jest trudny.", "Wybór między kawą a herbatą jest trudny."],
        ["Po zakończeniu remontu, sklep otworzono.", "Po zakończeniu remontu sklep otworzono."],
        ["W razie awarii, technik szybko przyjeżdża.", "W razie awarii technik szybko przyjeżdża."],
        ["Pojechał tam mimo, że lało.", "Pojechał tam, mimo że lało."],
        ["Zgodzę się pod warunkiem, że zapłacisz.", "Zgodzę się, pod warunkiem że zapłacisz."],
        ["Pod warunkiem, że zdążysz.", "Pod warunkiem że zdążysz."],
        ["Tyle, że nikt mu nie wierzył.", "Tyle że nikt mu nie wierzył."],
        ["Był bogaty, tyle, że skąpy.", "Był bogaty, tyle że skąpy."],
      ],
      neg: [
        "Mówił wtedy nawet, gdy nikt nie słuchał.",
        "Czy tak, czy owak, idziemy.",
        "O, ile tu ludzi!",
        "Kupił jabłka itp., itd.",
        "Zjadł tyle, że pękł.",
        "Mamo, jest już obiad.",
        "Lodówka, jak zwykle, jest pusta.",
        "Ustawa, powiedział, wchodzi w życie jutro.",
        "Herbata, kawa i sok stały na stole.",
        "Kupił dom, który lubił, i zamieszkał w nim.",
        "Spadł deszcz, i to ulewny.",
        "Nie oddał długu, ani nie przeprosił.",
        "I kawa, i herbata stygły.",
        "Na szczęście, nikt nie zginął.",
        "Po południu, jeśli zdążę, zadzwonię.",
        "W pracy, w domu i w szkole jest tak samo.",
        "W poniedziałek, wtorek i środę pracuję.",
        "Po chwili, gdy wrócił, zjedliśmy.",
        "Poza tym, ze względu na pogodę, mecz przełożono.",
        "Wypił tyle, że zasnął.",
      ],
    },
  ],
  [
    "polishMissingComma",
    "a comma before a subordinate clause",
    {
      pos: [
        ["Myślę że masz rację.", "Myślę, że masz rację."],
        ["Im dłużej o tym myślę tym mniej wiem.", "Im dłużej o tym myślę, tym mniej wiem."],
        ["Znam zarówno Annę jak i jej brata.", "Znam zarówno Annę, jak i jej brata."],
        ["Przyszedł żeby pomóc.", "Przyszedł, żeby pomóc."],
        ["Został w domu ponieważ padało.", "Został w domu, ponieważ padało."],
        ["To jest dom w którym mieszkam.", "To jest dom, w którym mieszkam."],
        ["Znam człowieka który to zrobił.", "Znam człowieka, który to zrobił."],
        ["Jest mały ale wygodny.", "Jest mały, ale wygodny."],
        ["Zadzwoń jeśli możesz.", "Zadzwoń, jeśli możesz."],
        ["Poszła na spacer mimo że lało.", "Poszła na spacer, mimo że lało."],
        ["Pomogę ci pod warunkiem że wrócisz.", "Pomogę ci, pod warunkiem że wrócisz."],
        ["Przyjdę nawet gdybyś nie chciał.", "Przyjdę, nawet gdybyś nie chciał."],
        ["Zasnął dopiero gdy zgasło światło.", "Zasnął, dopiero gdy zgasło światło."],
        ["Ja czytam podczas gdy ty śpisz.", "Ja czytam, podczas gdy ty śpisz."],
        ["Nie dość że padało, to jeszcze wiało.", "Nie dość, że padało, to jeszcze wiało."],
        ["Zadzwoń do mnie kiedy wrócisz.", "Zadzwoń do mnie, kiedy wrócisz."],
        ["Uśmiechnął się gdy weszła.", "Uśmiechnął się, gdy weszła."],
        ["Nie wiem gdzie zostawiłem klucze.", "Nie wiem, gdzie zostawiłem klucze."],
        ["Zapytaj szefa dlaczego zwlekał.", "Zapytaj szefa, dlaczego zwlekał."],
        ["Leżał na kanapie zamiast sprzątać.", "Leżał na kanapie, zamiast sprzątać."],
        ["Martwi mnie to że milczy.", "Martwi mnie to, że milczy."],
        ["Nie wiadomo kiedy wróci z delegacji.", "Nie wiadomo, kiedy wróci z delegacji."],
        ["Wyszedł wcześniej by zdążyć na pociąg.", "Wyszedł wcześniej, by zdążyć na pociąg."],
        ["Usiadła przy oknie by się ogrzać.", "Usiadła przy oknie, by się ogrzać."],
        ["Opowiedz o planach jakie masz na lato.", "Opowiedz o planach, jakie masz na lato."],
        ["Trudno sobie wyobrazić jaka to była ulga.", "Trudno sobie wyobrazić, jaka to była ulga."],
        ["Wszystko zależy od tego czy zdąży.", "Wszystko zależy od tego, czy zdąży."],
        ["Nie zwracaj uwagi na to gdzie mieszka.", "Nie zwracaj uwagi na to, gdzie mieszka."],
        ["Wrócił do domu zatem żeby odpocząć.", "Wrócił do domu zatem, żeby odpocząć."],
        ["Pobiegł na stację tylko żeby zdążyć.", "Pobiegł na stację, tylko żeby zdążyć."],
        [
          "Ustawił krzesła tak żeby wszyscy widzieli.",
          "Ustawił krzesła, tak żeby wszyscy widzieli.",
        ],
        ["Okna umyto by nie było smug.", "Okna umyto, by nie było smug."],
        ["Pracuję by dzieci miały co jeść.", "Pracuję, by dzieci miały co jeść."],
        ["Jak widać nikt nie przyszedł.", "Jak widać, nikt nie przyszedł."],
        ["Jak wiadomo koty lubią spać.", "Jak wiadomo, koty lubią spać."],
        ["Musisz się liczyć z tym że odmówi.", "Musisz się liczyć, z tym że odmówi."],
        ["Twierdzono jednak iż to nieprawda.", "Twierdzono jednak, iż to nieprawda."],
        ["Jest miły tylko że się spóźnia.", "Jest miły, tylko że się spóźnia."],
        ["Kupię to pod warunkiem że będzie tanie.", "Kupię to, pod warunkiem że będzie tanie."],
        ["Oto do czego prowadzi lenistwo.", "Oto, do czego prowadzi lenistwo."],
        ["Pomyśl o wszystkim co ważne.", "Pomyśl o wszystkim, co ważne."],
        ["Tak jak wczoraj tak i dziś pada.", "Tak jak wczoraj, tak i dziś pada."],
        ["Była to tak czy inaczej porażka.", "Była to, tak czy inaczej, porażka."],
        ["Ten rower nie jest twój tylko brata.", "Ten rower nie jest twój, tylko brata."],
        ["Chcę kawę a nie herbatę.", "Chcę kawę, a nie herbatę."],
        ["Trudno stwierdzić co z tego wyniknie.", "Trudno stwierdzić, co z tego wyniknie."],
        ["Spróbuj opisać jak to wyglądało.", "Spróbuj opisać, jak to wyglądało."],
        [
          "Nie wyjdę z domu póki nie przestanie padać.",
          "Nie wyjdę z domu, póki nie przestanie padać.",
        ],
        ["Pomogę ci o ile zdążę.", "Pomogę ci, o ile zdążę."],
        ["Lubię go chociaż mnie denerwuje.", "Lubię go, chociaż mnie denerwuje."],
      ],
      neg: [
        "Wyszedł, mimo że padało.",
        "Mówił tak że nikt nie rozumiał.",
        "A że padało, zostaliśmy.",
        "Wiem, że jeśli przyjdzie, to pomoże.",
        "To ustawa, na podstawie której go skazano.",
        "To młotek, za pomocą którego wbił gwóźdź.",
        "Mało który uczeń to wie.",
        "O której mogę przyjść?",
        "Poślij którego z nich.",
        "Nie ma żadnych ale.",
        "Właśnie że nie pójdę.",
        "Był w pokoju, w którym i w którego oknach paliło się światło.",
        "Wyszedł wcześnie, mimo że nikt go nie gonił.",
        "Przyjdę kiedy indziej.",
        "Szukaj gdzie indziej.",
        "Póki co nic nie wiemy, a my póki co czekamy.",
        "A ty gdzie się wybierasz?",
        "Pracowała dużo, dzięki czemu awansowała.",
        "Jaki ojciec, taki syn.",
        "Był jaki taki, ale nasz.",
        "Kupił chleb zamiast bułek.",
        "Ja czytałem, podczas gdy on spał.",
        "Zjadł wszystko, mimo że nie był głodny.",
        "Chodzi o to, że nie mamy czasu.",
        "Nie wiadomo kiedy zrobiło się ciemno.",
        "Nie wiadomo skąd pojawił się na progu kot.",
        "Można by to zrobić szybciej.",
        "Należało by o tym pomyśleć wcześniej.",
        "Dobrze by było wyjechać.",
        "Jaki piękny dzień dziś mamy!",
        "Taki sam jaki był wczoraj.",
        "Czekaliśmy jakie pół godziny.",
        "Kupował to czy tamto.",
        "To co mam teraz zrobić?",
        "Było tego co niemiara.",
        "Zrobiłbym tak by było lepiej.",
        "Nie tylko żeby pomóc.",
        "Jak widać na wykresie ceny rosną.",
        "Jak wiadomo z historii wojny się kończą.",
        "Dusza jak gdyby uleciała.",
        "Nie tylko że przyszedł, ale i pomógł.",
        "A to mimo że padało.",
        "Oto jak się robi pierogi.",
        "Nie mam tylko czasu.",
        "Nie tylko on przyszedł.",
        "Decyzja była taka a nie inna.",
        "Jechał między Krakowem a nie Warszawą.",
        "Czy tak czy owak, idziemy.",
        "Chcę ci powiedzieć co nieco.",
        "Musisz pokazać jak najwięcej.",
        "Odezwij się choć raz!",
        "Korzystaj póki czas.",
        "O ile wzrosła cena?",
      ],
    },
  ],
  [
    "polishPrepositionForms",
    "w/we, z/ze, od/ode and the other vowel-extended prepositions",
    {
      pos: [
        ["Spotkajmy się w wtorek.", "Spotkajmy się we wtorek."],
        ["Byłem w Francji.", "Byłem we Francji."],
        ["Mieszka we Łodzi.", "Mieszka w Łodzi."],
        ["Wrócił z szkoły.", "Wrócił ze szkoły."],
        ["Pogadaj z wszystkimi.", "Pogadaj ze wszystkimi."],
        ["To prezent od mnie.", "To prezent ode mnie."],
        ["Nie dam rady bez mnie.", "Nie dam rady beze mnie."],
        ["Stał przed mną.", "Stał przede mną."],
        ["Wyszedł przede nim.", "Wyszedł przed nim."],
        ["Uciekł s domu.", "Uciekł z domu."],
        ["Spotkajmy się we Wiedniu.", "Spotkajmy się w Wiedniu."],
        ["Przywiózł ser s Francji.", "Przywiózł ser z Francji."],
      ],
      neg: [
        "Mieszkam we Włoszech.",
        "Muzykę skomponował J. S Bach.",
        "Spotkajmy się we wtorek w Warszawie.",
        "Przede wszystkim spokój.",
        "Zbaw nas ode złego.",
        "Idziemy we dwoje.",
        "Wrócił ze Lwowa z wodą.",
        "Popatrzył spode łba.",
        "Byłem w wodzie i we mgle.",
        "Patrz na s. 12 w tekście.",
        "Wrócił z ZSRR i grał ze Sionem.",
        "Chodził w tę i we w tę.",
      ],
    },
  ],
  [
    "englishPhraseCorrections",
    "conventional forms: abbreviations, inflected names, na + regions, predicative -e",
    {
      pos: [
        ["Wyjechali do Węgier na urlop.", "Wyjechali na Węgry na urlop."],
        ["Polecimy do Islandii w maju.", "Polecimy na Islandię w maju."],
        ["Ważnym jest, aby odpocząć.", "Ważne jest, aby odpocząć."],
        ["Oczywistym było, że wygra.", "Oczywiste było, że wygra."],
        ["Ma 3 mln. długu.", "Ma 3 mln długu."],
        ["Podziękuj dr Nowakowi za pomoc.", "Podziękuj dr. Nowakowi za pomoc."],
        ["Wykład poprowadzi mgr. Anna Wiśniewska.", "Wykład poprowadzi mgr Anna Wiśniewska."],
        ["Kup 2 m. sznurka.", "Kup 2 m sznurka."],
        ["Na koncert przyszło ok dwustu osób.", "Na koncert przyszło ok. dwustu osób."],
        ["To zasługa mgr Jana Wiśniewskiego.", "To zasługa mgr. Jana Wiśniewskiego."],
        ["Lubię owoce, np jabłka.", "Lubię owoce, np. jabłka."],
        ["Zapłacił ok 50 zł.", "Zapłacił ok. 50 zł."],
        ["Widziałem Mark'a wczoraj.", "Widziałem Marka wczoraj."],
        ["Rozmawiałam wczoraj z Bruce'm.", "Rozmawiałam wczoraj z Bruce'em."],
        ["Wysłałem list do Freddie'go.", "Wysłałem list do Freddiego."],
        ["Myślę o Clive'ie.", "Myślę o Clivie."],
        ["Pojechałam z Tony'm.", "Pojechałam z Tonym."],
        ["Wysłał mi pięć SMSów.", "Wysłał mi pięć SMS-ów."],
      ],
      neg: [
        "Ta ziemia należała do Węgier.",
        "Z każdym jest tak, że się męczy.",
        "Mieszka pod nr. 5.",
        "Rozmawiałem z dr Kowalską.",
        "Przyjmuje dziś dr Jan Kowalski.",
        "Dzięki dr. Kowalskiemu zdążyliśmy.",
        "Wymienił itd. i itp.",
        "Zajmuję się Joyce'em.",
        "Myślę o Mike'u i Locke'u.",
        "Spotkałam Jane'a?",
        "To szansa dla Jacques'a.",
        "Biografia Kennedy'ego.",
        "Partia PiS wygrała.",
      ],
    },
  ],
];

/** Warnings without a fix: the range is flagged and nothing is offered. */
const POLISH_WARNINGS: Array<[CatalogRuleId, string, string]> = [
  ["polishDates", "Urodził się 31 kwietnia.", "31 kwietnia"],
  ["polishDates", "Termin to 30 II 2025.", "30 II 2025"],
  ["polishDates", "Rok 2023 miał dzień 29 lutego 2023.", "29 lutego 2023"],
  ["polishDates", "Było to w piątek, 1 października 2026.", "piątek, 1 października 2026"],
  ["polishDates", "Obóz trwa 20–3 lipca.", "20–3 lipca"],
  ["polishDates", "Wojna trwała w latach 1918–1914.", "1918–1914"],
  ["polishDates", "Faktura z dnia 31.06.2024 jest błędna.", "31.06.2024"],
  ["polishDates", "Zebranie zwołano na 12.15.2025.", "12.15.2025"],
  ["polishDates", "Termin 32.13.2020 minął.", "32.13.2020"],
  ["polishDates", "Było to w sobotę, 3.05.2023.", "sobotę, 3.05.2023"],
];

test("the opt-in range dash fixes Polish number ranges and leaves codes, phones, IDs and scores", () => {
  for (const [text, fixed] of [
    ["Mieszkał tam w latach 1990-1995.", "Mieszkał tam w latach 1990–1995."],
    ["Przeczytaj strony 12-14 na jutro.", "Przeczytaj strony 12–14 na jutro."],
    ["Sezon 2019-20 był trudny.", "Sezon 2019–20 był trudny."],
    ["Dzieci w wieku 3-4 lat bawią się same.", "Dzieci w wieku 3–4 lat bawią się same."],
    ["Temperatura wyniesie 18—22 stopnie.", "Temperatura wyniesie 18–22 stopnie."],
  ]) {
    const [d, ...rest] = findings("emdashShortcut", text);
    expect(rest).toEqual([]);
    expect(applyEdits(text, d.alternatives[0].edits)).toBe(fixed);
  }
  for (const text of [
    "Biuro jest przy ul. Polnej 5, 00-950 Warszawa.",
    "Paczkę wyślij na kod 34-100 Wadowice.",
    "Zadzwoń pod 500-600-700 po południu.",
    "Tel. 22-123-45-67, faks 22-123-45-68.",
    "Mój nr 12-15 jest na liście.",
    "Legia wygrała mecz 3-1.",
    "Przegrali u siebie 1-2 po dogrywce.",
    "Skończyło się 2-3 dla gości.",
    "Termin 2024-05-01 minął.",
    "Sklep jest otwarty 8.00-16.00.",
  ])
    expect(findings("emdashShortcut", text)).toEqual([]);
});

test("dotted dates that exist, and dotted numbers that are not dates, stay clean", () => {
  for (const text of [
    "Spotkanie jest w środę, 3.05.2023.",
    "Urodził się 29.02.2024 w Krakowie.",
    "Serwer ma adres 10.12.2023.4 w sieci.",
    "Wydano wersję 2.10.2024.",
    // After a version word, a dotted number is a version, also when it has the shape of a date.
    "Wersja 32.13.2020 została wydana.",
    "Pobierz wersję 31.06.2024 z serwera.",
    // No part can be a day or a month: the dotted number is not a date.
    "Kod 45.67.2020 działa.",
  ])
    expect(findings("polishDates", text)).toEqual([]);
});

test.each(POLISH_WARNINGS)("%s warns on %p", (ruleId, text, original) => {
  const found = findings(ruleId, text);
  expect(found.map((d) => [d.original, d.warningOnly])).toEqual([[original, true]]);
});

describe.each(POLISH_CASES)("%s: %s", (ruleId, _name, { pos, neg }) => {
  test.each(pos)("flags %p", (text, fixed) => {
    const [d, ...rest] = findings(ruleId, text);
    expect(rest).toEqual([]);
    expect(d).toBeDefined();
    expect(applyEdits(text, d.alternatives[0].edits)).toBe(fixed);
    expect(findings(ruleId, fixed)).toEqual([]);
  });
  test.each(neg)("leaves %p", (text) => {
    expect(findings(ruleId, text).map((d) => d.original)).toEqual([]);
  });
  test("runs only for Polish", () => {
    for (const [text] of pos) expect(findings(ruleId, text, "en_US")).toEqual([]);
  });
});

// Polish frames with clause lookbehinds must not reread long runs at every position.
const POLISH_TRIGGERS =
  "na prawdę za razem za pewne po woli z resztą co raz dla tego dla czego w prawdzie " +
  "tam ten widzi mi się zrobił by zrobili śmy za zwyczaj co miesięcznie wciągu bezsensu " +
  "zarówno ojciec, jak pełni ona istotną rolę dwie lub więcej godzin Oto co Tak jak tak i " +
  "nie jest twoja tylko Po zakończeniu prac, biuro do czekać ile warzy około pięć który, która " +
  "w przeciągu dwóch lat odnośnie tego tak długo a a a dopóki tam pisało że kliknij na link " +
  "do Krakowa i z potworem coraz lepie coraz ładnej, nie tylko a, a, a, alei zarzuty x y przestawił " +
  "zrobił si bał czele wespół ludźmi się wahał się na pływać cale życie ośrodek zdrowa rożnych lat " +
  "O ile a o tyle o tyle innymi słowy w miarę jak to a mianowicie tym bardziej, że uwagi, co do " +
  "w od godziny bynajmniej dla nie tyle a, ale zarówno a b jak również rozumie pod tym o wym " +
  "wiodącym destynacji opisał to w terminach na odcinku na okoliczność Generalnie Dokładnie. " +
  "genezy powstania cofnął się trochę do tyłu i/lub z Nami zwodniczym mirażem akwenów wodnych " +
  "wzdłuż polnej drużki kilku wierz do podług ciszej nisz był oby naważyli sobie " +
  "prze piękny prze siebie prze ze mnie 1990-1995 12-14 3 maja 20015 r. w maju 20155 roku ";

const slowest = (text: string) => slowestChunkMs(text, "pl_PL");

test("no Polish chunk stalls on long runs or repeated trigger words", () => {
  slowest(POLISH_TRIGGERS.repeat(40));
  const inputs = [
    "\t ".repeat(6_000),
    `x${" ".repeat(3_800)}${POLISH_TRIGGERS}`.repeat(3),
    POLISH_TRIGGERS.repeat(60),
    "ała ".repeat(3_000),
    "słowo ".repeat(700),
    // Clause starts after a line break look back over a bounded run of spaces only.
    `\n${" \t".repeat(1_950)}Mi się boje chodź to`.repeat(2),
  ];
  for (const text of inputs) expect(slowest(text)).toBeLessThan(100);
});

test("the clause-start lookbehind is bounded (V8 rereads an unbounded one at every position)", () => {
  expect(CLAUSE_START).not.toMatch(/[*+]/);
});

test('",," before a quoted word is the Polish opening quote', () => {
  const fix = (text: string) =>
    findings("duplicatePunctuationCollapse", text).map((d) =>
      applyEdits(text, d.alternatives[0].edits),
    );
  expect(fix('Nazwał to ,,lekką porażką" i wyszedł.')).toEqual([
    'Nazwał to „lekką porażką" i wyszedł.',
  ]);
  expect(fix("Film ,,Rejs” znam na pamięć.")).toEqual(["Film „Rejs” znam na pamięć."]);
  expect(fix("Mówił o ,,przygodzie’’ cały wieczór.")).toEqual([
    "Mówił o „przygodzie’’ cały wieczór.",
  ]);
  expect(fix("Kupiłem chleb,, mleko i masło.")).toEqual(["Kupiłem chleb, mleko i masło."]);
  expect(fix("Pisał ,,coś bez końca i tyle.")).toEqual(["Pisał ,coś bez końca i tyle."]);
});

test("a Polish style row skips a capitalized name inside the sentence", () => {
  expect(findings("stylePhrasing", "Mieszkamy przy Wysokiej Frekwencji od lat.")).toEqual([]);
  expect(findings("stylePhrasing", "Wczoraj była Wysoka frekwencja w klubie.")).toEqual([]);
  expect(findings("stylePhrasing", "Wysoka frekwencja cieszy organizatorów.")).toHaveLength(1);
  expect(findings("stylePhrasing", "Cieszy nas wysoka frekwencja.")).toHaveLength(1);
});

test('Polish "ok." before a numeral and "im." before a title start no sentence', () => {
  const starts = (text: string) => findings("capitalizeSentenceStart", text).map((d) => d.original);
  expect(starts("Czekałem ok. trzech godzin na autobus.")).toEqual([]);
  expect(starts("Przyszło ok. dwudziestu osób.")).toEqual([]);
  expect(starts("Pracuje w szpitalu im. dr. Wandy Błeńskiej.")).toEqual([]);
  expect(starts("Wszystko jest ok. potem pogadamy.")).toEqual(["p"]);
  expect(starts("Oddałem im. potem wyszedłem.")).toEqual(["p"]);
});

test('a lowercase "mi" at a sentence start gets no pronoun fix and does not stop Review', () => {
  expect(findings("englishPhraseCorrections", "mi się to nie podoba.")).toEqual([]);
  expect(findings("englishPhraseCorrections", "Mi się to nie podoba.")).toHaveLength(1);
});
