// Derives the small Spanish word-class lexicon behind Review's Spanish checks from the Hunspell
// dictionary the extension ships (es_ES.dic/.aff).
// Writes src/core/domain/grammar/review/spanish/spanishLexicon.generated.ts.
// Usage: bun run generate:spanish-lexicon
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  BLOOM_ALPHABET,
  bloomBits,
} from "../src/core/domain/grammar/implementations/helpers/EnglishLexicon";

const root = resolve(import.meta.dir, "..");
export const SPANISH_LEXICON_SOURCES = {
  dic: resolve(root, "resources_js/es_ES/hunspell/es_ES.dic"),
  aff: resolve(root, "resources_js/es_ES/hunspell/es_ES.aff"),
  out: resolve(root, "src/core/domain/grammar/review/spanish/spanishLexicon.generated.ts"),
};

// The .aff's conjugation flags (R/E -ar and regular, I/X irregular groups), the gender flag G
// (an adjective or a noun with -o/-a forms) and the plural flag S.
const VERB_FLAGS = /[REIX]/;
// 12 bits per key keeps the filter's false positives near 0.3%.
const BLOOM_BITS_PER_KEY = 12;

type Rule = { flag: string; strip: string; add: string; cond: RegExp };

function parseSuffixes(aff: string): Rule[] {
  const rules: Rule[] = [];
  for (const line of aff.split("\n")) {
    const [kind, flag, strip, add, cond] = line.trim().split(/\s+/);
    if (kind !== "SFX" || cond === undefined) continue;
    rules.push({
      flag,
      strip: strip === "0" ? "" : strip,
      add: (add === "0" ? "" : add).split("/")[0],
      cond: new RegExp(`${cond === "." ? "" : cond}$`),
    });
  }
  return rules;
}

const ACCENTS: Record<string, string> = { á: "a", é: "e", í: "i", ó: "o", ú: "u" };
const plain = (word: string) => word.replace(/[áéíóú]/g, (c) => ACCENTS[c]);

/**
 * Bloom keys: "v" + infinitive for every conjugated verb, "a" + the masculine form of every
 * word with -o/-a gender forms (adjectives and nouns like "niño"), "n" + every plural-taking
 * entry without gender forms (nouns). Plus the accented nouns and adjectives whose unaccented
 * spelling is a form of some verb ("término" / "termino"), listed in full.
 */
export function deriveSpanishLexicon(dic: string, aff: string) {
  const rules = parseSuffixes(aff);
  const entries = dic
    .split("\n")
    .slice(1)
    .map((line) => line.trim())
    .filter((line) => line && !/^\p{Lu}/u.test(line))
    .map((line) => {
      const [word, flags = ""] = line.split("/");
      return [word, flags] as const;
    });
  const keys = new Set<string>();
  const verbForms = new Set<string>();
  const nominal = new Set<string>();
  const expand = (word: string, flags: string, only: RegExp) => {
    const out: string[] = [];
    for (const r of rules)
      if (
        only.test(r.flag) &&
        flags.includes(r.flag) &&
        word.endsWith(r.strip) &&
        r.cond.test(word)
      )
        out.push(word.slice(0, word.length - r.strip.length) + r.add);
    return out;
  };
  for (const [word, flags] of entries) {
    if (VERB_FLAGS.test(flags)) {
      keys.add(`v${word}`);
      for (const form of expand(word, flags, VERB_FLAGS)) verbForms.add(form);
    }
    if (flags.includes("G")) keys.add(`a${word}`);
    else if (flags.includes("S")) keys.add(`n${word}`);
    if (/[GS]/.test(flags))
      for (const form of [word, ...expand(word, flags, /[GS]/)]) nominal.add(form);
  }
  // "ingles" and "cortes" are nouns too: only twins whose plain spelling is just a verb form.
  const accented = [...nominal]
    .filter((word) => /[áéíóú]/.test(word) && !nominal.has(plain(word)))
    .filter((word) => verbForms.has(plain(word)))
    .sort();
  return { keys: [...keys].sort(), accented };
}

function bloom(keys: string[]): string {
  const size = Math.ceil((keys.length * BLOOM_BITS_PER_KEY) / 6) * 6;
  const bits = new Uint8Array(size);
  for (const key of keys) for (const bit of bloomBits(key, size)) bits[bit] = 1;
  let filter = "";
  for (let i = 0; i < size; i += 6) {
    let value = 0;
    for (let b = 0; b < 6; b++) value |= bits[i + b] << b;
    filter += BLOOM_ALPHABET[value];
  }
  return filter;
}

export function buildSpanishLexicon(dic: string, aff: string): string {
  const { keys, accented } = deriveSpanishLexicon(dic, aff);
  const line = (name: string, value: string) => {
    const one = `export const ${name} = ${JSON.stringify(value)};`;
    return one.length <= 100 ? one : `export const ${name} =\n  ${JSON.stringify(value)};`;
  };
  return [
    "// Generated by bun scripts/generate-spanish-lexicon.ts from es_ES.dic/.aff. Do not edit.",
    line("SPANISH_BLOOM", bloom(keys)),
    line("SPANISH_ACCENTED_NOMINALS", accented.join(" ")),
    "",
  ].join("\n");
}

if (import.meta.main) {
  const [dic, aff] = await Promise.all([
    readFile(SPANISH_LEXICON_SOURCES.dic, "utf8"),
    readFile(SPANISH_LEXICON_SOURCES.aff, "utf8"),
  ]);
  const source = buildSpanishLexicon(dic, aff);
  await writeFile(SPANISH_LEXICON_SOURCES.out, source);
  console.log(`wrote ${SPANISH_LEXICON_SOURCES.out} (${source.length} bytes)`);
}
