// Lists the Arabic sound feminine plurals (-ات) whose singular ends in ة, for Review's
// number-gender check, from the Hunspell dictionary the extension ships (ar_SA.dic).
// Writes src/core/domain/grammar/review/arabic/lexicon.generated.ts.
// Usage: bun run generate:arabic-lexicon
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
export const ARABIC_LEXICON_SOURCES = {
  dic: resolve(root, "resources_js/ar_SA/hunspell/ar_SA.dic"),
  out: resolve(root, "src/core/domain/grammar/review/arabic/lexicon.generated.ts"),
};

// ar_SA.aff suffix classes HA-HD spell the sound feminine plural (جلسة/جلسات,
// مباراة/مباريات, انتصار/انتصارات); FLAG long, so flags are letter pairs.
const PLURAL_AT = /^H[A-D]$/;

/**
 * The -ات plurals, minus "ات", of the ة nouns that take one ("طاولة" -> "طاول").
 * A stem whose bare form also takes -ات ("قطار"/"قطارة", both -> "قطارات") is left
 * out: its plural may be the masculine noun's.
 */
export function buildArabicLexicon(dic: string): string {
  const pluralizing = new Set<string>();
  for (const line of dic.split("\n").slice(1)) {
    const [word, flags = ""] = line.trim().split("/");
    if (word && flags.match(/../g)?.some((flag) => PLURAL_AT.test(flag))) pluralizing.add(word);
  }
  const stems = new Set<string>();
  for (const word of pluralizing) {
    if (!word.endsWith("ة") || /[أ]ة$/u.test(word)) continue;
    const stem = word.endsWith("اة") ? word.slice(0, -2) + "ي" : word.slice(0, -1);
    if (stem.length >= 2 && !pluralizing.has(stem)) stems.add(stem);
  }
  return (
    "// Generated by bun scripts/generate-arabic-lexicon.ts from ar_SA.dic. Do not edit.\n" +
    `export const FEMININE_PLURAL_STEMS =\n  "${[...stems].sort().join(" ")}";\n`
  );
}

if (import.meta.main) {
  const dic = await readFile(ARABIC_LEXICON_SOURCES.dic, "utf8");
  const output = buildArabicLexicon(dic);
  await writeFile(ARABIC_LEXICON_SOURCES.out, output);
  console.log(`${ARABIC_LEXICON_SOURCES.out}: ${(output.length / 1024).toFixed(1)} K chars`);
}
