// Lists Arabic word classes for Review's agreement checks, from the Hunspell dictionary the
// extension ships (ar_SA.dic): the sound feminine plurals (-ات) whose singular ends in ة, and
// a tag set per bare word (noun gender, adjective, masculine -ات plural, verb homograph).
// Writes src/core/domain/grammar/review/arabic/lexicon.generated.ts.
// Usage: bun run generate:lexicons arabic
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { encodeWordGraph } from "../src/core/domain/grammar/review/wordGraph";

const root = resolve(import.meta.dir, "..");
export const ARABIC_LEXICON_SOURCES = {
  dic: resolve(root, "resources_js/ar_SA/hunspell/ar_SA.dic"),
  out: resolve(root, "src/core/domain/grammar/review/arabic/lexicon.generated.ts"),
};

// ar_SA.aff uses FLAG long, so flags are letter pairs. Its affix classes: AA-AD a noun of
// one gender (قلم, جلسة; also broken plurals), BA-BD a word that takes ة (معلم/معلمة:
// adjectives and agent nouns), CA-CD the dual of an AA-AD noun (broken plurals have none),
// HA-HD the sound feminine plural (جلسة/جلسات, انتصار/انتصارات). The other two-capital and
// two-lowercase classes are nominal. A capital + lowercase pair (Pa-Pj, Aa-Si) is verbal.
const PLURAL_AT = /^H[A-D]$/;
const ONE_GENDER = /^A[A-D]$/;
const TAKES_TA = /^B[A-D]$/;
const DUAL = /^C[A-D]$/;
const NOMINAL = /^(?:[A-Z][A-Z]|[a-z][a-z])$/;
const VERBAL = /^[A-Z][a-j]$/;

type Word = { dual: boolean; takesTa: boolean; at: boolean; atNoun: boolean } & {
  nominal: boolean;
  verbal: boolean;
};

/**
 * Tags per bare word, joined to the word by "|" ("قميص|m", "قلم|mv"):
 * m  a masculine-looking singular noun (one gender, has a dual, no ة, ى, ا or اء ending);
 * f  a singular noun in ة (one gender, has a dual);
 * a  a word that takes ة for its feminine (adjectives and agent nouns);
 * p  a noun without ة whose -ات plural is its own (اجتماع/اجتماعات), when the ة form
 *    does not also take -ات;
 * v  one of the above that may also be a verb ("ذهب", "قلم"); verbs alone are not listed.
 */
function wordClasses(words: Map<string, Word>): string[] {
  const out: string[] = [];
  for (const [word, w] of words) {
    if (word.startsWith("ال") || !/^\p{L}{2,}$/u.test(word)) continue;
    const plain = !/[ةىا]$|اء$/u.test(word);
    let tags = "";
    if (w.dual && plain) tags += "m";
    if (w.dual && word.endsWith("ة")) tags += "f";
    if (w.takesTa && !/[ةى]$/u.test(word)) tags += "a";
    if (w.atNoun && plain && !words.get(word + "ة")?.at) tags += "p";
    if (tags && w.verbal) tags += "v";
    if (tags) out.push(`${word}|${tags}`);
  }
  return out;
}

export function buildArabicLexicon(dic: string): string {
  const words = new Map<string, Word>();
  for (const line of dic.split("\n").slice(1)) {
    const [word, flagText = ""] = line.trim().split("/");
    if (!word) continue;
    const flags = flagText.match(/../g) ?? [];
    const has = (re: RegExp) => flags.some((flag) => re.test(flag));
    let w = words.get(word);
    if (!w) {
      w = { dual: false, takesTa: false, at: false, atNoun: false, nominal: false, verbal: false };
      words.set(word, w);
    }
    const oneGender = has(ONE_GENDER);
    w.dual ||= oneGender && has(DUAL);
    w.takesTa ||= has(TAKES_TA);
    w.at ||= has(PLURAL_AT);
    w.atNoun ||= oneGender && has(PLURAL_AT);
    w.nominal ||= has(NOMINAL);
    w.verbal ||= has(VERBAL);
  }
  // The -ات plurals, minus "ات", of the ة nouns that take one ("طاولة" -> "طاول").
  // A stem whose bare form also takes -ات ("قطار"/"قطارة", both -> "قطارات") is left
  // out: its plural may be the masculine noun's.
  const stems = new Set<string>();
  for (const [word, w] of words) {
    if (!w.at || !word.endsWith("ة") || /[أ]ة$/u.test(word)) continue;
    const stem = word.endsWith("اة") ? word.slice(0, -2) + "ي" : word.slice(0, -1);
    if (stem.length >= 2 && !words.get(stem)?.at) stems.add(stem);
  }
  return (
    "// Generated by bun scripts/generate-arabic-lexicon.ts from ar_SA.dic. Do not edit.\n" +
    "// Word graphs (review/wordGraph.ts).\n" +
    `export const FEMININE_PLURAL_STEMS =\n  ${JSON.stringify(encodeWordGraph(stems))};\n` +
    `export const WORD_CLASSES =\n  ${JSON.stringify(encodeWordGraph(wordClasses(words)))};\n`
  );
}

if (import.meta.main) {
  const dic = await readFile(ARABIC_LEXICON_SOURCES.dic, "utf8");
  const output = buildArabicLexicon(dic);
  await writeFile(ARABIC_LEXICON_SOURCES.out, output);
  console.log(`${ARABIC_LEXICON_SOURCES.out}: ${(output.length / 1024).toFixed(1)} K chars`);
}
