import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { format } from "prettier";
import { SUPPORTED_LANGUAGES } from "../src/core/domain/lang";

type Unit = {
  identity: string;
  symbol: string;
  prefixes: "decimal" | "binary" | "both" | "none";
  safe: boolean;
  ambiguity?: string;
  source: string;
  composition: boolean;
  ucum?: string;
};

const root = resolve(import.meta.dir, "..");
const sourcePath = resolve(root, "data/measurement/ucum-essence.xml");
const pinnedUcum =
  "https://raw.githubusercontent.com/ucum-org/ucum/ef4c31cd7d3bc81de1a1bf2cc8414bf502b6304f/ucum-essence.xml";
const pinnedUcumLicense =
  "https://raw.githubusercontent.com/ucum-org/ucum/ef4c31cd7d3bc81de1a1bf2cc8414bf502b6304f/LICENSE.md";

if (process.argv.includes("--refresh")) {
  const [response, licenseResponse] = await Promise.all([
    fetch(pinnedUcum),
    fetch(pinnedUcumLicense),
  ]);
  if (!response.ok || !licenseResponse.ok)
    throw new Error(`UCUM refresh failed: ${response.status}/${licenseResponse.status}`);
  await mkdir(dirname(sourcePath), { recursive: true });
  await Promise.all([
    writeFile(sourcePath, await response.text()),
    writeFile(resolve(root, "data/measurement/UCUM-LICENSE.txt"), await licenseResponse.text()),
  ]);
}

const [unitsText, localesText, sourceText, ucumXml] = await Promise.all([
  readFile(resolve(root, "data/measurement/units.json"), "utf8"),
  readFile(resolve(root, "data/measurement/locales.json"), "utf8"),
  readFile(resolve(root, "data/measurement/sources.json"), "utf8"),
  readFile(sourcePath, "utf8"),
]);
const units = JSON.parse(unitsText) as Unit[];
const locales = JSON.parse(localesText) as {
  locale: string;
  separator: string;
  decimalMarks: string[];
}[];
const sources = JSON.parse(sourceText) as {
  sources: { id: string; sha256?: string }[];
};
const sourceIds = new Set(sources.sources.map(({ id }) => id));
const ucumHash = createHash("sha256").update(ucumXml).digest("hex");
const expectedUcumHash = sources.sources.find(({ id }) => id === "UCUM-2.2")?.sha256;
if (!expectedUcumHash || ucumHash !== expectedUcumHash) {
  throw new Error(`UCUM SHA-256 mismatch: expected ${expectedUcumHash}, got ${ucumHash}`);
}

const symbols = new Set<string>();
for (const unit of units) {
  if (symbols.has(unit.symbol)) throw new Error(`duplicate symbol: ${unit.symbol}`);
  if (!sourceIds.has(unit.source)) throw new Error(`unknown source: ${unit.source}`);
  if (!unit.safe && !unit.ambiguity) throw new Error(`unsafe unit lacks ambiguity: ${unit.symbol}`);
  symbols.add(unit.symbol);
}

const expectedLocales = new Set(
  Object.keys(SUPPORTED_LANGUAGES).filter(
    (locale) => !["auto_detect", "textExpander"].includes(locale),
  ),
);
if (locales.length !== expectedLocales.size) throw new Error("measurement locale count mismatch");
for (const { locale, separator, decimalMarks } of locales) {
  if (!expectedLocales.delete(locale)) throw new Error(`unknown or duplicate locale: ${locale}`);
  const expectedMark = locale === "en_US" ? "." : ",";
  if (separator !== "\u00a0" || decimalMarks.length !== 1 || decimalMarks[0] !== expectedMark) {
    throw new Error(`invalid locale punctuation: ${locale}`);
  }
}
if (expectedLocales.size) throw new Error(`missing locales: ${[...expectedLocales].join(", ")}`);

const output =
  `// Generated by bun scripts/measurement-data.ts. Do not edit.\n` +
  `export const MEASUREMENT_UNITS = ${JSON.stringify(
    units.map(({ ucum: _ucum, ...unit }) => unit),
    null,
    2,
  )} as const;\n\n` +
  `export const MEASUREMENT_LOCALES = ${JSON.stringify(locales, null, 2)} as const;\n`;
await writeFile(
  resolve(root, "src/core/domain/grammar/measurement/registry-data.generated.ts"),
  await format(output, { parser: "typescript" }),
);

const ucumCodes = [...ucumXml.matchAll(/<(?:base-unit|unit)\b[^>]*\bCode="([^"]+)"/g)].map(
  ([, code]) => code,
);
const byUcum = new Map<string, Unit>();
for (const unit of units) {
  if (!unit.ucum) continue;
  if (byUcum.has(unit.ucum)) throw new Error(`duplicate UCUM mapping: ${unit.ucum}`);
  byUcum.set(unit.ucum, unit);
}
const rows = ucumCodes.map((code) => {
  const unit = byUcum.get(code);
  const standaloneEligible = unit?.safe && !/^[A-Z]$/.test(unit.symbol);
  const status = unit
    ? standaloneEligible
      ? "recognized-safe"
      : "recognized-ambiguous"
    : "unsupported";
  const note =
    unit?.ambiguity ??
    (unit
      ? standaloneEligible
        ? `prose symbol ${unit.symbol}`
        : `single capital symbol ${unit.symbol}: preserved standalone, available in compounds`
      : "not in prose registry");
  return `| \`${code.replaceAll("|", "\\|")}\` | ${status} | ${note.replaceAll("|", "\\|")} |`;
});
const counts = rows.reduce(
  (result, row) => {
    if (row.includes("recognized-safe")) result.safe++;
    else if (row.includes("recognized-ambiguous")) result.ambiguous++;
    else result.unsupported++;
    return result;
  },
  { safe: 0, ambiguous: 0, unsupported: 0 },
);
const coverage =
  `# UCUM atomic-code coverage\n\n` +
  `Generated from the pinned, unmodified UCUM 2.2 essence snapshot. This is a coverage audit, not a UCUM parser or a conformance claim. UCUM expression syntax and case-insensitive aliases are intentionally unsupported.\n\n` +
  `Snapshot SHA-256: \`${ucumHash}\`\n\n` +
  `| recognized-safe | recognized-ambiguous | unsupported | total |\n|---:|---:|---:|---:|\n` +
  `| ${counts.safe} | ${counts.ambiguous} | ${counts.unsupported} | ${rows.length} |\n\n` +
  `| UCUM code | classification | reason / prose symbol |\n|---|---|---|\n${rows.join("\n")}\n`;
await writeFile(
  resolve(root, "data/measurement/ucum-coverage.md"),
  await format(coverage, { parser: "markdown", proseWrap: "preserve" }),
);

console.log(
  `generated ${units.length} units, ${locales.length} locales, ${ucumCodes.length} UCUM coverage rows`,
);
