on:
  push:
    tags:
      - "*"

name: Upload Release Asset

permissions:
  contents: write

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true

  build_release:
    name: Build Release
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ["edge", "chrome", "firefox"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Prepare files
        run: |
          bun install --frozen-lockfile
          bun run build --platform=${{ matrix.browser }} --outdir=${{ matrix.browser }}
      - name: Zip Release
        run: |
          cd ${{ matrix.browser }}
          zip -r ../FluentTyper_${{ matrix.browser }}.zip .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./FluentTyper_${{ matrix.browser }}.zip
